OpenRadioss/OpenRadioss

engine/source/interfaces/int25/i25norm.F
An issue was introduced by my ac4657c496f06bd53001224a0c  commit : 
* the condition ledge(right)/=0 must be applied only for edge defined with ledge(i,1)/= 1 and with SH_EDGE = 1
Fix the IF condition
=> Fix a regression introduced by ac4657c496f06bd53001224a0c 

scripts/pre-push
Add a pre-push hook that prints a message when the author of the last commit of the branch is not the current user.
Generally, this is a sign that a squash was not correct.
=> pre-push hook that checks the user name of the last commit to be pushed

common_source/tools/input_output/write_routtines.c
=> bee2923091408e34d94210e0114fcc5f2112b08c : Missing Open Option for append

engine/source/output/h3d/h3d_results/h3d_quad_scalar.F, engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F, engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
During the ouptut calculation (massic energy density), a division by zero may occur when requesting /H3D/ELEM/ENER with material law151. it is now fixed. (QUAD,TRIA,BRIC)
=> /H3D/ELEM/ENER : fix with law151

hm_cfg_files/config/CFG/radioss2024/PLY/ply.cfg, hm_cfg_files/config/CFG/radioss2024/PLY/prop_ply.cfg, starter/source/properties/shell/hm_read_prop19.F
The design of  orthotropy direction is not easy 
Remove the flag from ply. All the possibitity are managed by flag in the stack
=> remove def_orth flag

hm_cfg_files/config/CFG/radioss2024/PLY/ply.cfg, hm_cfg_files/config/CFG/radioss2024/PLY/prop_ply.cfg
We can't read the input < 2024 with def_orth
Remove def_orth only for input >= 2024
=> remove def_orth only for input 2024

engine/build_windows.bat, starter/build_windows.bat
Build_windows shoud exit with error when build has an error.
=> build_windows.bat issue

engine/share/modules/sensor_mod.F, engine/source/engine/resol.F, engine/source/input/freform.F, engine/source/tools/sensor/sensor_init.F
New functionnality : possibility to reset already activated sensors at the beginning of the next engine run
added new input option for engine and a routine to reinitialize sensor list
=> Add new engine option : /SENS/RESET

hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
ignore reading of *DATABASE_DEFGEO option
=> ignore reading of *DATABASE_DEFGEO option

hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Activate conversion of Dyna *Database_Glstat_Mass_Properties.
In Data_hierarchy.cfg, activate conversion of *Database_Glstat_Mass_Properties.
=> Activate conversion of *Database_Glstat_Mass_Properties

hm_cfg_files/config/CFG/radioss2021/TABLE/inishe_strs_f_glob_sub.cfg
Correction of CFG file for /INISHE/STRS_F/GLOB
Correction of IMPORT/EXPORT in CFG file for /INISHE/STRS_F/GLOB
=> update of inishe_strs_f_glob CFG

starter/source/elements/shell/coque/corthini.F, starter/source/properties/shell/hm_read_prop09.F, starter/source/properties/shell/hm_read_prop10.F, starter/source/properties/shell/hm_read_prop11.F, starter/source/properties/shell/hm_read_prop17.F, starter/source/properties/shell/hm_read_prop51.F
new reference direction define IP=25 for orthotropic shell
=> add new orthotropic shell reference direction IP=25

hm_cfg_files/config/CFG/radioss2019/SYSTEM/frame_mov.cfg
inconsistency frame_mov.cfg file with skew_mov.cfg file
change nodes fields to N1 N2 N3 ( solver name)
=> inconsistency frame_mov.cfg file with skew_mov.cfg file

engine/source/engine/resol.F, engine/source/interfaces/intsort/intcrit.F, engine/source/interfaces/intsort/inttri.F
Avoid hang during the collision detection algorithm when nodal velocities are too high.
The run is stop, with the same message as /STOP
=> /INTER/TYPE25 stop the run if nodes have too high velocity

hm_cfg_files/config/CFG/radioss2024/FAIL/fail_biquad.cfg
There is a need to create a 2024 .cfg file for /FAIL/BIQUAD due to some change in flags default value. 
There is a need to create a 2024 .cfg file for /FAIL/BIQUAD due to some change in flags default value. (Note that the format of the input card remains the same as 2023 version)
=> Change default value in /FAIL/BIQUAD .cfg file

engine/source/elements/solid/solide4/s4forc3.F
one argument missed in calling in previous PR 07ca452852eb0d4f65391645e0565920afa0f219
correction of adding argument missed.
=> argument missed in 07ca452852eb0d4f65391645e0565920afa0f219

hm_cfg_files/config/CFG/radioss2021/TABLE/inishe_strs_f_glob_sub.cfg
Issue with standalone D2R conversion with CFG file of Initial stress full global of Shells
Correction of IMPORT/EXPORT in CFG file of Initial stress full global of Shells
=> Update CFG IMPORT/EXPORT Initial_Stress_Shell

engine/source/materials/mat/mat057/sigeps57c.F
LAW57- output of SIGEQ correction of the expression of the equivalent stress 
remove wrong added 2**m factor in sigeq
=> LAW57- output of SIGEQ correction

tools/th_to_csv/src/th_to_csv.c
correction IF condition NUMMAT -> NUMGEO
=> correction IF condition NUMMAT -> NUMGEO

Compiling_tools/script/or_build_info.py
=> Missing variable initialization in build_info.inc python

engine/source/materials/mat/mat107/mat107_newton.F, engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F, engine/source/output/th/hist2.F
Some table addresses bugs have been raised by sanitizer compiler. 
Fix the bugs.
=> Fix some bugs of table adresses

starter/source/elements/shell/coque/corthini.F
Small change in the recent development fa604428a02f323d433a353b3c35d9030933590e, now using element center instead of node 1 to compute the cylindrical coordinate system which is more precise.
=> small change to the new IP=25 for orthotropic shell

engine/source/materials/mat/mat057/sigeps57c.F
LAW57 - new code for plasticity calculation
aim: improve performance
=> LAW57 - new algo for plasticity

engine/share/modules/damp_mod.F, engine/source/assembly/damping.F, engine/source/assembly/damping_vref.F, engine/source/assembly/dampvref_sum6.F, engine/source/engine/resol.F, engine/source/engine/resol_head.F, engine/source/output/restart/arralloc.F, engine/source/output/restart/rdcomm.F, engine/source/output/restart/rdresb.F, engine/source/output/restart/wrcomm.F, engine/source/output/restart/wrrestp.F, starter/source/restart/ddsplit/c_dampvrel.F, starter/source/restart/ddsplit/ddsplit.F, starter/source/restart/ddsplit/w_dampvrel.F, starter/source/restart/ddsplit/wrcommp.F
Fix of SPMD and PARITH/ON issue for /DAMP/VREL + fix of uninitialized variable
=> /DAMP/VREL - SPMD fix

engine/CMake_Compilers/cmake_linuxa64.txt, engine/CMake_Compilers/cmake_win64.txt, qa-tests/CMakeLists.txt, qa-tests/qa_tools/miniqa.txt, qa-tests/test_script.bat, starter/CMake_Compilers/cmake_win64.txt
* Typo issue in linua64 executable
* Ctest build script : issues when using nin debug executables.
typo error in linxa64
=> Several issues in qa script (CTEST):

starter/source/properties/shell/hm_read_prop19.F
correcting typo 'INCRMENTAL' to 'INCREMENTAL' in /PROP/TYPE19 messages in out file and spacing of other lines for consistency
typo 'INCRMENTAL' in out file
corrected typo 'INCRMENTAL' to 'INCREMENTAL' (+ spacing of neighbouring lines)
=> Update hm_read_prop19.F (correct typo in messages in out file)

hm_cfg_files/config/CFG/radioss2021/TABLE/inish3_strs_f_glob_sub.cfg
Update IMPORT/EXPORT cfg for initial state of sh3n (stress full global)
Update IMPORT/EXPORT cfg
=> update IMPORT/EXPORT cfg with option Inish3_strsf_glob

starter/source/elements/shell/coque/csigini.F
found initial stress lecture issue with Ishell<=4 in recent development f0ab496c215867883d1e4bd206b68f3a9a83d9cd
correction for Ishell<=4
=> bug fixing in f0ab496c215867883d1e4bd206b68f3a9a83d9cd concerning ishell<=4

common_source/modules/setdef_mod.F, hm_cfg_files/config/CFG/radioss2024/SETS/set.cfg, hm_cfg_files/config/CFG/radioss2024/SETS/set_support.cfg, starter/source/model/box/read_box_box.F, starter/source/model/box/read_box_cyl.F, starter/source/model/box/read_box_rect.F, starter/source/model/box/read_box_spher.F, starter/source/model/sets/clause_init.F, starter/source/model/sets/create_ellipse_clause.F, starter/source/model/sets/fill_gr_surf_ellipse.F, starter/source/model/sets/fill_igr.F, starter/source/model/sets/hm_set.F, starter/source/model/sets/insert_clause_in_set.F, starter/source/model/sets/set_init.F, starter/source/output/qaprint/st_qaprint_set.F, starter/source/output/qaprint/st_qaprint_surf.F, starter/source/starter/lectur.F
New /SET/GENERAL implementation for ELLIPS clause (analytical surface definition)
Implement new /SET/GENERAL type ELLIPS + CFG
=> Set general new key ellips

engine/CMake_Compilers/cmake_linux64_gf.txt, engine/build_script.sh, engine/build_windows.bat, starter/CMake_Compilers/cmake_linux64_gf.txt, starter/build_script.sh, starter/build_windows.bat
Due to merge issue : asan was add twice in file, zlib library missing
=> OpenRadioss builds: Add a Warning at the en of build when Adress Sanitizer is used.

starter/source/materials/eos/hm_read_eos.F, starter/source/materials/mat/check_mat_elem_prop_compatibility.F, starter/source/materials/mat/init_mat_keyword.F, starter/source/materials/mat/mat044/hm_read_mat44.F
now the material law44 is compatible woth /EOS option
Added EOS compatibility keyword for the law and removed old error message
=> Allow compatibility of /MAT/LAW44 with /EOS

engine/source/materials/fail/gene1/fail_gene1_c.F, engine/source/materials/fail/gene1/fail_gene1_s.F
A potential bug can appear when using /FAIL/GENE1 with INISHE or INISH3N due to a bad condition (ISIGI == 0). 
Remove the condition (ISIGI == 0) that is useless.
=> Fix initialization issue with /FAIL/GENE1

starter/source/elements/shell/coque/csigini.F, starter/source/elements/shell/coqueba/scigini4.F
in recent development f0ab496c215867883d1e4bd206b68f3a9a83d9cd, moment in lecture is wrong
correction of lecture /INISHE(INISH3N)/STRS_F/GLOB (npt>0) with law1
=> correction on lecture of /INISHE/STRS_F/GLOB w/ law1

engine/source/constraints/thermic/convec.F, engine/source/constraints/thermic/fixflux.F, engine/source/engine/radioss2.F
Fix uninitialized variables, and print an error message when PARITH/ON
=> /IMPFLUX /CONVEC: various fixes

engine/source/engine/radioss2.F
/IMPFLUX: is not compatible with PARITH/ON :  switch to /PARITH/OFF
=> /IMPFLUX: switch to /PARITH/OFF

engine/source/engine/radioss2.F, engine/source/output/anim/generate/dfuncf.F
Regression on PARITH/ON of #2324 + asan fix
=> Fix regression + Asan in dfuncf.F

hm_cfg_files/config/CFG/Keyword971_R13.0/TABLE/initial_stress.cfg, hm_cfg_files/config/CFG/Keyword971_R13.0/TABLE/initial_stress_solid_subobj.cfg
Activate conversion of  *INITIAL_STRESS_SOLID cfg files
Activate conversion of  *INITIAL_STRESS_SOLID cfg files
=> conversion of *INITIAL_STRESS_SOLID cfg files

engine/source/mpi/interfaces/spmd_i25front.F
/INTER/TYPE25 segfault in SPMD when elements are deleted
=> /INTER/TYPE25 segfault in SPMD when elements are deleted

engine/source/elements/sph/spstab.F, starter/source/elements/reader/hm_read_sphcel.F, starter/source/elements/sph/spclasv.F, starter/source/elements/sph/spinih.F, starter/source/elements/sph/spinit3.F, starter/source/properties/sph/hm_read_prop34.F, starter/source/starter/lectur.F, starter/source/starter/starter0.F
New input with mass or volume per particle
=> SPH - ipnut mass per particle

starter/source/loads/pblast/hm_read_pblast.F
WRITE statment must be done on screen (unit=ISTDO), and Starter listing file (unit=IOUT)
=> /LOAD/PBLAST : Starter output on both Screen & Listing file

engine/share/spe_inc/vectorize.inc, starter/share/spe_inc/vectorize.inc
IVDEP was not active for Windows Builds
Refactor vectorize.inc for Starter & Engine : Remove obsolete platforms & simplifiy structure.
=> Windows : Optimization issue :

starter/source/elements/reader/hm_read_sphcel.F
Fix for new SPH input per particle
=> SPH mass input par particle fix

starter/source/elements/initia/initia.F
Wrong NPT value of shell (integration point number in thickness) in Review ELEM/MAT of Starter outfile if this value was modified by Radioss in some cases (e.g. law1)
Change to final value of NPT of shell in ELEM/MAT review.
=> might have wrong NPT value for shell in REVIEW of starter outfile

starter/source/materials/mat/mat090/law90_upd.F
Message said 'MAXIMAM YOUNG'S MODULUS' 
corrected to 'MAXIMUM YOUNG'S MODULUS'
=> Correct Typo in Starter Message

starter/source/model/sets/fill_gr_surf_ellipse.F, starter/source/model/sets/fill_igr.F, starter/source/output/qaprint/st_qaprint_set.F
Issue in QAprint for /SET/GENERAL key=ELLIPS
Correction of QAprint and uninitialized variable for SET_GENERAL key=ELLIPS
=> Correction of QAprint and uninitialized variable for SET_GENERAL_key_ELLIPS

engine/source/materials/mat/mat057/sigeps57c.F
This reverts commit 59800234b62a2d279689d674406b791f226d8239.
=> Revert "LAW57 - new algo for plasticity"

engine/source/materials/mat/mat051/sigeps51.F
argument issue fixed.
Specific case : LAW51 + NRF(law51+iform=6) + 2D
=> LAW51:2D fix for NRF

engine/source/materials/mat_share/mmain.F, starter/share/modules1/elbuftag_mod.F, starter/source/initial_conditions/inigrav/inigrav_load.F, starter/source/initial_conditions/inimap/ini_inimap1d.F, starter/source/materials/mat/mat004/hm_read_mat04.F, starter/source/materials/mat/mat049/hm_read_mat49.F, starter/source/materials/mat/mat102/hm_read_mat102.F, starter/source/materials/mat/mat103/hm_read_mat103.F
correct several errors introduced in previous PRs
set MAXEOS=20 instead of 17, latest EOS number is 18
remove pressure initialization for law 17 (law6 + iturb) before calling EOS in main
correct forcheck type errors with missing call arguments
changed default EOS type for law4 , 102, 103
=> EOS error corrections

engine/source/assembly/damping_vref_rby_stiff.F90, engine/source/constraints/general/rbody/rbyfor.F
bad reference to reference to rbody id
need to make reference to local id of rbody inside damp vrel routine
=> correction issue with damp vrel, need to make reference to local id of rbody inside damp vrel routine

engine/source/materials/mat/mat070/sigeps70.F, engine/source/materials/tools/table_mat_vinterp.F
Improve LAW70 Performance with tables
Interpolation algorithm improvement
Set missing  positions sigeps70
=> Law70 performance issue - Interpolation routine optimization and position setting in law70 routine

engine/source/output/restart/read_failparam.F
Address Sanitizer issue with /FAIL
=> /FAIL: pointer to unallocated array

engine/source/elements/forint.F, engine/source/elements/spring/preload_axial.F90, engine/source/elements/spring/rforc3.F, hm_cfg_files/config/CFG/radioss2024/LOADS/preload_axial.cfg, hm_cfg_files/config/CFG/radioss2024/data_hierarchy.cfg, starter/share/modules1/bpreload_mod.F, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/elements/initia/initia.F, starter/source/elements/spring/rgrhead.F, starter/source/elements/spring/rgrtails.F, starter/source/elements/spring/rinit3.F, starter/source/loads/general/preload/hm_pre_read_preload.F, starter/source/loads/general/preload/hm_read_preload.F, starter/source/loads/general/preload/hm_read_preload_axial.F90, starter/source/starter/lectur.F
new feature of preload of 1d element, part spring type13
=> new option /PRELOAD/AXIAL, part spring13

starter/source/elements/shell/coque/corth3.F, starter/source/elements/shell/coqueba/layini1.F
The use of not Associate pointer and variable not initialized
fixed .
=> DRAPE intialization of pointer

common_source/modules/setdef_mod.F, hm_cfg_files/config/CFG/radioss2024/SETS/set_support.cfg, starter/source/model/sets/clause_init.F, starter/source/model/sets/create_plane_clause.F90, starter/source/model/sets/fill_gr_surf_ellipse.F, starter/source/model/sets/fill_gr_surf_plane.F90, starter/source/model/sets/fill_igr.F, starter/source/model/sets/hm_set.F, starter/source/model/sets/insert_clause_in_set.F, starter/source/model/sets/set_init.F, starter/source/output/qaprint/st_qaprint_set.F
Add new /SET key=PLANE
Add new /SET key=PLANE
=> New SET_GENERAL_key_PLANE

engine/source/assembly/asspar4.F, engine/source/engine/resol.F
Openmp improvement  in asspar4 routine
asspar4 routine modification : 
- element part uses now a dynamic schedule
- single omp region is moved to the beginning of the routine with a NOWAIT condition
=> Openmp improvement : assembly routine asspar4

engine/source/output/h3d/h3d_build_cpp/c_h3d_create_nodal_tensor_datatype.cpp
might get wrong VonMises value of output /H3D/NODA/GPS (GPSTRAIN)
correction of wrong output values.
=> bug fixing of /H3D/GPS(GPSTRAIN) for wrong  VonMises value

engine/source/materials/mat/mat012/m12law.F, engine/source/materials/mat_share/mmain.F, starter/source/initial_conditions/inigrav/inigrav_eos.F, starter/source/materials/mat/hm_read_mat.F, starter/source/materials/mat/mat003/hm_read_mat03.F, starter/source/materials/mat/mat004/hm_read_mat04.F, starter/source/materials/mat/mat005/hm_read_mat05.F, starter/source/materials/mat/mat006/hm_read_mat06.F, starter/source/materials/mat/mat006/hm_read_mat06_keps.F, starter/source/materials/mat/mat010/hm_read_mat10.F, starter/source/materials/mat/mat011/hm_read_mat11.F, starter/source/materials/mat/mat011/hm_read_mat11_k_eps.F, starter/source/materials/mat/mat012/hm_read_mat12.F, starter/source/materials/mat/mat016/hm_read_mat16.F, starter/source/materials/mat/mat018/hm_read_mat18.F, starter/source/materials/mat/mat026/hm_read_mat26.F, starter/source/materials/mat/mat046/hm_read_mat46.F, starter/source/materials/mat/mat049/hm_read_mat49.F, starter/source/materials/mat/mat102/hm_read_mat102.F, starter/source/materials/mat/mat103/hm_read_mat103.F
resolve some backward compatibility problems with material / eos associations
set correct EOS compatibility flags and default EOS values in corresponding material laws
=> correct EOS default values and compatibility flag for hydrodynamic material laws

starter/source/general_controls/computation/hm_read_unit.F
Fix for unitab: trim unitab%nunits to the used size.
Regression introduced in #2394
=> Fix for unitab: trim unitab%nunits to the used size

HOWTO.md
=> Add Build instructions for ARM64 version

hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Ignore conversion of Dyna *DATABASE_SLEOUT
Ignore conversion of Dyna *DATABASE_SLEOUT
=> Ignore conversion of Dyna *DATABASE_SLEOUT

starter/source/groups/elegror.F
when non existing group listed in /SECT card, this can lead to memory issue
check if group is existing before using group arrays
=> correction issue when unexisting group listed in element groups in /SECT

starter/source/elements/initia/initia.F, starter/source/elements/sph/spinit3.F
Computation of nodal contact stiffness for SPH particles
=> SPH : nodal stiffness for contact

starter/source/materials/mat/mat090/law90_upd.F
When the E0 is little than the max of the initial slope of the curve we could leads to instability
Update the E0 accoding to the max of intial slope and alos Emax = Min(Emax_curce, 100*E0)
=> update E0 according to the max of initial curve and Emax

engine/source/materials/fail/fld/fail_fld_c.F, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/elements/elbuf_init/initvars_auto.F
correct possible seg fault in engine with failure models using local damage variable
corrected damage variable allocation in starter in element buffer initialization routine
=> correct local damage variable allocation in failure models

engine/source/output/restart/read_sensors.F, engine/source/output/restart/write_sensors.F
Possible Hang when using MPI  with more than 2 domains
=> /STOP/LSENSOR: Issue with Checkpoint/Restart option.

hm_cfg_files/config/CFG/Keyword971/CONTACT/contact_spotweld.cfg
contact_spotweld.cfg issue correction : MSTYP was not read correctly read
add missing MSTYP parameter
=> contact_spotweld.cfg issue correction : MSTYP was not read correctly read

engine/source/output/h3d/h3d_results/h3d_solid_tensor_1.F
output /H3D/SOLID/TENS/STRAIN_ENG might have precision issue w/ small values
actual algorithm to compute U_FROM_F has been replaced to get right values of engineering total strain output.
=> replace U_FROM_F algorithm due to precision issue for /H3D/SOLID/TENS/STRAIN_ENG

engine/source/materials/mat/mat090/sigeps90.F, hm_cfg_files/config/CFG/radioss2024/MAT/LAW90.cfg, starter/source/materials/mat/mat090/hm_read_mat90.F, starter/source/materials/mat/mat090/law90_upd.F
In tension we follow always the input curve
Adding the new feature, by adding the possibility to follow E0 in tension via Tflag
=> add tension flag for law90

engine/build_windows.bat, engine/source/engine/execargcheck.F, engine/source/engine/radioss_title.F, starter/source/starter/execargcheck.F, starter/source/starter/radioss_title.F
Add Double Precision in Header for Double Precision version Fix  a typo with -helt
Fix a typo in Windows build_script
=> Typo changes

engine/source/output/h3d/h3d_build_fortran/lech3d.F, engine/source/output/h3d/h3d_results/genh3d.F
.F line length > 120 char after re indentation 
correct lech3d.F line length
=> Correction lech3d line length < 120 char

engine/source/elements/solid/solide4/s4coor3.F, starter/source/boundary_conditions/ebcs/iniebcs.F, starter/source/interfaces/inter3d1/i11buc1.F, starter/source/interfaces/inter3d1/i25buc_vox1.F, starter/source/interfaces/inter3d1/i25buce_edg.F, starter/source/interfaces/inter3d1/i7buc_vox1.F, starter/source/materials/tools/nlsqf.F, starter/source/multifluid/multifluid_init2.F, starter/source/multifluid/multifluid_init2t.F, starter/source/multifluid/multifluid_init3t.F, starter/source/spmd/domdec2.F
=> Fixing some Fortran syntax issues.

starter/source/tools/sect/lecsec4bolt.F
IGU was not always initialized
=> /SECT/CIRCLE and /SECT/PARAL, uninitialized variable

engine/source/elements/spring/r23l113def3.F, engine/source/elements/spring/r4def3.F
Fix of failure for prop type13 and MAT113
=> Fix of multiaxial failure

starter/source/elements/initia/initia.F, starter/source/elements/solid/solide/srefsta3.F, starter/source/loads/reference_state/xref/hm_read_xref.F
make compatible of /XREF w/ Isolid=14,18
=> make compatible /XREF with fully integration hexa elements

starter/source/tools/seatbelts/create_seatbelt.F
Fix of error in case MAT_SEATBELT is present but not used
=> Fix is MAT_SEATBELT is not used

starter/source/output/th/write_thnms1.F90
Inconsistency beween : caller/callee routine on VARC argument
=> Issue in Commit ID : cff2711ecba307340f38b936531cc3b16655a42f

engine/source/output/h3d/h3d_build_cpp/c_h3d_create_skins.cpp
H3D external skin building potential bug with possible heap issue
reference to H3D_PART[IPARTQ[i] - 1] without testing if IPARTQ[i] > 0
add test if IPARTQ[i] > 0
=> H3D external skin building potential bug with possible heap issue

hm_cfg_files/config/CFG/UNITS/Units.dat, hm_cfg_files/config/CFG/UNITS/units.cfg, hm_cfg_files/config/CFG/radioss110/CARDS/ioflag.cfg, hm_cfg_files/config/CFG/radioss110/MAT/matl36_plas_tab.cfg, hm_cfg_files/config/CFG/radioss120/DAMP/Damp_Inter.cfg, hm_cfg_files/config/CFG/radioss120/MAT/matl36_plas_tab.cfg, hm_cfg_files/config/CFG/radioss140/MAT/law51_Iflag_4.cfg, hm_cfg_files/config/CFG/radioss140/MAT/law51_Iflag_5.cfg, hm_cfg_files/config/CFG/radioss140/MAT/matl11_b-k-eps.cfg, hm_cfg_files/config/CFG/radioss2017/MAT/matl36_plas_tab.cfg, hm_cfg_files/config/CFG/radioss2019/LOADS/pblast.cfg, hm_cfg_files/config/CFG/radioss2019/MAT/matl49_steinb.cfg, hm_cfg_files/config/CFG/radioss2020/DAMP/Damp_Inter.cfg, hm_cfg_files/config/CFG/radioss2020/MAT/LAW100.cfg, hm_cfg_files/config/CFG/radioss2020/MAT/mat102_DPRAG2.cfg, hm_cfg_files/config/CFG/radioss2020/MAT/mat_law6.cfg, hm_cfg_files/config/CFG/radioss2020/MAT/matl10_law10.cfg, hm_cfg_files/config/CFG/radioss2020/MAT/matl3_hydpla.cfg, hm_cfg_files/config/CFG/radioss2020/MAT/matl4_hyd_jcook.cfg, hm_cfg_files/config/CFG/radioss2021/LOADS/monvol.cfg, hm_cfg_files/config/CFG/radioss2021/LOADS/pblast.cfg, hm_cfg_files/config/CFG/radioss2021/SENSOR/sensor_hic.cfg, hm_cfg_files/config/CFG/radioss2022/FAIL/fail_alter.cfg, hm_cfg_files/config/CFG/radioss2022/LOADS/pblast.cfg, hm_cfg_files/config/CFG/radioss2022/SENSOR/sensor_nic.cfg, hm_cfg_files/config/CFG/radioss2023/CARDS/ioflag.cfg, hm_cfg_files/config/CFG/radioss2023/MAT/mat_EOS.cfg
=> Update CFG files

starter/source/materials/fail/hm_read_fail.F
hm_read_fail.F: inconsistent arguments
=> hm_read_fail.F: inconsistent arguments

engine/source/elements/sh3n/coquedk/cncoef3.F, engine/source/elements/shell/coqueba/cmatc3.F, engine/source/output/dynain/dynain_c_strag.F, engine/source/output/dynain/dynain_c_strsg.F, engine/source/output/sta/stat_c_strafg.F, engine/source/output/sta/stat_c_strsfg.F, engine/source/output/sty/c_tf_ne.F
the size of working table is not enough,the number of plys can't exceed 100
Use the dynamic allocation depending on the number of ply by groupe element
=> Use dynamic allocation for working table

HOWTO.md, tools/anim_to_vtk/README.md, tools/anim_to_vtk/linuxa64/build.bash, tools/th_to_csv/README.md, tools/th_to_csv/linuxa64/build.bash
Arm64 builds : create anim_to_vtk & th_to_csv builds for ARM64 
Some adjustments to the installation instructions to build ARM executable.
=> Arm64 builds : create anim_to_vtk & th_to_csv builds for ARM64 + compiler installation instructions changes. 

engine/source/elements/shell/coque/layini.F, starter/source/elements/shell/coqueba/layini1.F, starter/source/properties/composite_options/stack/lecstack_ply.F, starter/source/stack/stackgroup.F, starter/source/stack/stackgroup_drape.F
It's not identic to Lsdyna Input
change the sens of Z0 for ipos=2
=> reconsidering the position of middle shell surface in the case of Ipos=2

hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_beam_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_discrete_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_shell_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_solid_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_tshell_set.cfg
Activate *DATABASE_HISTORY_XXXX_SET files to enable reading set of parts
Activate *DATABASE_HISTORY_XXXX_SET files to enable reading set of parts
=> Update *DATABASE_HISTORY_XXXX_SET files to enable reading set of parts

hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_beam_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_discrete_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_shell_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_solid_set.cfg, hm_cfg_files/config/CFG/Keyword971_R6.1/OUTPUTBLOCK/database_history_tshell_set.cfg
Update *DATABASE_HISTORY_XXXX_SET CFG files to enable reading set of parts
Update *DATABASE_HISTORY_XXXX_SET CFG files to enable reading set of parts
=> *DATABASE_HISTORY_XXXX_SET CFG files update

engine/source/interfaces/int25/i25dst3_3.F, engine/source/interfaces/int25/i25mainf.F
not zero contact force at T=0 found in interface type 25 w/ special test example of inacti=5 
correction to fix the issue of inacti=5 (interface type25)
=> fixing issue of inacti=5 with interface type25

engine/source/materials/mat/mat122/mat122_newton.F, engine/source/materials/mat/mat122/mat122_nice.F, engine/source/materials/mat/mat122/mat122c_newton.F, engine/source/materials/mat/mat122/mat122c_nice.F, engine/source/materials/mat/mat122/sigeps122.F, engine/source/materials/mat_share/mulaw.F, starter/source/materials/mat/mat122/hm_read_mat122.F
For some critical projects, it was noticed that the damage behavior of /MAT/LAW122 was not fully consistent with theory due to some missing coupling terms. 
Fix the minor differences in /MAT/LAW122.
=> Update /MAT/LAW122 damage coupling

engine/source/materials/mat_share/mulawc.F, engine/source/materials/mat_share/usermat_shell.F
nothing yet
Needed to pass total shear strain component for further correction of Poisson effect in fablic material laws and user subroutines
=> Calculate total shear strain for anisotropic fabric laws 58/158 and orthotropic shell properties

engine/source/materials/mat/mat122/mat122_newton.F, engine/source/materials/mat/mat122/mat122_nice.F, engine/source/materials/mat/mat122/mat122c_newton.F, engine/source/materials/mat/mat122/mat122c_nice.F
Missing parameter in compression young modulus formula in /MAT/LAW122 (important for ongoing projects)
Missing parameter in compression young modulus formula in /MAT/LAW122 (important for ongoing projects)
=> Fix compression Young modulus formula in /MAT/LAW112

engine/build_script.sh, starter/build_script.sh
=> Build_script issue : specific syntax is not understood by some older bash shells

engine/source/implicit/imp_dyna.F, engine/source/implicit/imp_solv.F, engine/source/loads/general/force.F90, engine/source/loads/general/force_imp.F
force.F90 : issue in variable length
After force.F translation in force.F90 : skew length mismatch.
=> force.F90 : issue in variable length

hm_cfg_files/config/CFG/radioss2024/OUTPUTBLOCK/th_part.cfg, hm_cfg_files/config/CFG/radioss2024/OUTPUTBLOCK/th_subs.cfg
update th_part & th_subs cfg files
=> update th_part & th_subs cfg files

hm_cfg_files/config/CFG/radioss2024/PROP/prop_p18_int_beam.cfg
Update of cfg file for new sections of integrated beams
=> Update of cfg for integrated beam

engine/source/fluid/flow1.F, engine/source/tools/curve/vinter.F
Out-ouf-bound access to IFLOW in flow1.F
Possible out-of-bound access to TF, depending on the execution order of the if conditions
=> Fix bugs found using Asan

common_source/modules/setdef_mod.F, hm_cfg_files/config/CFG/radioss2024/SETS/set_support.cfg, starter/source/model/sets/clause_init.F, starter/source/model/sets/create_nodens_clause.F90, starter/source/model/sets/fill_igr.F, starter/source/model/sets/hm_set.F, starter/source/model/sets/insert_clause_in_set.F, starter/source/model/sets/set_init.F, starter/source/output/qaprint/st_qaprint_set.F
Add group of NODENS to the /SET/GENERAL
Add group of NODENS to the /SET/GENERAL
=> Add group of NODENS to the /SET/GENERAL

engine/source/output/anim/generate/dfuncc.F
A segfault issue in animation files generation has been detected when using /MAT/LAW25. 
Fix the segfault issue to print correctly  the damage variable.
=> Fix segfault issue with composite animation

engine/source/materials/fail/alter/fail_wind_frwave.F, starter/source/materials/fail/fractal/fractal_dmg_init.F90, starter/source/materials/fail/fractal/random_walk_dmg.F90
damaged element Id's were not correct in case of mixed 3n and 4n shell element mesh
corrected element index in the list copied from random walk structure to the element buffer
added check of already damaged elements in the loop of starting points
cleaned print-outs with debug option
=> /FAIL/FRACTAL_DMG : correct initially damaged element list

starter/source/elements/nodes/merge_bucket_search.F, starter/source/elements/nodes/merge_node.F, starter/source/elements/reader/hm_read_merge_node.F
Modification of /MERGE/NODE criteria
=> Fix of merge node

engine/source/output/anim/generate/aninflow.F
possible overflow in ANINFLOW routine
when using /BEM/FLOW and output nodal pressure in animation file
bad address correction
=> possible overflow in ANINFLOW routine

common_source/modules/skew_mod.F90
when a type calls another type, it must be defined before the main type
=> Issue on ARM build :

common_source/modules/cast_mod.F90, engine/source/airbag/fvbag1.F, engine/source/airbag/fvtemp.F, engine/source/mpi/airbags/spmd_fvb_gath.F
Fix floating point exceptions in sp for FVMBAGS
=> FVMBAGS: fix floating point exceptions in sp

engine/source/materials/fail/gene1/fail_gene1_c.F, engine/source/materials/fail/gene1/fail_gene1_s.F
Potential checkbounds issue due to a division by 0 was raised in /FAIL/GENE1
Avoid the division by zero at the beginning of the simulation
=> Fix potential division by 0 in /FAIL/GENE1

HOWTO.md
Fixed a typo in the documentation
=> fix typo in howto

engine/source/output/th/thquad.F
NEL was used before being initialized in the computation of JJ
=> Fix for TH for ALE

engine/source/implicit/imp_dyna.F, engine/source/implicit/imp_solv.F
fix following commits e7d9ac1005208101d336efe5d2bf0ce12b3a28ee(/TH/SURF) & fd8473f92dd8fdcc5b5ba1de7e173b17d6f24d97(SKEWS) . Bug is specific to implicit solver. Explicit solver had not been impacted.
=> /IMPLICIT /EIG : fix issue in implicit solver

hm_cfg_files/config/CFG/radioss130/TABLE/inibri_fail_sub.cfg
Update cfg of /INIBRI/FAIL option
Update cfg of /INIBRI/FAIL option. Correction of GUI.
=> Update cfg of /INIBRI/FAIL option

engine/source/ale/alemain.F, engine/source/elements/forint.F, engine/source/elements/solid/solide/s11fx3.F, engine/source/elements/solid/solide/sforc3.F, engine/source/elements/solid/solide4/s4forc3.F, engine/source/engine/resol.F
Wrong dimensioning if IXS array in s11fx3.F routine
=> Issue in Commit: 25277a59edd2687c30beda6cacf1a3912039bcd5

engine/source/materials/mat/mat083/sigeps83.F
avoid NAN in output of law83 depending on input parameter settings
Correction of potential mathematical singularities in plastic projection, depending of loading ans stress values
=> Correction of numerical singularity in material law83

engine/source/materials/mat/mat126/sigeps126.F90, engine/source/materials/mat_share/mulaw.F, starter/source/materials/mat/mat126/hm_read_mat126.F90
There is a need to make the recently added /MAT/LAW126 compatible with non-local regularization. 
Add compatibility with non-local regularization.
=> Add non-local regularization to /MAT/LAW126

engine/source/output/dynain/dynain_c_strag.F, engine/source/output/dynain/dynain_c_strsg.F, engine/source/output/sta/stat_c_strafg.F, engine/source/output/sta/stat_c_strsfg.F, engine/source/output/sty/c_tf_ne.F
Computation fails with segfault
Deallocate only the allocate table
=> fix bug /STATE/SHELL/../GLOBAL option

engine/CMake_Compilers/legacy_fortran.cmake, engine/source/engine/resol.F, engine/source/engine/resol_init.F, engine/source/interfaces/shell_offset/inter_offset_ini.F90, engine/source/interfaces/shell_offset/offset_nproj.F90, engine/source/modules/interfaces/sh_offset_mod.F90, engine/source/mpi/nodes/spmd_exch_vnpon.F90
Parith/on now available for shell offset supporting contact option
=> make Parith/on available for shell offset supporting contact

engine/source/interfaces/shell_offset/offset_nproj.F90, hm_cfg_files/config/CFG/radioss2024/CARDS/def_shell.cfg, starter/source/general_controls/default_values/hm_read_defshell.F
remove debug option Ioffset=3 for shell offset and fixing also potential bug in offset projection
=> remove Ioffset=3 for shell offset

starter/source/model/box/rdbox.F
check if a node is inside/ouside cylinder was wrong
recompute distance from axis
=> issue correction in box cylinder : check for node inside or outside was incorrect

engine/source/engine/resol.F
Rad2rad did not terminate after End of Time, but Hanged.
=> Bug in commit: db6846f78e35109dd05011d70bd48ba1af81c11d  with rad2rad

starter/source/tools/curve/hm_read_move_funct.F
correction MOVE_FUNC + TABLE option with negative x scale factor
negative scale factor was badly taken into account in case function was referenced in /TABLE
=> correction MOVE_FUNC + TABLE option with negative x scale factor

starter/source/spmd/domain_decomposition/c_domain_decomposition.cpp
=> bug fix for splipring (SPMD)

engine/source/engine/resol.F, engine/source/interfaces/shell_offset/inter_offset_ini.F90
OpenRadioss may hang when using large number of SPMD domain w/ partial offset shell in the model
correction to fix the SPMD issue of shell offset supporting contact
=> fix SPMD issue of shell offset supporting contact option

qa-tests/CMakeLists.txt, qa-tests/miniqa/AMS/auto_element_selection/data/test_files.json, qa-tests/miniqa/AMS/boxbeam/data/test_files.json, qa-tests/miniqa/INTERF/INT_22/1D_U-SURF_9ELEMS_LAW6_Linear_EOS_EULER_0.FVM/data/test_files.json, qa-tests/qa_tools/execute_solver.py, qa-tests/qa_tools/miniqa.txt, qa-tests/qa_tools/or_execute.py, qa-tests/qa_tools/qa_system.py, qa-tests/qa_tools/verify_results.py, qa-tests/test_script.bash, qa-tests/test_script.bat
Add :
-pon and -pon_run option in .bat and .bash script
run each example and compare checksums
3 test cases are not compatible with pon tests, add filter to skip them
=> QA test suite with Ctest : add parallel arithmetic functionality

engine/CMake_Compilers/cmake_linux64_intel.txt, engine/CMake_Compilers/cmake_linux64_intel_ifx.txt, engine/CMake_Compilers/cmake_win64.txt, engine/CMake_Compilers/cmake_win64_ifx.txt
The level of optimization of admmap4 is now reduced to -O2 to bypass a compiler issue
=> Fix a compiler issue in admmap4 routine

engine/source/elements/solid/sconnect/smom43.F, engine/source/elements/solid/sconnect/suser43.F, engine/source/materials/mat/mat169/sigeps169_connect.F90, starter/share/modules1/elbuftag_mod.F, starter/source/elements/elbuf_init/ini_mlaw_vars.F, starter/source/elements/elbuf_init/initvars_auto.F, starter/source/elements/elbuf_init/suinit3.F, starter/source/elements/solid/sconnect/spcoor3.F, starter/source/materials/mat/mat169/hm_read_mat169.F90
Add thickness calculation for cohesive element and add thickness variable in element buffer
=> Add thickness calculation for cohesive

engine/source/materials/mat/mat125/sigeps125c.F90, engine/source/materials/mat_share/mulawc.F, hm_cfg_files/config/CFG/radioss2024/MAT/matl125_laminated_composite.cfg, hm_cfg_files/config/CFG/radioss2024/data_hierarchy.cfg, starter/source/elements/initia/initia.F, starter/source/elements/shell/coque/set_elgroup_param.F, starter/source/materials/mat/hm_read_mat.F, starter/source/materials/mat/mat125/hm_read_mat125.F90
Only Law25 was used before, but is not enough 
New material law for composite. It's  Mat058 of lsdyna.
=> Laminated Mat058 lsdyna composite material model

starter/source/elements/elbuf_init/init_mlaw_tag.F
correct bug thickness THK in buffer - missing initialization
=> correct thickness THK in buffer

engine/source/elements/sph/spcompl.F, engine/source/elements/sph/sphprep.F
SPH - fix of IORDER=1 with SOL2SPH and SPMD
=> SPH order=1 - fix SPMD issue

engine/source/elements/sh3n/coquedk/cncoef3.F
Error check bound  due ro not initialized variable
The variable is defined.
=> intialization of variable

starter/source/elements/initia/initia.F
an argument missed in 0a761c07f0a30340ed3a0c7f7a18b1f8f271ce6f, model using Penta6 thick shell may fail w/ Starter. 
correction of fixing
=> correction on 0a761c07f0a30340ed3a0c7f7a18b1f8f271ce6f  of a missed argument

starter/source/elements/solid/solide10/s10init3.F
correction to fix missed argument in 0a761c07f0a30340ed3a0c7f7a18b1f8f271ce6f concerning tet10
=> argument missed in 0a761c07f0a30340ed3a0c7f7a18b1f8f271ce6f for tet10

starter/source/output/qaprint/st_qaprint_general_controls.F
correction of 0a761c07f0a30340ed3a0c7f7a18b1f8f271ce6f to fix not-initialized value in qaprint
=> correction of 0a761c07f0a30340ed3a0c7f7a18b1f8f271ce6f  for qaprint

engine/source/materials/mat/mat036/sigeps36.F, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/mulaw8.F, starter/source/materials/mat/mat036/hm_read_mat36.F, starter/source/materials/mat/mat044/hm_read_mat44.F
Material law36 is added to EOS compatibility list
Added necessary changes in law36 : deviatoric stress calculation and sound speed correction with EOS
=> /MAT/LAW36 : compatibility with /EOS

engine/source/materials/mat/mat125/sigeps125c.F90, starter/source/materials/mat/mat125/hm_read_mat125.F90
Variable not defined leading to NaN 
Enhancement by setting default values of damage parameters .
=> enhancement of law125 and add default value

common_source/modules/setdef_mod.F, starter/share/modules1/inverted_group_mod.F, starter/source/model/sets/clause_init.F, starter/source/model/sets/compute_connect_partelm.F, starter/source/model/sets/create_element_from_part.F, starter/source/model/sets/create_node_from_element.F, starter/source/model/sets/hm_set.F, starter/source/model/sets/inverted_group_alloc.F, starter/source/model/sets/inverted_group_dealloc.F, starter/source/model/sets/inverted_group_init.F, starter/source/model/sets/set_init.F, starter/source/model/sets/tag_node_from_part_sphcel.F90, starter/source/starter/lectur.F
Build /SET from part of /SPHCEL
Build /SET from part of /SPHCEL
=> Create SET of nodes from SPHCEL part

hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg, starter/source/starter/starter0.F
ENABLE INPUT FORMAT 2025
add radioss2025 directory + datahierarchy.cfg file
=> ENABLE INPUT FORMAT 2025

qa-tests/test_script.bash, qa-tests/test_script.bat
Typos and copy-paste error in qa scripts can lead to confusion
Fixed small typos and copy-paste error in qa-scripts
=> fix typos in qa-scripts

starter/source/elements/initia/lec_inistate_tri.F
correction issue with Y file initialisation with SPH element
=> correction issue with Y file initialisation with SPH element

starter/source/model/sets/compute_connect_partelm.F, starter/source/starter/lectur.F
Correct building SET from SPHCEL
Correct building SET from SPHCEL
=> Correct building SET from SPHCEL

common_source/modules/interfaces/intbuf_fric_mod.F90, engine/source/materials/mat_share/mulaw.F90, scripts/headers.py
exclude 'extlib' directory
bug fix for module procedure
update indetation for F90 files
header update for Fortran function support
=> update python script to generate headers

engine/source/materials/fail/fail_setoff_c.F, engine/source/materials/fail/fail_setoff_npg_c.F, engine/source/materials/mat_share/mulawc.F, engine/source/materials/mat_share/usermat_shell.F
There was a request to add the failure criterion name for element deletion messages. 
Add the name of failure criterion for element deletion messages.
=> Improve element deletion message with failure criterion names

engine/source/materials/mat/mat087/mat87c_tabulated_totalsr.F
An instability has been reported when using /MAT/LAW87 with QEPH shell elements formulation. 
Fix the ETSE factor computation in the material law.
=> Fix bug of law 87 with QEPH shell formulation

scripts/headers.py
Skip header for INTERFACE blocks
=> fix header for INTERFACE blocks

engine/source/materials/mat_share/mmain.F90, scripts/headers.py
small fix for header creation
+reindent mmain.F90 to be compatible with headers.py
=> fix header for functions in interface blocks

engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
Issue reported affecting some specific outputs option for LAW25 leading to potential ASAN error. 
Replace the LBUF%DAM table by the new LBUF%DMG table in outpout.
=> Fix output issue for LAW25

engine/source/materials/mat/mat042/sigeps42.F, engine/source/materials/mat/mat042/sigeps42c.F, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/mulaw8.F, engine/source/materials/mat_share/mulawc.F, hm_cfg_files/config/CFG/radioss2025/MAT/matl42_Ogden.cfg, starter/source/elements/sh3n/coque3n/c3derii.F, starter/source/elements/sh3n/coquedk/cdkderii.F, starter/source/elements/shell/coque/cdleni.F, starter/source/elements/shell/coqueba/cndleni.F, starter/source/materials/mat/hm_read_mat.F, starter/source/materials/mat/mat042/hm_read_mat42.F, starter/source/materials/mat/mat042/law42_upd.F, starter/source/materials/mat/mat042/sigeps42.F, starter/source/materials/mat_share/mulaw.F, starter/source/materials/updmat.F
activation of new input for Ogden material model, 10 terms are now available instead of 5
add new input in cfg file and hm_read routine
modified algorithm codes using parameter tables instead of scalar values
replaced old parameter storage in bufmat by new mat_param structure
=> /MAT/LAW42 : allow new input with 10 Ogden model terms instead of 5

hm_cfg_files/config/CFG/radioss2025/PROP/prop_p1_shell.cfg
/PROP/SHELL : remove ISTRAIN parameter in CFG file from version 2024
/PROP/SHELL : remove ISTRAIN parameter in CFG file from version 2024
=> /PROP/SHELL : remove ISTRAIN parameter in CFG file from version 2024

hm_cfg_files/config/CFG/radioss2024/PROP/prop_p1_shell.cfg
Remove ISTRAIN parameter in CFG file from version 2024
Remove ISTRAIN parameter in CFG file from version 2024
=> Remove ISTRAIN parameter in CFG file from version 2024

hm_cfg_files/config/CFG/radioss2025/CARDS/def_solid.cfg
=> correction Icontrol in def_solid cfg file

engine/source/materials/mat/mat025/m25law.F, engine/source/materials/mat/mat025/mat25_crasurv_s.F90, engine/source/materials/mat/mat025/mat25_tsaiwu_s.F90, engine/source/materials/mat_share/mmain.F90
The plastic strain is not correctly computed.
The 2D computing of plastic strain is Added as  for shell
=> wrong plastic behavior for mat25 and solid

engine/source/materials/mat/mat002/m2law.F, engine/source/materials/mat_share/mmain.F90, starter/source/materials/mat/mat002/hm_read_mat02.F
Jonhson-Cook material (LAW02) is now compatible wioth /EOS
added compatibility flag in starter
modified sound speed calculation and removed pressure calculation in engine when EOS is defined
=> /MAT/LAW02 : add compatibility with /EOS option

starter/source/materials/mat/mat042/law42_upd.F
Lprony + iform = 1 not working correctly
Update the material buffer
=> lprony + iform=1 and law 42 don't working correctly

tools/th_to_csv/README.md
=> fix copy-paste mistake in th_to_csv documentation

engine/source/elements/solid/solide8e/s8edefot12.F, engine/source/interfaces/int25/i25for3.F, engine/source/materials/mat/mat071/sigeps71.F, engine/source/materials/mat/mat100/sigpoly.F, engine/source/output/sta/stat_c_fail.F, starter/source/materials/mat/mat125/hm_read_mat125.F90
Fix compiler warnings about tabulation and uninitialized variable
=> Fix some compiler warnings

engine/source/mpi/python_spmd_mod.F90
=> /FUNCT_PYTHON: wrong use for NAME_LEN

starter/source/elements/shell/shell_offset/sh_offset_jonkt_chk.F90, starter/source/elements/shell/shell_offset/shell_offsetp.F90
Correction on the shell junction treatments in shell offset for contact  with high junction numbers
=> correction on shell offset for contact w/ special junction case

common_source/tools/clipping/polygon_clipping_mod.F90, starter/source/initial_conditions/inivol/init_inivol_2D_polygons.F90
The /INIVOL option initializes volume fractions using specified surfaces, which can include 3D shells, 2D segments, ellipsoids, or infinite planes. The user defines these surfaces along with submaterial identifiers to fill one side of the surface with the desired ratio.
For 2D cases, a clipping algorithm trims elements using the user-defined polygon. If polygon vertices align with mesh edges, this presents a limitation in the Weiler-Atherton algorithm. Introducing a tolerance resolves this issue.
=> INIVOL 2D / CLIPPING ALGO : manage degenerated cases with tolerance

engine/source/output/h3d/h3d_build_cpp/c_h3d_eroded_oned.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_eroded_quad.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_eroded_shell.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_eroded_skin.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_eroded_solid.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_eroded_sph.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_nodal_fvmbag_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_nodal_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_nodal_tensor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_nodal_vector.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_oned_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_oned_tensor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_oned_torsor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_oned_vector.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_quad_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_quad_tensor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_quad_vector.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_shell_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_shell_tensor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_shell_vector.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_skin_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_skin_tensor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_skin_vector.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_solid_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_solid_tensor.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_solid_vector.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_sph_scalar.cpp, engine/source/output/h3d/h3d_build_cpp/c_h3d_update_sph_tensor.cpp
replaced NULL by 0 when needed
=> warning in h3d: NULL was used as an integer

engine/source/materials/mat_share/mulaw8.F
Missing argument for sigeps44 in mulaw8.F. 
Add the missing argument.
=> Add missing argument for LAW44 in mulaw8.F

engine/source/output/anim/generate/dfuncf.F
Beam Type 18 + Animation issue : possible failure when Beam type18 has void material
Tries to access non existent array.
=> Beam Type 18 + Animation issue : possible failure when Beam type18 has void material

engine/source/user_interface/suforc3.F, starter/source/elements/elbuf_init/suinit3.F
Wrong buffer is used fir UVAR in user subroutines in Starter & Engine. The result is App crash when user properties are used.
=> Issue in User Properties (using in user libraries) : 

starter/source/restart/ddsplit/w_front.F
4395dc68a9e8ee0f618cd1fb905244c29df13ed5 optimized a quadratic treatment in the starter, but an issue was introduced
Fix the issue
=> Rwall option : fix an issue introduced by 4395dc68a9e8ee0f618cd1fb905244c29df13ed5

hm_cfg_files/config/CFG/radioss2024/MAT/LAW169.cfg
radioss law 169 cfg issue
remove character in "$ SHRMAX GCSHR PWRT PWRS SHRP SHT_SL" line
=> radioss law 169 cfg issue

engine/source/output/h3d/h3d_results/h3d_sol_skin_scalar.F, engine/source/output/h3d/h3d_results/h3d_sol_skin_scalar1.F
Fix checkbounds/asan issues for /FAIL/FLD output
Fix checkbounds/asan issues for /FAIL/FLD output
=> Fix checkbounds/asan issues for /FAIL/FLD output

starter/source/materials/fail/fld/hm_read_fail_fld.F
Uninitialized frequency that is conditionally read in the input. 
Uninitialized frequency that is conditionally read in the input.
=> Fix uninitialized frequency

engine/source/ale/grid/alew7.F
An issue was discovered when using SUBMODELING option (ROTATION) with /ALE/GRID/FLOW-TRACKING option. It is now fixed.
=> /ALE/FLOW-TRACKING+SUBMODEL ROTATION

engine/source/interfaces/shell_offset/inter_offset_ini.F90
issue of spmd (np>1) might be obtained with special model of shell junctions where part of them have offset
correction to fix spmd issue of shell offset for contact
=> fix spmd issue of shell offset supporting contact

engine/source/materials/mat_share/usermat_solid.F
=> Transfer DVOL to userlaw

engine/source/elements/solid/solidez/szforc3.F, engine/source/elements/solid_2d/quad/qforc2.F, engine/source/elements/solid_2d/quad4/q4forc2.F
possible core dumpi in engine with 2D quad elements
corrected argument list in qforc2 routine
=> correct argument list in qforc2

engine/source/airbag/init_global_monvol_frontier.F90, engine/source/airbag/init_monvol_omp_structure.F90
The array %NORMAL was not allocated for airbag /TYPE1
Allocate the array for this kind of airbag
=> Fix an issue with the airbag /TYPE1 introduced by a1a952b81d56d019a1732512fa3fcbf6269113aa

starter/source/model/sets/shell_surface_buffer_remesh.F
Using adaptative meshing 
issue creating surface from 3 node shells in /SET mechanism
=> issue creating surface from 3 node shells in /SET mechanism

engine/source/elements/solid/solide8z/mmats.F
implict non converging with material law 42
Bulk stiffness in implicit code was read in old parameter buffer, it's corrected using actual PM value
=> Correct implicit code with law42 after parameter storage refactoring

starter/source/starter/lectur.F
might get reading issue after 334230b8eb2b36300d00ceba4a9c39ff1688782c 
fix regression issue
=> regression due to 334230b8eb2b36300d00ceba4a9c39ff1688782c

engine/source/ale/alemain.F, engine/source/materials/mat/mat036/sigeps36c.F, engine/source/materials/mat_share/mulawc.F
Fix some missing or unmatching number of arguments
Fix some missing or unmatching number of arguments
=> Fix some missing arguments

common_source/comm/stacksize.cpp
=> Try to increase stakcsize to max available. If fails increase ulimit -s

engine/source/elements/elbuf/copy_elbuf_1.F, engine/source/mpi/nodes/spmd_exch_vnpon.F90, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/elements/initia/initia.F
small changes after some test results on shell offset supporting contact.
=> small changes in shell offset supporting contact

starter/source/elements/beam/pinit3.F, starter/source/elements/initia/initia.F, starter/source/elements/spring/rinit3.F, starter/source/elements/truss/tinit3.F
potential Starter failing with /PRELOAD/AXIAL 
correction check bounds issues in /PRELOAD/AXIAL
=> correction check bounds issues in /PRELOAD/AXIAL

common_source/tools/memory/extend_array.F90, engine/CMake_Compilers/cmake_linux64_gf.txt, engine/share/modules/inter_sorting_mod.F, engine/share/modules/inter_struct_mod.F, engine/source/interfaces/generic/inter_prepare_sort.F, engine/source/interfaces/int07/inter_sort_07.F, engine/source/interfaces/intsort/fill_voxel.F90, engine/source/interfaces/intsort/inter7_candidate_pairs.F90, engine/source/interfaces/intsort/inter7_collision_detection.F90, engine/source/interfaces/intsort/voxel_dimensions.F90, engine/source/mpi/generic/spmd_cell_exchange.F, engine/source/mpi/interfaces/spmd_cell_list_exchange.F, engine/source/mpi/interfaces/spmd_wait_nb.F, starter/build_script.sh, template/template.F90
Extract the non OpenMP parallel computations from the part to be ported on GPUs. Those computation (assign nodes to voxels) can be overlapped by MPI communications
=> Review MPI comminucation pattern when -preview is provided

engine/source/materials/mat/mat002/m2law8.F
correct possible coredump in engine using old solid elements with law2 and rhocp = 0
corrected numerical issue of division by zero
=> correct division by zero error in m2law8.F

starter/source/materials/mat/mat051/hm_read_mat51.F, starter/source/output/qaprint/st_qaprint_materials.F
update following https://github.com/OpenRadioss/OpenRadioss/pull/2967 (effect on output with QAprint only)
=> st_qaprint_materials : update

engine/source/constraints/general/rbody/rgbodfp.F
=> RBODY fix rotation of principal inertia skew

starter/source/model/sets/fill_igr.F
Correction of /SET/GENERAL with NODENS used with /INTER/TYPE8 
Activate %SORTED in the nodens group created by SET
=> /SET/GENERAL : starter error in /INTER/TYPE8 with key NODENS

engine/source/constraints/general/rbe2/rbe2_imp0.F, engine/source/constraints/general/rbe2/rbe2v.F
might get wrong result using RBE2 with skew in some special cases
correction of RBE2 using skew of special cases.
=> correction special case of RBE2 using local skew

engine/source/materials/fail/johnson_cook/fail_johnson.F, starter/source/materials/fail/johnson_cook/hm_read_fail_johnson.F
The was a need to add additional option for post-failure behavior of solid elements using /FAIL/JOHNSON. 
Add ifail_so = 3 and 4 to answers the dev specs.
=> New Ifail_so value available for /FAIL/JOHNSON

hm_cfg_files/config/CFG/radioss2025/MAT/matl125_laminated_composite.cfg, starter/source/materials/mat/mat125/hm_read_mat125.F90
We have difference in the attributs compared to Lsdyna
It's better to keep the same attributs ot facilitate the converson one  to one.
=> fix the diff of cfg file for Law125

hm_cfg_files/config/CFG/radioss2025/MAT/matl2_plas_johns.cfg, starter/source/materials/mat/mat002/hm_read_mat02.F
Added new input parameter - Tmax
Corrected unit conversion of Pmin
Updated cfg file with unit correction for Pmin
Added Tmax in input and cfg file
=> Add missing unit definition for Pmin in law2 cfg file

engine/source/elements/solid/solide/s_hg5.F, engine/source/elements/solid/solide/sforc3.F, engine/source/elements/solid/solidez/shour_ctl.F90, engine/source/elements/solid/solidez/szforc3.F, engine/source/elements/solid/solidez/szhour_ctl.F
might get unstable result when using distortion control for model using law90.
adjust stiffness of distortion control (hourgalss) and taking into account higher stiffness for time step compute
=> adjust stiffness of disortion control w/ law90

starter/source/materials/mat/hm_read_mat.F
Fix checkbounds issue LAW2
Fix checkbounds issue LAW2
=> Fix checkbounds issue LAW2

engine/source/constraints/general/rbe3/rbe3f.F
may get unstable issue when using RBE3 with long arm (distance between dependent and independent nodes) 
correction to fix instability issue of RBE3
=> fix instability issue of RBE3

hm_cfg_files/config/CFG/radioss2025/FAIL/fail_johnson.cfg
Update Johnson failure .cfg file 2025 format
Update Johnson failure .cfg file 2025 format
=> Update Johnson failure .cfg file 2025 format

starter/source/interfaces/int24/hm_read_inter_type24.F, starter/source/interfaces/int25/hm_read_inter_type25.F
remove hide option Inacti=1,3 in interface type24,25
=> remove hide option Inacti=1,3 in interface type24,25

starter/source/interfaces/inter3d1/i25trivox_edg.F, starter/source/interfaces/interf1/lecint.F
The dimensions of several arrays were wrong 
A condition was missing for the remnode algo + interface type25 + iedge/=0
Fix the dimensions
Fix the condition issue
=> Fix several issues related to the interface /TYPE25

engine/source/output/h3d/h3d_build_fortran/lech3d.F
Some Interfaces do not have Remote Secondary Node buffers
=> Error in c697016e4ef987aff9a825bc5e1899cfb7f366f6 : 

engine/source/output/anim/generate/genani.F
possible issue with anim dt & airbag
possible segmentation violation in animation file 
possible issue with anim dt & airbag
=> possible issue with anim dt & airbag

starter/source/materials/mat/mat125/hm_read_mat125.F90
init some non initialized values 
ef11t ef22t ef33t
=> non init value issue in mat125

engine/source/elements/solid/sconnect/suser43.F, engine/source/materials/mat/mat169/sigeps169_connect.F90, hm_cfg_files/config/CFG/radioss2025/MAT/LAW169.cfg, starter/source/materials/mat/mat169/hm_read_mat169.F90
changes of input format with respect to first integration
changes of input and formulation to better respect dyna2rad conversion rules
=> Law 169 : input cfg file and formulation change

hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Activate conversion of Dyna *MAT_122 in hierarchy.cfg file.
Activate conversion of Dyna *MAT_122 in hierarchy.cfg file.
=> Activate conversion of Dyna *MAT_122

common_source/eos/eoslinear.F, common_source/eos/eosmain.F, engine/source/materials/mat/mat004/m4law.F, engine/source/materials/mat_share/mmain.F90, starter/source/materials/mat/mat004/hm_read_mat04.F
the temperature calculation in law4 was completely wrong
Corrected temperature calculation in 2 cases : /heat/mat and with no EOS defined
=> Correct thermal behavior of law4 without EOS and with linear EOS

engine/source/materials/fail/johnson_cook/fail_johnson.F
Bound damage value to 1 for /FAIL/JOHNSON to avoid confusing post treatment. 
Bound damage value to 1 for /FAIL/JOHNSON to avoid confusing post treatment.
=> Bound damage value to 1 for /FAIL/JOHNSON

starter/source/elements/joint/rjoint/rini45.F
number of arguments not consistent with warning message
=> Fix of warning message for joints

starter/source/elements/joint/rjoint/rini45.F
fix of orientation of skew1 and skew2 for kjoints
=> KJOINTS orientation fix

engine/source/materials/mat/mat169/sigeps169_connect.F90
avoid spurious and multiple damage and failure messages in engine output file
added print blocking between threads
modified damage and failure message output criteria
=> update damage criteria printout in material law169

starter/source/elements/joint/rjoint/rini45.F
Fix of condition for alignement
=> KJOINTS initial rotation fix

CONTRIBUTING.md, HOWTO.md, README.md, RELEASES.md, Stable_code.md, doc/Visual_Studio_Debugger.md, tools/anim_to_vtk/README.md, tools/th_to_csv/README.md
Correct spelling and grammar in various markdown files.
=> Fix grammar and spelling in markdown files

starter/source/materials/mat/mat093/hm_read_mat93.F, starter/source/materials/mat/mat107/hm_read_mat107.F, starter/source/materials/mat/mat112/hm_read_mat112.F, starter/source/materials/mat/mat122/hm_read_mat122.F
wrong error message for orthotropic law
adding the correct checking of poisson ratio
=> check poisson ratio for orthotropic law 93, 107 and 112

engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/usermat_solid.F, starter/source/materials/mat/mat028/hm_read_mat28.F
user material laws did not work correctly with orthotropic solids
corrected problem of stress update in rotated orthotropic directions
corrected obsolete call to old  orthotropic skew orthogonalization routine
cleaned obsolete user material code
=> Correction of user material laws for orthotropic solids

engine/source/elements/forintc.F, engine/source/elements/sh3n/coque3n/c3forc3.F, engine/source/elements/sh3n/coquedk/cdkforc3.F, engine/source/elements/sh3n/coquedk6/cdk6forc3.F, engine/source/elements/shell/coque/cforc3.F, engine/source/elements/shell/coqueba/cbaforc3.F, engine/source/elements/shell/coquez/czforc3.F, engine/source/elements/xfem/c3forc3_crk.F, engine/source/elements/xfem/cforc3_crk.F, engine/source/elements/xfem/czforc3_crk.F, engine/source/engine/resol.F, engine/source/materials/mat/mat127/sigeps127c.F90, engine/source/materials/mat_share/cmain3.F, engine/source/materials/mat_share/mulawc.F, hm_cfg_files/config/CFG/radioss2025/MAT/matl127_enhanced_composite.cfg, starter/source/materials/mat/mat127/hm_read_mat127.F90
The chang chang model can't not be used with law127 using /FAIL
adding the chang chang model and failure based on strain in the law127
=> adding failure model for law127

common_source/tools/math/precision.c, common_source/tools/sort/my_orders.c, starter/source/output/analyse/analyse_read_tools.c, starter/source/user_interface/dyn_userlib.c
Clean C code to be compliant with more modern C
=> Adjust C code to be complaint with c11

hm_cfg_files/config/CFG/Keyword971/CONTACT/contact_spotweld.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_automatic_general.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_automatic_single_surface.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_automatic_surface_to_surface.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_force_transducer_penalty.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_option_nodes_to_surface.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_option_single_surface.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_option_surface_to_surface.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/contact_tiebreak_nodes_only.cfg, hm_cfg_files/config/CFG/Keyword971_R11.1/CONTACT/nodes_to_surface.cfg, hm_cfg_files/config/CFG/Keyword971_R13.0/CONTACT/contact_airbag_single_surface.cfg
Activate reading _TITLE option in *CONTACT Dyna cards
Activate reading _TITLE option in *CONTACT Dyna cards
=> Activate reading _TITLE option in *CONTACT Dyna cards

starter/source/materials/fail/fractal/fractal_element_neighbor.F90, starter/source/materials/fail/windshield_alter/brokmann_random.F90
avoid problem with /fail/alter and /fail/fractal_dmg using property type 11
corrected non initialized variable npt in case of property type 11
=> correct non initialized variable in starter for /fail/alter and /fail/fractal_dmg

common_source/eos/eosmain.F, engine/source/engine/resol.F, engine/source/interfaces/intsort/i10main_tri.F, engine/source/interfaces/intsort/i7main_tri.F, engine/source/materials/mat/mat075/sigeps75.F, engine/source/mpi/interfaces/spmd_i25slide.F, starter/source/model/assembling/hm_read_part.F
Arguments missings in 3 calls
INTENT IN/INOUT issues in several routines
=> Issues in somme routines calls : 

engine/source/elements/solid/solide/sdistror_ini.F90, starter/source/interfaces/interf1/stifint_icontrol.F90
small corrections on solid distortion control after tests
=> modif in distortion control

engine/source/materials/mat/mat075/sigeps75.F
=> Missing Argument in sigeps75.F

engine/source/elements/sh3n/coque3n/c3forc3.F, engine/source/elements/shell/coqueba/cbaforc3.F
possible error with 3nshells or Batoz shells using /heat/mat
corrected non initialized local variables
=> correct non initialized local variables used in thermal options for shells

starter/source/interfaces/inter3d1/i7buc_vox1.F, starter/source/interfaces/inter3d1/i7trivox1.F
Checkbound issue introduced by cabe3227ab7e4326d46537150cf6b05a3be809cc
Use the global number of segment instead of the local number of segment (local to the processor)
=> Checkbounds issues (starter) : the size of IRECT was wrong

common_source/modules/cpp_python_funct.cpp
min/max macros interfering with std lib
=> fix windows build

starter/source/elements/reader/hm_read_solid.F
renumbering of tetra10 in case of negative volume
=> INTER/TYPE25 - renumbering of tetra10 in case of negative volume

engine/source/mpi/implicit/imp_spmd.F
Prepare the code for automatic switch to OOC if mumps memory estimation is  larger than avail memory.
=> preparation of autmatic switch to OOC when not enough memory

engine/source/engine/resol.F, engine/source/interfaces/int24/i24for3e.F
option shell offset support contact might not be P/ON (np>1) for some cases.
fix P/ON issue of shell offset support contact
=> fix P/ON issue of shell offset support contact

engine/source/elements/solid/solide4_sfem/s4voln_m.F
b811635531c8391a7720d9728887e4b56f4fde14 is introducing a compiler issue on Windows in _s4voln_m.F_
Array size :  _integer,intent(in) ::  S_SFEM_NODVAR_
is declared before the declaration of : _my_real,intent(inout) SFEM_NODVAR( S_SFEM_NODVAR )_
=> Windows compiler issue

starter/source/initial_conditions/general/inivel/hm_read_inivel.F
sensor defined in /INIVEL doesn't work (workaround : to use T_start)
correction to fix bug of /INIVEL using sensor
=> bug fixing of /INIVEL w/ sen_id>0

engine/source/input/freimpl.F, engine/source/mpi/implicit/imp_spmd.F
add /IMPL/MUMPS/AUTOCORE implicit option to better manage ou-of-core option using MUMPS
=> add /IMPL/MUMPS/AUTOCORE for MUMPS out-of--core management

starter/source/initial_conditions/inivol/init_inivol.F90
+ Potential issue with variable bounds due to two unnecessary line of code (197-198). The line was removed to prevent possible out-of-bounds access or unintended behavior.
+ conditional test introduced on line 165
=> /INIVOL : removed unnecessary line to prevent potential variable bounds issue

common_source/eos/compaction.F, starter/source/materials/eos/hm_read_eos_compaction.F
cleaning undocumented formulation Iform=10.
=> /EOS/COMPACTION : cleaning

starter/source/elements/sh3n/coque3n/c3grtails.F, starter/source/elements/shell/coque/cgrtails.F
Suppressed wrong warning message about user mat incompatibility with Ismstr=10 with change to Ismstr=2
Regression from previous versions
Corrected check condition ins starter, adding user laws
=> Correct compatibility check of user materials for shells with Ismstr=10

starter/source/tools/curve/hm_read_table2_1.F
correct possible memory overflow after previous change
table index increment in the loop  was wrong
=> reading tables : correct index increment in hm_read_table2_1.F

starter/source/materials/mat/mat069/law69_upd.F
MOONEY-RIVLIN LAW PARAMETERS were written 'MOOONEY-RIVLIN LAW PARAMETERS' in starter, corrected
typo in starter output
corrected typo
=> Update law69_upd.F correct typo 'MOOONEY' - 'MOONEY'

engine/CMake_Compilers/cmake_win64_ifx.txt, engine/source/user_interface/eng_callback_c.c, starter/CMake_Compilers/cmake_win64_ifx.txt
=> Adjust cmake build headers for IntelOneAPI 2025.0.1

hm_cfg_files/config/CFG/Keyword971_R13.0/SETS/definehexspotweld.cfg, hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg, hm_cfg_files/config/CFG/radioss140/ELEMENTCLUSTER/cluster.cfg
Activate conversion of *DEFINE_HEX_SPOTWELD_ASSEMBLY:
Activate conversion of *DEFINE_HEX_SPOTWELD_ASSEMBLY:
- activate conversion in data_hierarchy.cfg
- create new cfg for the conversion of the option
=> Activate conversion of *DEFINE_HEX_SPOTWELD_ASSEMBLY

hm_cfg_files/config/CFG/radioss2025/INTER/inter_type2.cfg, starter/source/output/message/starter_message_description.txt
small change in message output when using new surf/surf in interface type2
=> message change (to Uppercase) of surf/surf input in interface type2

hm_cfg_files/config/CFG/Keyword971_R13.0/CURVE/define_curve_smooth.cfg, hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Activate conversion of *DEFINE_CURVE_SMOOTH
- Activate in data_hierarchy.cfg the conversion of *DEFINE_CURVE_SMOOTH
- add new cfg for the conversion of *DEFINE_CURVE_SMOOTH
=> Activate conversion of *DEFINE_CURVE_SMOOTH

starter/source/interfaces/int02/hm_read_inter_type02.F
may get check bounds issue if using surf/surf input w/ grnd_IDs=0
correction to avoid check bounds issue
=> avoid check bounds issue after introduction s2s input in interface type2

starter/source/materials/tools/func_table_copy.F90
Correction of bug with possible memory access problem when creating tables for material law50
Corrected wrong index of fscale in 1D table and allocation length of temporary buffer
=> Correction of table index value after previous development

engine/source/materials/mat/mat021/m21law.F, engine/source/materials/mat_share/mmain.F90
The unloading behavior with /MAT/LAW21 was incorrect. This issue has now been resolved.
=> /MAT/LAW21 : fixing unloading behavior

starter/source/materials/mat/mat051/fill_buffer_51.F
Submaterial definition of ALE multimaterial law51 can now be built from /MAT/PLAS_JOHNS (LAW2)
=> /MAT/LAW51 : input compatibility with /MAT/PLAS_JOHNS (LAW2)

engine/source/ams/sms_build_mat_2.F, engine/source/ams/sms_mass_scale_2.F, engine/source/elements/spring/r23l114def3.F, engine/source/engine/resol.F, engine/source/tools/seatbelts/redef_seatbelt.F90
Seatbelts : Dimensionning issue in seatbelt_redef.F
AMS : Double precision array was allocated as my_real (issue in Single Precision)
=> Issue in 3471995a8c752259fcc55585fc850d91ac4b6ae4

engine/source/materials/mat/mat050/sigeps50s.F90, starter/source/materials/mat/mat050/hm_read_mat50.F90
Correction of parameter output in starter
Correction of deformation definition et stress update in coupled compact state in engine
=> /MAT/LAW50 : correction of compact state deformation calculus

engine/source/tools/seatbelts/material_flow.F
Fix of slipring with locking activated by sensor
=> FIX for slipring and locking

engine/source/ams/sms_pcg.F, engine/source/constraints/general/rbody/rbyfor.F, engine/source/elements/shell/coque/cforc3.F, engine/source/interfaces/int07/inter_sort_07.F, engine/source/interfaces/int11/i11mainf.F, engine/source/interfaces/int22/i22mainf.F, engine/source/interfaces/intsort/i10main_tri.F, engine/source/interfaces/intsort/i11main_tri.F, engine/source/materials/mat/mat087/sigeps87c.F90, starter/source/restart/ddsplit/wrcomm.F
=> Fix several Fortran syntax issues : INTENTS / Caller/Callee routines

starter/source/materials/eos/hm_read_eos_compaction2.F90, starter/source/materials/mat/mat021/hm_read_mat21.F
/MAT/LAW21 : useless warning  message  removed
/EOS/COMPACTION2 (new eos) : mumax set by default to ep20
=> LAW21:update warning message 821

engine/source/materials/mat/mat057/sigeps57c.F90
Missing definition of nu parameter has been noticed, creating chkb issue ... 
Add the definition of nu from matparam structure.
=> Fix missing definition of Poisson's ratio

hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
/PARITH/OFF option was missing in 1.rad file build for dyna input
issue in datahierarchy.cfg file
=> /PARITH/OFF option was missing in 1.rad file build for dyna input

engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
replace Theta by Teta in h3d file output
=> replace Theta by Teta in h3d file output

engine/source/loads/general/load_pcyl/press_seg3.F, engine/source/loads/general/load_pcyl/pressure_cyl.F, engine/source/output/h3d/h3d_results/h3d_skin_scalar.F, engine/source/output/h3d/h3d_results/h3d_skin_vector.F
Corrected radius scale factor in table abscissa interpolation and added missing time factor for second variable
=> correct radius and time scale factors in /load/pcyl

CONTRIBUTING.md, HOWTO.md, RELEASES.md
=> Remove CentOS 7 from Documentation as it is no more compatible.

engine/source/elements/beam/fail_beam18.F, engine/source/elements/beam/fail_beam3.F, engine/source/elements/beam/main_beam18.F, engine/source/elements/beam/main_beam3.F, engine/source/materials/fail/gene1/fail_gene1_s.F, engine/source/materials/fail/visual/fail_visual_b.F90, engine/source/materials/fail/visual/fail_visual_ib.F90, engine/source/materials/mat/mat001/m1lawp.F, starter/source/materials/fail/visual/hm_read_fail_visual.F
1. Add the visual criteria for Beam Type3 Type18;
2. Rewrite the code in F90
3. Clean the code
The visual failure criteria for beam doesn‘t exist
Add the criteria for beam
=> Add Visual Failure Criteria for Type3 and Type18 Beam Elements

engine/source/elements/solid/solide/s_hg5.F, engine/source/elements/solid/solidez/shour_ctl.F90
improve distortion hourglass control for some stiffening materials
=> stiffness change in distortion hourglass control

common_source/eos/idealgas.F
Ideal Gas Temperature is now calculated when /EOS/IDEAL-GAS is defined as LAW151 submaterial (MM-ALE)
=> /MAT/LAW151 : Ideal gas temperature

engine/source/ams/sms_fsa_inv.F, engine/source/ams/sms_mass_scale_2.F, engine/source/ams/sms_pcg.F, engine/source/engine/resol.F, engine/source/modules/ams_work_mod.F90
Create a Working array type for AMS.
=> Slight AMS refactoring : Remove MOD_SMS_FSA common Module

engine/source/elements/solid/solide/s_hg5.F
regression observed after introduction of damping in Isolid=5.
rollback 8ed33f5dd9cd206f878c655fb5f9771273f04671 due to regression and the understanding of initial issue
=> rollback 8ed33f5dd9cd206f878c655fb5f9771273f04671 due to regression

Compiling_tools/script/load_extlib.py
In certain case : extlib can be present with JSON file but with no libraries. Force load of libraries in this case.
=> Fix in load_extlib:

engine/source/elements/spring/r23l114def3.F
=> RETRACTOR : fix of non initialized variable

starter/source/interfaces/inter3d1/remn_self24.F
Upper bound issue in remn_self24 routine (starter)
Fix the issue
=> Starter : upper bound issue in /TYPE24 routine

starter/source/model/sets/solid_surface_buffer.F, starter/source/model/sets/surface_buffer.F
Issue with external surface creation from /SET of shells and solids together
Enable creation of external surface creation from /SET of shells and solids together
=> /SET : issue with key PART_E and shell elements

engine/source/materials/mat/mat126/sigeps126.F90, engine/source/materials/mat_share/mulaw.F90, hm_cfg_files/config/CFG/radioss2025/MAT/matl126_johnson_holmquist_concrete.cfg, starter/source/materials/mat/hm_read_mat.F90, starter/source/materials/mat/mat126/hm_read_mat126.F90
Following recent feedbacks about /MAT/LAW126, some inconsistencies have been highlighted and new features asked for implementation. 
Fix the bad behavior, update the parameter storage and comments + add a new parameter to control the post failure behavior.
=> Improvement of /MAT/LAW126

engine/source/materials/mat_share/mulawc.F90
Fix potential segfault when using /FAIL/FLD due to non associated pointer. 
Fix potential segfault when using /FAIL/FLD due to non associated pointer.
=> Fix potential segfault with /FAIL/FLD

starter/source/elements/reader/hm_read_beam.F
add 3 real fields to /BEAM element reading
=> add VX VY VZ IN BEAM elements

engine/source/elements/solid/solide10/s10coor3.F, engine/source/elements/spring/redef3.F90, engine/source/materials/mat_share/mulawc.F90, engine/source/multifluid/multi_submatlaw.F, engine/source/output/th/thsol.F, qa-tests/miniqa/LOIS/LOI68/cisaillement/test1/input_51/data/test_files.json, qa-tests/scripts/or_QA.files_1miniqa
mulawc.F90 (Shell/Materials)
Tetra10 elements
Springs (redef3)
Time History (Solids)
Multi Materials
fix uninitialized variables
=> Fix uninitialized variables:

engine/source/elements/beam/main_beam3.F, engine/source/materials/fail/gene1/fail_gene1_b.F90, engine/source/materials/mat/mat002/m2lawp.F, engine/source/materials/mat/mat044/sigeps44p.F
There is a bug in the code (MiniQa 1.84) after the last modification of GENE1 for BEAM
Solve the bug for miniqatest 1.84
=> Solve the bug for the the test of miniqatest 1.84

starter/source/general_controls/damping/damping_rby_spmdset.F90, starter/source/general_controls/damping/hm_read_damp.F, starter/source/output/message/starter_message_description.txt, starter/source/starter/lectur.F
Fix small regression on reading of rbody in option /DAMP/VREL
=> DAMP/VREL fix regression of RBODY id

engine/source/loads/general/inivel/inivel_start.F90
/INIVEL w/ T_start (Starter keyword) might not work for several runs using restart
correction to fix issue of INIVEL
=> correction /INIVEL (starter) to avoid restart issue

starter/source/materials/mat/mat050/hm_read_mat50.F90
Corrected variable name inconsistent with cfg file. Pressure unit for scale factors were not correctly initialized.
=> Correction of scale factor reading for /MAT/LAW50  in starter

engine/source/elements/elbuf/allocbuf_auto.F, engine/source/elements/elbuf/w_elbuf_str.F, engine/source/general_controls/damping/damping_range_solid.F90, engine/source/materials/mat_share/mmain.F90, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/usermat_solid.F, engine/source/materials/visc/viscmain.F, hm_cfg_files/config/CFG/radioss2025/DAMP/Damp_freq_range.cfg, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/general_controls/damping/hm_read_damp.F, starter/source/restart/ddsplit/w_elbuf_str.F
=> DAMP_FREQ_RANGE - small fixes

engine/source/engine/resol.F
=> reindent resol.F

engine/source/ale/alemain.F, engine/source/ale/alethe.F, engine/source/ale/atherm.F
Fixed an issue introduced by commit 6dc61baaa27e5f3b28f26590406442bec27705a6. The value of NEL was inconsistent. It is now correctly defined as NEL = IPARG(2, NG).
=> /HEAT/MAT : fix NEL issue for ALE

engine/source/ale/ale2d/adiff2.F, engine/source/ale/ale3d/adiff3.F, engine/source/ale/atherm.F, engine/source/ale/euler2d/egrad2.F, engine/source/ale/euler3d/egrad3.F
The heat equation is solved when the /HEAT/MAT option is defined. In the ALE framework, it is implemented in the atherm.F subroutine. Currently, this section of the code is commented out.
Additionally, a fix has been introduced for the boundary condition: previously, the thermal diffusivity was set to 0 if an adjacent element was not associated with any /HEAT/MAT option. This was preventing the definition of Dirichlet boundary conditions.
=> ALE : comments for heat equation

common_source/modules/cpp_python_funct.cpp, common_source/modules/python_mod.F90, engine/source/engine/resol.F, engine/source/loads/general/force.F90, engine/source/loads/general/python_call_funct_cload.F90
Example: AX(ACTIVE_NODE), CX(ACTIVE_NODE)
=> /FUNCT_PYTHON for cload: get access to the current node

starter/source/elements/reader/hm_read_beam.F
=> Fix of output for beams

engine/source/ale/atherm.F, engine/source/general_controls/damping/damping_range_solid.F90, engine/source/materials/fail/gene1/fail_gene1_b.F90, engine/source/materials/fail/gene1/fail_gene1_ib.F90, engine/source/materials/fail/inievo/fail_inievo_b.F90, engine/source/materials/fail/inievo/fail_inievo_ib.F90, engine/source/materials/fail/visual/fail_visual_ib.F90, hm_cfg_files/config/CFG/radioss2025/LOADS/ebcs_propergol.cfg, hm_cfg_files/config/CFG/radioss2025/MAT/Law128_hill_visc_plast.cfg, hm_cfg_files/config/CFG/radioss2025/MAT/mat_law50.cfg, hm_cfg_files/config/CFG/radioss2025/MAT/matl81_81.cfg, starter/source/boundary_conditions/ebcs/hm_read_ebcs_propergol.F90, starter/source/boundary_conditions/ebcs/iniebcs_propergol.F90, starter/source/materials/mat/mat050/hm_read_mat50.F90, starter/source/materials/mat/mat128/hm_read_mat128.F90, starter/source/materials/mat/mat169/hm_read_mat169.F90, starter/source/modules/user_interface_mod.F90
=> Copyright update

engine/source/output/anim/generate/genani.F, starter/source/output/th/hm_read_thgrou.F, starter/source/restart/ddsplit/w_failwave.F, starter/source/restart/ddsplit/w_pon.F, starter/source/starter/lectur.F
=> some uninitialized variables fixes

hm_cfg_files/config/CFG/radioss2021/TABLE/inibri_strs_f_sub.cfg, hm_cfg_files/config/CFG/radioss2021/TABLE/inibri_strs_fglo_sub.cfg
correction /INIBRI/STRS_F and  /INIBRI/STRS_FGLO dimension for E_int
E_int dimension is energy density
=> correction /INIBRI/STRS_F and  /INIBRI/STRS_FGLO dimension for E_int

starter/source/constraints/general/impvel/read_impdisp.F
correction of regression of c884b5408d5dc6539e66266c623cd720486454de
=> regression of c884b5408d5dc6539e66266c623cd720486454de

engine/source/materials/fail/spalling/fail_spalling_s.F, engine/source/materials/mat_share/mmain.F90, engine/source/materials/mat_share/mmain8.F, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/mulaw8.F90, engine/source/materials/mat_share/usermat_solid.F, starter/source/materials/fail/hm_read_fail.F, starter/source/materials/fail/spalling/hm_read_fail_spalling.F
There was a need to output properly the 2 criteria of /FAIL/SPALLING
Create new 2 new modes (Johnson-Cook, Pmin) for SPALLING and save them in the element buffer.
=> Modes output for /FAIL/SPALLING

starter/source/starter/execargcheck.F
=> Starter '-v' Option: change version name for Input Reader.

engine/source/tools/seatbelts/redef_seatbelt.F90, engine/source/tools/seatbelts/update_slipring.F
Fix of NaN observed on Mat114 for seatblet + issue with contact for 2D seatbelts
=> SEATBELT - Fix of Mat114  + contact for 2Dseatbelt

engine/CMake_Compilers/cmake_win64.txt, engine/CMake_Compilers/cmake_win64_ifort.txt, engine/CMake_Compilers/cmake_win64_sse3.txt
=> MUMPS + ifx available

engine/source/general_controls/damping/damping_range_shell.F90, engine/source/general_controls/damping/damping_range_shell_mom.F90, engine/source/materials/mat_share/cmain3.F, engine/source/materials/mat_share/mulawc.F90, engine/source/materials/mat_share/mulawglc.F, engine/source/materials/visc/prony_modelc.F, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/elements/sh3n/coque3n/c3grhead.F, starter/source/elements/sh3n/coque3n/c3grtails.F, starter/source/elements/shell/coque/cgrhead.F, starter/source/elements/shell/coque/cgrtails.F, starter/source/starter/lectur.F
Apply damping frequency ange option to shell
=> DAMPINF_FREQ_RANGE for shells

engine/source/materials/mat_share/mmain.F90, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/usermat_solid.F, engine/source/materials/visc/visc_plas.F90, engine/source/materials/visc/viscmain.F, hm_cfg_files/config/CFG/radioss2025/MAT/mat_VISC_PLAS.cfg, hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/materials/visc/hm_read_visc.F, starter/source/materials/visc/hm_read_visc_plas.F90
We are not to map the frequency dependant damping of lsdyna
Developping new option /VISC/PLAS to able to map the frequency dependant damping of ls dyna inside mat077, mat0181 ... etc
=> adding frequency independent damping using /VISC/PLAS 

starter/source/materials/fail/spalling/hm_read_fail_spalling.F90
Missing check on the pmin value of /FAIL/SPALLING leading to no failure at all. 
Add a check to ensure having a negative value for PMIN.
=> Add input check in /FAIL/SPALLING reading routine

common_source/modules/cpp_python_funct.cpp
Possible issues with importing math lib from python code.
=> /FUNCT/PYTHON libpython opened with RTLD_GLOBAL

hm_cfg_files/config/CFG/Keyword971_R14.1/CONTROL_CARDS/NodalForceGrp.cfg, hm_cfg_files/config/CFG/Keyword971_R14.1/data_hierarchy.cfg
Activate conversion of DATABASE_NODAL_FORCE_GROUP
Activate conversion of DATABASE_NODAL_FORCE_GROUP
=> Activate conversion of DATABASE_NODAL_FORCE_GROUP

starter/source/materials/eos/hm_read_eos_compaction.F90, starter/source/materials/eos/hm_read_eos_compaction2.F90
=> /EOS/COMPACTION:typo in error message

engine/source/elements/beam/fail_beam18.F, engine/source/materials/fail/biquad/fail_biquad_ib.F, engine/source/materials/fail/cockroft_latham/fail_cockroft_ib.F, engine/source/materials/fail/energy/fail_energy_ib.F, engine/source/materials/fail/gene1/fail_gene1_ib.F90, engine/source/materials/fail/johnson_cook/fail_johnson_ib.F, engine/source/materials/fail/tensstrain/fail_tensstrain_ib.F, hm_cfg_files/config/CFG/radioss2025/FAIL/fail_biquad.cfg, hm_cfg_files/config/CFG/radioss2025/FAIL/fail_cockcroft.cfg, hm_cfg_files/config/CFG/radioss2025/FAIL/fail_energy.cfg, hm_cfg_files/config/CFG/radioss2025/FAIL/fail_gene1.cfg, hm_cfg_files/config/CFG/radioss2025/FAIL/fail_johnson.cfg, hm_cfg_files/config/CFG/radioss2025/FAIL/fail_tensstrain.cfg, starter/source/materials/fail/biquad/hm_read_fail_biquad.F, starter/source/materials/fail/cockroft_latham/hm_read_fail_cockcroft.F, starter/source/materials/fail/energy/hm_read_fail_energy.F, starter/source/materials/fail/gene1/hm_read_fail_gene1.F, starter/source/materials/fail/johnson_cook/hm_read_fail_johnson.F, starter/source/materials/fail/tensstrain/hm_read_fail_tensstrain.F
For the failure criteria of integrated beam element, the variable concerning the number of failed integration points to control the deletion of element doesn't exist
We add the variable FAILIP in all the criteria for integrated beam, with which we can control the necessary number of failed integration point to delete the related element.
=> New Keyword FAILIP for all the failure criterias in intergrated beam 

hm_cfg_files/config/CFG/radioss2022/INTER/inter_type18.cfg, starter/source/interfaces/int18/hm_read_inter_type18.F
regression introduced with 0763cd3408bf22704ddbcbc467733d6e13b6608f
It is now fixed
=> /INTER/TYPE18 : updating configuration file for the Reader

engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
Detonation Times are now correctly exported in H3D file when requested with LAw151 and TRIA(2d) elements
=> /H3D/ELEM/TDET + LAW 151 + TRIA (2d) : detonation times output

engine/source/output/anim/generate/ani_pcont.F
caused by  - uninitialized variable in some cases
=> Possible failure with /ANIM/VECT/PCONT whit tetra10

engine/source/materials/mat_share/mmain.F90, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/mulawc.F90, engine/source/materials/mat_share/usermat_shell.F, engine/source/materials/mat_share/usermat_solid.F
=> Added DFMX to engine USER flaw

common_source/modules/cpp_python_funct.cpp, common_source/modules/cpp_python_funct.h, common_source/modules/python_mod.F90, engine/source/elements/spring/r26sig.F, engine/source/elements/spring/r27def3.F, engine/source/elements/spring/redef3.F90, engine/source/engine/resol.F, engine/source/tools/seatbelts/redef_seatbelt.F90, starter/source/starter/lectur.F, starter/source/tools/sensor/hm_read_sensor_python.F90
- In case of the function can not be evaluated at the starter, the error should be ignored
- Issue when both python functions and python sensors are used
=> Regressions in /FUNCT_PYTHON

engine/source/materials/visc/viscmain.F
wrong declaration
Correct the declaration of variable because it's modified inside the subroutine.
=> change the declaration of variable

engine/source/ale/grid/alew7.F, engine/source/ale/grid/alew8.F90, engine/source/ale/grid/alewdx.F, engine/source/input/freform.F, engine/source/input/lectur.F, hm_cfg_files/config/CFG/radioss2025/CARDS/ale_grid_lagrange.cfg, hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg, starter/source/general_controls/ale_grid/hm_read_ale_grid.F
New ALE grid formulation available! This enhancement enables the use of the ALE solver within a Lagrangian framework.
**Possible applications:**
- Can be applied during a specific simulation period to reduce numerical diffusion (using Restart files).
- Can be used to solve the heat equation with FVM and compare the numerical solution with the FEM solution (true Lagrangian solver)."
- verification purpose (solver numerical solutions)
=> /ALE/GRID/LAGRANGE : ALE solver with lagrange framework (grid control)

engine/source/ale/ale2d/adiff2.F, engine/source/ale/ale3d/adiff3.F
fix following 313021a6b781fe775e6431e2df0eb3a096b7385a
=> /HEAT/MAT : fix for ALE

engine/source/elements/solid/solide/s_hg5.F, engine/source/elements/solid/solidez/shour_ctl.F90
unstable results could be observed using isolid=5 after rupture due to hourglass force. 
correction to remove the hourglass force after rupture of isolid=5
=> correction to remove hourglass force after rupture

hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
correction visc/plas reading
missing reference to /VISC/PLAS in datahierarchy file
=> correction visc/plas reading

starter/source/interfaces/inter3d1/select_s2s.F90
Starter might hang when interface type2 with surf/surf input of huge number of surf segments
correction to fix performance issue of interface type2 surf/surf input w/ special model
=> add bucket sort in case of huge surf/surf input in interface type2 to avoid performance issues

engine/source/output/h3d/h3d_build_fortran/lech3d.F
Add condition for array allocation IRUP_ID_ALL otherwise this can create segfault issue if multiple mode output are requested. 
Add condition for array allocation IRUP_ID_ALL otherwise this can create segfault issue if multiple mode output are requested.
=> Add condition for array allocation in MODE output

starter/source/materials/mat/hm_read_mat.F90, starter/source/materials/mat/mat070/law70_table.F, starter/source/materials/read_material_models.F, starter/source/materials/tools/table_values_2d.F, starter/source/starter/lectur.F
Last point of input curve in law70 could be not correctly initialized, resulting to NAN or very high value
Corrected a particular case of internal table creation routine with modified input functions
Corrected lenght of bufmat table passed to read_material_models()
=> Correction of input function update in /mat/law70

engine/source/interfaces/interf/intfop2.F, engine/stub/fvmbags_stub.F, starter/source/interfaces/int02/hm_read_inter_type02.F, starter/source/interfaces/inter3d1/i24sti3.F, starter/source/interfaces/inter3d1/i7sti3.F, starter/source/interfaces/interf1/lecint.F, starter/stub/fvmbags_stub.F
fvmbags stub, type mismatch
timers: type mismatch in intfop2
=> fix caller/callee type mismatch

starter/source/elements/elbuf_init/elbuf_ini.F
Memory issue generated by bad merge with git
=> fix of regression due to merge

starter/source/materials/mat/mat070/law70_upd.F
Wrong behavior. 
Update the E0 using the max of the initial slope of the curve
=> fix bug when E0 is set to zero

reader/build_script.bash, reader/source/cfgio/CMake_arch/CMake_linuxa64.cmake, reader/source/cfgkernel/CMake_arch/CMake_linuxa64.cmake, reader/source/cfgkernel/UTILS/file_utils.cpp, reader/source/dyna2rad/CMake_arch/CMake_linuxa64.cmake, reader/source/dyna2rad/_private/convertsets.cxx, reader/source/io/CMake_arch/CMake_linuxa64.cmake, reader/source/sdi/CMake_arch/CMake_linuxa64.cmake, reader/source/solver_interface/CMake_arch/CMake_linuxa64.cmake
=> Port OpenReader on ARM with gcc11 and gcc13

starter/source/general_controls/damping/hm_read_damp.F, starter/source/starter/lectur.F
Fix of issue in restart file + uninitialized variables
=> DAMP freq range - restart file issue

starter/source/restart/ddsplit/ddsplit.F, starter/source/restart/ddsplit/wrcommp.F, starter/source/starter/lectur.F
Memory optimisation for damping - array DAMP not used for damp freq range
=> DAMP range - memory opimisation

common_source/includes/qaprint_c.inc, starter/source/output/qaprint/st_qaprint_driver.F, starter/source/output/qaprint/st_qaprint_general_controls.F, starter/source/starter/lectur.F
=> Damp freq range - fix

engine/source/materials/mat/mat134/sigeps134s.F90, engine/source/materials/mat_share/mulaw.F90, hm_cfg_files/config/CFG/radioss2025/MAT/matl134_viscous_foam.cfg, hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg, starter/source/elements/initia/initia.F, starter/source/materials/mat/hm_read_mat.F90, starter/source/materials/mat/mat134/hm_read_mat134.F90, starter/source/starter/contrl.F
we don't had possibility to convert Mat62 of Lsdyna
Adding new Material law134 for D2R
=> adding dyna mat062

hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg, reader/source/cfgkernel/KERNEL/cfg_kernel.cpp, reader/source/cfgkernel/KERNEL/mv_descriptor.cpp, reader/source/cfgkernel/KERNEL/mv_file_format.cpp, reader/source/cfgkernel/KERNEL/mv_file_format.h, starter/source/starter/starter0.F
enable format 2026 + enable 2026 format for open_reader
=> enable format 2026 + enable 2026 format for open_reader

engine/source/loads/pblast/pblast_2.F, hm_cfg_files/config/CFG/radioss2026/LOADS/pblast.cfg, starter/source/loads/pblast/hm_read_pblast.F
New Ishape flag for SURFACE BURST MODEL only (exp_data=2)
=> /LOAD/PBLAST : new Ishape flag for Surface Burst Model

starter/source/elements/spring/rinit3.F, starter/source/properties/spring/hm_read_prop23.F
Fix of mass computation for spring with prop 23 : -> for MAT108 Imass is not always set to 2
-> default value of Imass is set to 2
=> Fix of Imass=1 for spring with law108

hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg, hm_cfg_files/config/CFG/radioss2026/MAT/matl134_viscous_foam.cfg, hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg, starter/source/materials/mat/mat134/hm_read_mat134.F90
the unity is missed for viscosity and typo error
Fix error and change the input version 2025 to 2026.
=> fix unit viscosity and change input version

engine/source/interfaces/interf/check_active_elem_edge.F, engine/source/interfaces/interf/count_remote_nb_elem_edge.F
Problem with Tetra10 for erosion generally
Element number for tetra1 in ixs10 is wrong
=> Correction problem with Tetra10 for erosion

engine/source/engine/lf_convert_c.c
* Workaround when hostname could not be grabbed
* Create C interfaces for lf_convert_c_flat
* remove obsolete lf_convert_c routine
=> CR/LF convertion process on Windows:

engine/source/output/anim/generate/tensorc.F
corrected deallocation issue of local tables in tensor animation output after previous integration concerning composite shell output
=> Correct allocation/deallocation problem in ANIM tensor output

starter/source/tools/seatbelts/create_seatbelt.F
Fix of mass computation for 1D/2D seatblet connection
=> Fix of mass computation for 1D/2D seatblet connection

starter/source/interfaces/inter3d1/i25buce_edg.F, starter/source/interfaces/inter3d1/i25trivox_edg.F
=> Fix build issue: size of arrays must be declared before the arrays

engine/source/interfaces/interf/get_neighbour_surface.F90, engine/source/interfaces/interf/get_neighbour_surface_from_remote_proc.F90, engine/source/interfaces/interf/get_segment_interface_id.F90
commit
Problem with bench in waiting spmd communication
Problem with identification of the edge of segment: the edge can be selected even if the nodes are not in the right order which can reveal a problem when searching neighbours
=> Correction problem erosion edge indentification

starter/source/tools/seatbelts/hm_read_slipring.F
Increase of tolerance for of SLIPRING node alignement check
=> SLIPRING shell = tolerance increase

starter/source/coupling/rad2rad/r2r_void.F, starter/source/tools/admas/hm_read_admas.F
Fix of compatibility issues between multdomains and prop51
=> Fix of multidomains + stack ply prop51

engine/share/includes/rad2rad_c.h, engine/source/coupling/rad2rad/rad2rad_c.c
reduce warnings in rad2rad_c.c:
create interfaces for all C functions.
create include file with those interfaces.
=> reduce warnings in rad2rad_c.c

hm_cfg_files/config/CFG/radioss110/CARDS/eng_dt.cfg, hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg
Activate conversion of *CONTROL_TIMESTEP into /DT
Activate conversion of *CONTROL_TIMESTEP into /DT, in data_hierarchy.cfg file and create a new cfg file for /DT
=> Activate conversion of *CONTROL_TIMESTEP into /DT

hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
correction datahierarchy file with profile 2025
CARDS/ale_grid_lagrange.cfg is available since version 2026
=>  correction datahierarchy file with profile 2025

engine/source/output/h3d/h3d_build_fortran/prelech3d.F90
Change condition to trigger the presizing and allocation of OUTPUT_LIST in H3D_DATA. 
Change condition to trigger the presizing and allocation of OUTPUT_LIST in H3D_DATA.
=> Fix presizing of H3D table OUTPUT_LIST

engine/source/output/h3d/h3d_build_fortran/lech3d.F
Fix failure output size issue
Fix failure output size issue
=> Fix failure output size issue

common_source/eos/eosmain.F, engine/source/materials/mat/mat012/m12law.F, engine/source/materials/mat/mat075/sigeps75.F, engine/source/materials/mat_share/mmain.F90, engine/source/materials/mat_share/mulaw.F90, engine/source/multifluid/multi_ebcs.F, engine/source/multifluid/multi_inlet_ebcs.F, engine/source/multifluid/multi_muscl_compute_pressure.F90, engine/source/multifluid/multi_muscl_fluxes_computation.F, engine/source/multifluid/multi_nrf_ebcs.F, engine/source/multifluid/multi_pressure_equilibrium.F, engine/source/multifluid/multi_propergol_ebcs.F90, engine/source/multifluid/multi_solve_eint.F90, engine/source/multifluid/multi_submatlaw.F, engine/source/multifluid/multi_timeevolution.F, engine/source/output/anim/generate/anim_nodal_ssp_elems.F90, starter/source/elements/initia/initia.F, starter/source/initial_conditions/inigrav/inigrav_eos.F, starter/source/initial_conditions/inimap/ini_inimap1d.F, starter/source/initial_conditions/inimap/multi_solve_eint.F90
Missing argument in EOSMAIN subroutine following : 5ea3e5fb7cef288d51414682dfd521fcbff92a33
=> eosmain missing args

engine/source/tools/curve/funct_python_update_elements.F90
Add missing argument for python function
Add missing argument for python function
=> Add missing argument for python function

engine/source/elements/solid/solide/s_hg5.F, engine/source/elements/solid/solide/sdistror_ini.F90, engine/source/elements/solid/solidez/shour_ctl.F90
improving distortion control w/ law42,69
=> solid distortion control update

hm_cfg_files/config/CFG/Keyword971_R14.1/data_hierarchy.cfg, hm_cfg_files/config/CFG/LsDynaToRad/LsDynaToRad.cfg, hm_cfg_files/config/CFG/radioss2026/MAT/matl134_viscous_foam.cfg, starter/source/materials/mat/mat134/hm_read_mat134.F90
Activate conversion of *MAT_062 (VISCOUS_FOAM) to /MAT/134 (VISCOUS_FOAM)
Activate conversion of *MAT_062 (VISCOUS_FOAM) to /MAT/134 (VISCOUS_FOAM)
=> Activate conversion of *MAT_062 (VISCOUS_FOAM) to /MAT/134 (VISCOUS_FOAM)

hm_cfg_files/config/CFG/radioss2026/FAIL/fail_lemaitre.cfg, starter/source/materials/fail/lemaitre/hm_read_fail_lemaitre.F90
Change default value and comment in .cfg file for /FAIL/LEMAITRE
Change default value and comment in .cfg file for /FAIL/LEMAITRE
=> Change default values and comment for recently added /FAIL/LEMAITRE

starter/source/restart/ddsplit/ddsplit.F
=> Fix of R2r + ALE_NE_CONNECT

starter/source/elements/initia/hm_read_inistate_d00.F, starter/source/starter/lectur.F
potential issue, when using springs , with SPRING Properties that have user variables + /INISPRI option on those springs 
bad array used
bad dimension
=> correction /INISPRI option issue

engine/source/materials/mat/mat075/sigeps75.F
Potential floating point exception in /MAT/LAW75 
Set a maximum value of EM20 to avoid zero value.
=> Fix floating point exception for /MAT/LAW75

engine/source/interfaces/int25/i25for3_e2s.F
=> Correction wrong size table E2S

starter/source/initial_conditions/detonation/eikonal_solver.F90, starter/source/initial_conditions/detonation/read_detonators.F, starter/source/initial_conditions/detonation/read_dfs_detcord.F, starter/source/initial_conditions/detonation/read_dfs_detline.F, starter/source/initial_conditions/detonation/read_dfs_detplan.F, starter/source/initial_conditions/detonation/read_dfs_detpoint.F, starter/source/initial_conditions/detonation/read_dfs_wave_shaper.F, starter/source/materials/eos/hm_read_eos.F, starter/source/materials/material_is_high_explosive.F90
- remove potential duplicated line for new Shadowing option
- column alignment (for all detonators type : point, line, plane, cord, etc ...)
- multimaterial law151 initial condition update (compatibility of law151 with Fast Marching Method)
=> Detonators : printout update + FMM compatibility with law151

starter/source/initial_conditions/detonation/read_dfs_detpoint.F
This added comma ensure correct compiler behavior on the ARM platforms.
=> fixing a potential compiler issue on ARM platform

hm_cfg_files/config/CFG/radioss2026/CARDS/anim_spring_forc.cfg, hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg
In D2R conversion of Dyna card *DATABASE_BINARY_D3PLOT, activate creation of Radioss card /ANIM/SPRING/FORC in engine
In D2R conversion of Dyna card *DATABASE_BINARY_D3PLOT, activate creation of Radioss card /ANIM/SPRING/FORC in engine
=> D2R: Request /ANIM/SPRING/FORC in engine where model includes springs

hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg
/INISH../..._GLOB was not read correctly with open_reader
change in data_hierachy.cfg file
=> correction reading of initial state with /INISH _GLO crads with open_reader

engine/source/engine/resol_init.F
Engine w/ multi restart might fail using /INIVEL (Starter) with different T_start
bug fixing of /INIVEL (Starter keyword) + restart
=> bug fixing of /INIVEL (Starter) + restart

engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
Segfault issue that might appear in DAMA output when using /PROP/TYPE11
Wrong numbering of the layers (NPT instead of NLAY)
=> Fix prop 11 output issue for DAMA

engine/source/constraints/general/rbe3/rbe3f.F, engine/source/constraints/general/rbe3/rbe3f_pen.F90, engine/source/constraints/general/rbe3/rbe3pen_init.F90, engine/source/engine/resol.F
RBE3 penalty was added recently by 7b5d8700547db0220a0f04d4f139bfb650e85b57, this might get trouble when implicit solution used w/ RBE3
correction to use only kinematic RBE3 with implicit solution
=> RBE3 penalty only for explicit

common_source/qa/kill_zombi.F
This file is not a radioss file, it is used by some QA tool.
=> revert modification on kill_zombi.F

starter/source/system/get_file_name_info.F
=> read dyn & DYN files

engine/source/materials/mat/mat066/sigeps66.F, engine/source/materials/mat/mat066/sigeps66c.F
Difference in the behavior in the case where PC=PT=0 for shear compared to Dyna
Fix the issue by considering the compressive yld in this case,
=> fix the difference of shear behavior against Dyna

engine/source/interfaces/interf/chkstfn3.F, engine/source/model/remesh/admini.F
Correction Admesh bugs : interface node deletion only after trimming
Correction Admesh bugs : interface node deletion only after trimming
=> Correction Admesh bugs : interface node deletion only after trimming

hm_cfg_files/config/CFG/radioss2026/CARDS/th_title.cfg, hm_cfg_files/config/CFG/radioss2026/data_hierarchy.cfg, starter/source/general_controls/engine/read_engine_driver.F
In D2R conversion, add /TH/TITLE to engine (datahierarchy.cfg)
In D2R conversion, add /TH/TITLE to engine (datahierarchy.cfg)
=> Add /TH/TITLE to engine file generated by D2R

engine/CMake_Compilers/cmake_linux64_ifort.txt, engine/source/materials/mat/mat052/sigeps52.F, engine/source/materials/mat/mat052/sigeps52c.F, starter/CMake_Compilers/cmake_linux64_ifort.txt, starter/CMake_Compilers/cmake_linux64_ifx.txt
Fix checkbound issue with /MAT/LAW52  
Fix checkbound issue with /MAT/LAW52 + fix compilation flag (made with Olivier)
=> Fix checkbound issue LAW52

common_source/modules/output/time_history_mod.F, common_source/tools/input_output/write_routtines.c, engine/source/engine/radioss0.F, engine/source/engine/radioss2.F, engine/source/implicit/imp_buck.F, engine/source/system/arret.F
Close Time History in arret : issue when TH type is not ieee fix unused routine to initialize IEEE writing use it for cleaner file handling Missing argument to genani
=> Fixes for checksum option:

common_source/tools/memory/extend_array.F90, starter/source/output/qaprint/st_qaprint_model_tools.F, starter/source/starter/lectur.F
Regression fixes on /SECTION reading from starter
=> fix qa print for /SECTION

engine/source/materials/mat_share/mulawc.F90
regression of QEPH with not elasto-plastic law(e.g. law19) due to e8b1eda1e3b6262493f66c35498507f0621486b1
correction to fix regression of QEPH
=> regression of QEPH in e8b1eda1e3b6262493f66c35498507f0621486b1

engine/share/modules/inter_sorting_mod.F, engine/source/engine/resol.F, engine/source/interfaces/generic/inter_box_creation.F, engine/source/interfaces/generic/inter_cell_color.F, engine/source/interfaces/generic/inter_color_coarse_voxel.F, engine/source/interfaces/generic/inter_component_bound.F90, engine/source/interfaces/generic/inter_count_node_curv.F, engine/source/interfaces/generic/inter_init_component.F90, engine/source/interfaces/generic/inter_init_component_list.F90, engine/source/interfaces/generic/inter_init_node_color.F90, engine/source/interfaces/generic/inter_minmax_node.F, engine/source/interfaces/generic/inter_prepare_sort.F, engine/source/interfaces/intsort/inttri.F, engine/source/mpi/interfaces/spmd_box_limit_reduction.F, engine/source/mpi/interfaces/spmd_cell_list_exchange.F, engine/source/mpi/interfaces/spmd_cell_size_exchange.F, engine/source/mpi/interfaces/spmd_cell_size_post_rcv.F, engine/source/mpi/interfaces/spmd_exch_component.F90
/TYPE7 performance improvement: add the concept of component to reduce the amount of mpi communication in the collision detection algorithm
Components are built at the beginning on the engine
Bounding boxes of component are exchanged in the collision detection algorithm
If 2 boxes intersect, the mpi communication between processor is mandatory
=> /TYPE7 performance improvement

engine/source/interfaces/int25/i25ass_e2s.F
Correction size tab Int25 iedgE2S
Correction size tab Int25 iedgE2S
=> Correction size tab Int25 iedgE2S

starter/source/starter/execargcheck.F
Fix uninitialized variable in execargcheck routine (starter)
=> Fix uninitialized variable in execargcheck routine (starter)

starter/source/initial_conditions/detonation/read_dfs_detpoint.F
An issue was identified when using the submodeling option (//SUBMODEL //ENDSUBMODEL). This has now been resolved
=> /DFS/DETPOINT : submodel fix

engine/source/implicit/imp_solv.F
issue commit 9d84673c9da1a7beb70e6109354c1ce2bf3c9d7a
=> issue_9d84673c9da1a7beb70e6109354c1ce2bf3c9d7a

engine/source/input/fredamp.F, engine/source/input/freform.F, engine/source/input/lecdamp.F
issue with /DAMP engine card reference to Id with more than 5 digits
allow to have damp_id up to 10 digits
=> issue with /DAMP engine card reference to Id with more than 5 digits

engine/source/output/h3d/input_list/h3d_list_shell_scalar.F, starter/source/elements/elbuf_init/elbuf_ini.F, starter/source/elements/initia/initia.F, starter/source/materials/mat/check_mat_elem_prop_compatibility.F, starter/source/multifluid/multifluid_global_tdet.F
Detonation times were affected when law151 is used with 2d solid triangles
before bug fix
after bug fix
=> LAW151 : regression bug fixed related to detonation times with tria solids(2d)

engine/source/assembly/damping.F, engine/source/assembly/damping_vref_compute_dampa.F90, engine/source/assembly/damping_vref_rby.F90, engine/source/engine/resol.F, engine/source/time_step/dtnodarayl.F
-> fix of elementary time step
-> factorisation of the code
=> DAMP/VREL - fit of elementary time step + factorisation

engine/source/output/h3d/h3d_results/genh3d.F
Simplifiy H3D / FVM Communication & structures.
=> H3D : review fvmbag option

starter/source/devtools/hm_reader/hm_get_float_array_2indexes.F, starter/source/interfaces/interf1/lecins.F, starter/source/materials/mat/mat092/law92_nlsqf.F90
Minor adjustments to ensure compatibility with gfortran **-ffixed-line-length=132**.
=> compatibility with -ffixed-line-length-132 gfortran flag

engine/source/engine/resol.F
correction to fix regression of /DAMP/VREL of recent development 14c5981b85c3dba37a087baf2769504b27cdf7f4
=> regression of /DAMP/VREL due to 14c5981b85c3dba37a087baf2769504b27cdf7f4

engine/source/input/read5p.F
Fix of input reading in engine for card /DEL
=> DEL/ELEM - fix of input reading in engin

starter/source/properties/hm_read_properties.F, starter/source/properties/spring/hm_read_prop13.F, starter/source/properties/spring/hm_read_prop23.F
fix of local skew when global skew is used and spring property in submodel
=> SPRING - fix of local skew with submodel

starter/source/properties/hm_read_properties.F, starter/source/properties/spring/hm_read_prop13.F, starter/source/properties/spring/hm_read_prop23.F
Fix of spring properties with no skew and submodel - local id of submodel must be used
=> Fix of skew for springs with submodels

engine/source/output/anim/generate/genani.F, engine/source/output/anim/generate/monvol_anim.F90, engine/source/output/h3d/h3d_results/h3d_nodal_scalar.F
genani.F indentation, and removal of /MONVOL related functions
=> begining refactor genani for node splitting

engine/source/materials/mat/mat109/sigeps109.F, engine/source/materials/mat/mat109/sigeps109c.F, engine/source/materials/mat_share/mulaw.F90, engine/source/materials/mat_share/mulawc.F90, starter/source/materials/mat/mat109/hm_read_mat109.F
/MAT/LAW109 was showing a non expected behavior compared to similar competitors material law. 
Fix and clean /MAT/LAW109 return mapping.
=> Fix /MAT/LAW109 return mapping

engine/source/materials/mat/mat044/sigeps44c.F, engine/source/materials/mat/mat065/sigeps65c.F, engine/source/materials/mat_share/mulawc.F90
differences of results compared to previous references
Strain rates in laws 44 and 65 are corrected in case of filtering
=> Strain rate correction for material laws 44 and 65

starter/source/general_controls/damping/hm_read_damp.F
correction in recent development 14c5981b85c3dba37a087baf2769504b27cdf7f4
=> correction for /DAMP/FUNCT

engine/source/materials/mat/mat129/sigeps129s.F90, starter/source/materials/mat/hm_read_mat.F90
This reverts commit e59fd2b5ab497fce48c54ea2cfdc273def0afca8.
=> Revert "Correction of material law129 behavior without creep"

engine/source/materials/mat/mat129/sigeps129s.F90
Correction of material law 129 without additional modification in hm_read_mat
=> Revert "Revert "Correction of material law129 behavior without creep""

engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
/FUNCT_PYTHON + Law 151: VELX,VELY,VELZ gives the velocities at the centroid
=> /FUNCT_PYTHON + Law 151: VELX,VELY,VELZ gives the velocities at the centroid

engine/CMake_Compilers/cmake_linux64_gf.txt, starter/CMake_Compilers/cmake_linux64_gf.txt
=> activate -Werror=maybe-uninitialized for gcc11 and gcc15 only

starter/source/interfaces/inter3d1/select_s2s.F90
In case of very different mesh density, surf/surf input of interface type2 might not have the good tied result 
improve surface(segment) selection algorithms of interface type 2 w/ surf/surf input
=> correction of surf/surf input of interface type2

engine/source/output/anim/generate/tensor6.F, engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
Engine crashed w/ composite thickshell Isolid=14 and output /H3D/SOLID/ORTHD
correction to avoid crash output w/ composite thickshell Isolid=14
=> avoid crash of composite thickshell(Isolid=14) + output /H3D/SOLID/ORTHD

engine/source/materials/mat/mat129/sigeps129s.F90
Use more precise algorithm of plasticity projection in law129
improvement of stress update due to thermal stresses and creep
=> Law129 : apply Newton iterations for plasticity instead of radial return

common_source/modules/interfaces/intbufdef_mod.F90, engine/source/engine/node_spliting/detach_node.F90, engine/source/engine/resol.F, engine/source/implicit/imp_int_k.F, engine/source/interfaces/intsort/i7buce.F, engine/source/interfaces/intsort/i7main_tri.F, engine/source/interfaces/intsort/inttri.F, engine/source/materials/mat_share/mulaw8.F90, engine/source/tools/lagmul/lag_mult.F, starter/source/interfaces/interf1/lecint.F, starter/source/restart/ddsplit/ddsplit.F, starter/source/restart/ddsplit/setlenwa.F, starter/source/starter/lectur.F
Remove WA that was used to save CAND_A
remove WA from /LAG options (that was always activated, even when not used)
The working array (WA) dimension should be refined. It of constant size per processor, and contains space for unused options.
=> Node-splitting + /INTER/TYPE7

starter/source/materials/mat/hm_read_mat.F90, starter/source/materials/updmat.F
correction regression of 8e66beff9056c250219ec2605e23ebf01e2e297c  for icontrol+law62
=> regression of 8e66beff9056c250219ec2605e23ebf01e2e297c (icontrol)

engine/source/elements/sh3n/coque3n/c3coef3.F, engine/source/elements/sh3n/coquedk/cncoef3.F, engine/source/elements/shell/coqueba/cmatc3.F, engine/source/materials/mat/mat127/sigeps127c.F90, starter/source/elements/sh3n/coque3n/c3derii.F, starter/source/elements/sh3n/coquedk/cdkderii.F, starter/source/elements/shell/coque/cdleni.F, starter/source/elements/shell/coqueba/cndleni.F
The law127 it's instable with QEPH Element (ISHELL = 24)
Correct the hourglass forces .
=> fix instability of QEPH shell element with Law127

engine/source/engine/resol.F, engine/source/tools/lagmul/lag_mult.F, starter/source/starter/lectur.F
Due to regressions, the working array is put back into /LAGMUL option
=> Restore WA for lagmul

engine/source/input/lectur.F
Correction of allocation of some output tables which now need to be done after H3D database initialization
Correction of allocation of some output tables which now need to be done after H3D database initialization
=> Correction LOAD DT curve : allocation of some output tables

starter/source/interfaces/inter3d1/i25sti3.F
Correction constant thickness gap with Igap=5 for springs
Correction constant thickness gap with Igap=5 for springs
=> Correction constant thickness gap for springs

common_source/eos/tillotson.F
Tillotson EoS subroutine for specific case of usage with multimaterial law 151 (/MAT/LAW151)
=> Multimaterial Solver law 151 : Tillotson EoS fix

common_source/modules/constant_mod.F, engine/source/elements/sh3n/coquedk/cncoef3.F, engine/source/elements/sh3n/coquedk/cndt3.F, engine/source/elements/shell/shell_offset_wm_ini.F90, engine/source/materials/mat/mat001/sigeps01g.F, engine/source/materials/mat_share/mulawc.F90, engine/source/materials/mat_share/mulawglc.F, engine/source/output/anim/generate/tensorc.F, engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
wrong or unstable results might happen when using standard shell w/ offset
correction on standard shell using offset
=> correction in standard shell using offset

common_source/eos/eosmain.F, common_source/eos/osborne.F
PMIN parameter introduced in Osborne EoS
no format change. Pmin parameter is read as usually from material definition /MAT/*
=> /EOS/OSBORNE : introducing cut off pressure (PMIN parameter)

starter/source/elements/spring/r4buf3.F
FIx of warning message for computation of skew for springs
=> FIx of warning message for computation of skew for springs

starter/source/constraints/thermic/hm_read_impflux.F
starter coredump using impflux
corrected index of igrsurf%eltyp and igrsurf/elem tables used tu fill up imflux buffer
=> Bug correction in hm_read_impflux

engine/source/materials/mat/mat126/sigeps126.F90, hm_cfg_files/config/CFG/radioss2026/MAT/matl126_johnson_holmquist_concrete.cfg, starter/source/materials/mat/mat126/hm_read_mat126.F90
Add the possibility to use the Cowper-Symonds strain rate dependency in /MAT/LAW126 
Add the possibility to use the Cowper-Symonds strain rate dependency in /MAT/LAW126  + Fix some old issues or bugs.
=> New features for /MAT/LAW126

engine/source/materials/mat/mat129/sigeps129s.F90, hm_cfg_files/config/CFG/radioss2026/MAT/Law129_therm_creep.cfg, starter/source/materials/mat/mat129/hm_read_mat129.F90, starter/source/materials/tools/func_table_copy.F90
New option for Norton Power law :
added tabulated time scale factor instead of analytical equation -  useful for easier correlation with experimental data
added new input in 2026 cfg file format
corrected function input transformation to internally stored tables in mat_param format
=> /MAT/LAW129 : add new input parameter in 2026 format

starter/source/materials/mat/mat088/cpp_table_mat_spline_fit.cpp, starter/source/materials/mat/mat088/hm_read_mat88.F90, starter/source/materials/mat/mat088/table_mat_spline_fit_mod.F90
Improve C1 spline approximation for /MAT/LAW88
Improve C1 spline approximation for /MAT/LAW88
=> Improve C1 spline approximation for /MAT/LAW88

starter/source/interfaces/inter3d1/i25neigh.F, starter/source/interfaces/inter3d1/i25norm3.F, starter/source/interfaces/inter3d1/i25sti3.F, starter/source/interfaces/inter3d1/inint3.F, starter/source/interfaces/inter3d1/insol3.F
COrrection force non null at t=0 for Inacti=5 and Iedg=22
COrrection force non null at t=0 for Inacti=5 and Iedg=22
=> Correction Inacti=5 with E2E non zero force + neighbhoor correction

engine/source/materials/mat/mat129/sigeps129s.F90
non initialized variable correction in the option using Garfallo creep law
=> Correct non initialized variable in material law129
