OpenRadioss/OpenRadioss

starter/source/elements/solid/solide/sinit3.F

Missing initialization for `DTX` for some materials

missing initialization of DTX in sinit3.F for material 26

---

engine/CMake_Compilers/cmake_linux64_AOCC.txt
engine/CMake_Compilers/cmake_linux64_gf.txt

Link sequence of the OpenMPI library is not good starting from  GCC/GFortran 9 (from Ubuntu 20).
It must be set in the lib area & not linking flags.

Change MPI flag place

---

common_source/eos/compaction.F
common_source/eos/eosmain.F
engine/source/multifluid/multi_submatlaw.F
hm_cfg_files/config/CFG/radioss2022/MAT/mat_EOS.cfg
starter/source/materials/eos/hm_read_eos_compaction.F

Legacy formulation is no longer the default one. It can however be used by setting IFORM=10
New default is IFORM=1 (unload slope is constant even if µ<0). Iform=2 is an additional formulation for which the unload slope increases with the compaction (from C1 to BUNL)
**Iform=1** : **Constant** unload modulus (BUNL) (**new default**)
**Iform=2** : **Linear** unload modulus form C1 to BUNL in [µ_min, µ_max]
**Iform=10** : **legacy** formulation which had a slope change when µ<0 (it switches from BUNL when µ>=0 to C1)
It can change numerical solution since unload behavior is affected (bug fix)
This change occurs with {/EOS/COMPACTION + UNLOADING + µ<0}

/EOS/COMPACTION:improve unload behavior

---

starter/source/elements/solid/solide/sderi3.F
starter/source/elements/solid/solide/sinit3.F
starter/source/output/message/message.F

Even if these options are not compatible Starter must go up to a normal termination and must print the expected error message. Starter had failed with ERROR TRAPPED before displaying the Error message related to this specific input incompatibility.
_Updates :_
1. SINIT3( ) : Usage of LBUF%VOL0DP is conditionned to its allocation E
2. SINIT3( ) : VOLU is initialized to 0.0 (otherwise it also prevents Starter from going up to normal termination in case of input inconsistency)

uninit:Starter must go up to Normal termination even with input inconsistency

---

engine/source/output/restart/w_gr_entity.F
engine/source/output/restart/w_line_str.F
engine/source/output/restart/w_surf_str.F

The length is set to `ncharline` instead of `LTITR`

fix for title lengths

---

engine/source/airbag/fv_up_switch.F
engine/source/airbag/fvbag.F

With Iequi=1 option (/MONVOL/FVMBAG1) Engine does not call fvbag.F and fv_up_switch.F subroutines. (polyhedra calculation skipped). Consequently at time to fire there was an initialization issue. Engine now works properly at time to fire when using /DT/FVMBAG/2

/DT/FVMBAG/2:fix issue at time to fire

---

starter/source/materials/mat/mat119/hm_read_mat119.F
starter/source/tools/curve/func_inters.F

In some cases for LAW119 intersection between loading and unloading curve is not found correctly generating error in the starter. The intersection search is corrected.

LAW119 fix of intersection between load/unload curve

---

starter/source/properties/solid/hm_read_prop14.F

Default values of qa, and qb are now set to 1.10 et 0.05. Pseudo viscosity is essential to stabilize staggered scheme and also to model shocks. It acts where and when it is necessary. 
Specific case when /CAA (obsolete) is used leads to qa=qb=ZERO
previous results obtained by setting qa=qb=1E-20

/PROP/FLUID:default values for pseudo viscosity

---

extlib/hm_reader/apr_license.txt
extlib/hm_reader/boost_license.txt
extlib/hm_reader/cpp-btree_license.txt
extlib/hm_reader/dtoa_license.txt
extlib/hm_reader/fdlibm_license.txt
extlib/hm_reader/openthreads_license.txt
extlib/hm_reader/phmap_license.txt
extlib/hm_reader/zlib_license.txt

Third Party code license files are now in 2 places :
* The directory where the third party belongs, 
* The license directory in extlib.

Add relevant license files in hm_reader directory

---

.github/workflows/prmerge_ci_main.yml

Change delivery binaries package to fit the source architecture
•	the executables are in exec directory (no more in bin)
•	config files are in hm_cfg_files (no more in cfg)
•	third party libraries are in extlib/ (no more in lib)

CI Merge - improve devliery binaries package structure

---

engine/source/materials/mat/mat104/mat104c_nodam_newton.F
engine/source/materials/mat/mat104/mat104c_nodam_nice.F

In simple precision, the test NORMSIG > ZERO could be fulfilled at a very low value even if the stress tensor is null. This could lead to FDR value close to zero generating NaN issue. 
Set up a strictly positive tolerance at EM10 to avoid NaN computation.

Fix SP issue for QA tests setup

---

engine/source/mpi/nodes/spmd_exch_vol.F

SPMD simulations were crashing in Simple precision when using ITET4 = 3 flag. 
The exchange routine had a bug. The arrays exchanged at boundaries are double precision arrays, but they were sent and received as REAL that depends on the precision. REAL has been changed to MPI_DOUBLE_PRECISION.

Fix SP issue for ITET4=3 with SPMD

---

engine/source/materials/fail/orthstrain/fail_orthstrain_s.F

PON issue on QA tests results for /FAIL/ORTHSTRAIN with solids
Revise the damage variable effect on stress computation + improve the output messages that were not precise enough and in agreement with the ones defined for shells.

Fix orthstrain parith on issue for solids

---

engine/share/modules/inter_sorting_mod.F
engine/source/interfaces/generic/inter_count_node_curv.F
engine/source/interfaces/int07/inter_sort_07.F
engine/source/interfaces/intsort/i7buce.F
engine/source/interfaces/intsort/i7main_tri.F
engine/source/interfaces/intsort/i7tri.F
engine/source/interfaces/intsort/i7trivox.F

An issue was introduced in the PR related to the new collision detection algorithm
The number of main nodes was overestimated, so the standard deviation was wrong and the voxel of main surface was not centre on the main nodes
This lead to a really bad performance of the i7trivox routine
The computation of the main node number is fixed

Fix an issue in the collision detection algo

---

engine/source/elements/solid/solide/sfint_reg.F
engine/source/elements/solid/solide/sforc3.F
engine/source/elements/solid/solide4/s4fint_reg.F
engine/source/elements/solid/solide4/s4forc3.F
engine/source/elements/solid/solide8e/s8eforc3.F
engine/source/elements/solid/solide8s/s8sforc3.F
engine/source/elements/solid/solide8z/s8zfint_reg.F
engine/source/elements/solid/solide8z/s8zforc3.F
engine/source/elements/solid/solidez/szforc3.F

Some issue appeared during erosion with non-local method. LE_MAX value seems to be too high in some cases to compute absorbing forces. 
Replace LE_MAX by the initial characteristic length of the element.

Fix non-local erosion for solid elements

---

starter/source/materials/mat/mat051/m51init.F
starter/source/materials/mat/mat051/nrf51ini.F

This change is fixing issue reported by runtime tool "check bounds" when Starter is compiled with debug version. (NEL << NUMELS or NUMELQ,   since NEL is group size, not total element numbers)

law51:array_dimension

---

engine/source/airbag/fv_up_switch.F
engine/source/airbag/fvbag.F

When using new time step option /DT/FVMBAG/2 a smoothing parameter can be input (lambda). It affects the airbag time step and this has to be taken into account in Time Histories output.
but it fixes output from /TH/MONV(DTBAG)

FVMBAG:DTBAG th output

---

starter/source/elements/initia/initia.F

In case of wrong value in /ANALY option (2D instead of 3D) the call of EPORIN3 subroutine is now unplug. Otherwise it is called with unallocated arguments and Starter crash. Starter is now running up to the end in this specific case (and error id 603 is displayed)

initia>eporin3( ) : unplug condition in case of incompatible input options

---

engine/source/output/h3d/h3d_results/h3d_shell_scalar.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

Numerical schlieren is output using exp (- 1.00 * ||grad(rho)||)
Related Engine keyword : /H3D/ELEM/SCHLIEREN
It was also the opportunity to update related h3d subroutines:
-  Cleaning unused variables
- Defining explicit array sizes

H3D:numerical schlieren for TRIA solid elements

---

engine/source/airbag/fvupd.F

Engine output regarding merging of finite volumes are suppressed when the verbose parameter (ILVOUT) of the FVMBAG1 and FVMBAG2 starter card is set to zero

removed merge output for fvmbags when verbose parameter is set to zero

---

engine/source/materials/fail/tabulated/fail_tab_s.F
starter/source/materials/fail/tabulated/hm_read_fail_tab1.F

Damage evolution function for /FAIL/TAB1 was not displayed in the starter .out file and was not properly used for solids.  
Add the output after starter and change the number of the function used in the engine.

Fix damage evolution function for fail tab1 with solids

---

engine/source/airbag/mhvis3.F
engine/source/elements/sh3n/coque3n/c3dt3.F
engine/source/elements/sh3n/coque3n/c3forc3.F
engine/source/elements/sh3n/coque3n/cssp2a11.F
engine/source/elements/sh3n/coquedk/cdkforc3.F
engine/source/elements/sh3n/coquedk/cndt3.F
engine/source/elements/sh3n/coquedk6/cdk6forc3.F
engine/source/elements/shell/coque/cforc3.F
engine/source/elements/shell/coqueba/cbaforc3.F
engine/source/elements/shell/coquez/czforc3.F
engine/source/elements/xfem/c3forc3_crk.F
engine/source/elements/xfem/cforc3_crk.F
engine/source/elements/xfem/czforc3_crk.F

fixing random sound speed value of law58
remove debug law58 (submit by Maciek before)
nodal time step isn't consisting w/ sound speed of law58
sound speed of law58 has been changed (Maciek), now nodal time step will take into account this change, generally higher

/DT/NODA taking into account sound speed for law58

---

engine/CMake_Compilers/cmake_linuxa64.txt

Issue linuxa64 build flags : it is -O3 instead of -03

Issue linuxa64 build flags : it is -O3 instead of -03

---

engine/source/output/anim/generate/schlieren.F
engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

Improves Engine behavior when /H3D/ELEM/SCHLIEREN is requested. Unplug calculation when it is not expected.
Schlieren calculation  requires :
- ALE frawework (adjacent elem buffer must be allocated to evaluate density gradient)
- 3d solids (hexas,tetras) , 2D solids (quads and trias)
It fixes a specific situation for case  {N2D=0 + /ALE/MAT +  /SHELL + /H3D/ELEM/SCHLIEREN} which may lead to segmentation fault

H3D:unplug schlieren calculation with unexpected situation

---

engine/source/interfaces/interf/check_active_elem_edge.F

An issue was found in the shooting node algorithm with the interface /TYPE11 : a segfault can occur if an edge is on a processor and if there isn't any element associated to the 2 nodes of the edge on this processor

Shooting algo : fix an issue

---

starter/source/elements/solid_2d/quad/qgrtails.F
starter/source/elements/solid_2d/tria/t3grtails.F
starter/source/elements/sph/spgrhead.F
starter/source/output/th/hm_read_thgrne.F

- qgrtail, t3grtail, spgrhead : IPARG(NPARG,NGROUP) restored with IPARG(NPARG,*) since IPARG is here IPARGTMP and dimension is oversized to NUMEL instead NGROUP. 
- hm_read_thgrne : ensure correct program behavior  (error message and normal termination) with check bounds runtime tool

updating array bounds

---

engine/source/materials/mat_share/mmain.F

Recently implemented /FAIL/TAB2 presented and issue when using old solid material laws (< /MAT/LAW28) 
Fix the bug by changing the stress softening variable.

Fix issue when using old material laws with fail tab 2 on solid elements

---

.gitattributes
HOWTO.md

When files are cloned on windows,
scripts must be in Unix format to be used in cygwin.
Adding stuff in .gitattributes

Add lf Attributes for script files 

---

engine/source/airbag/fvbag.F

OpenMP issue was fixed in fvbag.F.
It was necessary to define LOCAL variables in openMP loops.
_This is fixing potential engine failure  during first cycle in fvbag.F when -nt>1_

/MONVOL/FVMBAG1,2 : openmp fix

---

engine/source/materials/fail/gene1/fail_gene1_c.F
engine/source/materials/fail/gene1/fail_gene1_s.F
starter/source/materials/fail/gene1/hm_read_fail_gene1.F

Add the possibility to restrict the use of SIGP1 criterion to positive stress triaxialities. 
This is done with the input : 
- if SIGP1 < 0: it is restricted to positive stress triaxialities,
- if SIGP1 > 0: it is unrestricted.

Add possibility to restrict SIGP1MAX criterion to positive stress triaxialities

---

engine/source/output/anim/generate/nodalp.F

In specific cases, for example when /MAT/VOID is used, GBUF%SIG is not allocated. Nodal Pressure is also not relevant to be calculated. Conditionnal test was introduced to ensure relevant calculation.
it affects only output contour for nodal pressure

/ANIM/NODA/P:ensure calculation only if buffer is allocated

---

hm_cfg_files/config/CFG/radioss2019/MAT/matl25_compsh.cfg

Bad unit of MAT_SIG parameter when MAT_Iflag = 0, MAT_SIG was supposed to be dimensionless
Set MAT_SIG as dimensionless.

Fix unit of fmax in /MAT/LAW25 .cfg file

---

starter/source/system/sysfus.F

sysfus.F : msgid 79 is displayed only id ID is not 0
It prevents Starter from outputing unexpected messages
> ERROR ID :     79
> ** ERROR: DUPLICATE ID
> DESCRIPTION :  
>    IN TH GROUP
>    ID=0 is DUPLICATED
whenever a suitable message is already displayed :
>   ERROR ID :     69
> ** ERROR IN TH SELECTION (ELEMENT)
> DESCRIPTION :  
>    -- THGROUP ID:	2
>    -- THGROUP TITLE: New TH 2
>    TH ELEMENT SELECTION ID=64 DOES NOT EXIST

sysfus.F:msgid=79, prevent from unexpected output

---

engine/source/elements/solid/solide/sforc3.F
starter/source/elements/elbuf_init/suderi3.F
starter/source/elements/solid/solide/checksvolume.F
starter/source/elements/solid/solide/sderi3.F
starter/source/elements/solid/solidez/szderi3.F

Going back to original formulation for computation of volume because of unexpected numerical changes on benches.

Revert some changes in volume computation that caused numerical diffs

---

starter/source/elements/beam/dt1lawp.F
starter/source/properties/beam/hm_read_prop03.F
starter/source/properties/beam/hm_read_prop18.F

diverging result (instability) if using default flexural damping value
reset default flexural damping value to the same as beam type3 to fix the instability issue, some code cleaning have been done also for hm_read type3&type18

instability issue fixing for beam type18

---

engine/source/materials/mat/mat025/sigeps25cp.F

Bad initialization of SIGY variable. YLD must be initialized instead as it is the variable introduced in the plasticity routine called M25CPLRP2
Replace SIGY by YLD and remove the IPT condition as it must be initialized at each timestep (YLD is a local variable and not an element buffer variable like SIGY).

Fix uninitialized SIGY variable for /MAT/LAW25

---

engine/source/materials/fail/syazwan/fail_syazwan_c.F
engine/source/materials/mat_share/mulawc.F
engine/source/materials/mat_share/usermat_shell.F
hm_cfg_files/config/CFG/radioss2022/FAIL/fail_syazwan.cfg
hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
hm_cfg_files/config/CFG/radioss2022/hm_data_hierarchy.cfg
starter/source/materials/fail/hm_read_fail.F
starter/source/materials/fail/syazwan/hm_read_fail_syazwan.F

Added /FAIL/SYAZWAN, using ID 99. Currently available for shell element only.
1. Added features to initialize damage value from strain histories
2. Implementation of failure model based on failure surface equation
3. Mesh regularization function
4. Added option for instability based on Swift Instability theory (using n-value)
Comparison of damage value from complete simulation against the initialized value

Implementation of /FAIL/SYAZWAN 

---

engine/source/elements/shell/coque/cforc3.F

ALDT table is not computed with using Ishell = 1,2,3,4 and /DT/NODA. However, it is needed for some material laws and failure criteria. 
After debugging with Qiang, a condition "NODADT == 0"  was removed to fix the problem.

Fix element size regularization with Ishell 1 2 3 4

---

starter/source/materials/fail/gene1/hm_read_fail_gene1.F

The output message of starter code was not clear enough for /FAIL/GENE1 regarding hydrostatic pressure criteria. 
Improvements have been made according to Marian suggestions.

Improve starter message for /FAIL/GENE1 output

---

engine/share/modules/scratchfiles_mod.F
engine/source/engine/radioss2.F
engine/source/input/freform.F
engine/source/output/restart/rdresb.F
engine/source/output/restart/wrrest.F
engine/source/system/arret.F

Engine use internal Scratch files to parse input Deck & some options use some as well.
It is cleaner to use Real files and delete them after usage. 
Files are named now with deck Rootname + ProcessID + MPI Rank 
to avoid 2 MPI ranks have same file name.

replace internal scratch files with real files

---

engine/source/materials/fail/tensstrain/fail_tensstrain_c.F

When a shell element was deleted with /FAIL/TENSSTRAIN, the stdout message was not correct. Time and strain were inverted.
Replace correctly time and strain for the stdout output message.

Fix element deletion message for /FAIL/TENSSTRAIN

---

starter/source/interfaces/int07/hm_read_inter_type07.F

Write `ABS(STFAC)` instead of `-STFAC` in the *0.out

updated int07 hm reader to write ABS stfac values to 0000.out

---

starter/source/system/timediff.c

memset call int timediff.c needs an include : memset.h under Windows & string.h under Linux.

 Missing include in timediff

---

engine/source/materials/mat_share/mulaw.F
engine/source/output/h3d/h3d_results/h3d_fld_strain.F
engine/source/output/h3d/h3d_results/h3d_fld_tsh.F
engine/source/output/h3d/h3d_results/h3d_skin_scalar.F

file missed
actual /H3D/SOLID/FLDZ/OUTER has inconsistent result w/ output strain when fully integration thick-shell is used   
change actual  FLD output implementation to be consistent to the strain (elementary average) output, because FLD output curve for forming simulation need both of them that the consistence is important.

consisting FLD output (H3D)

---

engine/source/time_step/find_dt_for_targeted_added_mass.F
starter/source/coupling/rad2rad/r2r_speedup.F
starter/source/materials/time_step/outri.F
starter/source/tools/admas/add_mass_stat.F

The TRIRAP routine is a very old buggy sorting routine. The aim of this PR is to replace TRIRAP by a non-buggy routine MYQSORT 
TRIRAP is now replaced by MYQSORT routine. MYQSORT routine needs 4 arguments :
MYQSORT( N    ,    A     ,     PERM    ,      IERROR   )
N : size of array A and PERM
A : double or float array, this array is sorted 
PERM : integer array, permutation array
IERROR : integer, flag to detect an error

Remove the buggy sorting routine trirap

---

starter/source/materials/mat/mat025/hm_read_mat25.F

In simple precision, some default values defined in the law 25 can lead to NaN in the starter.
The computation now is done with double precision, then the double precision results are loaded in simple precision variable.

Fix a simple precion issue in the law 25

---

engine/source/time_step/find_dt_for_targeted_added_mass.F

A non-meticulous developer (me) introduced an issue in the PR#756
The size of TMP and PERM arrays is SIGZ and not NUMNOD

Fix an issue introduced in PR#756

---

engine/CMake_Compilers/cmake_linux64_AOCC.txt
engine/CMake_Compilers/cmake_linux64_gf.txt
engine/CMake_Compilers/cmake_linuxa64.txt

Typo issue in cmake scripts  for loading the libraries with -mpi-root option.

 typo issue in cmake scripts

---

starter/source/interfaces/friction/reader/hm_read_friction.F

Uninitialized variable in reading /FRICTION card. Starter crashes in debug mode.
Correction of un uninitialized variable, reading /FRICTION card.

Correction of an uninitialized variable in reading /FRICTION card

---

engine/CMake_Compilers/cmake_linux64_AOCC.txt
engine/CMake_Compilers/platforms.txt
engine/share/spe_inc/machine.inc
engine/share/spe_inc/my_allocate.inc
engine/share/spe_inc/vectorize.inc
extlib/lapack-3.10.0/lib_linux64_AOCC/libblas.a
extlib/lapack-3.10.0/lib_linux64_AOCC/liblapack.a
starter/CMake_Compilers/cmake_linux64_AOCC.txt
starter/CMake_Compilers/platforms.txt
starter/share/spe_inc/machine.inc
starter/share/spe_inc/my_allocate.inc
starter/share/spe_inc/vectorize.inc
starter/source/coupling/rad2rad/r2r_fork.F

The changes enables build with the latest release of AMD's AOCC-4.0 compiler. The changes, in theory, should only introduce perturbations to the results. 
1. removed some flags that are meaningless for AOCC-4.0 compiler and replaced them as needed in _cmake_linux64_AOCC.txt_
2. The '\\' in the C -preprocessor macros leads to the "unmatched quotes" error even with -fbacklash (or -fnobacklash) flag; mitigated this issue by minor modifcations in the  _engine/share/spe_inc/my_allocate.inc_ as well as _starter/share/spe_inc/my_allocate.inc_
which is AOCC specific and should not affect other compilers.  (Introduced COMP_AOCC for this purpose)
3. Built Lapack by AOCC-4.0 and integrated to the extlib/ using git-lfs; An alternative way would be to integrate lapack  by ExternalProject_Add utility …

addressing AMD's AOCC build issues

---

engine/CMake_Compilers/cmake_linux64_intel.txt
engine/CMake_Compilers/cmake_win64.txt

As seen in #811 , OneAPI compiler (ifx) may fail to compile FVMBAG routines
Optimization level set to 01. May be increased again after Intel's feedback

Intel OneAPI: lower optimization level for FVM airbags routines

---

starter/source/airbag/fvmesh.F
starter/source/airbag/polyhedr1.F

initialization of NELP and PTRI to 0 in order to disable Forcheck warnings (subroutines fvmesh.F and polyhedr1.F)

forcheck feedback

---

starter/source/elements/shell/coque/cgrtails.F
starter/source/elements/solid/solide/sgrtails.F
starter/source/starter/lectur.F

Element reordering was applied for both domain decomposition, but was useful only for the last one.
Do not reorder elements if IDDLEVEL == 0

No Cuthill-Mckee ordering after the first domain decomposition

---

engine/source/materials/mat/mat112/mat112_xia_newton.F
engine/source/materials/mat/mat112/mat112_xia_nice.F
engine/source/materials/mat/mat112/mat112c_xia_newton.F
engine/source/materials/mat/mat112/mat112c_xia_nice.F

Law 112 presented some issues in single precision when using NICE return mapping algorithm (QA test 8.1546). The return mapping was not fully correct with theory. Yield function value needed to be reset when the element behavior is not plastic. In addition, some loop performance could be increased by decreasing the number of treated element. 
Fix NICE return mapping issue by resetting the yield function value when element behavior is not plastic + improve some loop.

Law 112 performance improvement and bug fix on return mapping algorithm NICE

---

engine/source/tools/curve/table_tools.F

bug correction : problem of 3D table interpolation when second variable has only one value.
A case with incomplete table grid which is not detected in starter. When a second variable of 3D table has only one value, part of the table grid becomes undefined. Problem avoided directly in engine by skipping interpolation in second direction.

/TABLE/1 : correction of 3D table interpolation with incomplete grid

---

starter/source/elements/solid/solide/sgrtails.F
starter/source/elements/solid/solide/sinit3.F

strain and stress not written and read correctly with sta output and INIBRI card
set istrain=1 for law24 and store strain tensor in buffer in order to be retreived at the material level

/MAT/LAW24 : set istrain=1 for law24 and store strain in buffer

---

engine/source/output/anim/reader/anim_dcod_key_0.F

/ANIM/ELEM/TSAIWU was not functionnal (similar problem was noticed for DAMG).
Allow the engine keywords /ANIM/ELEM/TSAIWU and /ANIM/ELEM/DAMG

Fix missing output keyword for TSAIWU criterion in ANIM files

---

starter/source/system/fsdcod.F

Wrong initialization when a Material has a non existing sensor in input deck
Starter has UID to ID conversion for Materials. IUD was add in the Material Buffer.
When conversion fails,  a Warning message is printed, but the SensorID is still in UID format and not set to  0 (eg no sensors)
This can lead to a Engine core dump...

Wrong intialization when a Material has a non existing sensor in input deck

---

common_source/eos/tabulated.F

Initialization of sound speed derivative in case of colocated scheme (law151) with new tabulated EoS.
This fix ensures the expected behavior when A_func or B_func is not provided.
Changes are obvious : 
DERIA_A is set to 0.0 when A_FUNC is not provided
DERIA_B is set to 0.0 when B_FUNC is not provided

/EOS/TABULATED:init. derivative for colocated scheme

---

starter/source/system/fsdcod.F

Issue was made during Sensor availability check in materials.
When a Sensor is not found, it should print the warning & set to 0.
Here the Check was not well made. IF did not had THEN, so set to Zero was done all the time.

Issue in Sensor availibility cheks

---

starter/source/spmd/domain_decomposition/check_skew.F
starter/source/spmd/domdec2.F

A bug was recently introduced in PR#975 : CEP array is now always allocated with a size greater than 0. -fcheck=bounds (or intel compiler option -check bounds) complains about this new size in a starter routine
OFFSET variable is now an argument of CHECK_SKEW array : OFFSET allows to point to the good place in CEP array

Fix a check bounds issue

---

hm_cfg_files/config/CFG/Keyword971_R12.0/INCLUDE/include_radioss.cfg
hm_cfg_files/config/CFG/Keyword971_R12.0/data_hierarchy.cfg

Target of this dev is to be able to include radioss deck in dyna deck 
It's now possible to mix Radioss & Dyna input using *INCLUDE_RADIOSS card 
Limitations : part and related material & property ( section is dyna) should be in same format
nodes & elements not supported for the moment in the *INCLUDE_RADIOSS option

include radioss deck in dyna deck using *INCLUDE_RADIOSS option

---

engine/source/output/h3d/h3d_results/genh3d.F

Correction problem checkbound problem
Correction problem checkbound issue. The keyword H3D/NODA/CONT/MAX was changed to H3D/NODACONT/TMAX.
The change in code was missing in genh3d. It doesn't go in the right if bloc. That is why the NODAL_VECTOR was not well computed.

correction_bug_CONTMAX_output

---

starter/source/system/sysfus.F

Improving Starter behavior when group of nodes contains a unexisting node.
-1- FUNCTION USR2SYS2 : error message id=78 (leads now to a clear output message)
-2- FUNCTION ULIST2S    : case of unexisting node : prevent array index from being 0

improving Starter behavior in case of unexisting node in group

---

engine/share/modules/rad2r.F
engine/source/coupling/rad2rad/r2r_exchange.F
engine/source/coupling/rad2rad/r2r_getdata.F
engine/source/coupling/rad2rad/r2r_init.F
engine/source/coupling/rad2rad/rad2rad_c.c
engine/source/engine/resol.F
engine/source/engine/resol_init.F
engine/source/output/restart/read_nloc_struct.F
starter/source/coupling/rad2rad/new_link.F
starter/source/coupling/rad2rad/r2r_domdec.F
starter/source/coupling/rad2rad/r2r_group.F
starter/source/coupling/rad2rad/r2r_input.F
starter/source/coupling/rad2rad/tagnod_r2r_nl.F
starter/source/materials/fail/nloc_dmg_init.F
starter/source/restart/ddsplit/write_nloc_struct.F
starter/source/starter/lectur.F

Compatibility between rad2rad and NLOCAL method. NLOCAL dof must be coupled using rad2rad, in the same way than classical dof. New exchanges between rad2rad and engine is needed.

RAD2RAD compatibility with NLOCAL

---

starter/source/elements/shell/coque/corthini.F

IP=23 on orthotropic shell is not implemented as expected
change actual IP=23 to be consistent with Dyna AOPT=3

Change IP=23 in ortho_shell to be consistent with Ls_dyna

---

engine/source/materials/mat/mat036/sigeps36.F
engine/source/materials/mat/mat036/sigeps36c.F
engine/source/materials/mat/mat036/sigeps36pi.F
starter/source/materials/mat/mat036/hm_read_mat36.F

/MAT/LAW36 : add new option for tabulated yield stress interpolation using logarithmic base for strain rates
modified starter input (new values for ISRATE flag) and engine code for shells, solids and beams

add optional logarithmic interpolation for strain rate

---

starter/source/interfaces/inter3d1/i25pen3.F
starter/source/interfaces/inter3d1/i25trivox1.F
starter/source/interfaces/inter3d1/inint3.F

Correction of problem wrong penetrations computed in starter : no more warning for non real contact
Correction of problem wrong penetrations computed in starter :  keep all sorted couples first and exclude contact in wrong direction i25pen.F instead of i25trivox.F

correction of wrong initial penetrations inter25

---

starter/source/tools/curve/hm_read_move_funct.F

If there exists a /MOVE_FUNCT with negative Abscissa scale factor, then if there is another /FUNCT in the model, the 'transformed' function is incorrect/corrupted (values from that/those other curve(s) appear in the transformed curve), 
left below is without another curve (ok), with another curve, the transform is corrupt/incorrect, this is not just a 0000.out echo issue, the incorrect curve is used in model also (e.g. for non-linear spring etc)
there were some bug when resorting abscissa in case several func in the model

issue with move funct with negative xscale

---

engine/source/materials/mat/mat088/sigeps88c.F

/MAT/LAW88 for shell :  The introduction of hysterisis effect lead to wrong behavior in Shear qa test.
/MAT/LAW88 + Shell :  Improving the  criteria check of loading and unloading.

LAW88  ,  wrong behavior in Shear 

---

starter/source/materials/mat_share/matini.F

avoid bug (potential coredump) when INISTATE option is used to initialize plastic strain which is not allocated in the target material law
modification in matini.F : use local table as a epsp pointer target instead of non allocated element buffer variable

correct bug of writing to non allocated plastic strain table in elem

---

starter/source/constraints/general/mpc/hm_read_mpc.F
starter/source/constraints/general/rbe3/hm_read_rbe3.F
starter/source/constraints/general/rwall/hm_read_rwall_lagmul.F
starter/source/constraints/general/rwall/hm_read_rwall_therm.F
starter/source/elements/initia/scaleini.F
starter/source/elements/solid/solide/sgrtails.F

Few bug fixes of issues found with `-fsanitize=address`
- Invalid write into unallocated arrays in materials
- invalid read from unallocated arrays in some `hm_*` routines

various bugs found with address sanitizers

---

engine/source/materials/mat/mat058/sigeps58c.F

user needs output of engineering stress instead of true stress in user variables 1 and 2
update of previous code correction : delete old calculation of UVAR(1),UVAR(2) which were still overwritting engineering stress by true stress

/MAT/LAW58 : engineering stress output - delete forgotten previous user variable computation

---

starter/source/materials/mat/mat053/hm_read_mat53.F

Timestep in starter was badly estimated for /MAT/LAW53 (10E+21 in the test case). 
Add the estimation of the soundspeed in the reading routine for table PM(27) + add some missing data in PARMAT table. Now the timestep is correctly estimated.

Fix timestep computation in starter for /MAT/LAW53

---

engine/source/system/sysfus.F

Compilers may evaluate an if expression before applying condition.
Here the First condition applies, Number of node on domain is zero,
But second condition implies the opposite.
This fix separates the 2 conditions to avoid issues.

Issue in Global to local node conversion in Engine

---

starter/source/elements/elbuf_init/elbuf_ini.F
starter/source/restart/ddsplit/w_elbuf_str.F

Allocation of ELBUF_TAB%BUFLY%EOS%VAR is managed also for 1D elem which leads to a suitable BUFLEN value.
It fixes a potential issue with Element Buffer allocation.

EOS%VAR & 1D elems

---

starter/source/tools/sensor/inisen.F

Wrong number of caller/callee arguments in Sensor Init

Wrong number of caller/callee arguments in Sensor Init

---

engine/source/materials/fail/tsaihill/fail_tsaihill_c.F
engine/source/materials/fail/tsaihill/fail_tsaihill_s.F
engine/source/materials/fail/tsaiwu/fail_tsaiwu_c.F
engine/source/materials/fail/tsaiwu/fail_tsaiwu_s.F

Potential issue detected by check bound build when using /FAIL/TSAIWU and /FAIL/TSAIHILL. RFACTR is badly computed due to a potential division by zero. 
Avoid the division by zero and improve the TSAIHILL formula for solids.

Fix potential check bounds issue in /FAIL/TSAIWU and /FAIL/TSAIHILL

---

starter/source/interfaces/int18/hm_read_inter_type18.F

Parameters BUMULT(sorting factor) and VISC (damping coefficient) are obsolete since 2021 input version.
Printout in Starter listing file for these two parameters is now done only if relevant.
no expected change in numerical solution

/INTER/TYPE18:remove obsolete printout from Starter Listing file

---

engine/source/implicit/imp_buck.F

DTANIM in precompiler block "#if defined(MUMPS5) && defined(DNC)" was not correctly initilized
It is now defined from a module called ANIM_MOD
Fix for f6ce8bb50f84f0b6c261578f581baea0e62c025f

/ANIM/DT:set suitable definition for DTANIM in imp_buck.F

---

starter/source/interfaces/int18/hm_read_inter_type18.F

Error message is introduced when GRBRIC_ID=0 for following cases : 
- Constant Gap formulation (Igap=0,1000) but GAP=0.0
- Variable Gap formulation (Igap=1)
In these two cases group of bricks is required to call later LECINT > INGRBRIC_DX in order to estimate automatically gap value.

/INTER/TYPE18:improve Starter behavior by checking user input

---

engine/source/elements/solid/solide8z/s8zfint_reg.F

An OpenRadioss user has raised a small bug for element deletion with non-local when using fully integrated hexa elements. 
Change nodal velocity from 7 to 8 for the 8th nodes.

Fix non local bug in element deletion for fully int hexa

---

engine/source/elements/solid/solide10/s10bilan.F
engine/source/elements/solid/solide10/s10forc3.F
engine/source/elements/solid/solide20/s20bilan.F
engine/source/elements/solid/solide20/s20forc3.F
engine/source/elements/solid/solide4/s4bilan.F
engine/source/elements/solid/solide4/s4forc3.F
engine/source/elements/thickshell/solide16/s16bilan.F
engine/source/elements/thickshell/solide16/s16forc3.F
engine/source/elements/thickshell/solide6c/s6cbilan.F
engine/source/elements/thickshell/solide6c/s6cforc3.F
starter/source/elements/solid/solide/sbulk3.F

Fix THPART mass computation when element deletion occurs for TETRA, SOLID20, and THICKSHELL
Modification of PARTSAV mass computation + fix a sanitize bug introduced in 2015 in SBULK3.F

Fix thpart mass computation for tetra + quadratic solids + thickshells

---

engine/source/materials/mat/mat104/mat104_ldam_nice.F
engine/source/materials/mat/mat104/mat104_nldam_nice.F
engine/source/materials/mat/mat104/mat104_nodam_nice.F
engine/source/materials/mat/mat104/mat104c_ldam_nice.F
engine/source/materials/mat/mat104/mat104c_nldam_nice.F
engine/source/materials/mat/mat104/mat104c_nodam_nice.F
engine/source/materials/mat/mat110/sigeps110c_lite_nice.F
engine/source/materials/mat/mat110/sigeps110c_nice.F
engine/source/materials/mat/mat115/mat115_nice.F

An old NICE return mapping was implemented for /MAT/LAW104, /MAT/LAW110 and /MAT/LAW115
Update the return mapping algorithm by saving the old yield function value only when a plastic behavior is detected (DPLA > 0).

Update NICE return mapping for /MAT/LAW104 110 and 115

---

starter/source/interfaces/inter3d1/i25sti3.F

Correction of Error message Inter type 25 when using Ivis2 with solids (Ivis2= -1)
Correction of Error message Inter type 25 when using Ivis2 with solids :Ivis2 need to be equal to -1 ( Ivis2 seems can have other values different from 0 and -1 which is not in documentation)

Correction of Error message Inter type 25 when using Ivis2 with solids

---

engine/source/materials/mat/mat104/mat104c_ldam_newton.F
engine/source/materials/mat/mat104/mat104c_ldam_nice.F
engine/source/materials/mat/mat104/mat104c_nldam_newton.F
engine/source/materials/mat/mat104/mat104c_nldam_nice.F
engine/source/materials/mat/mat104/mat104c_nodam_newton.F
engine/source/materials/mat/mat104/mat104c_nodam_nice.F

Transverse shear in plastic behavior was considered in /MAT/LAW104 instead of remaining purely elastic as expected. This leads to strong instability in bending when using Ishell = 1,2 and 4. 
Remove transverse shear from plastic behavior in all routines of /MAT/LAW104.

Remove transverse shear from plastic behavior in /MAT/LAW104 for shells

---

starter/source/elements/initia/initia.F

wrong Isolid value of /BRICK20 (solid 20 node element) in Part/Mat Review of Starter outfile when the same Pid is shared by different solid parts
Correction done on the Isolid of S20, as well for tetra4,tetra10 and penta6.

correction in PART/MAT review of Starter w/ S20

---

common_source/modules/pblast_mod.F
engine/source/loads/general/pfluid/pfluid.F
engine/source/loads/pblast/pblast.F
engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F
starter/source/loads/general/pfluid/hm_read_pfluid.F
starter/source/loads/pblast/hm_read_pblast.F

- FSKY array is reset to 0. when time > Tstop. This change is following Tstop introduction with 66f61b7a8cb2b23572b2c6319147e272d19c043c
- prevent from data race in array A(1:3,1:NUMNOD) with parith_off option
- source cleaning : setting correct argument size in reader subroutine NUMLOADP->NLOADP

/LOAD/PBLAST:parith_on fix when time>Tstop

---

engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F

A typo error was spotted in the original paper "Glenn Randers-Pehrson, Kenneth A. Bannister, Airblast Loading Model, ARL-TR1310, March 1997" It is now fixed.
Incident wave factor updated : 1+cos²a-2cos a -->  1+cos a-2cos²a

/LOAD/PBLAST:formulation updated (scale factor for incident wave)

---

engine/source/output/restart/rdresb.F

Issue with 6f1560aff5a3c1758af380313af6cbf70d2aae9b : TMPDIR fix
Missing array size for TMPDIR directory on 2 routines

Issue with 6f1560aff5a3c1758af380313af6cbf70d2aae9b : TMPDIR fix

---

starter/source/airbag/hm_read_monvol_type11.F
starter/source/airbag/hm_read_monvol_type8.F
starter/source/airbag/hm_read_monvol_type9.F

Output titles in Starter listing file are now correct for airbag ventholes and porous surfaces. Similar fix for Airbag types 8, 9, and 11

FVMBAG:output correct titles for vent holes and porous surfaces

---

engine/source/output/sta/stat_s_ortho.F

Wrong Isolid value output in /STATE/BRICK/ORTHO when Isolid=18 (input)
wrong value corrected

Wrong Isolid value in /STATE/BRICK/ORTHO

---

engine/source/mpi/interfaces/spmd_exch_efric.F
engine/source/mpi/interfaces/spmd_exch_press.F
engine/source/output/h3d/h3d_build_fortran/lech3d.F

Adding the Friction energy output for interface type 19 ( only the friction of interface type 7 is taken into account) 
Adding the Friction energy output for interface type 19 : store the energy output from interfaces type 7 in the right output array corresponding to the interface type 19

friction energy output for Inter type19 (only inter7 part is included) 

---

starter/source/loads/pblast/hm_read_pblast.F

- Parameter PMIN (Minimum Pressure) read from option /LOAD/PBLAST is not output in Starter listing file.
- format 2021 & 2022 were removed  (redundant with format 2001 & 2002)

/LOAD/PBLAST:PMIN output in Starter listing file

---

engine/source/interfaces/intsort/intcrit.F
engine/source/mpi/interfaces/spmd_i7tool.F
engine/source/mpi/interfaces/spmd_i7xvcom2.F

Issue on remote Position & velocity send when interface got deactivated
In spmd_i7xvcom scheme : unballance between send & receive causing app to crash
This was raised after : 20dd3a70233fec9601d2b9d34b90e467e1bc131c

Fix issues when Interface is deactivated in SPMD communication scheme

---

engine/source/interfaces/intsort/intcrit.F
engine/source/mpi/interfaces/spmd_i7xvcom2.F

Interface without INACTI+ Sensors should receive the treatment. Regression from f94f51671ccfa1d6c72a727a76205db8b3f8472b
TYPE 25 interface should be excluded from Treatments.

Possible hang when interface is deactivated

---

starter/source/groups/hm_read_surf.F

When input unit system differs from working unit system (example m->cm) then unit translation was made two times and it led to a wrong value. It is now fixed.
(but only if /SURF/PLANE was used with unit translation)

/SURF/PLANE/id/unit_id:fix issue with unit translation

---

engine/source/materials/mat/mat124/sigeps124.F

Hillerborg regularization was not activated for exponential damage in /MAT/LAW124 due to a missing factor
Add the missing factor H(I)

Add missing regularization method when using exponential damage in LAW124

---

engine/share/spe_inc/machine.inc
engine/source/engine/execargcheck.F
starter/share/spe_inc/machine.inc
starter/source/starter/execargcheck.F

machine.inc was removed from execargcheck, causing -v to give wrong answer. Clean machine.inc regarding obsolete architectures

Starter & Engine: -V Option

---

engine/source/mpi/forces/spmd_i7fcom_pon.F

ISKYFI(NIN)%P(1) was passed as a dummy argument, but  P may be of size 0.

Avoid passing invalid memory address to INTCONTP

---

engine/CMake_Compilers/cmake_win64.txt
engine/CMake_Compilers/cmake_win64_compilers.bat
engine/build_windows.bat
starter/CMakeLists.txt
starter/CMake_Compilers/cmake_win64.txt
starter/CMake_Compilers/cmake_win64_compilers.bat
starter/build_windows.bat

cmake_win64.txt : with a3d293ab964b429f5731dd5fe2b7b33a83bad842 link method changed Stacksize setting was no more taken into account.
Create Windows native batch scripts for Starter and Engine to compile Radioss out of cygwin.

Windows Issue in cmake_win64.txt and new build scripts

---

engine/CMake_Compilers/cmake_win64.txt
starter/CMake_Compilers/cmake_win64.txt

Depending on cmake version tool used to link change on Windows win64 build Makefile builder
cmake 3.26.0 is using ifx
cmake 3.20.0 is using link.exe
Linking flags differt between both tools. This is causing on some build Stacksize not to be set properly

Issue: Win64 Link

---

engine/source/elements/solid/solide10/nsvis_sm12.F
engine/source/elements/solid/solide10/s10forc3.F
engine/source/elements/solid/solide8e/s8eforc3.F
engine/source/elements/solid/solidez/szforc3.F
engine/source/elements/solid/solidez/szhour3.F
engine/source/materials/mat/mat001/m1law.F

law1 with high Poisson ratio (quasi-uncompressible) has the difficulties with simple compression tests due to local buckling phenomena, improvements have been done to make solid elements tetra10,hexa isolid=24,18 to be more robustness in this situations using total Lagrange type strain formulations (Ismstr=10,11,12).

improve robustness of law1 w/ high Poisson ratio of solid elements

---

starter/source/loads/pblast/hm_read_pblast.F

line 1069 of source file hm_read_pblast.F has more than 132 characters. This may cause compiler error. It is now fixed.
(fixing d4d0655cf2de3869ce99eecf8ffe82570aaae6fe)

fixing the 132-character-limit

---

engine/source/output/th/write_th_restart.F

On commit : bc63ffea6a38d814e4e758112526af9c12408017 Intent(INOUT) was used in Restart writing routine, but it should be INTENT(IN) Buffer is not modified & caller routine has INTENT(IN).

Issue in Time History Restart writing routine

---

engine/source/elements/sh3n/coque3n/c3bilan.F
engine/source/elements/shell/coque/cbilan.F
engine/source/elements/solid/solide/sbilan.F
engine/source/elements/solid/solide/srbilan.F
engine/source/elements/solid/solide10/s10bilan.F
engine/source/elements/solid/solide20/s20bilan.F
engine/source/elements/solid/solide4/s4bilan.F
engine/source/elements/thickshell/solide16/s16bilan.F
engine/source/elements/thickshell/solide6c/s6cbilan.F
engine/source/output/th/hist2.F
starter/source/output/th/hm_read_thgrou.F

There is a need to plot in time history files, for PART and SUBSET, the number of eroded elements. 
Store the number of eroded elements for parts/subsets made of solids and shells in PARTSAV (case 25) to plot it in time history files. Moreover, a bad internal energy computation was found for PENT6 thickshells and was corrected.

Add number of eroded element in /TH/PART and /TH/SUBS

---

engine/source/elements/spring/r23l108def3.F
engine/source/elements/spring/r23l113def3.F
engine/source/elements/spring/r2def3.F
engine/source/elements/spring/r4def3.F
engine/source/elements/spring/r6def3.F

For a recent development, spring failure filtering was revised. Unfortunately, something was missed. Indeed, CRIT value can take values higher than 1 leading to a wrong filtering close to spring failure. 
Ensure CRIT to not overtake the value 1 before filtering.

Fix end of spring failure filtering

---

common_source/modules/ale/ale_mod.F
starter/source/properties/composite_options/stack/lecstack_ply.F
starter/source/stack/hm_read_stack.F

LECSTACK_PLY.F:
- Array size  (2nd dimension) is now set to the correct value.  IGEO(NPROPGI,**NUMSTACK + NUMPLY**) instead of IGEO(NPROPGI,**NUMGEO**). This may prevent debugger from detecting (false) out of bounds issue.
- By the way related subroutine was cleaned.
- arguments IGEO and GEO were renamed to IGEO_STACK & GEO_STACK (also in hm_read_stack.F)
ALE_MOD
Initialization of ALE%GRID%NWALE_ENGINE to -1 (This initialization fix is related to /ALE/GRID option in Engine file )

lecstack_plyf.F:cleaning

---

engine/source/loads/pblast/pblast_3.F

Change is related to 72c698740e31df4841e4c31d43d77e700a2e2733 where line defining  'Zdet' parameter  was removed.
It is now restored

PBLAST:restoring missing line

---

Apptainer/openradioss.def
Apptainer/openradioss_intel.def

The Apptainer build fails due to missing `which` and `python` commands not found. Add those as dependencies to fix early build failures.
Add the `which` and `python` packages to the Apptainer definition file.
Any feedback is welcome. Regards,
Fer

Add missing dependencies to the Apptainer definition file

---

starter/source/interfaces/inter3d1/insol3.F

Problem with orientation of segment 3nodes for Inter type25 (tetra4 elements)
Check orientation of a segment was not done properly for 3 nodes elements : problem with IC it is incremented even if the same element is detected

 Correction problem of orientation of tetra segments (Tetra4) Inter25

---

common_source/modules/elbufdef_mod.F
engine/source/elements/elbuf/allocbuf_auto.F
engine/source/elements/elbuf/w_elbuf_str.F
engine/source/materials/fail/hoffman/fail_hoffman_c.F
engine/source/materials/fail/hoffman/fail_hoffman_s.F
engine/source/materials/fail/max_strain/fail_maxstrain_c.F
engine/source/materials/fail/max_strain/fail_maxstrain_s.F
engine/source/materials/fail/tsaihill/fail_tsaihill_c.F
engine/source/materials/fail/tsaihill/fail_tsaihill_s.F
engine/source/materials/fail/tsaiwu/fail_tsaiwu_c.F
engine/source/materials/fail/tsaiwu/fail_tsaiwu_s.F
engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_scalar_datatype.cpp
engine/source/output/h3d/h3d_build_cpp/c_h3d_create_solid_scalar_datatype.cpp
engine/source/output/h3d/h3d_build_fortran/create_h3d_shell_scalar.F
engine/source/output/h3d/h3d_build_fortran/create_h3d_solid_scalar.F
engine/source/output/h3d/h3d_build_fortran/h3d_create_datatype.F
engine/source/output/h3d/h3d_build_fortran/lech3d.F
engine/source/output/h3d/h3d_results/genh3d.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
engine/source/output/h3d/h3d_results/h3d_solid_scalar.F
engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
engine/source/output/h3d/input_list/h3d_list_shell_scalar.F
engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
starter/source/elements/elbuf_init/elbuf_ini.F
starter/source/materials/mat/mat104/law104_upd.F
starter/source/restart/ddsplit/w_elbuf_str.F

There was a need to be able to output the damage variable in .h3d files for a specific failure criterion using its ID defined in the starter. This is particularly interesting when several failure criteria are attached to the same material law like for composite material laws.
Implementation of /H3D/ELEM/FAILURE/ID=XX keeping the /H3D/ELEM/DAMA options like PLY, LAYER, NPT, IR, IS , IT ... This work is done for solids and shells and was partially coded with @sebastienVilleneuve

Implementation of damage output with /H3D/ELEM/FAILURE

---

engine/source/elements/solid_2d/quad/qhvis2.F

The H3D / ANIM output of hourglass energy for QUAD element was conditioned to the keyword /ANIM/QUAD/HOURGLASS avoiding the possibility to plot Hourglass energy for quads in .h3d files. 
Remove a very old condition that disabled the filling of EANI table that stored the hourglass energy.

Add possibility to use /H3D/QUAD/HOURGLASS

---

engine/source/materials/mat/mat120/sigeps120.F
engine/source/materials/mat/mat120/sigeps120_dp.F
engine/source/materials/mat/mat120/sigeps120_tab_dp.F
engine/source/materials/mat/mat120/sigeps120_tab_vm.F
engine/source/materials/mat/mat120/sigeps120_vm.F
engine/source/materials/mat_share/mulaw.F
starter/source/materials/mat/mat120/hm_read_mat120.F

LAW120: correct damage and the dependency of triaxiality
Correction of the dependence on triaxiality, plus bug correction (variable initialization) 
Add DAMG for H3D output

law 120 damage correction + DAMG for H3D output

---

engine/source/output/h3d/input_list/h3d_list_quad_scalar.F

In h3d output files, for quads element, energy of Hourglass appeared under the name "Hourglass Energy" however, it should be "Hourglass Energy per unit mass" to be consistent with the unit. 
Change the title to "Hourglass Energy per unit mass"

Change hourglass output name in h3d for QUAD elements

---

engine/source/elements/elbuf/copy_elbuf_1.F
engine/source/elements/elbuf/w_elbuf_str.F

A missing value of failure criterion buffer was not written in the restart file which causes issue in restart simulation. 
Add the missing lines in the restart file writing sources + fix a bug found in element buffer copy from implicit to implicit

Fix checkpoint restart issue with FLOC buffer missing value

---

starter/source/elements/reader/hm_read_solid.F

Small buf fix for SOL2SPH : some properties not compatible with SOL2SPH are not preread so IPART(2) can be equal to zero in some cases that generates seg fault.

SOL2SPH : bug fix with PROP/TYPE22

---

engine/source/materials/fail/tensstrain/fail_tensstrain_c.F
engine/source/materials/fail/tensstrain/fail_tensstrain_s.F

And old initialization of UVAR(1:NEL,1) was used for /FAIL/TENSSTRAIN (TIME == ZERO). Unfortunately, it has been noticed a few years back that with some options, it can create issues as TIME is reset (like /PRELOAD). 
Change the condition to initialize UVAR(1:NEL,1).  Same kind of modifications have been made in other failure criteria.

Change initialization condition for /FAIL/TENSSTRAIN

---

starter/source/interfaces/interf1/ingrbric_dx.F
starter/source/interfaces/interf1/lecint.F
starter/source/materials/mat/hm_read_mat.F
starter/source/materials/mat/mat151/hm_read_mat151.F

fix for monomaterial laws. Automatic Stiffness Value is now correctly calculated. Density used to calculate stiffness is no longer 0.0

INTER18:fix for potential issue with Automatic Stiffness

---

CMakeSettings.json
engine/CMake_Compilers/cmake_win64.txt
engine/build_script.sh
starter/CMake_Compilers/cmake_win64.txt
starter/build_script.sh

Windows Visual Studio : Add H3D Support in CMakeSettings.json Debug runs can benefit of H3D Library
Windows Visual Studio : Debug Version : wrong debug flags on Windows - Visual Studio debugger cannot run.
Build scripts : issue on SMP build

Changes in build scripts

---

engine/source/materials/fail/biquad/fail_biquad_c.F
engine/source/materials/fail/biquad/fail_biquad_s.F
engine/source/materials/fail/connect/fail_connect.F
engine/source/materials/fail/gene1/fail_gene1_c.F
engine/source/materials/fail/gene1/fail_gene1_s.F
engine/source/materials/fail/ladeveze/fail_ladeveze.F
engine/source/materials/fail/orthstrain/fail_orthstrain_c.F
engine/source/materials/fail/puck/fail_puck_s.F
engine/source/materials/fail/snconnect/fail_snconnect.F
engine/source/materials/fail/tabulated/fail_tab_old_c.F
engine/source/materials/fail/tabulated/fail_tab_old_xfem.F
engine/source/materials/fail/tabulated/fail_tab_xfem.F
engine/source/materials/fail/tuler_butcher/fail_tbutcher_s.F
engine/source/materials/fail/wierzbicki/fail_wierzbicki_s.F

After the discovery of an incompatibility of /FAIL/TENSSTRAIN with PRELOAD due to TIME == ZERO conditions at initialization, the same issue has been detected in several other failure criteria. 
Remove/Replace the TIME == ZERO condition from the failure criteria.

Remove TIME==ZERO conditions from failure criteria for compatibility with PRELOAD

---

starter/source/initial_conditions/inivol/ale_box_creation.F

In 2D analysis, elements are defined in y,z plane. Dimension X is not used.
When entering in ale_box_creation.F min_x=MIN_MAX_DIMENSION(1) and max_x=MIN_MAX_DIMENSION(4) are then not defined (EP30). This is now correctly treated by ignoring the corresponding dimension (x dimension in case of 2D analysis) when creating the boxes.
This update is related to commit 82f062d

/INIVOL:fixing potential debugger warning when DX_BOX=EP30

---

engine/source/materials/fail/biquad/fail_biquad_c.F
engine/source/materials/fail/biquad/fail_biquad_s.F
engine/source/output/anim/generate/dfuncc.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

Add density output for shells in ANIM and H3D files
Fix checkbounds issues with /FAIL/BIQUAD and add Density output for shells in ANIM and H3D files
Change the condition to store the initial element size and add the density storage for outputs.

Fix checkbounds issues for /FAIL/BIQUAD + add Density output for shells

---

engine/source/materials/mat/mat071/sigeps71.F
engine/source/materials/mat/mat071/sigeps71c.F
engine/source/materials/mat/mat071/sigeps71pi.F

LAW71 add dependency on alpha for beams
LAW71 add dependency on alpha for beams
LAW71 add dependency on alpha for beams, now behavior can be non symmetrical between tension and compression

LAW71 add dependency on alpha for beams

---

starter/source/interfaces/interf1/lecint.F

INACTI integer is now correctly defined in the loop : INACTI = IPARI(22,NI)
This integer is required to define TYPE18 boolean : IF(NTYP==7 .AND. INACTI==7 )TYPE18=.TRUE.
This bug may have been silent if last interface from input file had INACTI=7

/INTER/TYPE18 : fix for INACTI initalization in lecint.F

---

engine/source/elements/spring/r26def3.F
engine/source/elements/spring/r27def3.F
engine/source/elements/spring/rforc3.F
engine/source/output/th/thres.F
starter/source/properties/spring/hm_read_prop26.F
starter/source/properties/spring/hm_read_prop27.F

Add FAIL time history output for spring properties /PROP/TYPE26 and /PROP/TYPE27
Add RUPTCRIT in corresponding properties buffer and filling it with corresponding failure options. 
(Changes are important for 2023)

Add FAIL time history output for SPR_TAB and SPR_BDAMP

---

engine/source/materials/mat/mat036/sigeps36.F
engine/source/materials/mat/mat036/sigeps36c.F
engine/source/materials/mat/mat036/sigeps36pi.F
starter/source/materials/mat/mat036/hm_read_mat36.F

Option description was modified : logarythmic strain rate interpolation is only using base n log 
corrected strain rate interpolation in solids
Ismooth input parameter has changed, according to the new input doc
strain rate value used for interpolation was corrected for solid elements (total strain rate instead of plastic strain rate)

Correct logarythmic strain rate interpolation in law36

---

starter/source/elements/solid/solide10/s10jaci3.F
starter/source/elements/solid/solide4/s4init3.F
starter/source/elements/solid/solide4/s4jaci3.F

wrong mapping result using law95 with tet elements (/INIBRI Itetetr4=3)
correction to get right mapping result

wrong mapping result with /INIBRI/EREF+LAW95 for tet elements

---

engine/source/output/h3d/h3d_build_fortran/lech3d.F

There was a necessity to support the keyword ALL for recently implemented new output called /H3D/ELEM/FAILURE. 
Add the ALL option for solids, shells and quads. This still support the keyword ID=XX.

Implementation of /H3D/ELEM/FAILURE/ID=ALL

---

starter/source/elements/solid/solide/scoor3.F

wrong result of tetra4 element + Ismstr>=10 when the input connectivity has been changed (permutation) due to negative Jacobian.
correction has been done.

bug of tetra4 element +Ismstr>=10 when the connectivity has been changed due to negative Jacobian

---

starter/source/spmd/node/ddtools.F

A memory corruption was detected : when a node is yet on a processor, ientry(node) is still egual to -1
If the node is not yet on a processor, the plist_ifront computation is skipped

Fix an issue in plist_ifront

---

starter/source/elements/reader/hm_read_solid.F
starter/source/starter/lectur.F

When the Jacobian (volume) is negative with input connectivity of tetra4, stiffness used for contact could be negative which will get trouble with the run.
Radioss (Starter) changes automatically the connectivity order of tetra4 in case of negative Jacobian, but this correction was done too late for contact stiffness initialization; the correction has been done now just after the lecture of connectivity to avoid negative stiffness for contact and other possible issues.

change early connectivity order for negative Jacobian  avoid negative stiffness of contact

---

engine/source/airbag/fvbag2.F

once all polyhedra were merged with Iswitch=2 then :
Tswitch and Pswitch parameters are updated in order to prevent any later switch to "Uniform Pressure" formulation 
in fvbag2.F  :
RVOLU(70) is TSWITCH
RVOLU(73) is PSWITCH

FVMBAG:iswitch=2 prevent from any further switch to "Uniform Pressure" formulation after the full merging

---

starter/source/loads/pblast/hm_preread_pblast.F
starter/source/loads/pblast/hm_read_pblast.F

/LOAD/PBLAST:surf_ID=0 is now allowed
- It is now allowed to provide SURF_ID=0. In this case blast calculation will be skipped during Engine since NUMSEG=0
Error message 2047 replaced with Warning 1907. Normal Termination is now ensured (hm_preread_pblast.F updated).
- Variable 'NN' renamed 'NUMSEG' in hm_read_pblast.F
- Indentation updated
- unused variables removed

/LOAD/PBLAST:surf_ID=0 is now allowed

---

starter/source/restart/ddsplit/w_front.F

This is a workaround, there may be an issue with the sliding to be fixed. But now the behavior is the same whatever the number of domains MPI buffer has been made consistent, using the id of the segments are sorting key

/INTER/TYPE25 bug fix in SPMD

---

starter/source/interfaces/inter3d1/i7remnode.F

In i7remnode routine, the size of INSERTED_NODE is not correct
Fix the size issue

i7remnode issue : the size of the array INSERTED_NODE is not correct

---

engine/source/output/anim/reader/anim_dcod_key_0.F

avoid problems in ANIM output using /ANIM/SHELL/TENS/MSTRESS option
Corrected wrong index in ANIM arrays containing output flag and adress to output value

Correct wrong array index in /ANIM/SHELL/TENS/MSTRESS output definition

---

engine/build_script.sh
starter/build_script.sh

Issue error when compiler is not found or when -arch does not exist.
cmake issues errors in that case but tries to find existing compiler.
This can cause some odd behave as compiler flags are wrong.

Build_script changes 

---

engine/CMake_Compilers/legacy_fortran.cmake
engine/source/input/lecstat.F

Recently added strict compilation flags, were made even more strict with gfortran 12
(tested with gcc 12.1.0)

Compatibility with gfortran 12

---

engine/source/output/h3d/h3d_results/genh3d.F

Data structure introduced with 559198c863bcd41c02e7e5ff351488e83d52b80c might be not correctly updated (%RWALL_SHIFT value). Consequently H3D file with /RWALL option may have some unexpected nodes displacement. It is now fixed.
_(%RWALL_SHIFT is shift value to determine RWALL node ids in H3D file. generated nodes for rigid walls in H3D file start from id=%RWALL_SHIFT+1)_

H3D:rwall fix

---

engine/source/materials/fail/hoffman/fail_hoffman_c.F
engine/source/materials/fail/hoffman/fail_hoffman_s.F
engine/source/materials/fail/max_strain/fail_maxstrain_c.F
engine/source/materials/fail/max_strain/fail_maxstrain_s.F
engine/source/materials/fail/tsaihill/fail_tsaihill_c.F
engine/source/materials/fail/tsaihill/fail_tsaihill_s.F
engine/source/materials/fail/tsaiwu/fail_tsaiwu_c.F
engine/source/materials/fail/tsaiwu/fail_tsaiwu_s.F

History effect was not taken into account into recently implemented composite failure models. 
Add the history effect my maximizing the damage variable accounting for its previous value. It does not affect the current results at all.

Add history effect in recently implemented composites failure criteria

---

engine/source/output/h3d/h3d_results/h3d_sph_scalar.F
engine/source/output/h3d/input_list/h3d_list_sph_scalar.F

SPH output for maximum damage presented 2 issues: the maximum over all criteria was not correctly computed and the output Title was not consistent with maximum damage output on the other types of element (solids, shells...)
Fix the maximum damage output and change the output title.

Fix maximum damage output for SPH and output title

---

starter/source/starter/contrl.F

When /H3D/PART option is used in the *1.rad, a error can occurred if the line contains a carriage return character 
Remove the carriage return character from the line

remove the carriage return character from the /H3D/PART reading option

---

engine/source/elements/forint.F
starter/source/tools/sect/hm_read_sect.F

A bad computation of resultant forces was observed when using PENTA6 elements. This was due to the fact that SECTIOS6 and SECTIOS were called at the same time. Only the first one should be called in FORINT. 
Change the ENDIF statement location to call only SECTIOS6 in FORINT.

Fix bad computation of forces on section with /PENTA6

---

engine/source/elements/solid/solidez/szhour3.F

unstable result observed with HEPH solid element (Isolid=24) when law92 (hyper-elastic) law used
Correction has been done to improve the robustness of HEPH+law92

Correction in HEPH (Isolid=24) with law92

---

starter/source/materials/mat/mat002/hm_read_mat02.F

Reverted changes to spacing in the reporting for Young's, Poisson's and Shear made in commit b183c50, since these cause misalignment in 0000.out, while the changes made in that commit look like they have corrected alignment in source, they do not account for the escaped ' characters in young's and poisson's, so misalignment occurs in output

Reverted changes to spacing in the reporting for Young's, Poisson's and Shear

---

starter/source/tools/sect/hm_read_sect.F

With option /SECT when node_id1, node_id2, and node_id3 are not defined in input file some tests must be skipped in order to avoid some  array indexes from being 0.
- node_id1 is stored in NSTRF(K0+3)
- node_id2 is stored in NSTRF(K0+4)
- node_id3 is stored in NSTRF(K0+5)

/SECT:prevent index from being 0

---

common_source/modules/loads/pblast_mod.F
common_source/tools/search/dichotomic_search_i_asc.F
common_source/tools/search/dichotomic_search_i_desc.F
common_source/tools/search/dichotomic_search_r_asc.F
common_source/tools/search/dichotomic_search_r_desc.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F
starter/source/loads/pblast/hm_read_pblast.F

Numerical Solution was compared to Reference solution (Free Air, Surface Burst, and Air Burst models). 
Warning/Error Message were tested to verify their consistency.
- Interpolation fix for Air burst model
- data structure updated  (array PBLAST_DATA%Curve_val_2_10 added in pblast_mod.F)
- some unit translation were fixed with scaled distance comparison ('FAC_UNIT' factor added)
- default ground definition fixed with Surface Burst model : b=(0,0,Zdet) n=(0,0,1)
Output :
- warning message fixed with Surface Burst model when ground is not defined
- output issue fixed ('****' occured in warning message instead of expected value)
cleaning :
- tabulation characters removed
- source lines trimed

/LOAD/PBLAST:updates from verification process

---

starter/source/materials/fail/gene1/hm_read_fail_gene1.F

DTMIN failure in /FAIL/GENE1 was not compatible with tria elements when used with /DT/NODA
The default value of DTMIN was changed to -INFINITY to fix the problem.

Fix GENE1 DTMIN criterion for Tria elements

---

engine/source/materials/mat_share/mulawc.F

NVARF for failure criteria should not be recovered from FBUF as it can create some conflict. 
Get NVARF from IPM instead.

Fix NUVAR wrong value for failure criteria

---

starter/source/elements/elbuf_init/suinit3.F

inertia was wrong, due to wrong offset.
This caused a bug for tetras solids with  `/PROP/CONNECT`
Fix the offset

Inertia was not initialized correctly for solids with IRODDL >0

---

engine/source/interfaces/int07/i7for3.F

Because of Inacti = 6, GAPV may be negative. Leading to the computation of `LOG(FACM1)` with FACM1 < 0. 
This has been replaced by `LOG(MAX(TINY(FACM1),FACM1))`

TYPE7 + Inacti=6: possible floating point exception

---

engine/source/materials/mat/mat036/sigeps36c.F

Possible division by 0 avoided

fix possible division by 0 for shells law36

---

starter/source/initial_conditions/inimap/hm_read_inimap2d.F

no influence for the user
changed test of null node identifiers to avoid integer overflow

Avoid integer overflow in case of big node IDs in hm_read_inimap.F

---

starter/source/materials/ale/ale_euler_init.F

When input file does not mention material identifier for a given /PART option then IMID may be '0' in ale_euler_init.F subroutine. (Same behavior if provided identifier does not exist in input file).
To avoid program issue in debug mode ('0' index), conditionnal tests are introduced.
This ensures normal termination (with 1 error message) of the Starter program even if user forgot to set material identifier.

Ensure Normal Termination in debug mode when IMID=0

---

starter/source/restart/ddsplit/w_isph.F

Fix of checkbounds issue : CELSPH must be read only if solid element has SPH particles

SOL2SPH fix of checkounds issue

---

engine/source/materials/mat/mat041/sigeps41.F
hm_cfg_files/config/CFG/radioss2023/MAT/matl41_lee_t.cfg
starter/source/materials/mat/mat041/hm_read_mat41.F

Parameters from LEE-TARVER material model are renamed to be consistent with bibliography from scientific community.
Following notation is now used : dF/dt = **I**(1-F)^**b**.(eta-1-**a**)^x  +  **G1**(1-F)^**c**.F^**d**.P^**y**  +  **G2**(1-F)^**e**.F^**g**.P^**z**
Following files were updated consequently :
- CFG file : ./radioss2023/MAT/matl41_lee_t.cfg  (new format 2023 introduced with new labels)
- Starter Reader : hm_read_mat41.F
- Engine file : sigeps41.F
**List of updated variables :**
_rki -> I
ex   -> b
ri   -> x
rkg -> G1
yg  -> g
zg  -> y
ex1 -> c
grow2 -> G2
ex2 -> e
yg2 -> g
zg2 -> z
ccrit -> a
fmxig -> Figmax
fmxgr -> FG1max
fmngr -> FG2min
check -> Ftol_
Manual Page is going to be updated consequently.

/MAT/LAW41 : parameters renamed

---

engine/source/engine/radioss2.F
engine/source/materials/mat_share/mmain.F
engine/source/output/anim/generate/dfunc6.F
engine/source/output/anim/reader/anim_dcod_key_0.F
engine/source/output/th/hist2.F
engine/source/output/th/thquad.F
engine/source/output/th/thsol.F
starter/source/materials/mat/hm_read_mat.F

Following improvements are introduced :
-  /TH/QUAD : following labels are now output in all relevant cases, 'SSP', 'MACH', 'VX', 'VY', 'VZ', and 'BFRAC' 
-  /ANIM/ELEM/BFRAC : Burn Fraction is now available with QUAD elems
-  /ANIM/ELEM/SSP : output is now available also with Lagrangian framework

Output updates (/TH/QUAD and /ANIM)

---

starter/source/interfaces/inter3d1/i11sti3.F

- line 426 : conditionnal test (**IP** > 0) introduced before testing  (THK_PART(**IP**) > ZERO ). This prevents debugger from stopping on segmentation signal.
- cleaning (identation, unused variables removed, array sizes introduced, intent(in/out/inout) , etc ...

i11sti3:prevent program to use 0 index

---

common_source/modules/loads/pblast_mod.F
engine/source/engine/resol.F
engine/source/loads/pblast/pblast.F
engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F
starter/source/loads/pblast/hm_read_pblast.F

- **TIME STEP / COMPUTATION TIME :** Time step calculation improved. When arrival time of blast wave is not reached, then time step is set to trigger blast on next cycle (unless there is a lower time step elsewhere in the computation domain). This makes possible to gain CPU time (no calculation before arrival time, and output results are not time shifted)
- **ENGINE UPDATE** Blast wave parameters can be updated during Engine (target may have move or may be defomed due to previous loads). When IZ flag is 2 then a single calculation is made on TDET and time step set to trigger on next cycle
- **NUMERICAL RESULT** Decay parameter is limited to [1.00,infinity[ to prevent any unphysical blast wave profile. When b<1.0 correlating positive impulse (with Iform=2) may lead to unphysical negative …

/LOAD/PBLAST : Improvements

---

engine/source/materials/mat_share/mmain8.F
engine/source/output/th/thsol.F

For some elem types, the sound speed was a local array ; it was not stored in element buffer.
Sound of Speed is now also stored in elem buffer from MMAIN8 subourtine (see line 388).
This prevents THSOL from stopping with a floating point exception when outputing mach number ( mach = velocity / ssp )
Mach number was introuced in Time Histories for all compatible elems with commit a589c23a27d0fc50d50e70e8b15a2bd2ca8607ab.

output SSP also in mmain8.F

---

engine/source/materials/fail/tensstrain/fail_tensstrain_c.F
engine/source/materials/fail/tensstrain/fail_tensstrain_s.F
engine/source/materials/mat_share/mmain.F
engine/source/materials/mat_share/mulaw.F
engine/source/materials/mat_share/mulaw8.F
engine/source/materials/mat_share/usermat_solid.F
starter/source/materials/updmat.F

/FAIL/TENSSTRAIN criterion does not give the same results with shell and solid elements in some specific cases: no stress softening for solids, additional check for compression with shells. 
Add stress softening for solids and remove additional check for shells.

Improve equivalence between shells and solids for /FAIL/TENSSTRAIN

---

engine/source/materials/fail/fabric/fail_fabric_c.F
hm_cfg_files/config/CFG/radioss2023/FAIL/fail_fabric.cfg
starter/source/materials/fail/fabric/hm_read_fail_fabric.F

/FAIL/FABRIC could only trigger the element deletion when the 2 directions of the shell had been broken. 
Add an additional parameter NDIR that allows to control the number of directions (NDIR) to brake prior triggering the element deletion.

Add new failure parameter in /FAIL/FABRIC

---

starter/source/interfaces/inter3d1/i11sti3.F

Part thickness value is wrong for Beam and Spring elements, as PARTID from Truss are used.

Interface Type11 initialization: in Starter

---

starter/source/elements/elbuf_init/elbuf_ini.F

avoid starter core dump when some failure models are used with beam elements
Corrected element buffer allocation in starter; several local variables used for failure models were not counted for beams.

Correct bug of element buffer allocation for beams

---

starter/source/materials/mat/mat121/hm_read_mat121.F

Correction of the Radioss starter reader. Error in printing out of all deck functions of /MAT/LAW121, if they exceed three digits.
Correction of starter printing out of functions ID for /MAT/LAW121.

Correction of starter output printing of input deck functions ID in /MAT/LAW121

---

engine/CMake_Compilers/cmake_win64.txt
engine/source/output/anim/generate/anim_nodal_contour_fvmbags.F

Fixed some errors...
Wrong Executable name for win64_impi Executable
Typo error in output routine.

Wrong Executable name for win64_impi Executable + typo in one routine

---

starter/source/materials/tools/nlsqf.F

Different fitting of the material when the order of data is different.
Initialization of working array.

fix wrong fitting of law69 when we have multiple materials

---

engine/source/materials/mat/mat025/sigeps25c.F
engine/source/materials/mat/mat066/sigeps66c.F
engine/source/materials/mat_share/mulawc.F

avoid potential problems in material laws 25 and 66
Corrected flag used for Prony model activation inside material laws for shells. When viscosity model was not used, the flag value was wrong or not initialized.

Correct bug of initialization Prony viscosity model with material laws 25 and 66

---

engine/source/input/lectur.F

In a specific case where a material (/MAT) is not related to a part (/PART) then output upwind parameter for mass & energy may be incorrect in Engine listing file (0 is displayed). This is fixed. (lines 1021:1023 in resol.F)
general cleaning in ./engine/source/input/lectur.f

Fix for Upwind parameter in Engine listing File

---

engine/source/materials/mat/mat124/sigeps124.F
engine/source/materials/mat_share/mulaw.F
hm_cfg_files/config/CFG/radioss2022/MAT/matl124_cdpm2.cfg
starter/source/materials/mat/mat124/hm_read_mat124.F

FAILIP parameter in /MAT/LAW124 was used to trigger element deletion using UELR table. However, this table is only allocated when using a failure criterion and not a material law alone. 
Remove FAILIP parameter and UELR table from /MAT/LAW124 to avoid checkbounds issue.

Remove FAILIP from /MAT/LAW124 which can cause segfault issue

---

engine/source/output/th/hist2.F

A SP issue was found in TH history : the time test ( t >= t_history) was done with float in hist2 routine and with double in sortie_main routine.
This lead to strange results in TH history
Harmonization of time test

fix a SP issue : harmonization of time comparison in hist2 and sortie_main routine

---

starter/source/boundary_conditions/ebcs/hm_read_ebcs_inlet.F

A bug is fixed in hm_read_ebcs_inlet.F. This is the subroutine related to reader of option /EBCS/INLET.
When reading lines related to submaterials, first line was used to define all of them.
This is now fixed.

/EBCS/INLET:reader fix for NSUBMAT>1

---

engine/source/output/h3d/h3d_build_fortran/lech3d.F

Issue was detected when /H3D/ELEM/FAILURE keyword is used in engine file and no /FAIL card is present in the starter file. This leads to a potential segfault issue. 
Add an additional condition to conditional loops regarding /H3D/ELEM/FAILURE. If no /FAIL card is detected (CPT_IRUP == 0), nothing is done.

Fix potential segfault issue with /H3D/ELEM/FAILURE

---

engine/source/materials/fail/fail_setoff_c.F
engine/source/materials/fail/fail_setoff_npg_c.F
engine/source/materials/mat_share/mulawc.F
engine/source/materials/mat_share/usermat_shell.F

For shell elements using /PROP/TYPE17 or 51 or 52, the element failure message was not clear enough. Indeed for these properties, layers correspond to plys which have their own IDS. Instead of printing out a layer failure message it should be good to have a ply failure message. 
Change the format of element failure message only for /PROP/TYPE17, 51 and 52. ID of the ply is used instead of the number of the layer.

New failure message format with PLY ids for shell elements

---

engine/source/engine/lf_convert_c.c

Input file is copied in tempo file  on for any MPI process. 
The Path is found wrong ad a '/' is missing.

Wrong Path/file name for Temporary file to parse input file

---

engine/source/engine/resol.F
engine/source/interfaces/interf/check_surface_state.F
engine/source/interfaces/interf/find_edge_inter.F
engine/source/interfaces/interf/find_surface_inter.F

A issue was found in the shooting node algorithm : some segments of interface are or are not (depending on the domain decomposition) deactivated. These segments are linked to degenerated elements (tetra4, penta6 ...)
Add 2 specific cases for tetra4 and penta6
Add a general treatment for solid8 element (because a solid8 can be a degenerated element)

tetra4, penta6 and degenerated element issues in shooting node algorithm

---

engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

argument were cleaned in subroutine OUTPUT_SCHLIEREN (v,w,pm arrays were removed) with commit 653b6326b72564a85393c40e22de56817f63942c. This cleaning was missing in h3d_shell_scalar1.F. This is now fixed.

schlieren subroutine : arguments update

---

engine/source/elements/solid/solide8e/m1tot_stab11.F
engine/source/elements/solid/solidez/nsvis_stab11.F
engine/source/elements/solid/solidez/szhour3.F
engine/source/materials/mat/mat001/m1lawtot.F

failing results observed w/ high compression test (up to 99%) with law1+ ismstr=11 for isolid=18,24
corrections to improve the robustness of law1+Ismstr=11

robustness improvement for law1+ismstr=11 for hexa solid elements

---

starter/source/restart/ddsplit/ddsplit.F

array index is updated. EBCS_TAB_LOC_2 is allocated to the total number of /EBCS/NRF options. 
In ddsplit.F:2169 :
- 'ii' is index loop over all existing /EBCS options.
- NEBCS_NRF is index loop over /EBCS/NRF options only

/EBCS/NRF:domain decomposition fix

---

engine/source/elements/sh3n/coquedk/cdkforc3.F
engine/source/elements/shell/coqueba/cbaforc3.F
engine/source/output/anim/generate/dfuncc.F
engine/source/output/anim/generate/dfuncc_ply.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

The cpu time with TYPE51 is about 10% higher than model with PID11 used with  fully integrated shell element
All computing needed for outp (anim, h3D) did in the element are moved to the output subroutine and not did every cycle.

improve the performance of model With Batoz shell and PID51

---

engine/source/output/anim/generate/dfuncc.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

Memory error for batoz shell element and PId51 or 52 if plastic output is requested in the animation
Correct the  Parameters of the Loop.

memory issue for outp plastic strain for Batoz shell and PID51 or 52

---

engine/source/output/anim/generate/tensorc.F
engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
engine/source/output/th/thcoq.F

We have core dump when Drape  option is used with /TYPE51 or /PROP/TYPE52 and the stress tensor is requested for the output
We must use the right memory array dedicated to the orthotropy of each slice.

fix the coredump issue wiht /PROP/TYPE51 and 52 with drape

---

starter/source/elements/initia/hm_read_inistate_d00.F

Core dump because the array is not enough to save variable and error message due the non compatibily of the number of integration point in the tickness.
Fix the issue by correcting the Id of the loop of the save and to save the right integration point .

fix the error of the read of /INISH/FAIL and STRS_F/GLOBAL

---

starter/source/starter/lectur.F

Missing starter initialization `PYTHON%NB_FUNCTS = 0`

PYTHON functions, missing starter initialization

---

engine/build_script.sh
starter/build_script.sh

build_script should exit with error code when build is failing like cmake

Build script issue:

---

common_source/interf/intbuf_ini.F

Invalid memory read of LISUBM(K) in i*for3.F routines, because the value of K could be length(LISUBM) + 1
add sentinel value at `LISUBM(size+1)`

subinterface: out-of-bound memory access

---

starter/source/materials/globmat.F

For /PROP/TYPE51, 17, 11 and TYPE52 when Ipos > 0 we don't have the same timestep. 
In order to get the same element timestep we should use the same membrane rigidiy

using the same membrane rigidity us Ipos=0

---

starter/source/output/tools/write_routines.c

At the engine, we had 100 file descriptors in sortie_c.c, but at the starter, there was only 3. INIMAP was using id 21
The number file descriptors is set to 100 in the starter, to be consistent with the engine

INIMAP issue with file reading

---

engine/source/mpi/interfaces/spmd_tri25vox.F

Missing initialization of NEDGE_REMOTE when the domain do not participate to the spmd communication of type25

/INTER/TYPE25 + iedge spmd bug fix

---

Apptainer/arm/arm_buildEnv.def
Apptainer/arm/build_arm.sh
Apptainer/arm/openradioss_arm.def

Fixes #2120 
1. Fix dependency and build issues
- `which` and `python3` added to list of packages installed via final `dnf` command.
- A symlink pointing `/usr/local/bin/python` --> `/usr/local/bin/python3` is added.
2. Clean up definition files
- A separate definition file arm_buildEnv.def is provided to download and install all prerequisites into a base image. This will only occur once.
- The following options are added to the `wget` command:
- `--show-progress` so user doesn't think progress has stalled when downloading the Arm compiler suite.
- `-c --read-timeout=15` to restart download after 15 seconds of inactivity and continue from the partially-downloaded file.
- `rm ...` commands are added to clean up the Arm compiler and performance library intermediate files (`*.tar` downloads …

Fixed and reorganized Apptainer arm def files

---

starter/source/elements/initia/initia.F
starter/source/elements/solid/solide/srefsta3.F
starter/source/elements/solid/solide4/s4refsta3.F
starter/source/materials/mat_share/mmain.F
starter/source/materials/mat_share/mulaw.F

correct bug with reference metrics with material law70 for solids
correctly defined argument declaration of MAT_PARAM structure, passing as scalar instead of vector

Correction of MAT_PARAM structure dimension in calling routines arguments

---

engine/source/materials/fail/hc_dsse/fail_hc_dsse_c.F
starter/source/materials/fail/hc_dsse/hm_read_fail_hc_dsse.F

There is a necessity to have a new Ifail_sh flag value in /FAIL/HC_DSSE input card to deactivate the element deletion. 
Add the new flag needed to deactivate element deletion.

Add option to deactivate element deletion in /FAIL/HC_DSSE

---

starter/source/materials/mat/mat110/hm_read_mat110.F

Automatic computation of parameters when using /MAT/LAW110 with Icrit = 3 was too severe. 
Change the constant of Abspoel formulas.

Fix LAW110 automatic parameter computing formula

---

common_source/modules/loads/pblast_mod.F
engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F
starter/source/loads/pblast/hm_read_pblast.F

1. A typo error in a warning message had been reporting an incorrect unit : µs/g^0.333. This unit is now replaced with the expected one : cm/g^0.333. Related files are in Starter and Engine when scaled distances are initilized (Started) or updated (Engine)
2. Limiter introduced for output messages. Once a warning message was printed for a related segment (shell face or solid face) then it is no longer output in the following Engine cycles. This prevent Engine computation from being slowed down.
This update has no effect on the numerical solution.

/LOAD/PBLAST:fixed typo error in output message

---

hm_cfg_files/config/CFG/radioss2023/data_hierarchy.cfg
hm_cfg_files/config/CFG/radioss2024/FAIL/fail_orthenerg.cfg

Recently implemented /FAIL/ORTHENERG must be defined for radioss2024 format
Change 2023 to 2024 format for /FAIL/ORTHENERG.

Change radioss format of /FAIL/ORTHENERG from 2023 to 2024

---

starter/source/elements/elbuf_init/elbuf_ini.F

correct bug in law70 with REFSTA option in starter
VARTMP  was not allocated in element buffer in starter while it was recently introduced for law70

Allocate VARTMP in element buffer

---

engine/source/interfaces/intsort/intcrit.F

When the run is diverging, due to high nodal velocities, the cost of the collision detection can become huge. 
In that case, a  warning is printed.

/INTER/TYPE25:  add a warning when VMAXDT is too high

---

engine/source/multifluid/multi_computevolume.F

When computing elem volume, user identifier is stored in NGL array. This identifier was wrong for QUAD elems and missing for TRIA elems. This array has no effect on numerical solution. It is used when a warning/error message has to be displayed to communicate related user identifier.
It was possible to get memory corruption since first index (NIXS line 226 ) was 0 in 2D. It is now fixed.

/MAT/LAW51 & 2D : fix in multi_computevolume.F (output purpose only)

---

engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F

An implicit conversion from LOGICAL to INTEGER is present in two source files. It is replaced by INTEGER instead of LOGICAL.

/LOAD/PBLAST:remove implicit conversion

---

engine/share/modules/aleanim_mod.F
engine/source/elements/solid/solide/sdefo3.F
engine/source/engine/resol.F
engine/source/interfaces/int18/i18for3.F
engine/source/interfaces/int18/int18_law151_update.F
engine/source/output/anim/generate/dfunc6.F
engine/source/output/h3d/h3d_build_fortran/create_h3d_input.F
engine/source/output/h3d/h3d_results/genh3d.F
engine/source/output/h3d/h3d_results/h3d_solid_scalar.F
engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
engine/source/output/h3d/h3d_results/h3d_solid_vector.F
engine/source/output/restart/arralloc.F
engine/source/output/restart/rdresa.F
engine/source/output/sortie_main.F

- Data strucutre FANI_CELL is updated to simplify source code and improve readability. Developer now quickly understands when it is used/allocated, and how to use it.
- Potential memory corruption fixed when calling subroutine from anincon0.F (allocation is now checked before initializating the array)
- /H3D/ELEM/VECT/CONT is now working with /INTER18 + /MAT/LAW151 (reaction force at cell centroids can be post-treated)
- Bug fix in case of EULER (instead of ALE), re-sorting criteria (voxel) is now fixed for /INTER/TYPE18

Code refactoring + output /H3D/ELEM/VECT/CONT (law151)

---

engine/source/interfaces/int24/i24cor3.F
starter/source/interfaces/int24/hm_read_inter_type24.F

Some issues observed of Press-fit simulation using interface type24 (Inacti=-1), in these cases, high stiffness should be used to get correct result.
Add new option of Preff-fit Inacti=-2 which uses high stiffness to get better result for some cases.

add new Press-fit option Inacti=-2 of int24 with high stiffness

---

Apptainer/arm/openradioss_arm.def
Apptainer/openradioss.def
Apptainer/openradioss_intel.def

Apptainer definition files have hardcoded values for number of build threads, varying from 1 to 80
Definition files query number of cores on host system and save to new environment variable. Calls to build_script.sh now reference -nt=$NCPU

Auto set number of build threads for Apptainer images

---

engine/source/output/h3d/h3d_build_cpp/c_h3d_create_quad_tensor_datatype.cpp
engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_tensor_datatype.cpp
engine/source/output/h3d/h3d_build_cpp/c_h3d_create_skin_tensor_datatype.cpp
engine/source/output/h3d/h3d_build_cpp/c_h3d_create_solid_tensor_datatype.cpp
engine/source/output/h3d/h3d_build_cpp/c_h3d_create_sph_tensor_datatype.cpp

EPSDOT output for H3D files was giving bad Von Mises equivalent values. 
Fix EPSDOT output by setting the strain rate tensor type to H3D_DS_STRAIN

Fix EPSDOT output for H3D files

---

starter/source/airbag/hm_read_monvol_type8.F
starter/source/airbag/init_monvol.F
starter/stub/fvmbags_stub.F

Kmesh=2 & 4 are deprecated. 
Change to Resp. KMesh=12 or 14 Remove code related to KMESH=2 or 4.

Airbag Defaults for Type 8 Airbags:

---

engine/source/output/anim/generate/tensorc.F
engine/source/output/h3d/h3d_results/h3d_shell_tensor.F

Stress tensor output for /MAT/LAW1 (and generally integrated law) was not working due to a regression.
Fix stress tensor output for ANIM and H3D for /MAT/LAW1.

Fix /MAT/LAW1 stress tensor output issue in ANIM and H3D

---

common_source/tools/input_output/write_routtines.c

Issue in : b20217fff64967a9709b0bfc7819f4909b4b1677
sta file content is dumped in Standart output when using Zip option.

Issue in : b20217fff64967a9709b0bfc7819f4909b4b1677

---

starter/source/materials/mat/mat070/law70_upd.F

possible small difference in results with law70 when input functions contain big number of abscissa points
the last function points of original tabulated input was missing after smoothing, it is added now

/MAT/LAW70 : add missing last input function point after tranformation to table

---

engine/source/elements/solid/solide8z/s8zforc3.F

possible failing of Engine (Isolid=14+Icpre=1) due to an argument missed in calling  
correction to add argument missed with Isolid=14

regression of Isolid=14 due to 7dd1f3dfc2c680920bcfd74ee974637eb1afe4f9

---

common_source/modules/names_and_titles_mod.F
starter/source/loads/reference_state/refsta/hm_read_refsta.F
starter/source/starter/contrl.F
starter/source/starter/starter0.F

Title array is dimensioned with 80 characters but input allows 100 - care it is truncated to 80 in TimeHistory due to timeHistory format

Issue in /TITLE option :

---

engine/source/elements/shell/coquez/czcorc.F

when using QEPH+law58+npt=1 of very soft stiffness, not zero accelerations observed at T=0 due to numerical error. 
Correction of this specific case to avoid acceleration error.

Avoid oscillation due to numerical error in case of QEPH+LAW58 npt=1

---

engine/source/output/h3d/h3d_results/h3d_quad_vector.F
engine/source/output/h3d/h3d_results/h3d_shell_vector_1.F
engine/source/output/h3d/input_list/h3d_list_quad_vector.F
engine/source/output/h3d/input_list/h3d_list_shell_vector.F

This output contour is now also working for following 2D solids : /QUAD & /TRIA
(Collocated scheme is enabled with /MAT/LAW151)

H3D/ELEM/VECT/ACC : quad and tria compatibility for collocated scheme

---

engine/source/multifluid/multi_computevolume.F

Bug fix in specific case of axisymmetric simulations (/ANALY : N2D=1) and quad elements (/QUAD)
law151 only (collocated scheme)

/MAT/LAW151 : axisymmetric fix with quads

---

starter/source/materials/mat/mat058/law58_upd.F

Avoid potential problem when material law58 definition contains non existing sensor 
Sensor number was not set to 0 in material parameter table when sensor is defined in material cards but does not exist

Correct sensor reference in material law 58

---

engine/source/tools/curve/table2d_vinterp_log.F

possible NAN results when static reference strain rate is equal to zero in material law input
correct log interpolation routine to avoid calculation of log(0) = inf

correction of singularity in logarythmic interpolation routine

---

starter/source/interfaces/inter3d1/i11remlin.F

Starter might hang up due to infinite loop when interface type11 defined Iremgap w/ asymmetry edges
correction to avoid infinite loop.

bug fixing to avoid infinite loop of int11+Iremgap

---

starter/source/materials/mat/hm_read_mat.F
starter/source/materials/mat/mat044/hm_read_mat44.F

It permits to avoid a pressure cut-off at zero in tension when /EOS is used with these laws
Initialize a material parameter Pmin = -inf in starter. It is used in some EOS and usually initialized in hydrodynamic matarial laws but not in  standard materials for solids

initialize minimal pressure as -inf for law109 and 44 in case of utilization with EOS

---

engine/source/tools/sensor/sensor_init.F

information about sensor reset was printed multiple times in engine output, by each proc
restricted engine output to proc 0

Correct /SENSOR/RESET output in engine, avoid multiple prints in spmd

---

engine/source/assembly/asspar4.F

My PR #2402 introduced some schedule(dynamic, chunk) or schedule(guided, chunk)
On ARM machine with a compiler,  define a chunk size for the omp schedule (dynamic or guided) leads to wrong results (no issue with static)
Remove the chunk size, and convert dynamic to guided to bypass the omp issue

OpenMP issue on ARM system

---

engine/source/materials/fail/johnson_cook/fail_johnson.F
engine/source/materials/fail/johnson_cook/fail_johnson_b.F
engine/source/materials/fail/johnson_cook/fail_johnson_c.F
engine/source/materials/fail/johnson_cook/fail_johnson_ib.F
engine/source/materials/fail/johnson_cook/fail_johnson_xfem.F
hm_cfg_files/config/CFG/radioss2024/FAIL/fail_johnson.cfg
starter/source/elements/elbuf_init/elbuf_ini.F
starter/source/materials/fail/johnson_cook/hm_read_fail_johnson.F

Add a lower value for plastic strain at failure for /FAIL/JOHNSON and fix a major memory issue in element buffer for beam failure (leading to segfault).
Add EPSF_MIN parameter and fix the element buffer problem in elbuf_ini.

Add lower value for plastic strain at failure for /FAIL/JOHNSON

---

engine/source/output/h3d/h3d_build_fortran/h3d_create_fvmbag_centroids.F
engine/source/output/h3d/h3d_build_fortran/h3d_update_fvmbag_centroids.F

Missing space causes a build dependency when building the engine file
Added a space between the use command and the mod.

Added space between USE and GROUPDEF_MOD

---

starter/source/materials/mat/mat025/read_mat25_crasurv.F90
starter/source/materials/mat/mat025/read_mat25_tsaiwu.F90

Avoid FPE problem in output routines with law25
several output routines still use PM table parameter storage, now  replaced by matparam in law25
I have restored these paramerets in PM to avoid problems of non initialized values

Add old PM parameter storage still used in outputs for material law 25

---

engine/source/mpi/spmd_mod.F90

Regression from 4d9cc3d3abfcb3273d3a4af363124d66c531ec68 in single precision.
Could cause segfault for SPH in sp

Fix for allreduce in sp

---

starter/source/elements/truss/tgrhead.F
starter/source/starter/lectur.F

no change for the user
modifed truss element group sorting criteria : force the same PID/MID for one group, same as other element types

truss element groups : add PID/MID as group sorting criteria

---

engine/source/boundary_conditions/ebcs/ebcs10.F

When using non reflecting frontier (BCs with option : /EBCS/NRF) then a specific treatment is required when used with new grid formulation /ALE/GRID/MASSFLOW
velocity increment at initial time is set to 0.0 (vold=vnew=zero in source file ebcs10.F)

/EBCS/NRF : specific treatment with /ALE/GRID/MASSFLOW

---

starter/source/elements/initia/initia.F

Tidying up format of output for Total Added Mass line (for non structural mass), removed 3 blank lines and align justification with header (indent 5 spaces instead of 1)
User was confused by all the blank lines and misalignment of ADMAS total added mass report under the header
Tidying up format of output for Total Added Mass line (for non structural mass), removed 3 blank lines, 1 at end of header and 2 at start of output and aligned justification with header (indent 5 spaces instead of 1)

Update initia.F for TOTAL ADDED MASS output from starter

---

starter/source/boundary_conditions/init_bcs_wall.F90

/BCS/WALL allows for blocking any internal face using a sliding wall boundary condition (collocated FVM scheme : law151). A Starter issue has been resolved when dealing with quad or tetra elements. The issue occured depending on the number of elements in the input files

/BCS/WALL : fix for quad and tetra

---

engine/source/elements/spring/preload_axial.F90

stiffness restoring in preloading period of /PRELOAD/AXIAL has been removed after some validation tests.

remove stiffness restring in /PRELOAD/AXIAL after some tests

---

starter/source/initial_conditions/inigrav/inigrav_load.F

Inigrav_load calls inigrav_eos without the NUMMAT argument
Add NUMMAT to the list of arguments

Fix missing argument in inigrav_load routine

---

common_source/output/restart/write_bcs_wall.F90
engine/source/boundary_conditions/bcs_wall_trigger.F90

/BCS/WALL: Eliminate implicit LOGICAL-INTEGER conversion
The implicit conversion from LOGICAL to INTEGER may vary depending on the compiler used (intel, gfortran, ...). The source code in write_bcs_wall.F90 has been updated to use explicit assignments of 1 or 0 to address this.

/BCS/WALL: Eliminate implicit LOGICAL-INTEGER conversion

---

engine/source/elements/solid/solide/s8get_x3.F
engine/source/elements/solid/solide/ssort_n4.F

Bug fix: my_real coordinates (in sforc3.F,szforc3.F,s8eforc3.F) were passed to DOUBLE PRECISION (s8get_x3). 
Get Nan or segfault in single precision for distortion control w/ Hexa solid elements
correction to fix the single precision issue of distortion control w/ Hexa solid elements

correction on distortion control of Hexa solid using single precision (argument type mismatch)

---

starter/source/materials/fail/fractal/random_walk_dmg.F90

correct bug introduced when adding a conditional output prints in /fail/fractal_dmg
modified an "if then" condition, forcing a correct order of term evaluation

correct the order of logical terms when evaluating "if" condition

---

starter/source/materials/mat/mat051/m51init.F

In response to the update introduced in commit 93c5e1eb0e1ab9056043f1866722eba0280bc12b, where uparam(31) was configured to 12 in fill_buffer51.F to facilitate the detection of input format when invoking m51init.F. Subsequently, it is imperative to reset uparam(31) to its original value of 1.
Although not classified as a bug currently, resetting this parameter to its expected value is essential to preempt any potential complications with future development reliant on upram(31) and material law51.

m51init:uparam(31) set to 1 when iform=12

---

starter/source/boundary_conditions/ebcs/read_ebcs.F

The argument 'TYP' from the subroutine 'HM_READ_EBCS_MONVOL' has been removed. This argument should have been removed during the previous cleanup (commit: bdd2ce631c9974f31b75f503e3e8ab3755263e9a). It is now done.

/EBCS/MONVOL:argument removed

---

engine/source/output/anim/generate/dfuncc.F
engine/source/output/anim/generate/genani.F

An issue was reported when using /ANIM/ELEM/VFRAC instead of /ANIM/BRICK/VFRAC. The animation file was corrupted and unreadable by HyperView. This source update resolves the issue. The animation file is now correctly written and readable.

/ANIM/ELEM/VFRAC : fix

---

common_source/modules/ale/ale_connectivity_mod.F
starter/source/restart/ddsplit/c_ixfloc.F
starter/source/restart/ddsplit/w_front.F
starter/source/spmd/split_cfd_solide.F

In the ALE framework, it is necessary to define connectivity between elements. Given an element, it is then possible to retrieve adjacent elements. This is facilitated by the ALE_CONNECTIVITY%%EE_CONNECT data structure ('ee' stands for element to element).
When dealing with triangles, the IXTG buffer is utilized. However, it is important to distinguish between 2D and 3D simulations. For 3D simulations, the IXTG array is used to store 3D 3-node-shell elements. For 2D simulations, IXTG stores triangle solids (for axial or planar analysis). This distinction is now correctly handled.
Prior to this update, there could have been a potential issue when the input file contained both 3D ALE elements (HEXA, TETRA) and 3-node-shell elements.

ale connectivity buffer: tria update

---

engine/source/ale/grid/alew1.F
engine/source/input/freform.F
engine/source/input/lectur.F
hm_cfg_files/config/CFG/radioss140/CARDS/ale_grid_disp.cfg
starter/source/general_controls/ale_grid/hm_read_ale_grid.F
starter/source/starter/contrl.F

With the ALE framework, employing a mesh smoothing technique becomes necessary due to the independence of mesh velocity from material velocity. The default formulation is 'DISP' (/ALE/GRID/DISP). Undocumented parameters (since version 51), namely vgxw, vgy, and vgz, have been present in source code. These scale factors have now been removed as they were never utilized in practice
- scale factors removed from source code
- removed from CFG file
- removed from Starter listing file & Reader
- removed from Engine Reader & its listing

/ALE/GRID/DISP:source cleaning

---

common_source/modules/loads/pblast_mod.F
starter/source/loads/pblast/hm_read_pblast.F

The PBLAT option represents a surface loading where the applied time history follows a Friedlander blast wave model. Parameters of the blast history are derived from empirical tables.
New defaults have been established:
- i_Tshift is set to 2 (the first cycle starts on the first arrival time).
- Pmin is set to 0.0.
- The decay parameter is bounded to [0.0, infinity[, instead of [1.0, infinity[.
- Finally a warning message is introduced when Pmin is negative. Users are advised to verify the blast history for negative pressure, as the empirical model is calibrated for the positive phase only.

/LOAD/PBLAST : new default values

---

engine/source/materials/fail/tabulated/fail_tab2_c.F
engine/source/materials/fail/tabulated/fail_tab2_s.F
starter/source/materials/fail/tabulated/hm_read_fail_tab2.F
starter/source/materials/updfail.F90

The switch to logarithmic scale for strain rate dependency in /FAIL/TAB2 was needed for DYN2RAD conversion. 
Add the detection of negative values in strain rate dependency table to switch to logarithmic scale.

Add logarithmic scale to /FAIL/TAB2 strain rate dependency

---

engine/source/elements/solid/sconnect/suser43.F
engine/source/materials/mat/mat083/sigeps83.F
starter/source/materials/mat/mat083/hm_read_mat83.F

strain rate was not calculated except when plastic strain rate was chosen (ISRATE=1)
corrected strain rate calculation including filtering by default
corrected plasticity projection algorithm

Correction of strain rate effect in law83

---

engine/source/system/progcond_c.c

Bug fix in progression bar for BEM/DAA.
Depending on the value of Iprint, a progression bar may be written in stdout. The dimension of the array outline was too small.

BEM: progression bar fix

---

starter/source/interfaces/inter3d1/i7remnode.F

Starter might crash in case of solid model using interface type25 + Iedge=1 
correction to fix Starter crash due to division by 0.

correction to avoid Starter stop due to division by 0 in case of interface type 25 w/o edge

---

engine/source/materials/mat/mat058/sigeps58c.F
engine/source/output/anim/generate/dfuncc.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F

UVAR4 and UVAR5 variable output was wrong according to actual documentation
changed index of UVAR in H3D and ANIM output in law 58.
updated UVAR description in engine code of the material law (in comments)

Correct H3D and ANIM output of total strain in law58

---

engine/source/materials/mat/mat126/sigeps126.F90

The name of element deletion message for /MAT/LAW126 was not consistent. Needed to change it. 
JH1 -> JHC for Johnson-Holmquist Concrete.

Change name of law 126 in element deletion message

---

engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
starter/source/multifluid/multifluid_global_tdet.F

Detination Times are calculated for time controlled explosive material law.
The detonation time is calculated for the entire region associated with the material law, even if the volume fraction is not yet present. This prevents unexpected detonations when a small volume fraction of explosive moves into a cell without explosive, where the detonation time was previously 0.0.
For post-processing purposes, the detonation time is displayed only where it is relevant.

LAW151:global detonation time

---

starter/source/elements/elbuf_init/r2r_matparam_copy.F

starter crashes with multidomains when one of the material models contain failure
MATPARAM structure needs to be copied between subdomains on the frontier. Allocation and copy of new failure model structure was missing.

multidomains : correction of MATPARAM copy between subdomains

---

starter/source/boundary_conditions/ebcs/hm_read_ebcs_inlet.F
starter/source/boundary_conditions/ebcs/read_ebcs.F

The //SUBMODEL option allows the definition of submodeling methods. In the case of /EBCS/INLET, function identifiers may be set to "-1" to define continuity. However, if the function is user-defined, then the identifiers must be offset by the submodel default offset ( _OFF_DEF = LSUBMODEL(SUB_INDEX)%OFF_DEF_ ). This update ensures that /EBCS/INLET is now compatible with the //SUBMODEL option.

/EBCS/INLET : compatibility with SUBMODELING (//SUBMODEL)

---

engine/source/engine/resol.F
engine/source/loads/general/pfluid/pfluid.F

A bug has been fixed when using PFLUID with the /PARITH/OFF option (parallel arithmetic). The previous behavior could lead to an unexpected termination of the Engine program.

/LOAD/PFLUID:update for parallel arithmetic OFF

---

engine/source/materials/mat/mat066/sigeps66.F

The Young modulus retained for soundspeed computation was not sufficient in case where Young modulus in compression is higher than Young modulus in tension. 
Keep the maximum value of soundspeed between Young modulus in tension and Young modulus in compression.

Fix soundspeed computation for /MAT/LAW66 in case of specific Young modulus in compression

---

.github/workflows/developer_ci.yml
.github/workflows/prmerge_ci_main.yml
.github/workflows/upd_headers_ci.yml

Upgrade some github actions to last version to be compatible with node.js 20 (node.js 16 will be deprecated in June 2024)
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

Build on CentOs 8 + upgrade actions download/upload/checkout to version 4 to be compatible with node.js 20

---

tools/th_to_csv/src/th_to_csv.c

precision of float to 6 decimal places was not sufficient for some units systems (stress in GPa for example) output modified to use engineering format for increase of precision
precision of float to 6 decimal places was not sufficient for some units systems (stress in GPa for example) output modified to use engineering format for increase of precision
format for csv output modified from %f to %e (double)

Update th_to_csv.c output to engineering format

---

engine/source/elements/sh3n/coquedk/cncoef3.F
engine/source/elements/shell/coquez/czforc3.F
engine/source/elements/xfem/czforc3_crk.F

NaN when define Law 25 in the part and Isotropic law in ply for property type51 with QEPH element
The issue is fixed

fix Nan issue when isotropic law used in Prop/type51 in the ply

---

engine/source/elements/sh3n/coquedk/cncoef3.F

, and setting Iorho =1 only if we have law15 or 25 in the ply for type11, 17, 51 and Pcommp
Leading to numerical difference compared to the case where all the material law belong to the ply are isotrop
Activation of orthopic flag for QEPH only if one ply is associated to law15 or 25

fix bug when we use /PROP/TYPE11 or 17 with QEPH and Isotropic law in the ply

---

starter/source/initial_conditions/inivol/init_inivol.F90
starter/source/initial_conditions/inivol/inivol_set.F

In a recent update, it was introduced an array index: nf1_2d (03b27e6efd0823662c54e15c7b8ee9e0e576f883). This index is now set to 1 when it is not in use (required_2d_polygon_clipping = .false.). This change prevents real-time debugging tools, such as "check bounds," from detecting an out-of-bounds index, even if the argument is not used in the called subroutine.
Additionally, some minor cleanup has been performed.

/INIVOL : check bounds + clean

---

engine/source/output/h3d/h3d_build_fortran/lech3d.F
engine/source/output/h3d/h3d_results/h3d_solid_tensor_1.F

only one or two integration point result are output of /H3D/SOLID/TENS/IR=ALL/IS=ALL/IT=ALL for tet10 element (or tet4+Itetra4=1).
correction to output rightly /H3D/SOLID/TENS/IR=ALL/IS=ALL/IT=ALL for tet10

correction to output /H3D/SOLID/TENS/IR=ALL/IS=ALL/IT=ALL for tet10

---

common_source/modules/interfaces/th_surf_mod.F

For instance, LOADP_FLAG is used in load_pressure.F even if TH_SURF%IOK == 0

missing initializaiton in TH_SURF

---

engine/source/materials/mat/mat104/mat104_ldam_nice.F
engine/source/materials/mat/mat104/mat104_nldam_newton.F
engine/source/materials/mat/mat104/mat104_nldam_nice.F
engine/source/materials/mat/mat104/mat104_nodam_newton.F
engine/source/materials/mat/mat104/mat104_nodam_nice.F
engine/source/materials/mat/mat104/mat104c_ldam_newton.F
engine/source/materials/mat/mat104/mat104c_ldam_nice.F
engine/source/materials/mat/mat104/mat104c_nldam_newton.F
engine/source/materials/mat/mat104/mat104c_nldam_nice.F
engine/source/materials/mat/mat104/mat104c_nodam_newton.F
engine/source/materials/mat/mat104/mat104c_nodam_nice.F
engine/source/materials/mat/mat104/sigeps104c.F
engine/source/materials/mat_share/mulawc.F

For /MAT/LAW104, the IOFF_DUCT was not initialized to one, leading to a brutal element deletion when used when some specific criteria. 
Add IOFF_DUCT initialization to 1 and update of the OFF flag in /MAT/LAW104.

Add IOFF_DUCT for ductile failure in /MAT/LAW104

---

engine/source/output/h3d/h3d_results/h3d_quad_scalar_1.F90

**Fix related to commit 298ec0762594c58de83ef78573b19601ef018643**
The **Is_written_quad** array was unexpectedly reset to 0 during the group loop for **'NG = 1, NGROUP'**.

H3D and QUAD : fix

---

engine/source/multifluid/multi_inlet_ebcs.F
starter/source/multifluid/multifluid_init2.F
starter/source/multifluid/multifluid_init2t.F
starter/source/multifluid/multifluid_init3.F
starter/source/multifluid/multifluid_init3t.F

When /EBCS/INLET is used with multi material law151 , IFUNC = 0 for submaterial density or energy is now working without any floating point exception.

/EBCS/INLET + /MAT/LAW151 : compatibility with ifunc=0

---

engine/source/materials/fail/fail_setoff_c.F
engine/source/materials/fail/fail_setoff_npg_c.F
engine/source/materials/mat_share/mulawc.F
engine/source/materials/mat_share/usermat_shell.F

For some cases, shell element deletion messages can be doubled or disappear. 
Avoid the disappearance or the doubling of the message by adding a flag to distinguish cases where element deletion printing message coming from mulawc.F is needed.

Fix doubled printing message when elements are deleted

---

common_source/modules/ale/multi_fvm_mod.F
starter/source/elements/initia/initia.F

elbufdef_mod was not called, but inherited from multi_fvm Module. This could cause initia not to be compiled when elbufdef_mod is modified.

Issue in intia routine : 

---

engine/source/output/h3d/h3d_results/h3d_quad_vector.F

The call of subroutine responsible for writing vector results for QUAD elements has been moved inside the conditional block. This change prevents unexpected data from being written to the H3D file. For example, in a scenario where the input file contains 1 QUAD element (group NG=1) and 4 TRUSS elements (group NG=2), the previous implementation would incorrectly set QUAD_VECTORS(1:3, **1,:4**) despite the allocation being only for QUAD_VECTORS(1:3, **1:1**). This mismatch was causing **memory corruption**.

/H3D : bug fix for QUAD elements and vectors output

---

common_source/modules/constant_mod.F
starter/source/initial_conditions/inivol/hm_read_inivol.F
starter/source/initial_conditions/inivol/iniphase.F
starter/source/initial_conditions/inivol/inivol_set.F

The /INIVOL option is an initial condition that allows setting volume fractions using a provided surface (which can consist of 3D shells, 2D segments, 2D/3D ellipsoids, or infinite planes). The user specifies surfaces and submaterial identifiers to fill one side of the surface with the given ratio.
At the end of the process, the sum of the volume fractions must total 100%, ensuring that the element volume is correctly partitioned. If the sum does not reach 100%, the remaining volume is automatically filled with the default submaterial.
The default submaterial ID has been updated. Previously, the default submaterial ID was set to 1. It is now set to the prevalent submaterial, which is defined when multimaterial laws (e.g., law51 or law151) are applied. This change makes the process more …

/INIVOL enhancement : default submat is the prevalent one

---

engine/source/output/anim/generate/output_schlieren.F
engine/source/output/anim/generate/schlieren_buffer_gathering.F
engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
engine/source/output/h3d/h3d_results/h3d_quad_scalar_1.F90
engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F

/H3D/ELEM/SCHLIEREN : A potential conflict between LLT and NEL has been resolved. LLT has been replaced with NEL to eliminate any ambiguity. Otherwise output result may be N/A
/H3D/ELEM/MACH : following 298ec0762594c58de83ef78573b19601ef018643 . 'mach' keyword replaced with 'MACH' otherwise output result is N/A

H3D : update for QUADS

---

starter/source/elements/elbuf_init/elbuf_ini.F

correct possible starter crash during beam element buffer allocation and initialization
failure model number was not initalized during element buffer allocation

correct bug in element buffer initialization for beams with failure

---

starter/source/spmd/domain_decomposition/initwg_shell.F
starter/source/spmd/domain_decomposition/initwg_tri.F

Correct a bug in starter during material law weight calculation for domdec, with material laws + /visc/prony
number of Prony series terms was checked using old obsolete adress in IPM instead of MAT_PARAM%VISC

Correction of material law weight calculation with /visc/prony

---

engine/source/output/h3d/h3d_build_fortran/lech3d.F

Some outputs command for H3D was not consistent with some element properties. This implies the creation of useless output making the post treatment confused in some cases. 
Limit the output option to some shell element properties: 
-> /H3D/SHELL/XXX/NPT= for Type 1 and 9 only,
-> /H3D/SHELL/XXX/LAYER= for Type 10, Type 11 and Type 16
-> /H3D/SHELL/XXX/PLY=/NPT= for Type 17, Type 51 and Type 52

Fix output options depending on properties in H3D

---

starter/source/restart/ddsplit/c_idglob.F
starter/source/restart/ddsplit/ddsplit.F

The loop over element groups (1, NGROUP) previously processed unexpected element types, such as shells. The loop has now been refined to focus exclusively on relevant element types: hexahedrons, quads, and triangles. Additionally, quads and triangles, which were previously overlooked, are now correctly taken into account.

LAW151 + Navier-Stokes : fix for domain decomposition

---

.gitignore
Apptainer/arm/openradioss_arm.def
Apptainer/openradioss.def
Apptainer/openradioss_intel_ifx.def

Update the Apptainer definition files to use the `-release` flag and update the Intel compiler. The changes have been made following the post earlier this year of #2272 
The Apptainer files have been updated to use the `-release` flag so as to not have any debugging or sanitation procedures. This makes them ready for production workloads. The Intel compiler toolchain has been updated to the latest current version, which hopefully yields slight better performance and less issues.
I have not been able to build the Apptainer files locally as I currently do not have a nice stable internet connection, but they should build without issue as the changes are very minor. Nonetheless, the changes to the Intel directories have been verified.

Update Apptainer files

---

starter/source/initial_conditions/inivol/inivol_set.F
starter/source/materials/mat/mat051/hm_read_mat51.F

A potential issue was introduced with commit 7a5fa806dd297c7b7211286c1a63b7e3befdd08b. The array PM(20+1 : 20+NB_SUBMAT) was being used for laws 20 and 151, but it is not compatible with law 51.
This issue has now been resolved. A dedicated data structure is going to be introduced in a future update to standardize data storage and improve overall readability using MAT_PARAM data structure.

INIVOL / LAW51 : bug fix

---

starter/source/initial_conditions/inivol/hm_read_inivol.F
starter/source/initial_conditions/inivol/iniphase.F
starter/source/materials/mat/mat151/hm_read_mat151.F

When using INIVOL with /MAT/LAW151 user can defines vrfrac =(0,0,..,0) because INIVOL is supposed to set volume fractions.
to avoid any unexpected division by zero, default dubmaterial is then set to 1 by defining vfrac = (1.0 , 0 ... 0)

/MAT/LAW151 : default vfrac filling

---

engine/source/airbag/get_volume_area.F90
engine/source/airbag/volpresp.F

The dimension of NORMAL and CONTRIBUTION_NUMBER are not correct
The dimension of NORMAL is NUMELC+NUMELTG+NUMNOD (instead of NUMNOD)
The dimension of CONTRIBUTION_NUMBER is NODE_NUMBER+1 (instead of NODE_NUMBER)

The dimension of array was wrong in a subroutine, introduced by a1a952b81d56d019a1732512fa3fcbf6269113aa

---

engine/source/airbag/init_global_monvol_frontier.F90
engine/source/airbag/init_monvol_omp_structure.F90

Segfault / memory issues were detected with a type8 airbag model
A type 8 airbag can be transformed into type 7 when a condition is reached. Some arrays allocated at the beginning of the engine (only for airbag type 1,2,3,4,5,7,9, >10) must also be allocated for type 8

Fix an issue introduced by a1a952b81d56d019a1732512fa3fcbf6269113aa

---

starter/source/initial_conditions/inivol/ale_box_coloration.F

/INIVOL algorithm uses a voxel. The cells crossed by the surface (defined by segments) of /INIVOL must be tagged. But there was an issue with this part of the code : only the cells containing the 4 nodes of the segment were tagged
Fix the issue
Issue :
Ideal case : 
Fix :

/INIVOL : the result of getphase was not correct if the surface used coarse mesh

---

engine/source/materials/mat/mat002/m2iter_imp.F
engine/source/materials/mat/mat002/m2law.F
starter/source/materials/mat/mat002/hm_read_mat02.F
starter/source/materials/therm/hm_read_therm.F

possible slight change of law2 results with thermal options
corrected bug in law2 for solids concerning max hardening stress with strain rate dependency
Default value of reference temperature was modified to be the same as in all other thermal laws and options
The same initial temperature was defined in /heat/mat to avoid incorrect zero Kelvin and possible numerical singularity
bug correction : max stress value should be vector depending of element strain rate instead of scalar (solids only)

Change default values of initial temperature for LAW2 and /HEAT/MAT

---

engine/source/output/th/thsol.F

Strain rate was not output in time history for law83
added necessary term in th output - strain rate is calculated and stored in element buffer

Correct strain rate TH output for material law 83

---

engine/source/interfaces/int22/w_bufbric_22.F

Additional update following 5908984f37d026b0c2483879e7d5335590f9231b where Integer Read/Write was replaced with Real Read/Write.   Arrays Adjacent_FLUX and Adjacent_upwFLUX are real arrays and must be Read/Write with subroutines READ_DB and WRITE_DB instead of READ_I_C and WRITE_I_C

restart file fix

---

starter/source/elements/elbuf_init/r2r_matparam_copy.F

R2D Option (RAD 2 RAD):
The R2D option enables running multidomain computations in Radioss.
Special handling is required in the R2R subroutines (data structure splitting) due to the introduction of a new member in the MATPARAM data structure. This update follows commit 09d45d46cf3bcb558c080d13c899fbaa7579b26c, which introduced MATPARAM%MULTIMAT.

RAD2RAD : update required due to the introduction of new buffer MATPRAM%MULTIMAT

---

hm_cfg_files/config/CFG/radioss2025/MAT/matl125_laminated_composite.cfg
hm_cfg_files/config/CFG/radioss2025/MAT/matl127_enhanced_composite.cfg
starter/source/materials/mat/mat125/hm_read_mat125.F90
starter/source/materials/mat/mat127/hm_read_mat127.F90

Not corresponding to dyna input for poisson ratio's
Use the same input as dyna law nu21, nu31 and Nu32 instead nu12, nu13,nu23

input correction for law125 and law127 according to dyna input

---

common_source/modules/cpp_python_funct.cpp
engine/source/mpi/spmd_mod.F90

The syntax CX(1) was broken in the python callback to Fortran nodal variables

/FUNCT/PYTHON regression fix for nodal value callback

---

starter/source/model/sets/create_seg_clause.F
starter/source/model/sets/fill_gr.F
starter/source/model/sets/hm_set.F

In the 2D case, when the surface is built from user segments, specific data buffer is used (%LINE_NODES instead of %SURF_NODES). This is now taken into account and Starter is now able to build the polygonal surface from user segments.

/SET : 2D surface fix

---

starter/source/output/qaprint/st_qaprint_set.F

ST_QAPRINT_SET : update for 2D case
A recent fix has been introduced for the /SET/GENERAL (SEG) functionality in 2D (commit: 3c95cb8041379bd5270fba631782cc1d9aab218b). Previously, surfaces composed of segments were not being correctly constructed. The ST_QAPRINT_SET subroutine now properly handles and displays non-empty surfaces. However, this also revealed that the 2D case was not initially anticipated.
The display of user node identifiers has been refined to ensure they are only shown when relevant. In the 2D case, when IGRSURF(IGR)%NODES(N, 3:4) is set to 0, these indices should not be used to reference the ITAB array. This issue has now been resolved. Consequently, user node identifiers 3 and 4 are no longer displayed when not applicable to the 2D case.
No effect on numerical …

ST_QAPRINT_SET : update for 2D case

---

engine/source/mpi/interfaces/spmd_i7tool.F
engine/source/output/h3d/h3d_build_fortran/lech3d.F

Allocation of Remote EFRICFI array in i7tools.F requires values which are set after. Move this allocation to the routine settings all values.

Issue in /H3D/NODA/CSE_FRIC option:

---

starter/source/starter/lectur.F

correction possible overflow in INISPHCEL when NUVAR > 0
move init o
This pull request includes changes to the `LECTUR` subroutine in the `starter/source/starter/lectur.F` file. The changes involve the initialization and allocation of variables, specifically related to the `NUSPHCEL` variable.
Initialization and allocation changes:
* Added initialization size for `NUSPHCEL` to 0. (`starter/source/starter/lectur.F`, [starter/source/starter/lectur.FR1274-R1277](diffhunk://#diff-b7cfbd6038ee923f835b05bcea0774e4375066ddc226b80bdd2f2cc8442f7ebdR1274-R1277))
* Removed redundant initialization of `NUSPHCEL` to 0, as it is now handled earlier in the subroutine. (`starter/source/starter/lectur.F`, [starter/source/starter/lectur.FL8189](diffhunk://#diff-b7cfbd6038ee923f835b05bcea0774e4375066ddc226b8 …

correction possible overflow in INISPHCEL when NUVAR > 0

---

engine/source/materials/mat/mat069/sigeps69.F
engine/source/materials/mat/mat069/sigeps69c.F
engine/source/materials/mat_share/mulaw.F90
engine/source/materials/mat_share/mulawc.F
engine/source/materials/mat_share/usermat_shell.F
engine/source/materials/mat_share/usermat_solid.F
engine/source/materials/visc/prony_modelc.F
engine/source/output/anim/generate/dfuncc_ply.F
engine/source/output/anim/generate/genani.F
engine/source/output/anim/generate/tensorc.F
engine/source/output/anim/generate/tensorc_crk.F
engine/source/output/anim/generate/tensorc_ply.F
engine/source/output/dynain/dynain_c_strsg.F
engine/source/output/dynain/gendynain.F
engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
engine/source/output/sortie_main.F
engine/source/output/th/thcoq.F
starter/source/elements/solid/solide/sgrtails.F
starter/source/materials/visc/hm_read_visc.F
starter/source/spmd/domain_decomposition/initwg_solid.F

possible missing viscosity stress in engin outputs
removed all references to IPM table in viscosity models.
IPM It was already replaced by MAT_PARAM%VISC structure, but still present in the code

clean references to IPM parameters in viscosity models

---

tools/th_to_csv/src/th_to_csv.c

- The output file of `th_to_csv` cannot be changed, it is hardcoded to `input_file`+`.csv`
- Not specifying an input-file leads to segmentation fault
~~~
pbucher:~/.../th_to_csv/linux64$ ../../../exec/th_to_csv_linux64_gf 
** ERROR: FILE (null) NOT FOUND
** ERROR: FILE (null) NOT FOUND
Floating point exception (core dumped)
~~~
- A proper error is issued if no input file is specified. Now ` ** ERROR: MISSING INPUT ARGUMENT: TH-FILE` is issued and the return code is 1
~~~
pbucher:~/.../th_to_csv/linux64$ ../../../exec/th_to_csv_linux64_gf 
** ERROR: MISSING INPUT ARGUMENT: TH-FILE
~~~
- Adding the parsing of a second input argument, which allows to specify the output file for the csv-conversion
- Usage documentation is updated:
~~~
// To launch conversion :
// th_to_csv.linux64.exe T01File …

optionally allow output file in th_to_csv

---

engine/source/output/th/thcoq.F

potential problem in TH output of viscous stress 
The material number used in MAT_PARAM adress was wrong for multilayer properties

Correct wrong material number in MAT_PARAM in thcoq.F

---

hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg

This pull request includes changes to the `hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg` file to update the data hierarchy configuration, modifying the list of databases included in the hierarchy.
Updates to data hierarchy configuration:
* [`hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg`](diffhunk://#diff-4cc2f9c0821867f2a581f76580df7bd026dc59e58201ba6c855c491387242128L7487-R7489): enabled `DATABASE_NCFORC` and `DATABASE_NODFOR` while keeping `DATABASE_NCFORC_FILTER` commented out.

read *DATABASE_NODFOR & NCFORC dyna cards

---

engine/source/elements/solid/solidez/szhour_ctl.F

might get wrong gpstrain output value due to not initialized variable nu for isolid=24 with distortion control
fix not initialized variable issue

not initialized variable for isolid=24 with distortion control

---

starter/source/starter/lectur.F

When using Rad2Rad (R2R) method, 'MPARAM_R2R' data structure must be deallocated after domain decomposition in DDSPLIT ( ). Destrutor introduced with 8e4ff80b7912bdc3e3c9d9660335df8abd7d5e7b is now moved at the end of lectur.F, after the call of DDSPLIT where pointer MAT_ELEM%MAT_PARAM => MPARAM_R2R is no longer used.

fixing R2R deallocating issue

---

engine/share/modules/shooting_node_mod.F
engine/source/engine/resol.F
engine/source/interfaces/interf/get_neighbour_surface.F90
engine/source/interfaces/interf/get_neighbour_surface_from_remote_proc.F90
engine/source/interfaces/interf/get_segment_orientation.F90
engine/source/interfaces/interf/init_nodal_state.F
engine/source/mpi/interfaces/spmd_exch_neighbour_segment.F90
starter/source/restart/ddsplit/split_interfaces.F
starter/source/restart/ddsplit/split_seg_ielem.F

2 issues : 
* coating shell elements were not compatible with the erosion of solid element of the interface /TYPE25
* orientation of segment of wrapped elements can lead to bad numerical response 
To support coating shell element : 
* ielem_m array contains element ID (solid, shell or shell3n)
* the element id are shifted : 0 for solid, NUMELS+NUMELQ for shell, NUMELS+NUMELQ+NUMELC+NUMELR+NUMELT+NUMELP 
* the "real" element id is found thanks to this shift
Orientation : 
Orientations of all segments were computed. Now only the orientation of new active segments is computed

Coating shell elements were not compatible with the erosion of solid element + interface /TYPE25

---

engine/source/materials/mat/mat083/sigeps83.F

NaN can appear in law 83, due to a division by FPRIM which can be zero.

/LAW83: avoid division by zero

---

engine/source/elements/forintp.F
engine/source/mpi/spmd_mod.F90
starter/source/materials/mat/write_eosparam.F90
starter/source/materials/mat/write_matparam.F
starter/source/materials/mat/write_viscparam.F

GLOB_THERM argument must be intent(inout) as it can be modifed in downstream routines 
Missing argument to MPI_ABORT Call
starter argument mismatch at write_mat_table.F

Argument and Intent mismatch:

---

starter/share/modules1/inivol_mod.F
starter/source/initial_conditions/inivol/ale_box_coloration.F
starter/source/initial_conditions/inivol/hm_read_inivol.F90
starter/source/initial_conditions/inivol/init_inivol.F90
starter/source/initial_conditions/inivol/init_inivol_2D_polygons.F90
starter/source/initial_conditions/inivol/inivol_set.F
starter/source/initial_conditions/inivol/surface_min_max_computation.F

The INIVOL option calculates the initial volume fraction by filling submaterial fractions based on the user-defined surface. Recently, polygon clipping was introduced to handle user-defined surfaces in 2D (polygons)
With this update, polygon clipping now also manages super-ellipses (/SURF/ELLIPS) and infinite planes (/SURF/PLANE), replacing the previous method (Monte Carlo) for these shapes.
_This change improves the precision of the calculations, as the clipping method is more accurate than the legacy Monte Carlo method. As a result, you may notice slight changes in the numerical solution when using super-ellipses or infinite planes, as the new clipping method offers better precision._
_(No difference to expect if /INIVOL option is not use with /SURF/ELLIPS or /SURF/PLANE)_

INIVOL 2d : manage superellipse and infinite plane with polygonal clipping method

---

starter/source/properties/composite_options/stack/lecstack_ply.F
starter/source/properties/hm_read_properties.F

There was a need to be able to compute the initial thickness of the whole stack of plies for composites properties. 
Add the computation of the initial stack thickness for properties type 17/51/52

Compute global initial stack thickness for composite property in Radioss starter

---

starter/source/spmd/domain_decomposition/grid2mat.F

Segfault when small rigid bodies are attached to tetra10 middle nodes

/TETRA10 + /RBODY: starter segfault for SPMD

---

common_source/modules/connectivity.F90
common_source/modules/spring_functions_mod.F90
common_source/tools/memory/extend_array.F90
engine/share/modules/debug_mod.F
engine/share/modules/restart_mod.F
engine/source/engine/node_spliting/nodal_arrays.F90
engine/source/engine/radioss2.F
engine/source/engine/resol.F
engine/source/engine/resol_head.F
engine/source/output/outfile/check_nan_acc.F
engine/source/output/restart/arralloc.F
engine/source/output/restart/rdcomm.F
engine/source/output/restart/rdresb.F
engine/source/output/restart/wrrestp.F
engine/source/output/sortie_main.F
engine/source/output/th/hist1.F
engine/source/output/th/hist13.F
engine/source/output/th/thnod.F
engine/source/user_interface/uaccess.F
engine/source/user_interface/userwindow_interface_routines.F
starter/source/restart/ddsplit/wrcommp.F

The nodal values are now gathered in a user defined type. For instance, from resol.F, the coordinates are now NODES%X instead of 'X'
Those nodal arrays can be reallocated when nodes are spawned

Node split

---

engine/source/elements/beam/pforc3.F

unstable behave observed w/ /PRELOAD/AXIAL using beam type18 for some models
(workaround : using beam type3 or spring type13)
correction to fix unstable issue w/ /PRELOAD/AXIAL of beam type18

correction /PRELOAD/AXIAL w/ type18 (beam)

---

engine/source/materials/fail/gene1/fail_gene1_c.F
engine/source/materials/fail/gene1/fail_gene1_s.F

Potential floating invalid issue when using /FAIL/GENE1 combined with other failure criterion. If failure is triggered by the other criterion, the strain tensor is not anymore valid for some operation in /FAIL/GENE1. 
Condition the operations on strain/stress tensor to active (not broken) element only. Otherwise, set the variable to zero.

Fix potential floating invalid issue with /FAIL/GENE1

---

starter/source/materials/mat/mat036/hm_read_mat36.F

The Young's modulus (E) is essential for describing material behavior in the elastic domain. The Starter now verifies that E is correctly defined. If E ≤ 0.0, an error message will be displayed.
ERROR ID :    **276**
** INPUT ERROR IN MATERIAL LAW 36
DESCRIPTION :  
-- MATERIAL ID: 1
-- MATERIAL TITLE:  my_material_law_36
YOUNG MODULUS SHOULD BE GREATER THAN 0.

/MAT/LAW36 : check if Young's modulus is defined

---

engine/source/engine/resol.F

Out-ouf-bound access passed as argument, but not used due to the /PARITH/OFF option.

fix check bounds issues

---

common_source/tools/container/umap.cpp
common_source/tools/container/umap_mod.F90
engine/source/constraints/general/bcs/lcbcsf.F
engine/source/engine/node_spliting/nodal_arrays.F90
engine/source/engine/resol.F
engine/source/interfaces/chkload.F
engine/source/interfaces/interf/chkstfn3.F
engine/source/interfaces/interf/count_remote_nb_elem_edge.F
engine/source/interfaces/interf/find_edge_from_remote_proc.F
engine/source/interfaces/interf/find_surface_from_remote_proc.F
engine/source/interfaces/interf/init_nodal_state.F
engine/source/mpi/interfaces/spmd_exch_deleted_surf_edge.F
engine/source/mpi/interfaces/spmd_exchmsr_idel.F
engine/source/mpi/kinematic_conditions/spmd_exchseg_idel.F
engine/source/output/anim/generate/animx.F
engine/source/output/restart/rdresb.F

SYSFUS is using ITABM1 which is of size 2:NUMNOD.
Hash table should perform better than linear search, and it is easier to update when nodes are added

Replace sysfus function by hash table (engine)

---

engine/source/engine/resol.F
engine/source/interfaces/intsort/intcrit.F
engine/source/interfaces/intsort/inttri.F

In case of high velocities, too many nodes were printed. Now we print only one node per spmd domain per interface.

/INTER/TYPE25 print less error messages in case of high velocities

---

hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg

In data_hierarchy.cfg, activate conversion of LOAD_BODY for options _RX,_RY,_RZ and _VECTOR
In data_hierarchy.cfg, activate conversion of LOAD_BODY for options _RX,_RY,_RZ and _VECTOR

Activate conversion of LOAD_BODY for options _RX,_RY,_RZ and _VECTOR

---

starter/source/materials/mat/mat151/hm_read_mat151.F

When law151 is used with /INIVOL option it is possible to define vfrac_i=0.0 in /MAT/LAW151.
In this case default submaterial is set to 1. This is now correctly taken into account in the MATPARAM%MULTIMAT buffer

/MAT/LAW151 : matparam update

---

engine/source/materials/mat/mat005/m5law.F
engine/source/materials/mat_share/mmain.F90

The material law subroutine is updated 
-  usual notation of JWL EoS is now used : A,B,R1,R2,W,...
- Argument and Variables are described
- Main sections of source code commented
- General Cleaning

/MAT/JWL (LAW5) : usual notation + cleaning

---

starter/source/materials/fail/hm_read_fail.F

wrong initialization of strain type (Ismstr) in failure criteria lecture made error or incomprehensible warning message 
remove the wrong initialization.

remove wrong initialization of Ismstr in failure reading

---

common_source/eos/eosmain.F
common_source/eos/gruneisen.F
hm_cfg_files/config/CFG/radioss2025/MAT/mat_EOS.cfg
starter/source/materials/eos/hm_read_eos_gruneisen.F

- **PSH parameter available** : The PSH parameter was added in Mie-Gruneisen EoS. It allows to model relative pressure by shifting pressure.
- **P0 parameter available** : E0 is now automatically calculated when user provides P0.  E0 is such as P(µ0, E0) = P0
Verification (isentropic path expansion/compression)

/EOS/GRUNEISEN : new P0 and PSH parameters

---

engine/source/loads/general/load_pcyl/press_seg3.F

scale factor applied to radius of pressure cylinder in /PCYL option was wrong
correction : multiplication of radius by scale factor instead of division

Correct scale factor on input radius in /PLCYL

---

starter/source/materials/mat/mat057/hm_read_mat57.F90

Shear modulus g was not defined anymore in radioss starter. 
Replace g by matparam%shear.

Fix checkbound issue for /MAT/LAW57 starter

---

engine/source/ale/alemain.F
engine/source/engine/resol.F

Missing arguments introduced with changes e560c0c4280e38f1c42e829b8603aa41c5b5ace9.
It is related to STAPMING simulation and LAW151

Missing arg wfext

---

engine/source/materials/mat_share/mulaw.F90

Go back to previous storage of bulk modulus and density, new matparam storage was not well initialized yet in some material laws. Avoid division by zero in these cases in calculation of sound speed;

revert storage of material density and bulk in mulaw.F90

---

engine/source/interfaces/int07/i7for3.F
engine/source/interfaces/int20/i20for3.F
engine/source/interfaces/int21/i21for3.F
engine/source/interfaces/int23/i23for3.F
engine/source/interfaces/int24/i24for3.F
engine/source/interfaces/int25/i25for3.F

Problem of formula of mu computation of friction Law Ifric=4  : mu=c1+(fric - c1 ) e-c2V instead of mu=fric+(c1- fric ) e-C2V
fr

Correction friction Law Ifric=4 formulation

---

engine/source/output/th/hist2.F
engine/source/output/th/thquad.F
engine/source/output/th/thsol.F
starter/source/output/th/hm_read_thgrou.F
starter/source/output/th/th_titles.F90
starter/source/output/th/write_thnms1.F90

- /TH/BRIC (WPLA) : now available for law25 in addition to law14
- /TH/BRIC (VSTRAIN) : volumetric strain
- /TH/QUAD (VSTRAIN) : volumetric strain

/TH/BRIC : new available output (VSTRAIN and WPLA)

---

engine/source/constraints/thermic/convec.F

possible PON issue using /CONVEC
Initialize variable T_INF outside the loop. It was initially non initialized but previous correction put it in a wrong place

/CONVEC : noninitialized variable was initialized in wrong place

---

starter/source/model/sets/solid_surface_buffer.F

Issue wit SET_D of coating shells.
Recreate surface segments of already deleted coating shells in SET_D.

/SET : Wrong definition of /INTER/TYPE25 secondary nodes in case of coating shells over solids

---

engine/source/materials/mat/mat128/sigeps128c.F90
engine/source/materials/mat/mat128/sigeps128s.F90
starter/source/materials/mat/mat128/hm_read_mat128.F90

Correction to avoid problems with high reference strain rate value in the input. Hardening should never be lower than static curve.
Added lower limit of strain rate in Cowper-Symonds factor and tabulated curve extrapolation.

Add lower limit for strain rate extrapolation in law128 to avoid hardening lower than static value

---

hm_cfg_files/config/CFG/radioss2025/MAT/Law128_hill_visc_plast.cfg
hm_cfg_files/config/CFG/radioss2025/data_hierarchy.cfg
starter/source/materials/mat/mat128/hm_read_mat128.F90

Added optional material law name in cfg file
Corrected mean value of orthotropic Lankford parameter in starter used as default

/MAT/LAW128 : update cfg file with optional name, correct ortotropic parameter initialization

---

engine/source/materials/mat_share/mulawc.F90

Use of uninitialized zcfac when not using Ishell=24 (QEPH formulation)
Tag the use of zcfac with flag_zcfac boolean

Fix zcfac for /MAT/LAW2 when using QEPH

---

starter/source/materials/mat/mat088/hm_read_mat88.F

with ou strain rate we should use standart formulation corresponding to hys >0 .  We ovoid numerical chane 
Use Hys > 0 as before, when we don't considerer the strain rate effect.

using standard damage formulation with out strain rate effect

---

engine/source/materials/mat/mat187/sigeps187.F

Use of uninitialized variable YLDP in /MAT/LAW187.
For this specific combination of input flags, YLDP must be replaced by DYDX. That is why YLDP was not initialized.

Fix uninitialized variable in /MAT/LAW187

---

engine/source/output/anim/generate/dfunc0.F
engine/source/output/anim/generate/dfunc6.F
engine/source/output/anim/generate/dfuncc.F
engine/source/output/anim/generate/genani.F
engine/source/output/anim/reader/anim_dcod_key_0.F
engine/source/output/h3d/h3d_results/h3d_quad_scalar_1.F90
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
engine/source/output/h3d/input_list/h3d_list_shell_scalar.F
hm_cfg_files/config/CFG/radioss2025/OUTPUTBLOCK/th_bric.cfg
hm_cfg_files/config/CFG/radioss2025/OUTPUTBLOCK/th_quad.cfg
hm_cfg_files/config/CFG/radioss2025/OUTPUTBLOCK/th_tria.cfg

Volumetric strain output is now compatible with ALE-multimaterial law (hexa, quad, tria)
example : /H3D/ELEM/VSTRAIN/3 or /ANIM/ELEM/VSTRAIN/3 will output volumetric strain for submaterial 3

VSTRAIN output for TRIA and ALE-multimaterial compatibility

---

engine/source/model/remesh/admdiv.F
engine/source/model/remesh/admfor0.F
engine/source/model/remesh/admregul.F
engine/source/model/remesh/admvit.F

Temperature distribution was wrong with adaptative mesh.
Corrected thermal flag declaration in arguments passed to remesh routines: they were declared as my_real instead of integer

Correction of thermal options problem with adaptative meshing

---

hm_cfg_files/config/CFG/radioss2025/MAT/mat_EOS.cfg
starter/source/materials/eos/hm_read_eos.F
starter/source/materials/eos/hm_read_eos_compaction2.F90

/EOS/COMPACTION2/[mat_ID]/**[eos_unit_ID]**
- The 'Fscale' parameter is the scale factor for the pressure function (user-defined function).
- It now has the correct dimension in the CFG file (_"pressure"_).
- Furthermore, when the default value is set to 1, this value must be converted to the working unit system (_eos_unit_ID -> working unit_).

/EOS/COMPACTION2:Fscale default value is now consistent with unit system

---

engine/source/materials/fail/orthstrain/fail_orthstrain_c.F
engine/source/materials/fail/orthstrain/fail_orthstrain_s.F
engine/source/materials/mat_share/mmain.F90
engine/source/materials/mat_share/mulaw.F90
engine/source/materials/mat_share/mulawc.F90
engine/source/materials/mat_share/usermat_shell.F
engine/source/materials/mat_share/usermat_solid.F
starter/source/materials/fail/hm_read_fail.F
starter/source/materials/fail/orthstrain/hm_read_fail_orthstrain.F

Change modes name
There is a need to get a precise post processing of /FAIL/ORHTSTRAIN failure (per orthotropic direction). 
Add failure modes into new matparam data structure for /FAIL/ORTHSTRAIN and compute them into the engine.

Add failure modes output for ORTHSTRAIN

---

engine/CMake_Compilers/cmake_win64.txt
engine/CMake_Compilers/cmake_win64_ifort.txt
engine/CMake_Compilers/cmake_win64_sse3.txt

Win64 / Builds with MUMPS : flags are missing on specific compiled files

Win64 / Builds with MUMPS : flags are missing on specific compiled files

---

tools/th_to_csv/src/th_to_csv.c

F1/F2/F3 M1/M2/M3 are not valid for outpuType=102 ( RBODY) but, it is for sectionx (outpuType = 104)
No need to add MX/MY/MZ ,, it is already well handle

correction of impuse value derivation for section

---

common_source/eos/compaction.F90
common_source/eos/compaction2.F90
common_source/eos/eosexponential.F90
common_source/eos/eoslinear.F
common_source/eos/eospolyno.F
common_source/eos/gruneisen.F
common_source/eos/idealgas.F
common_source/eos/idealgas_vt.F
common_source/eos/jwl.F
common_source/eos/lszk.F
common_source/eos/murnaghan.F
common_source/eos/nasg.F
common_source/eos/noble_abel.F
common_source/eos/osborne.F
common_source/eos/powder_burn.F
common_source/eos/puff.F
common_source/eos/sesame.F
common_source/eos/stiffgas.F
common_source/eos/tabulated.F
common_source/eos/tillotson.F
common_source/modules/interfaces/cut-cell-buffer_mod.F
common_source/modules/mat_elem/elbufdef_mod.F90
common_source/qa/qa_out_mod.F
common_source/tools/set_operation/set_graph.cpp

Fixes typos in common_source/   
Note: some trailing whitespace was trimmed as well.
Found via `codespell -q 3 -S "./.git,./extlib" -L activ,addresse,adress,adresse,adresses,agrv,alph,als,ans,bloc,bord,branche,bu,candidat,candidats,childs,classe,clos,commun,connectes,connec,connecte,contrl,crach,crypted,daa,datas,defaut,detecte,determinee,differents,divde,dum,eddge,filles,fils,fixe,flagg,fonction,fonctions,fourty,fpr,fpt,fram,frequence,globaly,groupe,groupes,hashin,idel,imform,incluse,indx,initiales,inout,interm,invers,iself,ist,itens,ivalid,iverse,lamda,lamdas,lengt,limite,marge,mater,mot,mouvement,nam,nax,nd,nin,ninty,nodel,normale,normales,parametres,parm,penality,pinter,pointeur,polygone,pres,probleme,propt,renforce,reste,rige,rin,prset,remplace,rotat,runn,sav,secnd,secnds,serie,shft,s …

Fix typos in common_source

---

starter/source/materials/eos/hm_read_eos.F
starter/source/materials/eos/hm_read_eos_compaction.F90
starter/source/materials/eos/hm_read_eos_compaction2.F90
starter/source/materials/read_material_models.F

The compaction EoS (/EOS/COMPACTION & /EOS/COMPACTION2) enable modeling of unloading using user-defined parameter(s) (slope). This value is compared with the provided function. The unloading modulus must be greater than the slope of the curve; otherwise, the mathematical model lacks physical validity.
When situation is not exected an error message is now displayed . Here is an example of such messages :
> ERROR ID :     67
** ERROR IN EOS DEFINITION
DESCRIPTION :  
-- EOS ID        : 1
-- EOS TYPE      : /EOS/COMPACTION2
BMIN MUST BEGREATER THAN DERIVATIVE OF P(MU) AT 0.0
> ERROR ID :     67
** ERROR IN EOS DEFINITION
DESCRIPTION :  
-- EOS ID        : 1
-- EOS TYPE      : /EOS/COMPACTION2
BMAX MUST BEGREATER THAN DERIVATIVE OF P(MU) AT MUMAX
These new Starter checks are helping user to …

COMPACTION EOS : unload modulus check

---

common_source/tools/sort/myqsort_d.F90
starter/source/tools/curve/hm_read_table2_1.F
starter/source/tools/curve/simple_checksum.cpp
starter/source/tools/curve/simple_checksum_mod.F90

Starter routine of /TABLE1 uses a simple checksum routine to detect multiple type of input errors.
Previous version showed conflicts in several correctly defined models. The algorithm was changed, the new routine uses more stable crc32 algorithm.
To avoid C uint32_t data type to fortran integer conversion problems, the hash value is now defined as double precision.

Change checksum routine algorithm for input error detection in /TABLE/1

---

starter/source/coupling/rad2rad/r2r_prelec.F

Following commit d336d359e94f96bd5e8b83a523c77726c862667d, the Reader section in the R2R subroutine (r2r_prelec.F) must be updated accordingly. Otherwise, the ALE side of interface type 18 will not be read correctly, leading to an error message.

R2D : Reader update due to fix in CFG file

---

starter/source/loads/pblast/hm_read_pblast.F

The data structure may not be initilized to 0 depending and compiler or compiler options.
It must be initialized to 0 when retrieving node identifier (if defined) :
`NODE_ID = INT(OUTPUT_USER_PARAMS(5,K_BLAST))`  _hm_read_pblast.F : 1126_ 
Consequently if NODE_ID is not provided in the input NODE_ID is 0 as expected.

/LOAD/PBLAST : zeroing output data structure

---

engine/source/materials/mat/mat128/sigeps128c.F90
engine/source/materials/mat/mat128/sigeps128s.F90

possible floating point exception in hourglass striffness calculation
Corrected yield stress initialization with kinematic hardening and tabulated input using 1D function

Correct yield stress calculation in law128 for hourglass in case of kinematic hardening

---

engine/source/interfaces/int24/i24cor3.F
engine/source/interfaces/int24/i24dst3.F

In some special case of Pressfit, effective stiffness is too small in de-penetration phase which result out instability issue in the final Pressfit phase.
improve robustness  of Pressfit (Inacti=-1 of interface type24) for special cases

improve Pressfit with inacti=-1 of interface type24

---

engine/source/engine/radioss2.F
engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
starter/source/user_interface/uaccess.F

MDS crashing at the beginning of engine
Mds initialization routine must be called after engine input file is read. It uses input parameters which are not initialized otherwise.
Corrected h3d output of mds user variables in composite shells.

Correction of MDS initialization in Radioss engine

---

engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F
starter/source/loads/pblast/hm_read_pblast.F

The warning messages have been updated to clearly explain the situation and guide the user in updating their input file.
Example with Surface Burst model :
Example with Free Air model : 
Additionally, the array OUTPUT_USER_PARAMS in hm_read_pblast.F is initialized to 0 to prevent potential issues on the Windows platform

/LOAD/PBLAST : improving warning messages

---

starter/source/interfaces/interf1/stifint_icontrol.F90

correction to avoid buffer overflow in case using istif=-1,iedge=1 of interface type24

bug fixing for auto stiffness option of interface type24 +iedge=1

---

starter/source/materials/mat/mat163/law163_upd.F90
starter/source/materials/tools/table_slope.F

A bug is fixed in table_slope subroutine for case ndim=2
The slope calculation was incorrect.
/MAT/LAW163 is now calculating youngmax using table_slope subroutine for better readability and maintenance

/TABLE : slope calculation fixed

---

engine/source/assembly/damping.F
engine/source/assembly/damping_vref_sum6_rby.F90
engine/source/elements/sh3n/coque3n/c3bilan.F
engine/source/interfaces/int23/i23optcd.F

ARM porting on Armflang 24.04 : remove calls to vectorize.inc on non vectorizable loops

ARM porting on Armflang 24.04 : remove calls to vectorize.inc on non vectorizable loops

---

engine/source/engine/radioss2.F

some of the MDS variables used for h3d output were not correctly initialized in engine
Moved MDS table allocations before lectur() in resol2.F

Correct MDS variable allocation at the beginning of Radioss engine

---

starter/source/initial_conditions/detonation/detonation_times_printout.F90
starter/source/multifluid/multifluid_global_tdet.F

Following a2ec816587dc0d1f39e917e14c37d175b9ffaa9d the default detonation time when no detonator option is present in input file must be 0.

/DFS/DET : detault detonation time with mm-ale law 151

---

starter/source/interfaces/inter3d1/i25trivox1.F
starter/source/interfaces/inter3d1/i7trivox1.F

Sorting algorithm for interface /TYPE7 & /TYP25 was parrallelized thanks to omp directives.
The pair of candidates order was not deterministic and could change if several omp threads were used
Ensure a deterministic order

OMP parrallelization of i7trivox or i25trivox can lead to different domain decompositions

---

starter/source/fluid/mass-fluid_qd.F
starter/source/loads/bem/hm_read_bem.F
starter/source/starter/lectur.F

/BEM/DAA option: Lapack call was conditionned by MKL but can always be used :
Lapack on gfortran
Armpl on ARM64
MKL on Windows / Linux ifx

/BEM/DAA option: Lapack call was conditionned by MKL but can always be used 

---

engine/source/materials/mat_share/mulawc.F90

Division by zero in some materials depending on temperature but without defining initial and reference temp

Correct division by zero in materials when thermal parameters are not defined

---

engine/source/loads/pblast/pblast_2.F
starter/source/loads/pblast/hm_read_pblast.F

/LOAD/PBLAST is a loading option which model a blast wave hiting a structure. It depends on the angle of the structure. This angle must be updated in the specific cases of the Surface Burst model with Ishape=1 or 2 (spherical propagation).
This update is missing in commit : bfe0dd22269795d6db2856f399f74378ebf2de83

/LOAD/PBLAST:cosinus update for Ishape=1,2

---

engine/CMake_Compilers/cmake_linuxa64.txt
starter/CMake_Compilers/cmake_linuxa64.txt

This pull request updates compiler flags and library paths in Armflang configuration files, adding a consistent `-fveclib=none` flag.

Compatibility with Armflang 24.10.1, fix issue in Starter link

---

engine/source/materials/mat/mat002/m2cplr.F
engine/source/materials/mat/mat002/m2law.F
engine/source/materials/mat_share/mmain.F90
engine/source/materials/mat_share/mqviscb.F

Temperature influence on hardening in law2 was conditionned by strain rate dependency parameters.
After correction, strain rate and temperature dependency are independent.

Allow thermal dependency on hardening in law2 regardless of strain rate

---

engine/source/output/anim/generate/genani.F
engine/source/output/anim/generate/tensorc.F
engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
engine/source/output/sortie_main.F

Animation file output of strains  was not taking into account the real layer positon when offset was defined in the inout (IPOS > 0
The correction requests the call of layini routine in the anim output that was missing, while it was correct in h3D. It calculates the vertical position of each layer depending of composite shell configuration

Correct strain output in ANIM for the composite shells with layer position offset

---

reader/source/dyna2rad/_private/convertcards.cxx
reader/source/dyna2rad/_private/convertcontacts.cxx
reader/source/dyna2rad/_private/convertdampings.cxx
reader/source/dyna2rad/_private/convertmats.cxx
reader/source/dyna2rad/_private/convertprops.cxx
reader/source/dyna2rad/_private/convertsets.cxx
reader/source/dyna2rad/convertdampings.h
reader/source/solver_interface/source/cfg_reading/GlobalModelSdi.cpp

*MAT_S01 to *MAT_S08: set density to 1e-12 in /MAT/LAW108 and Imass=1, Area=1 in /PROP/TYPE23
*MAT_057, *MAT_083 : add conversion of Navie Stokes parameter Lambda in /PROP/SOLID
*CONTROL_TIMESTEP: new rule in case TSSFAC is defined and DT2MS=0
*HOURGLASS, *CONTROL_HOURGLASS : update conversion
*DAMPING_FREQUENCY_RANGE : read and convert to /DAMP/FREQUENCY_RANGE
implement conversion of *CONTACT_AUTOMATIC_ONE_WAY_SURFACE_TO_SURFACE_TIEBREAK
MAT_034 : issue in case FORM=14, no shear curve, G=0
D2R *MAT_034 FORM=14 w/o load curves
CONTACT_AUTOMATIC_ correct conversion of IPSTF and iedge in case SOFT=2
correction duplicated spring in seatbelts

update open_reader source code 

---

engine/source/materials/mat/mat042/sigeps42.F
engine/source/materials/mat/mat069/sigeps69.F

it's observed that when law42,62 w/ low Poisson ratio used (nu<0.49), the anti-buckling treatment isn't efficient with distortion control. 
remove anti-buckling treatment w/ low Poisson ratio for law42,69

remove anti-buckling treatment w/ small Poisson ratio for law42,69

---

engine/source/interfaces/int25/i25dst3_e2s.F
engine/source/interfaces/interf/check_surface_state.F
starter/source/interfaces/inter3d1/i24sti3.F
starter/source/interfaces/inter3d1/i25sti3.F
starter/source/interfaces/inter3d1/i25surfi.F
starter/source/interfaces/inter3d1/i7sti3.F
starter/source/interfaces/inter3d1/inint3.F
starter/source/interfaces/inter3d1/insol3.F
starter/source/interfaces/interf1/inintr.F
starter/source/interfaces/interf1/lecins.F
starter/source/interfaces/interf1/lecint.F
starter/source/starter/lectur.F

Taking into account elements defined in contact for defining activated surface for /SURF/PART and SURF/GRBRIC.
Desactivating error message when E2E solid is used with Idel
- tagging elements defined in Contact surface
- When searching element for segments check which one is in contact surface. If just 1 element surface is external and if both of them segment is internal

Erosion solid Inter25 : take into account elemets defined in surface

---

common_source/eos/compaction.F90
common_source/eos/eosmain.F
hm_cfg_files/config/CFG/radioss2026/MAT/mat_EOS.cfg
starter/source/materials/eos/hm_read_eos.F
starter/source/materials/eos/hm_read_eos_compaction.F90
starter/source/materials/eos/hm_read_eos_compaction_tab.F90
starter/source/materials/mat/mat133/hm_read_mat133.F90
starter/source/materials/mat/mat133/law133_upd.F90

The C_SOLID parameter can be automatically retrieved from the input function using the C_unload function at the point where rho = 'RHO_TMD'. It is then removed from input format to simplify user experience.
Additionally:
- The starter checks that the C_unload function is monotonic.
- /MAT/LAW133 computes bulk_mak at the maximum compaction density for all families of compaction EoS (COMPACTION, COMPACTION2, COMPACTION_TAB). Using the maximum shear modulus : G=G(RHO_TMD) or G=G( RHO0*(1+MU_MAX) )

/EOS/COMPACTION_TAB : automatic C_SOLID parameter

---

common_source/modules/cpp_python_funct.cpp
common_source/modules/cpp_python_funct.h
common_source/modules/python_mod.F90
engine/source/coupling/python/python_share_memory.F90
engine/source/engine/resol.F
engine/source/loads/general/python_call_funct_cload.F90
engine/source/tools/curve/python_register.F90
starter/source/tools/curve/hm_read_funct_python.F90

A special /FUNCT/PYTHON function can be defined, with the name sync. This function takes a dictionary context, which contains pointers to the nodal values, and element connectivity.

Share direct pointers with /FUNCT_PYTHON sync

---

common_source/modules/loads/pblast_mod.F90
engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F
starter/source/loads/pblast/hm_read_pblast.F

The /LOAD/PBLAST option is a loading method used to apply a time-dependent blast wave pressure on a Lagrangian surface.
The blast wave is generated using the Friedlander model, characterized by a decay parameter b:
The parameter b is calculated so that the resulting impulse matches the target value interpolated from input data:
However, in some cases, the target positive impulse may be too high to construct a realistic wave using the corresponding peak pressure and positive phase duration.
In such situations, a triangular wave shape is used as a fallback (b = 0.0) to maximize the impulse magnitude. This approach may result in large negative pressures. To address this, a warning is issued, and users are strongly encouraged to define a PMIN value to limit unphysical negative pressures. …

/LOAD/PBLAST : warning message Imodel=2

---

common_source/modules/mat_elem/eos_param_mod.F90
starter/source/materials/eos/hm_read_eos_powderburn.F90
starter/source/materials/mat/mat010/hm_read_mat10.F

The old format of /MAT/LAW10 includes an embedded Equation of State (EoS). In this case, the allocation of the EoS data structure must be handled directly within the material law.
The file hm_read_mat10.F was updated accordingly.
**This issue only occurs when using the old format of /MAT/LAW10. It has no effect when the new format is used.**

/MAT/LAW10 : eos buffer allocation with embedded eos

---

engine/source/system/arret.F

This pull request includes a small change to the `engine/source/system/arret.F` file. The change ensures that the output unit (`IOUT`) is closed properly when specific conditions are met, improving resource management.#### Description of the feature or the bug

close IOUT unit in case ARRET(2)

---

starter/source/model/sets/fill_igr.F

This pull request introduces enhancements to the `SUBROUTINE FILL_IGR` in the file `starter/source/model/sets/fill_igr.F`. The changes improve the handling of specific key patterns and refine the reading logic to better process lines starting with a `#` character. These modifications aim to increase the robustness and accuracy of the subroutine.
* Added support for the `/INIV/AXIS/Y/2` key pattern in the conditional checks, ensuring it is processed alongside `/INIV/AXIS/X/2` and `/INIV/AXIS/Z/2`.
* Introduced multiple `DO WHILE` loops to handle lines starting with `#` during the reading process. This ensures that such lines are skipped appropriately before processing the next meaningful line. These loops were added for various key patterns, including `/DT/NODA/CST/1`, `/DYREL/1`, …

group creation issue when referencing engine keywords with comments

---

engine/source/materials/mat/mat002/sigeps02c.F
engine/source/materials/mat_share/mulawc.F90

there were no temperature update in law2 for shells with /heat mat 
Deleted test on lagrangian model type in law2 for shells. Radioss shells are not compatibles wit ALE or EULER, JLAG flag was never initialized.

Correct wrong test of lagrangian formulation in law2 for shells

---

starter/source/elements/solid/solide20/s20init3.F
starter/source/elements/thickshell/solide16/s16init3.F

Corrected missing element temperature initialization in solid and thickshell elements when /heat/mat ot /initemp is absent

correct non initialized element temperature in 16 and 20 node solids …and thickshells

---

starter/source/materials/mat/mat070/hm_read_mat70.F

Correction of bug introduced in previous developpement, resulting in incorrect function translation into tables with multiple unloading functions are defined

Correct function treatment in law70 with multiple unloading curves

---

engine/source/materials/mat/mat024/conc24.F
starter/source/elements/solid/solide/sgrtails.F

total strain was twice the correct value in law24
Corrected total strain calcutation which was performed in both element routines and material law. The second calculation is deleted.

Correct the total strain calculation in law24

---

hm_cfg_files/config/CFG/radioss2025/MAT/Law128_hill_visc_plast.cfg

some solver names in law128 cfg file were wrong 
This pull request updates comments in the `Law128_hill_visc_plast.cfg` configuration file to improve clarity and consistency in naming conventions. The changes replace ambiguous terms with clearer ones.
Comment updates for improved clarity:
correction solver names in law128 cfg file

correction solver names in law128 cfg file

---

reader/source/dyna2rad/_private/convertrigids.cxx

correction of a potential issue when NODE_ID is empty in PART_INERTIA+ use of CONTRAINED_EXTRA_NODES
check validity of objects

correction of a potential issue when NODE_ID is empty in PART_INERTIA+ use of CONTRAINED_EXTRA_NODES

---

engine/source/engine/resol.F
engine/source/implicit/imp_solv.F
engine/source/input/lectur.F

when /IMPL/CHECK is defined to run implicit check, run was stopped due to MUMPS solver which isn't used by implicit check
correction to run /IMPL/CHECK w/o MUMPS

remove the limitation of MUMPS solver for /IMPL/CHECK

---

engine/source/loads/pblast/pblast_1.F
engine/source/loads/pblast/pblast_2.F
engine/source/loads/pblast/pblast_3.F

Resolved an issue where parallel execution using multiple threads could cause incorrect behavior when processing a single element. The problem was more likely to occur with more than one OpenMP thread active.

OpenMP fix for /LOAD/PBLAST option

---

starter/source/materials/mat/mat088/hm_read_mat88.F

Strain rate filtering flag and cutoff frequency was not written to stater output file

Add missing starter output in law88

---

starter/source/elements/spring/rinit3.F

time step compute has not been done for spring SPR_AXI (type25) in Starter, zero value in Starter out file
add time step compute in Starter for SPR_AXI

add missed time step compute of spring (SPR_AXI) in Starter

---

starter/source/elements/spring/rinit3.F

Starter might stop due to compatibility check between /PRELOAD/AXIAL and spring tyep23+mat 113
correction of wrong compatibility check

wrong compatibility check of /PRELOAD/AXIAL and spring type23 using mat113

---

engine/source/elements/beam/pbilan.F

M31 (M3) and M32 (M6) are switched for Node_1 and Node_2 of beams in /ANIM/BEAM/FORC
M31 (M3) and M32 (M6) are switched for Node_1 and Node_2 of beams in /ANIM/BEAM/FORC

/ANIM/BEAM/FORC: M31 (M3) and M32 (M6) are switched

---

engine/source/materials/mat/mat090/sigeps90.F

We can't get match better mat057 
Tcut it's reduced occording the  unloading when Hys and shape are used.

enhancement of unloading for Fail=0 when tcut is used

---

common_source/modules/constraints/rbe3_mod.F90
engine/source/constraints/general/rbe3/rbe3f.F
engine/source/constraints/general/rbe3/rbe3f_pen.F90
engine/source/constraints/general/rbe3/rbe3pen_init.F90
engine/source/output/restart/restart_rbe3pen.F90

Actual Rbe3 penalty formulation might not be free to rigid rotation in case of dependent node has only translation dofs (solid)  
improvement of penalty formulation of RBE3

improvement in RBE3 penalty method

---

engine/source/elements/sh3n/coque3n/c3forc3.F
engine/source/elements/sh3n/coquedk6/cdk6forc3.F
engine/source/elements/shell/coque/cforc3.F
engine/source/elements/shell/coquez/czforc3.F

strain rate was missing in Radioss output for under-integrated shells
saved strain rate in global element buffer which is available in output routines

Save global element strain rate of under-integrated shells to element buffer for output

---

engine/source/elements/sh3n/coque3n/c3forc3.F
engine/source/elements/sh3n/coquedk6/cdk6forc3.F
engine/source/elements/shell/coque/cforc3.F
engine/source/elements/shell/coquez/czforc3.F

This reverts commit a70eb1d40a829399bd736d7643a15507e012c8ed.

Revert "Save global element strain rate of under-integrated shells to element buffer for output"

---

engine/CMake_Compilers/legacy_fortran.cmake
engine/source/mpi/spmd_mod.F90
engine/source/mpi/spmd_pack.F90
engine/source/mpi/spmd_unpack.F90

This pull request introduces two new Fortran modules, `spmd_pack_mod` and `spmd_unpack_mod`, providing standardized interfaces and implementations for packing and unpacking MPI messages containing real, integer, and double precision data. These modules encapsulate MPI packing and unpacking operations, handle optional communicator arguments, and integrate error handling for robust parallel communication.
**New MPI packing and unpacking modules:**
* Added `spmd_pack_mod` module in `spmd_pack.F90`, implementing generic `spmd_pack` interface with procedures for packing real, integer, and double precision arrays using MPI routines and error handling.
* Added `spmd_unpack_mod` module in `spmd_unpack.F90`, implementing generic `spmd_unpack` interface with procedures for unpacking real, integer, …

add pack and unpack to spmd_mod

---

engine/source/engine/resol.F
engine/source/loads/general/python_call_funct_cload.F90

ACTIVE_NODE may not work in case of ALE, even if /FUNCT_PYTHON is not used by any ALE option
This is due to TIMFUN function that calls every functions, even when not needed.

/FUNCT_PYTHON bug fix with ACTIVE_NODE

---

starter/source/initial_conditions/detonation/detonation_times_printout.F90
starter/source/initial_conditions/detonation/eikonal_compute_adjacent.F90
starter/source/initial_conditions/detonation/eikonal_fast_marching_method.F90
starter/source/initial_conditions/detonation/eikonal_init_sorting.F90
starter/source/initial_conditions/detonation/eikonal_init_start_list_2d.F90

The Fast Marching Method (FMM), recently introduced in OpenRadioss to model detonation waves in heterogeneous media (e.g., obstacles, varying propagation velocities), is used with high-explosive material laws.
The iterative numerical process is executed on the Starter side to compute the arrival times of the detonation wave, which are then transferred to the Engine via the restart file (.rst). (See: https://github.com/OpenRadioss/OpenRadioss/pull/3585)
This update includes:
- domain decomposition (SPMD): The algorithm now guarantees consistent detonation arrival times regardless of the number of MPI domains specified.
- Starter listing file :  It now displays the correct element IDs when outputting detonation times for triangular meshes.
**Verification Test :** 
The case description is …

FAST MARCHING METHOD : Update (SPMD)

---

engine/source/elements/solid/solide/preload_solid_ini.F90

This pull request includes a small but important fix to the `preload_solid_ini` subroutine. The change initializes the variables `t_start` and `t_stop` to zero at the start of the subroutine to address potential warnings from GCC 15's `-maybe-uninitialized` flag.

GCC15 -maybe-uninitialized compatibility

---

common_source/modules/cpp_python_funct.cpp
common_source/sortie/plot_curve.F
engine/source/interfaces/generic/inter_box_creation.F

This pull request introduces several improvements and minor fixes across the C++ and Fortran codebases. The main changes address type consistency for function arguments, numerical stability in calculations, and code documentation for potential issues.
**Type consistency and compatibility:**
* Changed the argument types of `cpp_python_sample_function` from `my_real*` to `double*` in both the enabled and disabled Python code paths in `cpp_python_funct.cpp` to ensure consistency and avoid type mismatches. [[1]](diffhunk://#diff-8ee81975bf0e8025a7734ce71df8049246ed2119cc34a24144e2f9d289786b10L1349-R1349) [[2]](diffhunk://#diff-8ee81975bf0e8025a7734ce71df8049246ed2119cc34a24144e2f9d289786b10L1497-R1497)
**Numerical stability and bug fixes:**
* Added checks in `plot_curve.F` to prevent division …

/FUNCT_PYTHON in single precision: bug fix

---

engine/source/engine/radioss2.F

After tests on windows, it appears that python called from OpenMP (even with critical) is not safe

/FUNCT_PYTHON disable OpenMP at engine

---

engine/source/output/sta/stat_size.F

Corrected undefined element buffer access to FAIL substructure when NFAIL=0 in current element group.

Correct NAN bug when writing STA file in engine

---

engine/source/materials/mat/mat002/sigeps02c.F
engine/source/materials/mat/mat063/sigeps63c.F
engine/source/materials/mat/mat064/sigeps64c.F
engine/source/materials/mat/mat073/sigeps73c.F
engine/source/materials/mat_share/mulawc.F90

Added missing energy scaling factor defined in /heat/mat with law2
Correct element volume used in conjunction with total energy in laws 63,64,71,74 for temperature update

Correction of internal heat calculation in material laws 2,63,64,71,73

---

common_source/interf/intbuf_ini.F
common_source/modules/nodal_arrays.F90
common_source/modules/python_mod.F90
engine/source/elements/sph/spbuc3.F
engine/source/mpi/kinematic_conditions/spmd_exch_fr6.F
starter/source/restart/ddsplit/ddsplit.F
starter/source/restart/ddsplit/w_front.F
starter/source/restart/ddsplit/wrcommp.F
starter/source/starter/lectur.F

This pull request primarily addresses memory allocation robustness and fixes several data race issues in parallel regions, particularly involving OpenMP. It also removes or disables variables that were previously susceptible to concurrency bugs. Additionally, some minor code organization and initialization changes are included.
* Updated all array allocations in routines such as `INTBUF_INI`, `allocate_nodal_arrays`, and `SPMD_EXCH_FR6` to use `MAX(1, ...)` for the allocation size, preventing zero-sized allocations that could cause runtime errors. (`common_source/interf/intbuf_ini.F` [[1]](diffhunk://#diff-629b32eacf1c111b3002b254430a66579b9588332d69dc39c227dcb03b12ec36L815-R815) [[2]](diffhunk://#diff-629b32eacf1c111b3002b254430a66579b9588332d69dc39c227dcb03b12ec36L1472-R1472) …

starter: data races and checkbound issues

---

engine/source/elements/beam/fail_beam3.F

Test on temperature dependance in global beam failure models was based on  wrong element buffer level.
Inexistent layer variable was used instead of global buffer variable.
Possible engine failure due to not allocated memory access.

Correct test of temperature dependance in failure models for global beam elements

---

engine/source/elements/beam/mulaw_ib.F
engine/source/materials/mat/mat036/sigeps36pi.F
engine/source/materials/mat/mat044/sigeps44pi.F

For Beam 18 when the failure criterion is defined in material law，the number of integration point is not indicated
Add this message for law36 law44

Add the number of integration point indication for Beam 18 failure

---

engine/source/engine/node_spliting/detach_node.F90
engine/source/engine/resol.F

Minor changes:
enable print of the detached node list
enable /ANIM/VECT/* by calling ALLOCATE_OUTPUT_DATA function (that does the reallocation also)

node spliting; enable /ANIM/VECT*
