OpenRadioss/OpenRadioss

- engine/source/output/restart/rdresb.F
looping correctly over the fvbag in input file.
> fvmbag:multiple definition /DT/FVMBAG/2 (fix)

- engine/source/loads/general/pfluid/pfluid.F
- starter/source/loads/general/pfluid/hm_preread_pfluid.F
- starter/source/loads/general/pfluid/hm_read_pfluid.F
- NSIGN was incorrect when VEL was negative. It is now fixed.
- Explicit argument dimensions
- Obsolete operators Replaced
- comment translation
- identation
> /LOAD/PFLUID:clean + Fix loading orientation(V<0)

- HOWTO.md
Small typo in the documentation.
Corrected the typo
> Correct spelling mistake web side = website

- starter/source/initial_conditions/inigrav/inigrav_load.F
- remove NP=3 and NP=4 (number of point of current face) which is no longer needed
- NP (number of part) renamed NPART_IN_GROUP
> /INIGRAV:fix potential issue with NP variable

- engine/source/materials/mat/mat062/sigeps62.F
- engine/source/materials/mat/mat062/sigeps62c.F
- hm_cfg_files/config/CFG/radioss2022/MAT/matl62_visc_hyp.cfg
- starter/source/materials/mat/mat062/hm_read_mat62.F
The poisson's ratio is constant for all Mu_i and alpha_i parameters
use  poison's ratio for each  Mu_i and alpha_i parameters
> add nu_i parameters

- starter/source/materials/mat/mat003/hm_read_mat03.F
- starter/source/materials/mat/mat004/hm_read_mat04.F
- starter/source/materials/mat/mat010/hm_read_mat10.F
- starter/source/materials/mat/mat037/hm_read_mat37.F
- starter/source/materials/mat/mat049/hm_read_mat49.F
- starter/source/materials/mat/mat083/hm_read_law83.F
Reader subroutines for law 3,4,10,37,and 49 have now IS_ENCRYPTED boolean initialized to .FALSE.
> /MAT: initialize IS_ENCRYPTED & IS_AVAILABLE (laws 3,4,10,37,49)

- starter/source/materials/mat/mat090/hm_read_mat90.F
Fcut not depending on the work_unit_system
Fcut depending on the work_unit_system
> update fcut unity in material law 90

- engine/source/tools/seatbelts/material_flow.F
- engine/source/tools/seatbelts/update_slipring.F
- starter/source/starter/starter0.F
Fix of non initialized variables for 2D seatbelts + fix of NaN
> 2D seatbelt non initialised variables

- engine/source/output/sty/outp_c_t.F
Revert to keep old operator in the comment of `*.sty` files
> fix format for OUTP / sty files 

- engine/source/elements/solid/solide4_sfem/s4voln_m.F
Simple precision issue when using ITET4 = 3 flag with incremental large deformation
Copy volume value in double precision variable.
> Fix SP issue for ITET4=3 flag

- starter/source/model/submodel/lecsubmod.F
case of node defined in multiple submodes: possible segmentation violation.
(confusion between NUMNOD and NUMNUSR)
> submodel fix for dyna input

- engine/source/materials/mat/mat080/sigeps80.F
Correct the equation for the transformation of bainite during cooling. Must have considered the equilibrium fraction
change to take into account the equilibrium fraction for bainite as for pearlite.
> Law80 solid exe intel stops with error

- engine/source/output/sty/outp_c_t.F
Revert some changes made on comments of outp/sty files.
> fix for outp

- engine/source/elements/elbuf/alloc_elbuf_imp.F
Segfault error appears in implicit test due to two missing variables in the element buffer definition. 
Add the missing variables
> Fix implicit segfault error

- engine/CMake_Compilers/cmake_linuxa64.txt
- engine/CMake_Compilers/cmake_linuxa64_compilers.txt
- extlib/hm_reader/linuxa64/libapr-1.0.so
- extlib/hm_reader/linuxa64/libapr-1.so
- extlib/hm_reader/linuxa64/libhm_reader_linuxa64.so
- extlib/lapack-3.10.0/lib_linuxa64/liblapack.a
- extlib/lapack-3.10.0/lib_linuxa64/librefblas.a
- extlib/lapack-3.10.0/lib_linuxa64/libtmglib.a
- extlib/metis/linuxa64/libmetis_linuxa64.a
- starter/CMake_Compilers/cmake_linuxa64.txt
- starter/CMake_Compilers/cmake_linuxa64_compilers.txt
- starter/build_script.sh
Add OpenRadioss support for Arm compiler
library stack
cmake compiler scripts
> OpenRadioss support for ARM Compilers

- starter/source/airbag/hm_read_monvol_type2.F
Ouput of curve type for pressure was wrong in the 0.out file. 
Now corrected according to documentation
> correction of /MONVOL/PRES output

- starter/source/materials/mat/mat051/fill_buffer_51.F
- starter/source/materials/mat/mat051/hm_read_mat51.F
- starter/source/materials/mat/mat051/hm_read_mat51_iform11.F
- starter/source/materials/mat/mat051/ie_bound.F
- starter/source/materials/mat/mat051/lecm51__check_initial_state.F
- starter/source/materials/mat/mat051/m51init.F
- starter/source/materials/mat/mat051/nrf51ini.F
- starter/source/materials/mat_share/matini.F
subdirectory : ./starter/source/materials/mat/mat051
> /MAT/LAW51:comments translation

- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_strain.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_strain_shell_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_strain_solid_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_strain_tshell_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_stress.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_stress_beam_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_stress_shell_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_stress_solid_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971/TABLE/initial_stress_tshell_subobj.cfg
- hm_cfg_files/config/CFG/Keyword971_R12.0/data_hierarchy.cfg
- hm_cfg_files/config/CFG/radioss130/TABLE/inish3_strs_f_glob_sub.cfg
- hm_cfg_files/config/CFG/radioss130/TABLE/inishe_strs_f_glob_sub.cfg
*INITIAL_STRESS_SHELL : read and convert to /INISHE/STRS_F/GLOB or /INISH3/STRS_F/GLOB
Plugin new D2R *CFG files for *INITIAL_STRESS_SHELL dyna card conversion into Radioss
> plug new D2R CFG files for *INITIAL_STRESS_SHELL dyna card

- hm_cfg_files/config/CFG/radioss130/TABLE/inish3_strs_f_glob_sub.cfg
- hm_cfg_files/config/CFG/radioss130/TABLE/inishe_strs_f_glob_sub.cfg
Wrong nb of read lines in D2R cfg files /INISHE and INISH3
Correction of nb of lines read in *CFG files for /INISHE and /INISH3
> update of *CFG for /INISHE and /INISH3

- starter/source/constraints/general/merge/hm_read_merge.F
correction possible overflow with /GRAV + /RBODY +/MERGE/RBODY
a negative index was used in an array 
( a node was already taged for external forces work output)
> correction possible overflow with /GRAV + /RBODY +/MERGE/RBODY

- engine/share/includes/param_c.inc
- engine/source/elements/solid/solide10/s10forc3.F
- engine/source/elements/solid/solide4_sfem/s10sigp3.F
- engine/source/engine/resol.F
modifications after comments
correction (value not initialized)
modifs missed pull
last modif w/o pullrequest (no initial value)
potential mem error fixed
> T10+ICPRE(hyper-elastic laws, Ismstr=10)

- starter/source/properties/hm_preread_properties.F
- starter/source/stack/hm_read_stack.F
Error in memory allocation  PCOMPP composite properties 
Correction of memory allocation issue in Radioss starter when there  stacks  with different numbers of ply
> memory correction

- engine/source/materials/fail/orthstrain/fail_orthstrain_s.F
Simple precision issue on 8.1719 with intel compilation
Remove the forced reset of the stresses for solids.
> Fix SP issue with fail orthstrain

- engine/source/tools/seatbelts/update_slipring.F
- starter/source/materials/mat/mat119/hm_read_mat119.F
MAT119 : new variable per element is needed to trigger stress reactivation in sigeps119.F
> MAT119 : new variable for stress reactivation

- engine/source/materials/mat/mat037/sigeps37.F
- starter/source/materials/mat/mat037/hm_read_mat37.F
- starter/source/materials/mat/mat037/m37init.F
- Initial stress tensor correctly initizlied during Starter
- Stress tensor fixed when used as boundary material
- comments updated 
- code updates for better redability when PSH parameter is used (Pressure Shift)
possible change when Pressure Shift is disabled (PSH=+/-1e-20)
> /MAT/LAW37: initial stress tensor fixed + cleaning

- starter/source/elements/initia/hm_read_inistate_d00.F
- starter/source/elements/initia/lec_inistate.F
- starter/source/starter/lectur.F
wrong consistent flag value check if /INIBRI and Rad input using auto flag
correction of wrong checking
> Wrong Ismstr check when /INIBRI + Ismstr=-1 (auto)

- starter/source/elements/solid/solide/sgrtails.F
regression HEPH+law24 due to Ihkt auto
reset Ihkt=2 w/ Law24
> regression since Ihkt auto

- engine/source/materials/mat_share/mulaw.F
change rho to rho0 in ssp law109
change rho to rho0 in ssp law109
> change rho to rho0 in ssp law109

- engine/source/materials/fail/orthstrain/fail_orthstrain_s.F
Add some checkings to avoid any potential NaN issue and uninitialized table.
Add some checkings to avoid any potential NaN issue and uninitialized table.
> Add checkings to avoid potential NaN in ORTHSTRAIN for solids

- engine/source/elements/spring/r23l114def3.F
SEATBELT 2D : additional shear to stabilise seatbelt when crossing slipring
> 2D SEATBELT : shear stiffness for crossing of slipring

- engine/source/interfaces/interf/init_nodal_state.F
> Fix a variable declaration issue

- engine/source/materials/mat/mat080/sigeps80.F
LAW80 solid improvements
Improvements of the calculation of plasticity in global and local yield
change solving method to Newton and direct explicit method when local yield
> LAW80 solid improvements 

- engine/source/mpi/output/spmd_collect_seatbelt.F
- engine/source/mpi/seatbelts/spmd_exch_a_seatbelt.F
- engine/source/tools/seatbelts/kine_seatbelt_force.F
Fix of parithon issue for 2D seatblets
> 2D SEATBELT parithon issue

- starter/source/materials/ale/ale_euler_init.F
- starter/source/materials/ale/ale_set_convection_codes.F
- starter/source/materials/ale/read_ale_mat.F
- starter/source/materials/ale/read_euler_mat.F
- starter/source/materials/mat/mat051/fill_buffer_51_0.F
- starter/source/materials/read_material_models.F
- starter/source/materials/therm/hm_read_therm.F
+ Specific Subroutine Created
+ ALE treatment removed from Thermal subroutine
+ explicit array sizes
+ comments
> Material reader : cleaning ALE+THERM

- engine/CMake_Compilers/cmake_linuxa64.txt
Engine Optimization flags are missing for linuxa64 version
> optimization flag for Fortran / ARM

- starter/source/materials/ale/ale_euler_init.F
- starter/source/materials/ale/ale_set_convection_codes.F
- starter/source/materials/ale/read_ale_mat.F
- starter/source/materials/ale/read_euler_mat.F
- starter/source/materials/mat/mat051/fill_buffer_51_0.F
- starter/source/materials/read_material_models.F
- starter/source/materials/therm/hm_read_therm.F
commit https://github.com/OpenRadioss/OpenRadioss/commit/bdca5e93b35dae5c21fea7249bb5b439ea80fe01 is now fixed. Argument ID is removed from subroutine READ_MATERIAL_MODELS when calling READ_ALE_MAT and READ_EULER_MAT. Random issue is no longer occuring. READ_MATERIALS_MODELS subroutine is now cleaned and all related ALE subroutines are moved to ./starter/source/materials/ale
> /ALE/MAT:cleaning 

- starter/source/tools/seatbelts/ini_seatbelt.F
2D SEATBELT : fix of compilation issue generated by previous PR
> 2D SEATBELT : compilation issue fix

- starter/source/materials/mat/mat051/fill_buffer_51_0.F
max bound is IADBUF+NPAR**-1** and not IADBUF+NPAR
it affects only program behavior when running with check bounds runtime tool
> LAW51/iform_12:UPARAM bound updated

- engine/source/elements/sh3n/coque3n/c3dt3.F
modif after test of  Dima on the industry model
nodal time step +law58+sh3n
> modif in nodal time step taking into account sound speed law58

- Apptainer/openradioss.def
- HOWTO.md
- INSTALL.md
This is documentation effort that describes how to build OpenRadioss container using Apptainer and its usage.
The documents provides the procedures for building OpenRadioss container using Apptainer and the procedures for running OpenRadioss container using Apptainer.
> How to build/run OpenRadioss container using Apptainer

- engine/source/output/sta/stat_s_eref.F
state output error in /INIBRI/EREF (number of node)
bug fixing
> bug fixing for /INIBRI/EREF+Itetra4=3

- common_source/modules/elbufdef_mod.F
- engine/source/elements/elbuf/alloc_elbuf_imp.F
- engine/source/elements/elbuf/allocbuf_auto.F
- engine/source/elements/elbuf/copy_elbuf_1.F
- engine/source/elements/elbuf/w_elbuf_str.F
- engine/source/elements/solid/solide/sforc3.F
- engine/source/materials/fail/tabulated/fail_tab2_c.F
- engine/source/materials/fail/tabulated/fail_tab2_s.F
- engine/source/materials/mat/mat072/sigeps72c.F
- engine/source/materials/mat/mat104/sigeps104c.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulawc.F
- engine/source/materials/mat_share/usermat_shell.F
- engine/source/materials/mat_share/usermat_solid.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_tab2.cfg
- hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
- starter/share/modules1/elbuftag_mod.F
- starter/source/devtools/hm_reader/hm_convert_fail_tab.F
- starter/source/elements/elbuf_init/allocbuf_auto.F
- starter/source/elements/elbuf_init/elbuf_ini.F
- starter/source/elements/elbuf_init/ini_mlaw_vars.F
- starter/source/elements/elbuf_init/init_mlaw_tag.F
- starter/source/elements/elbuf_init/initvars_auto.F
- starter/source/elements/elbuf_init/zerovars_auto.F
- starter/source/materials/fail/hm_read_fail.F
- starter/source/materials/fail/tabulated/hm_read_fail_tab2.F
- starter/source/materials/updmat.F
- starter/source/restart/ddsplit/w_elbuf_str.F
Implementation of a new version of the tabulated failure criterion /FAIL/TAB2
Implementation of a new version of the tabulated failure criterion /FAIL/TAB2
> Implementation of /FAIL/TAB2

- engine/source/output/sty/outp_s_s.F
run crash for output /OUTP/BRICK/USERS when Itetra4=1
fixing crash issue
> crash run w/ /OUTP/BRICK/USERS

- starter/source/coupling/rad2rad/r2r_split.F
- starter/source/coupling/rad2rad/r2r_void.F
- starter/source/starter/lectur.F
RAD2RAD : fix for stack and ply incompatibilty + clean of r2r_void
> RAD2RAD : stack ply fix

- starter/source/tools/seatbelts/create_seatbelt.F
SEATBELT 2D : fix of QA chkb issue
> 2D SEATBELT : fix of ISKN issue

- engine/source/elements/sh3n/coque3n/c3fint_reg.F
- engine/source/elements/sh3n/coque3n/c3forc3.F
- engine/source/elements/sh3n/coquedk/cdkfint_reg.F
- engine/source/elements/sh3n/coquedk/cdkforc3.F
- engine/source/elements/sh3n/coquedk6/cdk6fint_reg.F
- engine/source/elements/sh3n/coquedk6/cdk6forc3.F
- engine/source/elements/shell/coque/cfint_reg.F
- engine/source/elements/shell/coque/cforc3.F
- engine/source/elements/shell/coqueba/cbafint_reg.F
- engine/source/elements/shell/coqueba/cbaforc3.F
- engine/source/elements/shell/coquez/czforc3.F
- starter/source/elements/sh3n/coque3n/c3init3.F
- starter/source/elements/sh3n/coquedk/cdkinit3.F
- starter/source/elements/shell/coque/cinit3.F
- starter/source/elements/shell/coqueba/cbainit3.F
- starter/source/properties/shell/hm_read_prop01.F
- starter/source/properties/shell/hm_read_prop09.F
Some issues have been observed with non-local method used on shell elements during element deletions. 
Change the computation of the non-local absorbing forces using the initial thickness and area instead of current ones.
> Modify shell element deletion with non local regularization

- engine/source/engine/resol.F
correction problem checkpoint
correction problem checkpoint
> correction_chkpt_prob

- starter/source/output/th/hm_thgrki_vent.F
obvious change. 
Prevent N from being unexpected value in case of unexisting identifier.
> /TH/VENT:handling unexisting airbag_id

- engine/source/materials/mat/mat087/mat87c_swift_voce.F
/MAT/LAW87: improve the kinematic hardening with the swift-voce isotropic hardening
Correct the update of BS in the plastic projection
> LAW87 - KH - swiftVoce- improvements

- starter/source/materials/mat/mat087/hm_read_mat87.F
Add fisokin-chard in output
Add fisokin-chard in output
> Add fisokin-chard in output

- engine/source/output/h3d/h3d_results/h3d_skin_off.F
regression of /H3D/SHELL(SOLID)/PEXT (doesn't work)
regression issue fixed
> regression /H3D/SHELL(SOLID)/PEXT

- engine/source/elements/solid/solide/sderi3.F
- starter/source/interfaces/inter3d1/volint.F
Volint computation in Starter and sderi3 in Engine are found problematic for some test cases
> Volint computation in Starter and sderi3 in Engine are found problematic for some test cases

- hm_cfg_files/messages/CONFIG/msg_hw_radioss_reader.txt
in case bad format version there is reference in error message to /BEGIN even for dyna input
change error message in case bad format version
> change error message in case bad format version

- engine/source/elements/spring/r23l114def3.F
- engine/source/engine/resol.F
- engine/source/tools/seatbelts/material_flow.F
- engine/source/tools/seatbelts/update_slipring.F
2D SEATBELT fix : 
fix of SMP parithon issue -> some code is moved from r23l114def3.F to update_slipring.F
fix of a small bug with friction -> in material flow.F
> 2D seatbelt SMP PartihON fix

- engine/source/materials/mat/mat087/mat87c_tabulated_totalsr.F
Improve the plasticity calculation with kinematic hardening for tabulated input with total strain rate dependency
Correct the update of the backstress in the iterative plastic projection algorithm
> LAW87 - improvements - KH with tabulated input + SR  

- engine/source/materials/mat/mat087/mat87c_hansel.F
LAW87 - hansel and KH improvements -2
LAW87 - hansel and KH improvements - correct the Backstress update in iterative plastic projection
correct the Backstress update in iterative plastic projection
> LAW87 - hansel and KH improvements

- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_1d_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_1d_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_nodal_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_quad_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_quad_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_quad_vector_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_vector_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_skin_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_skin_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_skin_vector_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_solid_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_solid_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_solid_vector_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_sph_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_open_file.cpp
- engine/source/output/h3d/h3d_build_cpp/h3d_dl.c
Issue in H3D 
after refactoring system C layer calls had wrong size
> Issue in h3d C Layer strcat_s & strcpy_s & strncpy_s had wrong size

- engine/source/materials/mat/mat087/mat87c_tabulated_plas_sr.F
LAW87 - correction KH for tabulated with PL SR 
LAW87 - correction Kinematic hardening for tabulated with plastic SR dependency
correction Kinematic hardening for tabulated with plastic SR dependency
> LAW87 - correction KH for tabulated with PL SR

- starter/source/tools/curve/func_inters.F
bug correction  if function tables contained scale factors - problem in seatbelt materiall with unloading
multiply function values by scale factors
> bug in table intersection : scale factors were not taken into account

- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_nodal_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_solid_tensor_datatype.cpp
- engine/source/output/h3d/h3d_build_cpp/h3d_dl.c
After some changes related to OpenRadioss porting for Windows,
Some additional issues needed to be fixed.
> issue in h3d on Windows

- engine/source/elements/sh3n/coquedk/cncoef3.F
- starter/source/materials/mat/mat058/law58_upd.F
hourglass stiffness correction of QEPH in case law58 w/ curve stif input
improvement of QEPH+airbag unflating simulation
> QEPH hourglass stiffness correction for law58

- engine/source/interfaces/int25/i25dst3_22.F
- engine/source/interfaces/intsort/i25main_opt_tri.F
- engine/source/interfaces/intsort/i25optcd.F
- starter/source/interfaces/inter3d1/i25pwr3.F
- starter/source/interfaces/inter3d1/inint3.F
Correction of problem single precision of case Intel 
Improving detection of intersection when the tolerances are not precise : the solution already implemented in int24
> correction_sp_problem_intersection_detection_inter25

- engine/source/output/tools/sortie_c.c
Some issues have been raised with Windows changes in sortie_c.c
Those change will be reverted. The consequence is an increase of Warning statements during compilation.
> Revert changes in sortie_c.c to solve some issues

- engine/source/engine/resol.F
- engine/source/interfaces/int25/i25norm.F
possible missing initialization
+smp fix
> i25norm.F bug fix

- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_vector_datatype.cpp
/H3D/ELEM/VECT is not working after change in C layer
> H3D Vector issue

- starter/source/devtools/hm_reader/hm_get_floatv_without_uid.F
change API to get info from unitless card
modification hm_get_floatv_without_uid routine
> modification hm_get_floatv_without_uid routine

- engine/source/airbag/fv_up_switch.F
adding variable COUNT (integer) in PRIVATE omp declaration to prevent from any issue while computing time step when all polyhedra are merged (fv_up_switch.F)
> fvmbag:omp update in case of full merging

- engine/source/groups/alloc_surf_str.F
The title was written in *rst files, animation files, but not initialized.
> missing initializion of IGRSURF%TITLE

- engine/source/elements/solid/solide4_sfem/s4lagsfem.F
- engine/source/elements/solid/solide4_sfem/s4voln_m.F
difference between single/double precision with Itetra4=3
reduce the difference with Itetra4=3 on single/double precision
> small improvement of SFEM T4 single precision

- engine/source/interfaces/int25/i25dst3_22.F
resolve potential problem of pon
resolve potential problem of pon
> correction_initialisation_pon_problem

- hm_cfg_files/config/CFG/Keyword971_R12.0/data_hierarchy.cfg
For D2RAD conversion of *MAT_156 into MAT_MUSCLE, the CFG file needs to be updated to take into accout this conversion.
Update CFG for D2RAD conversion of *MAT_156
> update CFG for D2R converion of *MAT_156

- engine/source/materials/fail/inievo/fail_inievo_c.F
- engine/source/materials/fail/inievo/fail_inievo_s.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_inievo.cfg
- starter/source/materials/fail/inievo/hm_read_fail_inievo.F
A useless additional parameter was expected in the recently introduced INIEVO criterion (last week). 
Before the release of this option, it has been chosen to remove this parameter.
> Remove useless parameter from INIEVO input card INI_P2

- engine/source/interfaces/int25/i25cor3_e2s.F
- engine/source/interfaces/int25/i25cor3e.F
- engine/source/interfaces/int25/i25dst3_e2s.F
- engine/source/interfaces/int25/i25for3_e2s.F
- engine/source/interfaces/int25/i25mainf.F
- starter/source/interfaces/inter3d1/i25dst3_e2s.F
Correction of problem of self contact forming case and Intel case 
Correction of problem of self contact forming case and Intel case  : missing contacts
change of exclusions conditions ( remove someones, increase tolerance for others)
> correction_problem_self_contact_missing_contact_E2S

- engine/source/interfaces/int24/i24dst3.F
QA P/ON  issues after commit "fix potential issue in int24"
> fix P/ON issue cause by #687

- hm_cfg_files/config/CFG/Keyword971_R12.0/FREQUENCY/frequency_domain_acceleration_unit.cfg
- hm_cfg_files/config/CFG/Keyword971_R8.0/FREQUENCY/frequency_domain_acceleration_unit.cfg
- hm_cfg_files/config/CFG/Keyword971_R8.0/MAT/mat_248.cfg
- hm_cfg_files/config/CFG/radioss2018/INTER/inter_type11.cfg
some typo in cfg files
correction of the remaining typo
> correction typo of some cfg files

- engine/source/materials/fail/inievo/fail_inievo_c.F
- engine/source/materials/fail/inievo/fail_inievo_s.F
Some checkbounds issue and NaN were found in some new qa tests for /FAIL/INIEVO
Some value were divided by zero at first step and some tables did not have the correct dimension. These problems have been fixed for solids and shells.
> Fix checkbounds issues for INIEVO QA tests

- hm_cfg_files/config/CFG/Keyword971_R12.0/data_hierarchy.cfg
Conversion of Dyna *MAT_177 in Radioss /MAT/LAW62, needs an update of data_hierarcy.cfg, to take it into accout.
Update of data_hierarcy.cfg file to activate conversion of Dyna *MAT_177.
> Update data_hierarchy.cfg to allow for *MAT_177 conversion

- extlib/intelOneAPI_runtime/license/Compiler/third-party-programs.txt
- extlib/intelOneAPI_runtime/license/MKL/intel-simplified-license-software-october-2022.pdf
- extlib/intelOneAPI_runtime/license/MKL/third-party-programs-openmp.txt
- extlib/intelOneAPI_runtime/license/MKL/third-party-programs-safestring.txt
- extlib/intelOneAPI_runtime/license/MKL/third-party-programs.txt
- extlib/intelOneAPI_runtime/win64/libiomp5md.dll
- extlib/intelOneAPI_runtime/win64/mkl_intel_thread.2.dll
Add Intel OneAPI runtime libraries need for OpenRadioss releases.
Add copyright notices to be add in releases.
> Intel OneAPI runtime libraries & Copyright files for GitHub releases

- engine/source/time_step/dtnodarayl.F
P/ON (QA test 8.0) issue of last comment on /DAMP
P/ON issue fixed
> fix P/ON issue w/ last time step improving of /DAMP

- engine/source/tools/sensor/sensor_temp.F
- engine/source/tools/sensor/sensor_vel.F
- engine/source/tools/sensor/sensor_work.F
- starter/source/airbag/hm_read_monvol_type2.F
- starter/source/airbag/hm_read_monvol_type3.F
- starter/source/airbag/read_monvol.F
- starter/source/tools/sensor/read_sensor_work.F
bug correction
correct forcheck issues in sensor routines
> New sensor data structure : correct forcheck issues

- INSTALL.md
Add information regarding Intel runtime for Windows.
Releases & Native builds
> Install.md documentation for Windows : Add Runtime information for releases

- engine/source/materials/mat/mat025/sigeps25cp.F
Forcheck issue was found on an inconsistent number of argument
Add the missing TSAIWU argument.
> Fix forcheck issue for TSAIWU output

- engine/source/ams/sms_fixvel.F
bug correction
checkbound correction for fixvel using sensors in ams
> checkbound correction for fixvel using sensors in ams

- starter/source/tools/sensor/iniparsen.F
- starter/source/tools/sensor/read_sensor_gauge.F
- starter/source/tools/sensor/read_sensor_work.F
bug corrections
simple bugs in table allocation length, non initialized variable and incorrect parameter index
> correct bugs in sensor starter routines

- engine/source/interfaces/int21/i21therm.F
Make /THERMAL compatible with /INTER/TYPE21
Use the thermal scale factor for flux computing
> thermal_acceleration_intertype21

- engine/source/elements/solid/solide4_sfem/s10volnodt3.F
might get diverging result when using T10 + Ismstr=10 and Icpre=1 (SFEM)
bug fixing
> debug T10 +SFEM in single precision

- common_source/comm/memory_use_c.c
- engine/CMake_Compilers/cmake_linux64_intel.txt
- engine/CMake_Compilers/cmake_linux64_intel_compilers.txt
- engine/source/coupling/rad2rad/sys_pipes_c.c
- starter/CMake_Compilers/cmake_linux64_intel.txt
- starter/CMake_Compilers/cmake_linux64_intel_compilers.txt
- starter/source/system/get_ibuiltin_arch.c
Intel OneAPI build tested against Rocky Linux 9
> Intel OneAPI build tested against Rocky Linux 9

- engine/source/output/h3d/h3d_results/genh3d.F
- engine/source/output/h3d/h3d_results/h3d_nodal_vector.F
- engine/source/output/h3d/input_list/h3d_list_noda_vector.F
- engine/source/output/sortie_main.F
new h3d nodal vector output: rotational acceleration
creation of new h3d nodal vector output: rotational acceleration
> new h3d nodal vector output: rotational acceleration

- Apptainer/openradioss_intel.def
Definition file for Intel oneAPI build of OpenRadioss Apptainer container
This PR depends on #759.
> Definition file for Intel oneAPI build of OpenRadioss

- Apptainer/oneAPI.repo
This is supplementary material for #762.
This file is required to be #762 works.
> Supplementary material for Intel oneAPI build of OpenRadioss

- starter/source/tools/sensor/write_sensor_tab.F
correct /sensor/dist bug in spmd
local node number must be written in sensor structure for each proc (restart file)
> correct local node numbering in /sensor/dist

- engine/source/mpi/fluid/spmd_cfd.F
> spmd_cfd.F:comments_translation

- tools/anim_to_vtk/README.md
- tools/anim_to_vtk/src/anim_to_vtk.cpp
- tools/anim_to_vtk/win64/build.bat
- tools/th_to_csv/README.md
- tools/th_to_csv/src/th_to_csv.c
- tools/th_to_csv/win64/build.bat
build script + code change to be able to compile anim_to_vtk + th_to_csk on Windows.
> Porting th_to_csv & anim_to_vtk for windows

- engine/source/tools/sensor/sensor_contact.F
/sensor/inter : output message about sensor desactivation was repeated each cycle
recode the check of sensor activation / desactivation status.
> correct code and activation output message for /sensor/inter

- engine/source/materials/fail/syazwan/fail_syazwan_c.F
- engine/source/materials/mat_share/mulawc.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_syazwan.cfg
- starter/source/materials/fail/hm_read_fail.F
- starter/source/materials/fail/nlocal_init_sta.F
- starter/source/materials/fail/syazwan/hm_read_fail_syazwan.F
- starter/source/materials/mat_share/cnloc_matini.F
/FAIL/SYAZWAN is one of the first external contribution to OpenRadioss. It needed to be clarified and reviewed to be supported. 
Reviewing the code and make some modifications/improvements.
> Reviewing of /FAIL/SYAZWAN

- engine/source/materials/mat_share/usermat_shell.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_syazwan.cfg
Fix forcheck issue after /FAIL/SYAZWAN submission + fix a wrong format in .cfg file. 
Fix forcheck issue after /FAIL/SYAZWAN submission + fix a wrong format in .cfg file.
> Fix forcheck + input format in .cfg file for /FAIL/SYAZWAN

- engine/source/output/h3d/h3d_results/genh3d.F
- engine/source/output/h3d/h3d_results/h3d_nodal_scalar.F
- engine/source/output/h3d/h3d_results/h3d_nodal_tensor.F
- engine/source/output/h3d/h3d_results/h3d_nodal_vector.F
h3d nodal output per part was missing
enable h3d nodal output per part
> enable h3d nodal output per part

- engine/source/interfaces/int21/i21therm.F
small correction in multiplication operation
> correction_thermal_option_inter21

- engine/source/interfaces/int25/i25therm.F
correction problem of thermal exchange inter type 25 and make it compatible with option /THERMAL
correction problem of thermal exchange inter type 25 and make it compatible with option /THERMAL
> correction_thermal_exchange_solids

- engine/source/interfaces/int25/i25for3e.F
- engine/source/mpi/interfaces/spmd_i25front.F
- starter/source/restart/ddsplit/w_fi.F
Correction of problem of hanging of a Qa test
Correction of some bugs : tabs used without being allocated, problem of copy/paste, problem in case of rupture segment id can be negatif
> debug_inter25_testQa_hanging

- engine/source/materials/mat/mat088/sigeps88.F
- starter/source/materials/mat/mat088/law88_upd.F
model with unloading option TENSION=-2 fails after cycle 1
Fix the issue  and change de formulation to improve the behavior.
> Fix NaN in law88 with itens=2

- engine/source/elements/spring/r23l114def3.F
- engine/source/tools/seatbelts/redef_seatbelt.F
- starter/source/tools/seatbelts/create_seatbelt.F
2D seatbelts : improvement of NL formulation for springs
> 2D seatbelts : new NL formulation for springs

- starter/source/tools/sensor/hm_read_sensors.F
- starter/source/tools/sensor/read_sensor_acc.F
- starter/source/tools/sensor/read_sensor_and.F
- starter/source/tools/sensor/read_sensor_contact.F
- starter/source/tools/sensor/read_sensor_disp.F
- starter/source/tools/sensor/read_sensor_dist_surf.F
- starter/source/tools/sensor/read_sensor_energy.F
- starter/source/tools/sensor/read_sensor_gauge.F
- starter/source/tools/sensor/read_sensor_hic.F
- starter/source/tools/sensor/read_sensor_not.F
- starter/source/tools/sensor/read_sensor_or.F
- starter/source/tools/sensor/read_sensor_rbody.F
- starter/source/tools/sensor/read_sensor_rwall.F
- starter/source/tools/sensor/read_sensor_sect.F
- starter/source/tools/sensor/read_sensor_sens.F
- starter/source/tools/sensor/read_sensor_temp.F
- starter/source/tools/sensor/read_sensor_time.F
- starter/source/tools/sensor/read_sensor_vel.F
- starter/source/tools/sensor/read_sensor_work.F
clean old sensor tables from sensor reading routines
no change
delete old sensor tables from sensor reading routines in starter
> clean old sensor tables from sensor reading routines

- engine/source/user_interface/usensor.F
Wrong Arguments in routine call - leads to use uninitialzed variable
> Wrong Arguments in routine call

- starter/source/materials/mat/mat024/hm_read_mat24.F
law24 add ottosen parameters in output file 
add 4 parameters in output file starter
> law24 add ottosen parameters in output file

- engine/source/engine/resol.F
- engine/source/tools/sensor/sensor_base.F
- engine/source/tools/sensor/sensor_time.F
no change
code clean after introducing new sensor structure. sensor1() routine becomes sensor_base() with parallel loop inside.
Sensor TIME is put in a separate routine like all other sensors
> modify routine sensor1 -> sensor_base with parallel loop inside

- engine/source/materials/fail/puck/fail_puck_c.F
- engine/source/materials/fail/puck/fail_puck_s.F
- engine/source/materials/mat_share/mulawc.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_puck.cfg
- starter/source/materials/fail/puck/hm_read_fail_puck.F
/FAIL/PUCK was presenting some parasite element deletion due to stress wave. 
Add a stress filtering like in /FAIL/COCKCROFT to limit the stress wave effect.
> Add stress tensor filtering in /FAIL/PUCK

- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_syazwan.cfg
In .cfg file of /FAIL/SYAZWAN, a function ID was defined as an integer
Change type from integer to function.
> Fix .cfg file for /FAIL/SYAZWAN

- engine/CMake_Compilers/cmake_linux64_intel.txt
- engine/CMake_Compilers/cmake_win64.txt
Compilation was failing because special flags C_BASIC were not used with debug=1
> compilation with -debug=1 for with OneAPI

- hm_cfg_files/config/CFG/radioss2022/SENSOR/sensor.cfg
The add of New type 19 NIC_NIJ was in conflict with previous type 18 
the type19 implementation is modified to be in sync with TYPE18 and also all the older Format are added again with correct type handling (a lot was removed)
> sensor fix new type 19 NIC_NIJ errasing type 18

- engine/source/materials/fail/puck/fail_puck_c.F
- engine/source/materials/mat_share/usermat_shell.F
Fix forcheck issue for /FAIL/PUCK recent modification
Fix forcheck issue for /FAIL/PUCK recent modification
> Fix forcheck issue /FAIL/PUCK

- Apptainer/openradioss_arm.def
- engine/CMake_Compilers/cmake_linuxa64.txt
- engine/CMake_Compilers/cmake_linuxa64_compilers.txt
- starter/CMake_Compilers/cmake_linuxa64.txt
- starter/CMake_Compilers/cmake_linuxa64_compilers.txt
Arm Compiler for Linux build of OpenRadioss and its Apptainer definition file.
BIG Thank you for Lucas Pettey at Arm and Phil Ridley at Arm for your generous support!
> Arm Compiler for Linux build and its Apptainer definition file

- hm_cfg_files/config/CFG/radioss2022/INTER/inter_type8.cfg
can remove the last blank line in the input inter type8
can remove the last blank line in the input  inter type8
> inter_type8_input_change

- starter/source/elements/shell/coque/cgrtails.F
- starter/source/elements/solid/solide/sgrtails.F
Some QA tests results depends on the internal number of the elements. 
Do not try to reduce bandwidth when QAPRINT is ON, or when ADMESH is used
> Do not renumber solids and shells for QA PRINT and ADMESH

- starter/source/interfaces/inter3d1/i2_dtn_27.F
Out-of-bound memory usage of BID3
BID was of size=3, but used as size=4 when passed to i2loceq.F
> array BID3 dimension fix

- starter/CMake_Compilers/cmake_linux64_gf.txt
- starter/CMake_Compilers/cmake_linux64_intel.txt
- starter/source/loads/laser/leclas.F
- starter/source/restart/ddsplit/ddsplit.F
- starter/source/spmd/domdec2.F
- starter/source/starter/lectur.F
- starter/source/starter/starter0.F
- starter/source/system/c_hash_table.cpp
All allocatable arrays *must* be allocated when passed as dummy argument. 
Allocate arrays
> Unallocated array passed as argument 

- engine/source/elements/spring/r23l114def3.F
Fix issue identified for seatbelts with NL material
> 2D seatbelt NL fix

- tools/anim_to_vtk/src/anim_to_vtk.cpp
Add pointer initialization to two variables.
Some compilers may complain about these non-initialized pointers.
pointer initialization was missing for these two variables, simply add it.
> Add pointer initialization to two variables

- starter/source/interfaces/int25/i25remlin.F
Correction bug starter
Correction bug starter
> Correction_problems_inter25

- engine/source/interfaces/interf/i2for27p_pen.F
Unallocated array IN was used
Not using IN in `i2for27_pen.F` if `IRODDL == 0`
> type 2 interface bug fix

- starter/source/properties/beam/hm_read_prop18.F
write L2 when used in prop18
write L2 when used in prop18 - add dependency to isect
> write L2 when used in prop18

- engine/source/materials/fail/inievo/fail_inievo_c.F
- engine/source/materials/fail/inievo/fail_inievo_s.F
Validation report has shown some differences between RADIOSS and competitors results
Differences has been found for ALPHA variable computation. This formula has been modified.
> Fix validation issue on /FAIL/INIEVO

- engine/source/output/th/thpout.F
AREA was not initialized in GBUF%AREA
correct area initialization for TH BEAM using geo
> correct area initialization for TH BEAM

- starter/source/constraints/general/bcs/lecbcscyc.F
Wrong automatic searching node pair in /BCS/CYCLIC
the sorting algorithm has been improved to find right node pair.
> improve sorting algorithm in bcs_cyclic

- engine/source/tools/sensor/sensor_dist.F
- starter/source/spmd/domdec2.F
- starter/source/tools/sensor/write_sensor_tab.F
bug correction of two sensors : /dist and /dist_surf
/sensor/dist : correction of activation/deactivation rule
/sensor/dist/surf : bad sensor type resulting in skipping of special treatment to change global node number to local
> correction of sensors /dist and /dist_surf

- engine/source/engine/execargcheck.F
Typo in the message of the engine help
> Correct typo in Engine

- common_source/modules/ebcs_mod.F
- engine/CMake_Compilers/cmake_linux64_intel.txt
- starter/CMake_Compilers/cmake_linux64_intel.txt
- Review of compiler options for some C files
- (workaround) Remove unnecessary deallocation in `ebcs_mod.F` seems to fix a compiler bug (hang) on QA 1.59
> OneAPI 2023 portability for Linux

- engine/source/materials/fail/inievo/fail_inievo_c.F
- engine/source/materials/fail/inievo/fail_inievo_s.F
Some small issues has been found after a new validation of /FAIL/INIEVO
Fix the issues reported: principal deviatoric stress computation.
> Fix validation report 2 issues for /FAIL/INIEVO

- engine/source/materials/mat/mat036/sigeps36.F
- engine/source/materials/mat/mat036/sigeps36c.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulaw8.F
- engine/source/materials/mat_share/mulawc.F
- starter/source/materials/mat/mat036/hm_read_mat36.F
Add a specific damage variable output for failure option available in /MAT/LAW36 card.
Use the DMG damage variable to add the new output.
> Add damage output for /MAT/LAW36

- engine/CMakeLists.txt
- engine/CMake_Compilers/cmake_linux64_gf12.txt
- engine/CMake_Compilers/cmake_linux64_gf12_compilers.txt
- starter/CMakeLists.txt
- starter/CMake_Compilers/cmake_linux64_gf12.txt
- starter/CMake_Compilers/cmake_linux64_gf12_compilers.txt
- starter/CMake_Compilers/platforms.txt
Compilation with GCC12 is available using `arch=linux64_gf12`
> initial support for GCC12

- engine/source/elements/solid/solide8e/s8ederi3.F
Nan result (drop test) with deleted  w/ Isolid=18 element
fixing volume value for deleted element to avoid Nan result
> avoid Nan w/ deleted element

- engine/source/output/tools/ieee.cpp
- starter/source/output/tools/ieee.cpp
- starter/source/spmd/domdec2.F
Fix #973 
Rename SCEP into LEN_CEP (dummy argument had the same name as a common variable)
> Rename variable SCEP

- hm_cfg_files/config/CFG/Keyword971_R12.0/data_hierarchy.cfg
Ignore Dyna card *CONTROL_ALE in D2R conversion
In D2R conversion, *CONTROL_ALE card is ignored.
> Ignore Dyna card *CONTROL_ALE

- engine/source/elements/beam/pdlen3.F
- starter/source/elements/beam/dt1lawp.F
- starter/source/elements/beam/pmass.F
QA test 8.91 failed (energy error) w/ new time step of beam
refining time step compute for special case (test QA 8.91) to avoid instability
> beam time step correction after QA test 8.91

- engine/source/output/th/thpout.F
global plastic strain for type 3 is zero 
add global plastic strain for type 3 in thpout
> add plastic strain for type3 beam

- engine/source/elements/beam/pdlen3.F
- engine/source/elements/beam/pforc3.F
- engine/source/elements/forint.F
regression of beam time step change found 
regression fixed.
> regression of last time step change for beam

- engine/source/materials/mat_share/mmain.F
different result depending on ismstr for /MAT/ELAST
change the calculation of amu to be coherent with the thermal strain calculation
> thermal expansion correct amu for ismstr=4

- starter/source/interfaces/inter3d1/i25pen3.F
Correction problem forces at time 0 for Inacti=5
Correction penetration computation for coating shells ( same penetration starter/engine)
> /TYPE25 interface: debug inacti=5 forces at T=0

- hm_cfg_files/config/CFG/radioss2022/MAT/mat117.cfg
LAW117 - wrong unit conversion 
correct dimension of exponents MAT_EXP_G and MAT_EXP_BK
>  LAW117 - correct dimension of exponents

- engine/source/output/anim/generate/dfuncc.F
- engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
- engine/source/output/h3d/input_list/h3d_list_quad_scalar.F
Recently implemented TSAIWU criterion output was not available for QUAD element. 
Add TSAIWU output for QUAD elements.
> TSAIWU H3D and ANIM output for QUAD elements

- engine/source/output/th/thpout.F
epsp giving zero value due to wrong index
th beam epsp correct index
> /TH/BEAM/EPSP correct index

- engine/source/materials/mat/mat088/sigeps88.F
Core dump
Variable  not initialized correctly
> fix check bounds

- starter/source/restart/ddsplit/ddsplit.F
Line length limit issue in ddsplit.F
> Build fix for Intel compilers

- engine/source/mpi/interfaces/spmd_tri25vox.F
/INTER/TYPE25 may segfault when a domain do not receive any remote secondary node
> Possible segfault in /INTER/TYPE25

- engine/source/coupling/rad2rad/r2r_init.F
Fix of bug identified  in SPMD
> RAD2RAD + NLOCAL - SPMD fix

- engine/source/interfaces/int21/i21ass3.F
Correction regression Skid lines output
The nodes ids were not well computed.
RePutting the bloc of skid lines output after IXI computing
> correction bug Skidline output

- engine/source/engine/resol.F
Correction problem H3d file outputted even if it is not requested 
Correction problem H3d file outputted even if it is not requested
> Unrequested animation file written at last cycle

- starter/source/interfaces/interf1/trintfric.F
Correction debug gfortran special case /FRICTION when no set of parts is defined
Correction debug gfortran special case /FRICTION when no set of parts is defined
> /FRICTION model correction init when no set of part is defined

- engine/source/time_step/dtnodarayl.F
issue found :  Rayleigh damping +/dt/noda/cst at T=0,  added mass is still a little high
corrections at T=0 (dt1=0), and added mass improvement has been done
> modification rayleigh damping with /DT/NODA/CST 

- starter/source/coupling/rad2rad/r2r_prelec.F
Fix of rad2rad and ale/link in case master node is a rigid body
> RAD2RAD + ALE/LINK fix

- engine/source/materials/mat/mat066/sigeps66.F
- hm_cfg_files/config/CFG/radioss2022/MAT/mat_law66.cfg
- starter/source/materials/mat/mat066/hm_read_mat66.F
/MAT/LAW66: New feature- young modulus for compression
> /MAT/LAW66 add EC

- engine/source/user_interface/dyn_userlib_callback.c
- starter/source/user_interface/dyn_userlib_callback.c
Remove calls to deleted functions
> Compilation fix for windows

- engine/source/tools/sensor/sensor_energy.F
/SENSOR/ENERGY : constant energy criterion was not working
bug correction : activation time was not initialized correctly at time 0
> /SENSOR/ENERGY : correct bug with constant energy criterion

- common_source/eos/eosmain.F
- common_source/eos/tillotson.F
- engine/source/output/anim/generate/dfunc6.F
- engine/source/output/anim/generate/dfuncc.F
- engine/source/output/anim/generate/genani.F
- engine/source/output/anim/reader/anim_dcod_key_0.F
- engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
- engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
- engine/source/output/h3d/h3d_results/h3d_sph_scalar.F
- engine/source/output/h3d/input_list/h3d_list_quad_scalar.F
- engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
- engine/source/output/h3d/input_list/h3d_list_sph_scalar.F
- starter/source/materials/eos/hm_read_eos.F
- starter/source/materials/eos/hm_read_eos_tillotson.F
Region identifier in p,v diagram can now be output for post-treatment in H3D & ANIM files.
/ANIM/ELEM/TILLOTSON & /H3D/ELEM/TILLOTSON   (BRICK,QUAD,SPH)
1:compression
2:cold expansion
3:transition
4:hot expansion
> H3D/ANIM:New output, Tillotson EoS region identifier in p,v diagram

- starter/source/interfaces/int18/hm_read_inter_type18.F
- Starter output in listing file is improved for better readability (gap and stiffness)
- Unused local variables removed
- Buffer Storage ordered (FRIGAP,IPARI)
- some comments added
> /INTER/TYPE18:improving output in Starter listing file

- engine/source/elements/beam/pdamp3.F
- engine/source/elements/beam/pforc3.F
- engine/source/elements/beam/pmain3.F
- engine/source/materials/mat/mat001/m1lawp.F
- engine/source/materials/mat/mat002/m2lawp.F
- engine/source/materials/mat/mat044/sigeps44p.F
failing result of same models due to too high value used in damping of beam (w/ small beam length)
not realistic dimensioning in damping terms has been corrected.
> correction damping of beam

- starter/source/materials/mat/mat036/hm_read_mat36.F
correction of strain rate interpolation flag in starter output (wrong flag was written out)
small change only in starter output (flag change in WRITE )
> /MAT/LAW36 correct starter output flag of strain rate interpolation

- engine/source/elements/sh3n/coque3n/c3forc3.F
- engine/source/materials/mat_share/mulawc.F
- engine/source/materials/mat_share/mulawglc.F
- engine/source/materials/mat_share/rotos4.F
- engine/source/materials/mat_share/usermat_shell.F
Init. ZCFAC (c3forc3.F:256) and ETSE (mulawglc.F:149) to 0.0.
+comment translation
+subroutine split in independent files  (rotos4.F)
> C3FORC3:initialization to 0.0

- engine/source/materials/fail/tsaihill/fail_tsaihill_c.F
- engine/source/materials/fail/tsaihill/fail_tsaihill_s.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulawc.F
- engine/source/materials/mat_share/usermat_shell.F
- engine/source/materials/mat_share/usermat_solid.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_tsai_hill.cfg
- hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
- starter/source/materials/fail/hm_read_fail.F
- starter/source/materials/fail/tsaihill/hm_read_fail_tsaihill.F
- starter/source/materials/updmat.F
Fix cfg file + starter output
Needs to have the Tsai-Hill failure criterion in Radioss database. 
Implementation of /FAIL/TSAIHILL for solids and shells.
> Implementation of /FAIL/TSAIHILL for solids and shells

- engine/source/materials/fail/hoffman/fail_hoffman_c.F
- engine/source/materials/fail/hoffman/fail_hoffman_s.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulawc.F
- engine/source/materials/mat_share/usermat_shell.F
- engine/source/materials/mat_share/usermat_solid.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_hoffman.cfg
- hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
- starter/source/materials/fail/hm_read_fail.F
- starter/source/materials/fail/hoffman/hm_read_fail_hoffman.F
- starter/source/materials/updmat.F
Need to implement the composite materials failure model of Hoffman 
Implementation for solids and shells.
> Implementation of /FAIL/HOFFMAN for solids and shells

- engine/source/engine/radioss2.F
- engine/source/loads/pblast/pblast.F
- engine/source/loads/pblast/pblast_1.F
- engine/source/loads/pblast/pblast_2.F
- engine/source/loads/pblast/pblast_3.F
- hm_cfg_files/config/CFG/radioss2022/LOADS/pblast.cfg
- starter/source/loads/pblast/hm_read_pblast.F
- starter/source/starter/starter0.F
New parameter "Tstop" is introduced. It allows to stop loading on the structure when most of the blast impulse is transmitted and then gain cpu time
Default is Tstop=1e20
> /LOAD/PBLAST:new option Tstop

- engine/source/materials/fail/max_strain/fail_maxstrn_c.F
- engine/source/materials/fail/max_strain/fail_maxstrn_s.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulawc.F
- engine/source/materials/mat_share/usermat_shell.F
- engine/source/materials/mat_share/usermat_solid.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_max_strain.cfg
- hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
- starter/source/materials/fail/hm_read_fail.F
- starter/source/materials/fail/max_strain/hm_read_fail_maxstrn.F
- starter/source/materials/updmat.F
Need to implement a maximum strain failure criterion for composite materials failure
Implementation for shells and solids + fix a rebase overwritting incident with /FAIL/HOFFMAN integration
> Implementation of /FAIL/MAXSTRN for solids and shells

- engine/source/constraints/general/rbody/rbyonf.F
- engine/source/constraints/general/rbody/rbypid.F
Fix of activation and deactivation of elts inisde hierachical rbodies
-> rbyonf : additional call of rbypid for hierachical rbodies -> if elts activated but inside another rbodies that are still active they must be deactivated. A new flag PRI_OFF is sent to rbypid to deactivate printout.
-> rbypid : clean of comments in french + clean of printout in listing
> RBY with sensor and hierachy : fix of act/deactiv of elyt

- engine/source/output/anim/generate/dfunc0.F
- engine/source/output/anim/generate/genani.F
Tillotson region identifier is now available with SPH particles.
> SPH:compatibility with /ANIM/ELEM/TILLOTSON

- hm_cfg_files/config/CFG/radioss2022/INCLUDE_DYNA/includedyna.cfg
- hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
- starter/source/general_controls/engine/read_engine_driver.F
- starter/source/starter/lectur.F
- starter/source/starter/starter0.F
New option  /INCLUDE_DYNA to use an include file with Dyna format in a main model in Radioss format
New option with Format :
/INCLUDE_DYNA
include_file.k
possible to have several /INCLUDE_DYNA options in a Radioss main model
> new keyword /INCLUDE_DYNA to include dyna model in Radioss one

- hm_cfg_files/config/CFG/Keyword971/CONTROL_VOLUME/airbag_Particle.cfg
- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Activate *Airbag_particle option in data_hierarchy.cfg
Activate *Airbag_particle option in data_hierarchy.cfg and update of airbag_Particle.cfg file.
> Activate dyna *Airbag_Particle cfg in data_hierarchy

- engine/source/loads/general/pfluid/pfluid.F
- starter/source/loads/general/pfluid/hm_read_pfluid.F
Comments introduced to help external contributors by improving the readability of the source file. (some work is under investigation)
> /LOAD/PFLUID:comments added

- hm_cfg_files/config/CFG/radioss2022/RAD2R/subdomain.cfg
- starter/source/coupling/rad2rad/lecextlnk.F
- starter/source/coupling/rad2rad/r2r_group.F
- starter/source/coupling/rad2rad/r2r_prelec.F
- starter/source/starter/lectur.F
Fix of incompatibilites between rad2rad and several options 
-> /TRANSFORM
-> TYPE25
-> /DFS/DETPOINT
-> /SUBMODEL
Modification of subdomain cfg for compatibilty with subdomains
> RADRAD : fix for TYPE25 + TRANSFORM

- engine/source/output/tmax_ipart.F
different result with /H3D/NODA/GPS(GPSTRAIN)/TMAX in special case due to not initialized value
fixing not initialized values in special case
> avoid values not initialized in special case

- engine/source/interfaces/int17/i17for3.F
Important bug in Interface type 17 revealed by checkbound. The correction will change drastically the results. So to be checked.
Correction of bug checkbound : need to use for computing the contact area the parametric coordinate of the center computed by diving the area in small areas
> Inter17 correction problem checkbound

- starter/source/interfaces/inter3d1/i2cor3.F
Inter type2 output  Search distance in starter output file
Inter type2 output  Search distance in starter output file
> Inter type2 Search distance output in starter output file

- starter/source/devtools/hm_reader/hm_set_floatv.F
possible issue with set float function in _sp
cast to double precision
> possible issue with set float function in _sp

- engine/source/output/h3d/h3d_results/h3d_skin_scalar.F
- engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
new output H3D for failure model FLD
> new output /H3D/SOLID/FLDZ(FLDF)/OUTER_AVERAGE

- engine/source/input/freiniv.F
issue in engine when several /INIV cards
leads to some unexpected error messages :
MESSAGE ID :        189
** ERROR:  IS NOT A VALID KEYWORD
MESSAGE ID :         73
** ERROR IN SOLVER INPUT DECK CARD: INIV 
bad increment of line number
> issue in engine when several /INIV cards

- starter/source/interfaces/inter3d1/i2buc1.F
- starter/source/interfaces/inter3d1/i2cor3.F
- starter/source/interfaces/inter3d1/i2tri.F
Dsearch output Int2 : output only for couples retained
Dsearch output Int2 : output only for couples retained
> Improving Dsearch output Int2 : output only for couples retained

- starter/source/materials/mat/mat058/law58_upd.F
reference to wrong function in mat 58 error message
correction of the function that is referenced in law58 error message
> reference to wrong function in mat 58 error message

- engine/source/materials/mat/mat066/sigeps66.F
- engine/source/materials/mat/mat066/sigeps66c.F
take the tension young modulus for sound speed calculation instead of the variable one between tension and compression
> take the tension young modulus for sound speed calculation

- engine/source/materials/fail/max_strain/fail_maxstrain_c.F
- engine/source/materials/fail/max_strain/fail_maxstrain_s.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulawc.F
- engine/source/materials/mat_share/usermat_shell.F
- engine/source/materials/mat_share/usermat_solid.F
- hm_cfg_files/config/CFG/radioss2022/FAIL/fail_max_strain.cfg
- hm_cfg_files/config/CFG/radioss2022/data_hierarchy.cfg
- starter/source/materials/fail/hm_read_fail.F
- starter/source/materials/fail/max_strain/hm_read_fail_maxstrain.F
Recently implemented /FAIL/MAXSTRN has not a very good explicit name. 
Change /FAIL/MAXSTRN into /FAIL/MAXSTRAIN
> Change keyword /FAIL/MAXSTRN by /FAIL/MAXSTRAIN

- hm_cfg_files/config/CFG/radioss51/LOADS/cload.cfg
correction cload cfg file , possible issue 
correction cload cfg file
> correction cload cfg file

- starter/source/elements/initia/initia.F
- starter/source/elements/solid/solide/sinit3.F
- starter/source/elements/solid/solide/sjacidp.F
- starter/source/elements/solid/solide10/s10jaci3.F
- starter/source/elements/solid/solide4/s4init3.F
- starter/source/elements/solid/solide4/s4jaci3.F
- starter/source/elements/solid/solide8z/s8erefcoor3.F
- starter/source/elements/solid/solide8z/s8zinit3.F
different stresses found at T=0 of 2nd run with initial state (using Ismstr=10 or 12)  if compared with the output of state of 1er run.
corrections have been done to get consisting result using /INIBRI/EREF
> correction on /INIBRI/EREF in starter

- engine/source/system/tmpenv_c.c
Scratch file adjustments :
Radioss Engine tmp file should be written in TMPDIR in local directory instead. TMPDIR might be set to Wrong place. Ensure temp files are written in execution directory
> Radioss Engine temp file location

- engine/source/materials/mat/mat124/sigeps124.F
- engine/source/materials/mat_share/mulaw.F
- starter/source/materials/mat/mat124/hm_read_mat124.F
Initial element deletion method for recently implemented /MAT/LAW124 was to brittle in comparison with physical results
Change the erosion strategy and add the option to deactivate element deletion.
> Add new erosion strategy for /MAT/LAW124

- README.md
Updated link to latest Radioss online help (no longer a versioned link)
> Update link to Radioss online help in README.md

- hm_cfg_files/config/CFG/radioss2022/SENSOR/sensor_nic.cfg
comment correction in cfg file sensor_nic.cfg
sensor_nic.cfg comment was not well positioned
> comment correction in cfg file sensor_nic.cfg

- engine/share/modules/h3d_mod.F
- engine/source/output/h3d/h3d_build_cpp/c_h3d_create_shell_scalar_datatype.cpp
- engine/source/output/h3d/h3d_build_fortran/lech3d.F
- extlib/h3d/lib/linux64/libh3dwriter.so
H3D structure was not correctly initialized
The h3d library used pthread
Fix the initialization issue
Re-build the h3d library without pthread
> uninitialized variable in h3d structure

- INSTALL.md
Create Table of contents with browseable links
> INSTALL.md create Table of Contents

- starter/source/elements/initia/initia.F
Bug fix: IP2NG1(I) was used instead of IP2NG1(IP)
> correction in part/mat review

- engine/source/output/dynain/dynain_c_strag.F
revert previous PR - npg=4 for ishell=24
> revert previous PR - npg=4 for ishell=24

- engine/source/mpi/output/spmd_flush_accel.F
`/DEBUG/CHKSM` is now available with for the engine binary compiled without MPI.
> /DEBUG/CHKSM available in SMP

- engine/source/elements/sh3n/coque3n/therm3c.F
- engine/source/elements/sh3n/coquedk/cndt3.F
- engine/source/elements/shell/coqueba/cbatherm.F
- engine/source/materials/mat_share/thermc.F
Add compatibility Thermal acceleration for shells elements
Add compatibility Thermal acceleration for shells elements : add coefficient THEACCFACT  for thermal shell flux computation
> Add compatibility Thermal acceleration for shells elements

- engine/source/tools/sensor/sensor_and.F
- engine/source/tools/sensor/sensor_not.F
- engine/source/tools/sensor/sensor_or.F
- engine/source/tools/sensor/sensor_sens.F
/SENSOR/SENS has 3 states : ON : 1, OFF=0, DEAD = -1 (Dead means will never activates again)
Other Logical Sensors need to take care of the third state
> /SENSOR/SENS with other logical sensors

- engine/source/elements/elbuf/alloc_elbuf_imp.F
regression for implicit solution of PR ca0696e2e31ea7711229428c3d24e31e9b9cec23
Correction done
> implicit part forgotten in PR ca0696e2e31ea7711229428c3d24e31e9b9cec23

- .gitignore
.gitignore : Add new files & directories
Avoid Testsuite results be in Status
> .gitignore : Add new files & directories

- engine/source/materials/mat_share/cmain3.F
- starter/source/properties/composite_options/drape/shellthk_upd.F
The elapse time of shell test are increased.
Fix the elapse time issue by using dynamic allocation
> fix elapse time issue for  the test with shell

- engine/source/elements/sh3n/coque3n/c3bilan.F
- engine/source/elements/sh3n/coque3n/c3forc3.F
- engine/source/elements/sh3n/coquedk/cdkforc3.F
- engine/source/elements/sh3n/coquedk6/cdk6forc3.F
- engine/source/elements/shell/coque/cbilan.F
- engine/source/elements/shell/coque/cforc3.F
- engine/source/elements/shell/coque/csubc3.F
- engine/source/elements/shell/coqueba/cbaforc3.F
- engine/source/elements/shell/coquez/czforc3.F
- engine/source/elements/xfem/c3forc3_crk.F
- engine/source/elements/xfem/cforc3_crk.F
- engine/source/elements/xfem/czforc3_crk.F
- starter/source/elements/sh3n/coque3n/c3init3.F
- starter/source/elements/shell/coque/cinit3.F
- starter/source/elements/shell/coqueba/cbainit3.F
After a recent submission about shells and solids element energy balance and mass evolution with failure, some issues appeared with XFEM. 
Add a particular case when computing energy balance and mass evolution for shells XFEM element.
> Fix energy balance with XFEM elements

- engine/source/elements/beam/pdlen3.F
- starter/source/elements/beam/dt1lawp.F
- starter/source/elements/beam/pinit3.F
improving time step with beam type18
> improve time step of type18

- starter/source/materials/ale/ale_euler_init.F
- starter/source/model/assembling/hm_read_part.F
fix for e10890bc980a148c11e39fc4d84db9e45030caf6
Initialization of NVCONV integer and CODV array are done once all PARTS are read.
> EBCS:fix for allocation flags

- engine/source/elements/shell/coque/layini.F
- starter/source/elements/shell/coque/cinmas.F
- starter/source/restart/ddsplit/w_drape.F
Error on spmd 
Fix the spmd issue
> fix error message on impi for /DRAPE

- starter/source/starter/check_dynain.F
Correction of 6a69c66da736084854120c2ff7a3fa8a31ae1fd9 dynain check 
Correction previous commit dynain check : zip flag no need to be read in starter
> Correction previous commit dynain check 6a69c66da736084854120c2ff7a3fa8a31ae1fd9

- starter/source/materials/ale/ale_euler_init.F
Fix following changes from e10890bc980a148c11e39fc4d84db9e45030caf6
Related to material law 20 (obsolete)
> fix for mat law20

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
read and ignore *DATABASE_BINARY_D3DRLF
plug *DATABASE_BINARY_D3DRLF reading
> read and ignore *DATABASE_BINARY_D3DRLF

- hm_cfg_files/config/CFG/radioss2020/MAT/mat_law106.cfg
error in comments in mat106 cfg file
correction mat106 cfg file
> correction mat106 cfg file

- HOWTO.md
- INSTALL.md
1. Ubuntu may need additional python-is-python3 package
2. Link error in Howto.md
> Doc Change - Install.md & Howto.md

- engine/share/modules/drape_mod.F
- engine/source/elements/sh3n/coque3n/c3forc3.F
- engine/source/elements/sh3n/coque3n/c3ke3.F
- engine/source/elements/sh3n/coquedk/cdkforc3.F
- engine/source/elements/sh3n/coquedk/cncoef3.F
- engine/source/elements/sh3n/coquedk6/cdk6forc3.F
- engine/source/elements/shell/coque/cforc3.F
- engine/source/elements/shell/coque/layini.F
- engine/source/elements/shell/coqueba/cbaforc3.F
- engine/source/elements/shell/coqueba/cbake3.F
- engine/source/elements/shell/coqueba/cmatc3.F
- engine/source/elements/shell/coquez/czforc3.F
- engine/source/elements/shell/coquez/czke3.F
- engine/source/elements/shell/coquez/czkel3.F
- engine/source/elements/xfem/c3forc3_crk.F
- engine/source/elements/xfem/cforc3_crk.F
- engine/source/elements/xfem/czforc3_crk.F
- engine/source/implicit/imp_glob_k.F
- engine/source/materials/mat_share/cmain3.F
- engine/source/output/dynain/dynain_c_strag.F
- engine/source/output/dynain/dynain_c_strsg.F
- engine/source/output/sta/stat_c_strafg.F
- engine/source/output/sta/stat_c_strsfg.F
- engine/source/output/sty/c_tf_ne.F
- starter/source/elements/sh3n/coque3n/c3inmas.F
- starter/source/elements/shell/coque/cinmas.F
With /DRAPE in spmd :
SMP issue due to concurrent access of shared variable in Module. This can cause app crash
the bug is fixed in smp by passing the variable in the argument.
> fix smp issue with /DRAPE

- engine/source/elements/solid/solide8e/s8eforc3.F
- engine/source/elements/solid/solide8e/s8fupd11t12.F
- engine/source/elements/solid/solide8z/s8zforc3.F
fix missing argument in #1269 for solid 8
> missing dummy argument

- hm_cfg_files/config/CFG/radioss2023/data_hierarchy.cfg
- starter/source/starter/starter0.F
plug new input format 2023
enable input format 2023
> plug input format 2023

- starter/source/interfaces/inter3d1/i25norm3.F
Correction Problem Parithon and initial forces Inacti=5
Correction Problem Parithon and initial forces Inacti=5
VTX_BISECTOR tab have to be reset to zero each time ( the computation done 2 times IDDLEVEL)
> Correction Problem Parithon and initial forces Inacti=5

- starter/source/materials/mat/mat120/hm_read_mat120.F
LAW120 -missing initial yield in output
correct output message in starter by adding missing yield parameter
> LAW120 - correct output message in starter

- engine/source/ale/atherm.F
Regression introduced in #1314 
NEL was added twice in the call of M51TH.
> Argument mismatch in M51TH

- common_source/modules/ale/ale_connectivity_mod.F
- common_source/qa/qa_out_mod.F
- engine/share/modules/diffusion_mod.F
- engine/share/modules/linear_solver_mod.F
- engine/share/modules/segvar_mod.F
> module updates with upper cases

- engine/CMakeLists.txt
- starter/CMakeLists.txt
Sometimes this causes file creation failure on Windows.
> Issue In CMakefile build_info.inc build is doing twice

- engine/source/elements/solid/solide8e/s8eforc3.F
not expected change with Isolid=17 with PR 63549ea5068081c98df1a0df84f565aacaf7eb35, correction done to keep it as before.
> exclude Isolid=17 in change 63549ea5068081c98df1a0df84f565aacaf7eb35

- engine/source/elements/elbuf/allocbuf_auto.F
- engine/source/output/h3d/h3d_build_fortran/lech3d.F
- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
For /H3D/SHELL/USER  with /TYPE51 or /PROP/TYPE52 we get Not a number 
We need just to initialized and  the value and Tag the element if this user variable is not available of the material law.
> fix bug /h3d/shell/UVAR=ALL ... + /PROP/TYPE17,51 et 52

- starter/source/elements/thickshell/solide6c/s6cinit3.F
- starter/source/elements/thickshell/solide6c/s6fraca3.F
- starter/source/elements/thickshell/solide6c/s6mass3.F
make Imas in DEF_SOLID compatible with penta6 element
> make penta6 element compatible with Imas

- starter/source/elements/shell/coque/cinit3.F
/DRAPE : memory problem with shell's expect Batoz
Use the right argument.
> fix memory problem of shell with drape expect Batoz shell

- hm_cfg_files/config/CFG/radioss2023/FAIL/fail_hoffman.cfg
- hm_cfg_files/config/CFG/radioss2023/FAIL/fail_max_strain.cfg
- hm_cfg_files/config/CFG/radioss2023/FAIL/fail_tsai_hill.cfg
- hm_cfg_files/config/CFG/radioss2023/FAIL/fail_tsai_wu.cfg
Change the .cfg file format to 2023 for recently implemented /FAIL/TSAIWU, /FAIL/TSAIHILL, /FAIL/HOFFMAN and /FAIL/MAXSTRAIN + Create FAIL folder in radioss2023 .cfg file main folder. 
Change the .cfg file format to 2023 for recently implemented /FAIL/TSAIWU, /FAIL/TSAIHILL, /FAIL/HOFFMAN and /FAIL/MAXSTRAIN + Create FAIL folder in radioss2023 .cfg file main folder.
> Update format 2023 for Tsai-Wu, Tsai-Hill, Hoffman and Maxstrain

- engine/source/coupling/rad2rad/rad2rad_c.c
Fix of imcompatibility issue between rad2rad and impvel
> Rad2rad compatibility with impvel + tstop

- engine/source/output/dynain/dynain_shel_mp.F
- engine/source/output/dynain/dynain_shel_spmd.F
Correction for dynain output for orthotropic shells *ELEMENT_SHELL_THICKNESS_BETA keyword writting
Correction for dynain output for orthotropic shells *ELEMENT_SHELL_THICKNESS_BETA keyword writting 
missing _BETA (copy paste problem)
> Correction of Zipped dynain file for orthotropic shells

- hm_cfg_files/messages/CONFIG/msg_arrays.cfg
- hm_cfg_files/messages/CONFIG/msg_hw_radioss_reader.txt
- hm_cfg_files/messages/CONFIG/msg_table.cfg
some typo & other minot issues in cfg files
correction of issues found
> cfg files corrections

- engine/source/elements/beam/pforc3.F
- engine/source/interfaces/interf/intmass_update.F
- starter/source/restart/ddsplit/ddsplit.F
Regression introduced in #1324
> use of uninitialized variable

- engine/source/output/dynain/dynain_c_strag.F
- engine/source/output/dynain/dynain_c_strsg.F
The flag Large is not in the correct case for sh3n
The flag Large is not in the correct case for sh3n
> correction position Large flag for Sh3N

- starter/source/output/qaprint/st_qaprint_time_histories.F
Commit : bc63ffea6a38d814e4e758112526af9c12408017 introduced an issue in some check option  on Time History
> Issue in Starter Time History checks

- hm_cfg_files/config/CFG/radioss2023/PROP/prop_p20_tshell.cfg
- hm_cfg_files/config/CFG/radioss2023/PROP/prop_p21_tsh_orth.cfg
- hm_cfg_files/config/CFG/radioss2023/PROP/prop_p22_tsh_comp.cfg
- starter/source/properties/thickshell/hm_read_prop22.F
bug introduced in prop_type22 with 84a99ee51571788d2ab4bfecbf5557378e9e2db5
correction type error
> wrong type introduced in prop_type22 by 84a99ee51571788d2ab4bfecbf5557378e9e2db5

- engine/source/coupling/rad2rad/r2r_exchange.F
- engine/source/coupling/rad2rad/rad2rad_c.c
RAD2RAD : compatibility with IMPVEL - fix of regression in case of multiple input file
> RAD2RAD : compatibility with IMPVEL - fix for multiple input file

- hm_cfg_files/config/CFG/Keyword971/MAT/mat_105.cfg
- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Activate CFG file for Dyna *MAT_105 (MAT_DAMAGE_2) conversion
Correction and activation of dyna CFG file for conversion of *MAT_105 (MAT_DAMAGE_2)
> activate CFG file for Dyna *MAT_105 conversion

- starter/source/interfaces/inter3d1/i11sti3.F
Segmentation violation at Starter
Integer variable was passed when double precision was expected
> bug fix for type11 contact interface

- starter/source/interfaces/inter3d1/i24sti3.F
- starter/source/interfaces/inter3d1/i25sti3.F
- starter/source/interfaces/inter3d1/i7sti3.F
- starter/source/interfaces/inter3d1/insol3.F
Correction problem performance starter after commit 6cb04d3434d3d3bd0ee232888440124821676c5e
The allocate, initialization and deallocate in the subroutines insol3d was expensive as it is done for each segment
> Correction problem performance starter after commit 6cb04d3434d3d3bd0ee232888440124821676c5e

- engine/source/materials/mat/mat120/sigeps120_connect_dp.F
- engine/source/materials/mat/mat120/sigeps120_connect_tab_dp.F
- engine/source/materials/mat/mat120/sigeps120_connect_tab_vm.F
- engine/source/materials/mat/mat120/sigeps120_connect_vm.F
damage + bug correction
Modify the damage calculation with the dependency of triaxiality + bug correction
> LAW120- cohesive elements - correct damage

- engine/source/elements/solid/solidez/szhour3.F
- engine/source/elements/solid/solidez/szhour3_or.F
Possible Nan result of Isolid=24 + Icpre=2
adding condition to avoid memory issue
> potential memory issue (avoid to use not allocated array)

- engine/source/interfaces/int24/i24for3.F
worse results with single precision using interface type24 for some special cases
improvement of single precision result with interface type24
> improve single precision result w/ interface type24

- engine/source/elements/spring/r23l113def3.F
- engine/source/elements/spring/redef3_law113.F
- hm_cfg_files/config/CFG/radioss2023/MAT/mat113_spr_beam.cfg
- starter/source/materials/mat/mat113/hm_read_mat113.F
Not map Dyna Mat074
Adding scale damping function in order to map Dyna MAT074
> adding scale fonction to stiffness for spring 23 and law 113

- engine/source/elements/shell/coque/layini.F
Wrong behavior with IINT=2 for /PROP/TYPE51 & 52 with XFEM 
Fix bug to get similair result as IINT=1
> fix bug for /PROP/TYPE51 & 52 + XFEM for IIT=2

- engine/source/engine/resol.F
- engine/source/interfaces/interf/check_remote_surface_state.F
Some issues were introduced in PR #1414 
2 arguments were wrongs in resol.F
A mpi communication was buggy
> Shooting node algorithm : fix some issues for the interfaces 24 and 25

- hm_cfg_files/config/CFG/Keyword971/LOAD/load_node_force_rigid_body.cfg
- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
- hm_cfg_files/messages/CONFIG/msg_hw_radioss_reader.txt
Convert new Dyna option: *LOAD_RIGID_BODY
Activate CFG file for conversion of a new Dyna option: *LOAD_RIGID_BODY
> Activate CFG file for dyna *LOAD_RIGID_BODY option

- starter/source/elements/elbuf_init/elbuf_ini.F
add hourglass control for penta6 thickshell element
> add hourglass for penta6

- engine/source/elements/solid/solide8s/s8sforc3.F
remove /DT/BRICK/CST/1 for special hexa solid element (only used for implicit)
> remove /DT/BRICK/CST/1 for special hexa solid element

- engine/source/materials/fail/ladeveze/fail_ladeveze.F
The condition OFF(1) == ONE can be met at a wrong moment in the simulation creating some re-initialization of UVAR(I,12). 
Change OFF(1) == ONE to UVAR(1,1) == ONE which is safer.
> Fix initialization of some parameters for /FAIL/LAD_DAMA

- engine/source/elements/thickshell/solide6c/s6cforc3.F
- engine/source/elements/thickshell/solide6c/s6chourg3.F
some tests shown the hourglass results with penta6 thickshell elements
adding hourglass controls (in thickness direction) in penta6 element
> add hourglass control in penta6 thickshell

- engine/source/interfaces/interf/check_active_elem_edge.F
A bug was introduced in the shooting node algorithm : the number of node was wrong.
Fix the number of node
> Shooting node algo : fix an issue related to the number of node of a surface

- engine/source/elements/thickshell/solide6c/s6chourg3.F
possible failing issue using penta6 on windows platform from d664da156792e7ec7f2e22eb727609dc0e6f9d85
fixing windows platform issue w/ penta6
> penta6 element issue on windows platform

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
- hm_cfg_files/config/CFG/Keyword971_R6.1/VECTOR/define_vector.cfg
support of *DEFINE_VECTOR_NODES card
plug reading of *DEFINE_VECTOR_NODES card
> support of *DEFINE_VECTOR_NODES card

- engine/source/elements/shell/coquez/czforc3.F
- engine/source/output/dynain/dynain_c_strag.F
- engine/source/output/sta/stat_c_strafg.F
- starter/source/elements/elbuf_init/elbuf_ini.F
- starter/source/elements/shell/coqueba/cbainit3.F
- starter/source/starter/check_qeph_stra.F
- starter/source/starter/lectur.F
add condition for npg=4 total strain compute for QEPH to improve the performance
> add condition for npg=4 total strain compute with QEPH

- starter/source/materials/mat/mat051/hm_read_mat51.F
Unexpected Error message id 99 may have been displayed. It is now fixed.
> fix following commit 91210744bb6a8178f5ceefe57f8ff56d7dfd9c5e

- engine/build_script.sh
- engine/source/coupling/rad2rad/r2r_init.F
- engine/source/coupling/rad2rad/sys_pipes_c.c
- starter/source/system/rad_sys_call.c
* Argument error in waitpid calls in Starter
* In the Engine Remove obsolete Signal handler.
> Fix code after compilation errors on new ArmFlang Compiler

- common_source/modules/ale/ale_connectivity_mod.F
This update is improving algorithm related to ALE connectivity buffer (ale_connectivity_mod.F).
This is related to the specific case of degenerated HEXA element : degenerated edges are ignored.
> ALE : update for connectivity buffer

- engine/source/output/h3d/h3d_results/h3d_skin_ixskin.F
wrong result or not initialize issue with /H3D/ELEM/PEXT with /LOAD/PRESSURE in the model
bug fixing
> bug fixing in /H3D/ELEM/PEXT for /LOAD_PRESSURE

- starter/source/materials/tools/nlsqf.F
The comment on a vector variable seems inaccurate. 
A tiny revision on the comment, and no logic changes.
> Fix a typo in comment

- tools/th_to_csv/src/th_to_csv.c
th to csv issue with spring forces ( considered as impulses)
derivation not done anymore for this output
> th to csv issue with spring forces

- starter/source/elements/initia/initia.F
Formatting part mass and inertia table
Format update mass and inertia table and separating part name and id
> Part mass table formatting

- engine/source/ale/agauge.F
- engine/source/ale/alemain.F
- engine/source/ale/alethe.F
Wrong /TH/GAUGE fileds output.
Correction of pressure, internal energy and density output in /TH/GAUGE.
> Correction of GAUGE option in time history

- common_source/modules/elbufdef_mod.F
- engine/source/elements/elbuf/alloc_elbuf_imp.F
- engine/source/elements/elbuf/allocbuf_auto.F
- engine/source/elements/elbuf/copy_elbuf_1.F
- engine/source/elements/elbuf/w_elbuf_str.F
- engine/source/elements/thickshell/solide6c/s6cfint_reg.F
- engine/source/elements/thickshell/solide6c/s6cforc3.F
- engine/source/elements/thickshell/solidec/scfint_reg.F
- engine/source/elements/thickshell/solidec/scforc3.F
- engine/source/materials/mat/mat104/mat104_ldam_nice.F
- engine/source/materials/mat/mat104/mat104c_ldam_nice.F
- engine/source/materials/mat/mat104/sigeps104.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/output/h3d/h3d_build_fortran/lech3d.F
- engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
- engine/source/output/h3d/input_list/h3d_list_solid_scalar.F
- engine/source/tools/sect/sectio.F
- hm_cfg_files/config/CFG/radioss2023/MAT/matl104_drucker.cfg
- starter/source/elements/elbuf_init/elbuf_ini.F
- starter/source/elements/elbuf_init/initvars_auto.F
- starter/source/materials/fail/nloc_dmg_init.F
- starter/source/materials/mat/mat104/hm_read_mat104.F
- starter/source/materials/mat/mat104/law104_upd.F
- starter/source/properties/thickshell/hm_read_prop20.F
- starter/source/restart/ddsplit/w_elbuf_str.F
Non-local method was not compatible with thickshells element (Isolid = 15). 
Make it compatible, add some output missing in h3d, fix some issues in /MAT/LAW104 definition, and a potential segfault issue in SECTION output for thickshells.
> Implementation of non-local for thickshells Isolid=15

- starter/source/interfaces/inter3d1/inintr2.F
- starter/source/interfaces/inter3d1/remn_self24.F
- starter/source/starter/lectur.F
guidelines compliance
+ minor coding style improvements
> pass the size of NOD2ELS into remn_self24.F

- starter/source/materials/mat/mat088/law88_upd.F
Error message if the unloading function not exist.
Fix the error message. The compute of intersection point are did only if the loading and unloading function are available.
> fix error message issue  if the unloading function not exist

- starter/source/interfaces/intbuf/intbuf_ini_starter.F
- starter/source/interfaces/inter3d1/inintr2.F
- starter/source/interfaces/inter3d1/remn_self24.F
regression in 1a0f8bbb902544485e09a7d568cab028005c0878 concerning interface type 24, crash result could happen with some special models.
fixing regression issues
> regression int24 PR 1a0f8bbb902544485e09a7d568cab028005c0878

- engine/source/materials/fail/syazwan/fail_syazwan_s.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mmain8.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/mulaw8.F
- engine/source/materials/mat_share/usermat_solid.F
- hm_cfg_files/config/CFG/radioss2023/FAIL/fail_syazwan.cfg
- starter/source/materials/fail/syazwan/hm_read_fail_syazwan.F
A recent contribution of Syazwan Samad has been improved by himself and submitted to ensure compatibility with solid elements. However, this needed some reviewing as it has created a forcheck issue and some equations were not correct with theory. 
Fix the theory and the forcheck issue + improve the code to be consistent with the rest of the failure criteria library.
> Review of /FAIL/SYAZWAN compatibility for solids and fix equations + forcheck issues

- engine/source/engine/radioss2.F
- engine/source/engine/resol.F
- engine/source/input/lectur.F
- engine/source/output/h3d/h3d_build_fortran/lech3d.F
- engine/source/output/h3d/h3d_results/genh3d.F
- engine/source/output/h3d/h3d_results/h3d_skin_ixskin.F
- engine/source/output/h3d/h3d_results/h3d_skin_pre_map.F
- engine/source/output/h3d/h3d_results/h3d_skin_scalar.F
- engine/source/output/h3d/h3d_results/h3d_skin_vector.F
- engine/source/output/sortie_main.F
make compatible output /H3D/ELEM/PEXT for new /LOAD/PCYL
> add /LOAD/PCYL compatible with /H3D/ELEM/PEXT

- tools/anim_to_vtk/src/anim_to_vtk.cpp
- tools/th_to_csv/src/th_to_csv.c
The output converter tools use now  the MIT License
> License file Update: anim_to_vtk and th_to_csv in MIT License

- engine/source/engine/resol.F
- engine/source/tools/sensor/sensor_base.F
compilation bug correction
passed table length as argument to correct a variable declaration
> Correct length declaration of argument table in sensor_base.F

- engine/source/output/anim/reader/anim_build_index_all.F
A variable IGTYP was not initialized 
Initialize the variable
> fix an uninitialized variable introduced by 226e90fd29dbaefd7924118f2193818fb487a104

- engine/source/interfaces/int07/i7therm.F
- engine/source/interfaces/int21/i21therm.F
Debug Inter type 7 thermal exchange : problem with computation of exchange area and the material of secondary nodes for solids
Debug Inter type 7 thermal exchange : problem with computation of exchange area and the material of secondary nodes for solids
> Inter7 thermal exchange debug

- engine/source/output/h3d/h3d_results/h3d_nodal_vector.F
Correction H3d output CONT/MAX PCONT/MAX stamping memory problem
Correction H3d output CONT/MAX PCONT/MAX stamping memory problem : FCONT_MAX, FNCONT_MAX, FTCONT_MAX size is non zero only in ISPMD=0
> Correction H3d output CONT/MAX PCONT/MAX stamping memory problem

- engine/source/output/anim/generate/tensgpstrain.F
- engine/source/output/anim/generate/tensor6.F
Radioss (Engine) crashed when law151 used and /H3D/NODA/GPS or /GPSTRAIN defined for output
crash result fixed
> bug fixing on law151+/H3D/NODA/GPS(GPSTRAIN)

- engine/CMake_Compilers/cmake_linux64_gf.txt
- starter/CMake_Compilers/cmake_linux64_gf.txt
Ensure that no new warning are added.
>  turn warnings into errors

- engine/source/output/anim/generate/dfuncc.F
- engine/source/output/anim/reader/anim_build_index_all.F
- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
- engine/source/output/sta/stat_c_orth_loc.F
The orhotropy in the h3D are the same for all slice even drape is used.
correct the orthotropy of the slice using  the storage corresponding to each slice.
> correct the orthotropy of the slice in H3D and /ANIM

- engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
/H3D/ELEM/TENS/STRESS was not working at all for shells returning N/A output. 
Add the corresponding output for /H3D/ELEM/TENS/STRESS (consistent with /H3D/ELEM/TENS/STRAIN).
> Fix /H3D/ELEM/TENS/STRESS issue with shells

- engine/source/interfaces/intsort/i25optcd.F
Argument should be intent(inout) and was intent(out)
> wrong intent in i25optcd.F

- engine/source/output/anim/generate/tensorc.F
- engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
- engine/source/output/h3d/h3d_results/h3d_write_sh_tensor_array.F
correcting runtime issues when using animation and h3d tensor output for shells
h3d : corrected uninitialized array index in the code
anim : I have added checks to avoid passing to the output calculations in not compatible cases
> Correct non initialized array index in h3d and fix compatibility issues in anim shell output

- engine/source/materials/mat/mat079/sigeps79.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- hm_cfg_files/config/CFG/radioss2023/MAT/matl79_79.cfg
- starter/source/materials/mat/mat079/hm_read_mat79.F
Add element deletion in /MAT/LAW79 + clean code (intent attribute, arguments, comments ...) and review constitutive equations. 
Element deletion is now available and constitutive equations have been verified with comparisons of numerical results.
> Add element deletion and revision of /MAT/LAW79

- engine/source/output/sta/genstat.F
- engine/source/output/sta/stat_beam_spmd.F
- engine/source/output/sta/stat_shel_spmd.F
- engine/source/output/sta/stat_spring_spmd.F
- engine/source/output/sta/stat_truss_spmd.F
Use of Uninitialized argument in stat_shel_spmd
Clean unused argument in State file routine
> STATE output files

- starter/source/materials/mat/write_matparam.F
material othotropy settings used in h3d and anim outputs were not taken into account
Corrected missing flag during writing restart of matparam structure in starter
> Correct restart writing of matparam in starter

- engine/source/interfaces/int24/i24dst3.F
- engine/source/interfaces/int24/i24for3.F
after some validation tests on the automatic stiffness of interface type24, some modifications have been done to avoid regression of implicit solution and improvement for the this option
> change on interface type of Istif=-1 (auto) after some validations tests

- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulaw.F
- engine/source/materials/mat_share/usermat_solid.F
- engine/source/materials/visc/visc_prony.F
- engine/source/materials/visc/viscmain.F
- starter/source/materials/mat/mat062/law62_upd.F
- starter/source/materials/visc/hm_read_visc_prony.F
missed argument , adding not used variable.
Adding missed argument and reduce the number of internal variable.
> fix missed argument issue and memory buffer issue

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
New CFG activation needed for conversion of Dyna *MAT_224.
Activate *MAT_224 in Dyna data hierarchy CFG file.
> activate Dyna cfg data hierarchy file for *MAT_224

- engine/source/materials/mat/mat002/m2cplr.F
- engine/source/materials/mat/mat002/m2law.F
- engine/source/materials/mat/mat002/sigeps02c.F
- engine/source/materials/mat_share/mmain.F
- engine/source/materials/mat_share/mulawc.F
- hm_cfg_files/config/CFG/radioss2023/MAT/matl2_plas.cfg
- hm_cfg_files/config/CFG/radioss2023/MAT/matl2_plas_johns.cfg
- hm_cfg_files/config/CFG/radioss2023/MAT/matl2_plas_zeril.cfg
- starter/source/materials/mat/hm_read_mat.F
- starter/source/materials/mat/mat002/hm_read_mat02.F
/MAT/LAW2; add new feature VP=1,2,3 for strain rate dependency
VP=1  EQUIVALENT PLASTIC STRAIN RATE
VP=2  TOTAL STRAIN RATE (DEFAULT)
VP=3  DEVIATORIC STRAIN RATE
> LAW2 VP 1-2-3 shell and solid

- starter/source/materials/mat/mat002/hm_read_mat02.F
LAW2 correct default value Asrate for VP=2
remark: Fcut used for output only
> LAW2 - correct default value of asrate for vp=2

- common_source/fxbody/fxbvini.F
- engine/source/input/lecinv.F
- engine/source/input/lectur.F
Compatibility with inivel in engine and fxbody
-> routine fxbvini.F is moved in common source in a new directory
> FXBODY : compatibility with inivel in engine

- engine/source/elements/beam/beam_fail.F
- engine/source/elements/beam/mulawp.F
- engine/source/elements/beam/pforc3.F
- engine/source/elements/beam/pmain3.F
- engine/source/elements/forint.F
- engine/source/engine/resol.F
- engine/source/materials/mat/mat002/m2lawpi.F
- engine/source/materials/mat/mat034/sigeps34pi.F
- engine/source/materials/mat/mat036/sigeps36pi.F
- engine/source/materials/mat/mat044/sigeps44pi.F
- engine/source/materials/mat/mat071/sigeps71pi.F
- starter/source/elements/beam/pgrhead.F
- starter/source/elements/beam/pgrtails.F
- starter/source/starter/lectur.F
no change for the user
I have modified the beam element sorting criteria to have homogeneous groups with the same material
Prepared main routine for failure treatment of integrated beams in future
> Change beams group decomposition, add failure model treatment in integrated beams

- starter/source/elements/beam/pgrhead.F
avoid bug in beam element group creation
Corrected indexes of sorting criteria table in beam group decomposition
> Correct memory access issue in beam element group decomposition

- engine/source/interfaces/int24/i24dst3.F
- starter/source/interfaces/inter3d1/i24sti3.F
wrong contact could be happen with interface type24 (Iedge=1) for special case (solid to shell impact)
correction done to avoid wrong contact with type24
> avoid wrong plan-to-plan contact in int24

- engine/source/elements/beam/beam_fail.F
- engine/source/elements/beam/pmain3.F
- engine/source/materials/fail/johnson_cook/fail_johnson_pi.F
- starter/source/elements/elbuf_init/elbuf_ini.F
Added first failure model for integrated beams (Johnslon-Cook)
Added allocation of failure model buffer for beams
Created new routine for Johnson-Cook failure and fixed element erosion criterion
> Add Johnson-Cook failure model for integrated beams

- engine/CMake_Compilers/legacy_fortran.cmake
- engine/source/engine/radioss2.F
- engine/source/input/lectur.F
Non-existing interface id in /INTER card can produce a segfault
Fix the issue + remove warnings and errors from lectur.F
> Non-existing interface id in /INTER card produce a segfault

- engine/source/elements/beam/pforc3.F
- engine/source/elements/beam/pmain3.F
- engine/source/materials/mat/mat002/m2cplr.F
- engine/source/materials/mat/mat002/m2lawp.F
- engine/source/materials/mat/mat002/m2lawpi.F
- engine/source/materials/mat/mat002/sigeps02c.F
- engine/source/materials/mat/mat002/sigeps02g.F
- engine/source/materials/mat_share/mulawglc.F
- starter/source/materials/mat/mat002/hm_read_mat02.F
LAW2 - add VP for beams + correction in shell and solid
LAW2 - add VP for beams + correction in shell and solid
> LAW2 - add VP option for beams

- engine/source/materials/mat/mat002/sigeps02g.F
LAW2 shell NPT=0 correct variable
> LAW2 shell NPT=0 correct variable

- hm_cfg_files/config/CFG/Keyword971_R13.0/CURVE/define_table_3D.cfg
- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Conversion of Dyna *DEFINE_TABLE_3D card to Radioss Table_3D
Activate CFG Dyna file for conversion of Dyna *DEFINE_TABLE_3D option
> conversion of Dyna *DEFINE_TABLE_3D to Radioss table_3D

- engine/source/interfaces/int24/i24cor3.F
Stmin now has no effect in case of Istif=-1 (auto) of interface type24
> remove Stmin in Istif=-1 of interface type24

- engine/source/output/anim/generate/tensgpstrain.F
- engine/source/output/anim/generate/tensor6.F
> correction on GPS output

- engine/source/interfaces/int24/i24for3.F
raised by issues #1757, remove useless elseif block in i24for3.F
> remove useless coding block in int24

- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
- engine/source/output/sta/stat_c_orth_loc.F
- starter/source/elements/initia/hm_read_inistate_d00.F
- starter/source/elements/initia/lec_inistate_tri.F
- starter/source/elements/sh3n/coque3n/c3init3.F
- starter/source/elements/sh3n/coquedk/cdkinit3.F
- starter/source/elements/sh3n/coquedk/cmaini3.F
- starter/source/elements/shell/coque/cinit3.F
- starter/source/elements/shell/coque/corthdir.F
- starter/source/elements/shell/coque/corthini.F
- starter/source/elements/shell/coqueba/cbainit3.F
- starter/source/elements/shell/coqueba/layini1.F
- starter/source/properties/composite_options/drape/hm_read_drape.F
- starter/source/stack/hm_read_stack.F
- starter/source/stack/pres_stackgroup.F
/STATE option is not compatible with /DRAPE
Getting orthotropic direction for each slice and make /INISHE and /INISH3 compatible with drape.
> Option State, INISHEL, INISH3 and drape & fix issue related to drape

- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
- engine/source/output/sta/stat_c_orth_loc.F
- starter/source/elements/initia/hm_read_inistate_d00.F
- starter/source/elements/initia/lec_inistate_tri.F
- starter/source/elements/sh3n/coque3n/c3init3.F
- starter/source/elements/sh3n/coquedk/cdkinit3.F
- starter/source/elements/sh3n/coquedk/cmaini3.F
- starter/source/elements/shell/coque/cinit3.F
- starter/source/elements/shell/coque/corthdir.F
- starter/source/elements/shell/coque/corthini.F
- starter/source/elements/shell/coqueba/cbainit3.F
- starter/source/elements/shell/coqueba/layini1.F
- starter/source/properties/composite_options/drape/hm_read_drape.F
- starter/source/stack/hm_read_stack.F
- starter/source/stack/pres_stackgroup.F
This reverts commit 4e701ece6cd9e7afa50bf1d0fd928dfc83bd286f.
> Revert "Option State, INISHEL, INISH3 and drape & fix issue related to drape"

- engine/source/elements/beam/main_beam3.F
- engine/source/elements/beam/pdamp3.F
- engine/source/materials/mat/mat044/sigeps44p.F
Corrected beam 3 behavior using default element damping
fixed a bug in damping term calculation
fixed non initialized variable in law 44 with beams type 3
> Correction of damping calculation in beams type 3

- engine/source/elements/beam/main_beam3.F
- engine/source/materials/mat/mat002/m2lawp.F
- engine/source/materials/mat/mat044/sigeps44p.F
no influence for the user
corrected issue when OFF factor was applied twice after failure of beam type 3 inside material laws 2 and 44
> Correct post rupture behavior of beams type 3 with material laws 2 and 44

- engine/source/materials/mat/mat041/sigeps41.F
- engine/source/materials/mat_share/mulaw.F
- starter/CMake_Compilers/legacy_fortran.cmake
- starter/source/materials/mat/hm_read_mat.F
- starter/source/materials/mat/mat041/hm_read_mat41.F
Improve Readability and introduce Burn fraction output to start verification process with better conditions.
- source code commented, descriptions added, french comments translated
- some local variables renamed (ex:vol->vol_rel to avoid misunderstanding)
- subroutine renammed to improve readability
- source file hm_read_mat41**.F.F** renamed into hm_read_mat41.F
- arguments : INTENT and explicit size are defined
- Burn Fraction element buffer introduced (LBUF%BFRAC) : will be used for later verification
> /MAT/LAW41:cleaning

- engine/source/materials/mat_share/mulaw8.F
fix following commit 0f0cf18d14c7f441f7726bc59eb52554ed199cc3
New argument LBUF%BFRAC added in sigesp41.F.
SIGESP41 called by :
- mulaw.F
- mulaw8.F
> mulaw8.F:adding missing argument

- engine/source/output/h3d/h3d_results/h3d_quad_scalar.F
- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
- engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
1. Loop optimized ; conditionnal tests:
-  'IALEL==0' 
-  'N2D==0' 
are now out of the elem loop.
2. Indentation fixed
related keywords :
- energy : /H3D/ELEM/EINT,EINTM,EINTV 
- enthalpy : /H3D/ELEM/ENTH,ENTHM,ENTHV
> H3D:loop optimization for EINT* & ENTH* output

- engine/source/tools/sensor/sensor_energy.F
- hm_cfg_files/config/CFG/radioss2023/SENSOR/sensor_energy.cfg
- starter/source/tools/sensor/read_sensor_energy.F
redefinition of constant energy criteria of /SENSOR/ENERGY, more user friendly
small change in sensor energy cfg file and adaptation of sensor code for new criteria definition
> change constant energy sensor activation criteria (/SENSOR/ENERGY)

- engine/source/interfaces/interf/i2for27_pen.F
Array IN may be unallocated, but was accessed
Access to the array, only if MSEGTYP2 == 1
> /INTER/TYPE2 spotflag 27: memory issue

- engine/source/output/anim/generate/tensorc.F
no influence for the user
correct wrong array sizes between routine call and local declaration in uroto_tens2d
> correct float overflow in tensor output (ANIM)

- extlib/hm_reader/hm_reader_license.txt
- extlib/license/hm_reader_license.txt
Typo issue in Copyright text files for hm_reader library
> Typo issue in Copyright text files for hm_reader library

- engine/source/output/sortie_main.F
Additional argument required for ABFHIST2 library due to change in thsol.F (a589c23a27d0fc50d50e70e8b15a2bd2ca8607ab)
> additional argument abfhist2 subroutine

- engine/source/output/anim/generate/dfuncf.F
- engine/source/output/anim/generate/genani.F
- engine/source/output/anim/reader/anim_dcod_key_0.F
- engine/source/output/h3d/h3d_results/h3d_oned_scalar.F
- engine/source/output/h3d/input_list/h3d_list_1d_scalar.F
damage output for beams is now available : /ANIM/BEAM/DAMA and /H3D/BEAM/DAMA
Added new options in h3d and anim routines
> Add H3D and Anim output of failure model damage in beams

- engine/build_script.sh
- starter/build_script.sh
- starter/build_windows.bat
c043ad40841a2745e89de9d14160621eb7a5a3da are missing some changes in build_script & build_windows.bat
> c043ad40841a2745e89de9d14160621eb7a5a3da are missing some changes 

- engine/source/materials/fail/orthstrain/fail_orthstrain_c.F
- engine/source/materials/fail/orthstrain/fail_orthstrain_s.F
Element failure message in 01.out file was not sufficiently explicit for /FAIL/ORTHSTRAIN. 
Improve element failure message for /FAIL/ORTHSTRAIN, printing out failure strain, and critical value.
> New output file format for /FAIL/ORTHSTRAIN

- engine/source/tools/seatbelts/material_flow.F
Fix of computation of retractor when seatbelt material is NL
> SEATBELT : fix for retractor with NL material

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Conversion of DYNA *MAT_120 (Gurson)
Activation of conversion of Dyna *MAT_120 in hierarchy CFG file
> Activate conversion of DYNA MAT_120

- engine/source/interfaces/int24/i24dst3.F
- engine/source/interfaces/int24/n2edge3l.F
performance issues of sorting observed with interface type24 +Iedge=1 with shell model
correction on shell-to-shell intersection algorithm to avoid wrong contact detection (reason of sorting issue)
> correction on shell_to_shell plan intersection algorithm of int24

- engine/source/output/sortie_main.F
- starter/source/tools/sensor/read_sensor_energy.F
The change of default value may avoid incorrect behavior in case of negative energy
Added check in starter if the Min energy was not defined
Corrected INTENT declaration of SENSOR structure in engine
> Change default value of IEMIN in sensor energy input, correct INTENT declaration

- starter/source/elements/beam/pmass.F
- starter/source/properties/beam/hm_read_prop18.F
instability issue observed on special beam model (very small section).
Correction on beam inertia compute to avoid instability issue
> modification on beam inertia to avoid instability issue

- engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
When the number of slice are different by group of element possible core with /H3D
Out put only the result for the existing slice
> fix Segmentation Violation with /H3D

- engine/source/output/anim/generate/dfuncc.F
A segfault can occurred in the dfuncc routine if /ANIM/ELEM/MACH is required with a model without any triangle element
The issue is fixed
> fix an issue related to /ANIM/ELEM/MACH option

- engine/source/materials/mat/mat078/sigeps78c.F
- starter/source/materials/mat/mat078/hm_read_mat78.F
/MAT/LAW78 reset number of variables to 6
> LAW78 reduce nuvar

- starter/source/elements/initia/hm_read_inistate_d00.F
DEALLOCATE unallocated array
Deallocate array only if it's allocated
> fix issue of DEALLOCATE unallocated array

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
Conversion of Dyna *MAT_019 into Radioss needs an activation in datahierarchy CFG file.
Activate conversion of Dyna *MAT_019 into Radioss, in CFG file.
> Activate conversion of Dyna *MAT_019 in CFG file

- hm_cfg_files/config/CFG/radioss2023/LAMINATE/stack.cfg
- starter/source/stack/hm_read_stack.F
Pthickfail parameter was not available for /PROP/TYPE52
Create a new RADIOSS 2023 format with Pthickfail parameter for /PROP/TYPE52 + add the read of this parameter and its storage in the property tables.
> Implementation of PTHICKFAIL for /PROP/TYPE52

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
New conversion *LOAD_SEGMENT and *LOAD_SEGMENT_SET Dyna cards supported in CFG file.
Activate conversion of *LOAD_SEGMENT and *LOAD_SEGMENT_SET in data hierarchy CFG file.
> activate conversion of *LOAD_SEGMENT in datahierarchy CFG file

- engine/source/materials/fail/fld/fail_fld_tsh.F
- engine/source/materials/fail/fld/fail_fld_xfem.F
- engine/source/output/h3d/h3d_results/h3d_sol_skin_scalar.F
Function ID was removed from the list of argument of FINTERFLD in a previous commit
Some FINTERFLD calls still contain the function id
Remove all function ids from FINTERFLD calls
> number of arguments was inconsistent in FINTERFLD calls

- engine/source/ale/bimat/bforc2.F
- engine/source/elements/solid_2d/quad/qhvis2.F
qhvis2.F : same treatment as qhvis3.F (BRICK) cumulated hourglass energy has no meaning since hourglass energy is not advected.
> QUAD+ALE : unplug cumulated hourglass value

- engine/source/elements/beam/main_beam18.F
- engine/source/elements/beam/main_beam3.F
- engine/source/elements/beam/pdamp3.F
- engine/source/elements/beam/pdlen3.F
- engine/source/elements/beam/pforc3.F
instability issue found with beam type18 in case of small section dimension using mass scaling
1)instability issue of type18 fixed
2)dimension unity for damping issue found in beam type3 and it's fixed
3)one common damping subroutine is called now for both type3&type18
> improvement on robustness of beam

- engine/source/elements/beam/fail_beam18.F
- engine/source/elements/beam/fail_beam3.F
- engine/source/elements/beam/main_beam18.F
- engine/source/elements/beam/main_beam3.F
- engine/source/elements/beam/pforc3.F
- engine/source/materials/fail/tensstrain/fail_tensstrain_b.F
- engine/source/materials/fail/tensstrain/fail_tensstrain_c.F
- engine/source/materials/fail/tensstrain/fail_tensstrain_ib.F
- starter/source/materials/fail/tensstrain/hm_read_fail_tensstrain.F
Add compatibiliy of /FAIL/TENSSTRAIN to beams type3 and type18
Add compatibiliy of /FAIL/TENSSTRAIN to beams type3 and type18
> fail tensstrain for beam (3 and 18)

- engine/source/materials/mat/mat124/sigeps124.F
- hm_cfg_files/config/CFG/radioss2023/MAT/matl124_cdpm2.cfg
- starter/source/materials/mat/mat124/hm_read_mat124.F
/MAT/LAW124 will finally be released in 2023 format and not 2022 format. The .cfg file must be modified + add a flag to deactivate element deletion. 
Create .cfg file for /MAT/LAW124 in radioss2023 + add the flag.
> Change LAW124 to format 2023 + flag for element deletion

- engine/source/output/anim/generate/forani1.F
- engine/source/output/anim/generate/forani2.F
- engine/source/output/anim/generate/forani3.F
Comments were introduced in order to clearly understand the calling sequence in main Engine subroutin resol.F : FORAN1, then FORANI2 and finally FORANI3
> FORANI1|2|3:adding comments

- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
/H3D/FAIL option was not working at all. This comes from a bad condition to write the output. 
Remove the bad condition IFAILURE == 0.
> Fix bug of /H3D/FAIL

- engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
Layer output for shell tensor was not available if NPT=ALL was mentionned. 
Remove a bad condition that creates the bug in /H3D/SHELL/TENS routine.
> Fix /H3D/SHELL/TENS/XXXX/LAYER=ALL/NPT=ALL output

- engine/source/engine/resol.F
- engine/source/output/anim/generate/forani1.F
- engine/source/output/anim/generate/forani2.F
- engine/source/output/anim/generate/forani3.F
- engine/source/output/reaction_forces_th.F
- engine/source/output/reactions.F
+ Comments were introduced to clearly understand the calling sequence in the solver loop (resol.F)
+ subroutines renammed with a more suitable name
+ INTENT (in / inout) introduced
related options : values FREAC/MREAC for /ANIM /OUTP /H3D and /TH
> FREAC output : comments introduced

- engine/source/interfaces/interf/check_neighbours_surface_state.F
Correction problem compilation commit 312eb706c7b5c796f96dc6a5aaa233eba83b
Correction problem compilation commit 312eb706c7b5c796f96dc6a5aaa233eba83b
> correction_problem_compil_commit_312eb706c7b5c796f96dc6a5aaa233eba83bf90

- engine/source/output/anim/generate/tensorc.F
Some output for solid stress tensor were not working any more after a recent development. 
Fix some wrong table size: tensor (3*NEL) instead of (5*NEL), and MVSIZ instead of NEL. + Fix a bug for layers output.
> Fix animation issue with solid stress tensor output

- engine/source/elements/beam/fail_beam18.F
- engine/source/materials/fail/cockroft_latham/fail_cockroft_ib.F
Add Fail cockroft compatibility with type 18 integ beam
> Add Fail cockroft compatibility with type 18 integ beam

- engine/source/interfaces/int25/i25dst3_22.F
Correction problem Pon inter type 25
ICONT_I tab is not communicated. In that case no need to update it if node is detected on the other side.
>  correction problem pon int25

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
add *MAT030 & *MAT154 reading
add *MAT030 & *MAT154 reading
> add *MAT030 & *MAT154 reading

- engine/source/materials/mat_share/mqviscb.F
An issue was introduced in b323d7acbe61339e681d4fa3fa344b272ae5bb6e commit.
Fix the issue
> fix an issue in mqviscb routine introduced by b323d7acbe61339e681d4fa3fa344b272ae5bb6e

- starter/source/elements/initia/hm_read_inistate_d00.F
- starter/source/elements/shell/coque/csigini.F
- starter/source/elements/shell/coqueba/scigini4.F
A conflict in the Number on integration point in the thickness leading to error message
when /INISHE/STRA_F and /INISHE/STRS_F are in the data for /PROP/TYPE51 and PCOMPP
Ignore the number of number of point given by /INISHE/STRA_F
> fix error message when INISHE/STRA_F & /INISHE/STRS_F with TYPE51 or PCOMPP are used

- .gitignore
- qa-tests/CMakeLists.txt
- qa-tests/miniqa/ACCELEROMETRES/data/test_files.json
- qa-tests/miniqa/AIRBAG/jetting41b/data/test_files.json
- qa-tests/miniqa/AMS/boxbeam/data/test_files.json
- qa-tests/miniqa/FLUIDE_NEW/EBCS/INIV/data/test_files.json
- qa-tests/miniqa/INTERF/INT_22/1D_U-SURF_9ELEMS_LAW6_Linear_EOS_EULER_0.FVM/data/test_files.json
- qa-tests/miniqa/INTERF/INT_7/idel7=2/data/test_files.json
- qa-tests/miniqa/INTERF/INT_7/igsti/small_boule_igsti/data/test_files.json
- qa-tests/miniqa/INTERF/INT_7/small_boule/data/test_files.json
- qa-tests/miniqa/LOIS/LEAK_MAT/run2_LAW58_quads/data/test_files.json
- qa-tests/miniqa/LOIS/LOI25/test_crasurv_bloc/input_44/data/test_files.json
- qa-tests/miniqa/LOIS/LOI51/JWL/01-PG_degenerated/01a_P-E/data/test_files.json
- qa-tests/miniqa/LOIS/LOI68/cisaillement/test1/input_51/data/test_files.json
- qa-tests/miniqa/PROP/spring_beam_Hardening7/Type4/Hardening7/data/test_files.json
- qa-tests/miniqa/RESSORT/prop_type32/ILOCK2/data/test_files.json
- qa-tests/miniqa/RESTART/cra2/data/test_files.json
- qa-tests/miniqa/RESTART/int7_small_boule_rst/data/test_files.json
- qa-tests/miniqa/SOLIDES/inibri_stress/data/test_files.json
- qa-tests/miniqa/onefile_rad/data/test_files.json
- qa-tests/qa_tools/constants.json
- qa-tests/qa_tools/execute_solver.py
- qa-tests/qa_tools/miniqa.txt
- qa-tests/qa_tools/or_execute.py
- qa-tests/qa_tools/qa_system.py
- qa-tests/qa_tools/verify_results.py
- qa-tests/test_script.bash
- qa-tests/test_script.bat
Create Python functions to execute Radioss & Verify the results with Tolerances
The tool might be extended in the Future
> QA_script for OpenRadioss using CTest and Python

- .gitattributes
- engine/build_windows.bat
> Force .bat files in Windows CR/LF format

- starter/source/elements/shell/coque/csigini.F
- starter/source/elements/shell/coqueba/scigini4.F
We get error message for NPT=0
The message is ignored if we use only /INISHE/STRA_F
> fix error message related to /INISHE/STRA_F

- starter/source/materials/mat/mat042/sigeps42.F
Starter code of /MAT/LAW42 was containing some mistakes that could create checkbounds issues. 
Fix the mistakes + clean the code: add intent attributes, comments ...
> Fix potential checkbounds issue with /MAT/LAW42

- engine/source/elements/solid/solide8e/m1tot_stab18.F
- engine/source/elements/solid/solidez/m1tot_stab24.F
using constants avoid compatibility (sp,dp) issue
> using constant to avoid compatibility (sp,dp) error

- starter/source/elements/beam/pmass.F
missing Starter part of c0ec1b679f2bf4065bf7277983d929a8a80bebb5, in some case will get smaller time step
add Starter part of instability fixing c0ec1b679f2bf4065bf7277983d929a8a80bebb5 to be consisting between Starter&Engine
> complete Starter part of c0ec1b679f2bf4065bf7277983d929a8a80bebb5

- starter/source/stack/hm_read_stack.F
Due to recent changes, output message in starter for /STACK needs to be updated. 
Change the starter output message for /STACK.
> Change output message in /STACK starter code

- engine/source/output/h3d/h3d_build_fortran/create_h3d_input.F
The command /H3D/SHELL/TENS/EPSDOT was working fine but not  /H3D/ELEM/TENS/EPSDOT
Switch IEPSDOT to 1 for /H3D/ELEM/TENS/EPSDOT
> Fix unworking command /H3D/ELEM/TENS/EPSDOT

- engine/source/elements/beam/fail_beam18.F
- engine/source/materials/fail/energy/fail_energy_ib.F
Fail energy for integrated beams, adjust the failure condition 
Delete element when all IPs reach failure
> Fail energy beam type18-review failure condition

- engine/source/multifluid/multi_muscl_fluxes_computation.F
When error occurs during flux calculation in source file "multi_muscl_fluxes_computation.F", an explicit error message is introduced and recommendations are provided.
> /MAT/LAW151 + /ALE/MUSCL : explicit error message + recommendations

- starter/source/elements/spring/rinit3.F
possible bad element reference in error 328
correction element id outputed in error 328 listing
> possible bad element reference in error 328

- engine/source/output/h3d/h3d_build_fortran/lech3d.F
- hm_cfg_files/config/CFG/radioss2023/FAIL/fail_orthenerg.cfg
Some dimensions were missing in .cfg file of /FAIL/ORTHENERG. 
Add the missing dimension + add ORTHENERG name in H3D output
> Fix missing dimensions in .cfg file

- hm_cfg_files/config/CFG/radioss2023/MAT/matl69_69.cfg
Not an issue
adding the default value in the cfg file
> adding default flag in the cfg file for law69

- engine/CMakeLists.txt
Some files could be removed  when Single Precision is compiled.
This PR fixes the code ensuring this.
> Potential issue in Single Precision build

- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
- engine/source/output/h3d/input_list/h3d_list_shell_scalar.F
- starter/source/elements/elbuf_init/initvars_auto.F
Add the output option PLY and LAYER for /H3D/ELEM/DAMG. 
Add the output option PLY and LAYER for /H3D/ELEM/DAMG.
> Add PLY and LAYER output for /H3D/ELEM/DAMG

- starter/source/materials/mat/mat042/sigeps42.F
- starter/source/materials/mat_share/mulaw.F
Wrong intent for dummy argument in sigeps42.F (starter)
> invalid intent(out) to unused dummy argument

- engine/source/assembly/damping.F
- hm_cfg_files/config/CFG/radioss2023/DAMP/Damp_Vrel.cfg
- hm_cfg_files/config/CFG/radioss2023/data_hierarchy.cfg
- starter/source/general_controls/damping/hm_read_damp.F
- starter/source/starter/starter0.F
New option for Rayleigh dampin /DAMP/VREL with new cfg file
> New /DAMP/VREL option

- common_source/modules/ale/multi_fvm_mod.F
- engine/source/elements/solid/solide8e/s8eforc3.F
- starter/source/interfaces/int18/hm_read_inter_type18.F
- starter/source/interfaces/int18/int18_law151_alloc.F
- starter/source/interfaces/int18/int18_law151_init.F
- starter/source/interfaces/inter3d1/inint3.F
- starter/source/interfaces/interf1/ingrbric_nodes.F
- starter/source/interfaces/interf1/inintr.F
- starter/source/interfaces/interf1/lecins.F
- starter/source/interfaces/interf1/lecint.F
- starter/source/restart/ddsplit/ddsplit.F
- starter/source/restart/ddsplit/inter_tools.F
- starter/source/restart/ddsplit/split_interfaces.F
- starter/source/restart/ddsplit/w_fi.F
- starter/source/spmd/domain_decomposition/grid2mat.F
- starter/source/starter/lectur.F
Several issues were found with the interface 18 with material law 151
Fix the issues
> fix several issues for the interface 18 with material law 151

- common_source/modules/cpp_python_funct.cpp
- qa-tests/miniqa/PYTHON/FUNCT_PYTHON/data/test_files.json
- qa-tests/qa_tools/execute_solver.py
- qa-tests/qa_tools/miniqa.txt
- qa-tests/qa_tools/or_execute.py
- qa-tests/qa_tools/verify_results.py
- starter/source/starter/execargcheck.F
Improve Python library load in Windows.
Fix issue in strcpy_s fonction
Add Python test in CTEST MiniQA.
Clean debug  comments
> Python Functions : improvements for windows

- engine/source/output/h3d/h3d_results/h3d_oned_scalar.F
- engine/source/output/h3d/input_list/h3d_list_1d_scalar.F
Make compatible beams with EINTV output options. 
Add the option /H3D/BEAM/EINTV
> Add /H3D/BEAM/EINTV : internal energy per unit volume

- engine/build_windows.bat
- starter/build_windows.bat
Strange Batch file issue with specific option.
Lines after call are ignored.
> Strange Batch file issue with specific option.

- engine/source/interfaces/int18/int18_law151_alloc.F
Restart issue for interface type18+law151 model
An array is not allocated if a 2nd engine is run
> fix a restart issue for interface type18 with the law151

- starter/source/materials/mat/mat069/law69_upd.F
- starter/source/materials/tools/law69_nlsqf_auto.F
Core dump for not initialized variable for new option for law69 
clean of the not used part in the code.
> fix check bound issue related to new fitting option of law69

- starter/source/materials/tools/law69_nlsqf_auto.F
Error in the dimension of table for the new option of fitting law69.
fix  the right dimension of table.
> fix the error related to conversion of MAT077 Lsdyna

- starter/source/interfaces/inter3d1/i7remnode.F
Avoid integer overflow in irem_i2
> /INTER/TYPE7 irem_i2: possible integer overflow at starter

- starter/source/starter/lectur.F
fixing missing argument due to commit a77bc14e5fe2b63767b9a84216af1daf5eeae9d1
> fixing missing argument

- engine/source/output/anim/generate/tensorc.F
- engine/source/output/h3d/h3d_results/h3d_shell_tensor.F
- starter/source/starter/contrl.F
Tensors output in ANIM or H3D files for composite shell properties was not working as expected. 
Fix the outputs + avoid a potential segfault issue in starter when using /H3D/XXXX/XXXX/TMAX output with a part ID.
> Fix output issue for composite shell properties

- engine/source/output/th/thcoq.F
Possible core dump in th outp in the case of type17 with drape
We should use the right array of the ply orthotropy
> correct the th outp of the case of type17 with drape

- HOWTO.md
Change recommended compiler on Windows to Intel OneAPI 2023.2.
Refactor Markdown document
> OpenRadioss Documentation change:

- hm_cfg_files/config/CFG/radioss2023/MAT/mat_VISC_LPRONY.cfg
updat and correction of the dimension of parameters
Correct the dimension and update the comment.
> correct the cfg file for lprony option

- starter/source/interfaces/inter3d1/i24surfi.F
code cleaning and potential performance improvement on /INTER/TYPE24 (Iedge=1)
> code cleaning of subroutine I24EDGE2 after comments in issue #2054

- starter/source/materials/mat/mat070/law70_upd.F
avoid starter issue with law70 when EPSMAX is not correctly defined in the input
added check of table length when looking for EPSMAX value in a static function table
> local table treatment correction in law70

- starter/source/starter/execargcheck.F
Print commitID when existing
Print tag from hm_reader library
> Starter Traceability : -v command line option

- engine/source/materials/mat/mat071/sigeps71.F
LAW71 - solid- change condition for phase change
> LAW71 - solid- change condition for phase change

- starter/source/interfaces/inter3d1/i25buc_vox1.F
- starter/source/interfaces/inter3d1/i25cor3t.F
- starter/source/interfaces/inter3d1/i25pen3a.F
- starter/source/interfaces/inter3d1/i25sto.F
- starter/source/interfaces/inter3d1/i25trivox1.F
- starter/source/interfaces/inter3d1/inint3.F
Correction problem of inter25 test heating 3 pieces. The problem is with initial penetrations computation of shells
The problem is coming from Inacti=5 and initial penetrations computation for shells
> Correction problem int25 tetra4 elements

- starter/source/airbag/writeMesh.F
- starter/source/elements/ige3d/nbadigemesh.F
- starter/source/loads/general/load_pcyl/hm_read_pcyl.F
- starter/source/model/group/line_decomp.F
The length of the DATA did not match the actual length of the string
Comments should not contain backslashes
> remove some warnings in hm_read_pcyl.F

- starter/source/interfaces/inter3d1/inint3.F
- starter/source/spmd/domain_decomposition/update_weight_inter_type11.F
In the starter, the size of %IRECTS was not correct.
use NRTS instead of NSN
> The size of IRECTS for the interface type 11 was not correct - starter part

- starter/source/materials/mat/mat070/law70_upd.F
correct problem with law70 in starter with multiple loading and unloading functions
number of loading functions was used for unloading function treatment
> correct unloading function treatment in starter for law70

- engine/source/output/h3d/h3d_results/h3d_shell_scalar_1.F
Core dump for /H3D/SHELL/PHI and PROP51 or PROP52 with drape
Correct the access to memory.
> fix the core dump related to /H3D/SHELL/PHI and PROP51, 52 with Drape

- common_source/modules/loads/loads_mod.F
- engine/share/modules/restart_mod.F
- engine/source/assembly/disp_vel_saved_cload.F
- engine/source/engine/radioss2.F
- engine/source/engine/resol.F
- engine/source/engine/resol_head.F
- engine/source/implicit/imp_dyna.F
- engine/source/implicit/imp_solv.F
- engine/source/loads/general/force.F
- engine/source/loads/general/force_imp.F
- engine/source/output/restart/arralloc.F
- engine/source/output/restart/rdcomm.F
- engine/source/output/restart/rdresb.F
- engine/source/output/restart/wrcomm.F
- engine/source/output/restart/wrrestp.F
- hm_cfg_files/config/CFG/radioss2023/LOADS/cload.cfg
- hm_cfg_files/config/CFG/radioss2023/LOADS/pload.cfg
- starter/share/modules1/restart_mod.F
- starter/source/loads/general/cload/hm_read_cload.F
- starter/source/loads/general/pload/hm_read_pload.F
- starter/source/restart/ddsplit/c_nloads.F
- starter/source/restart/ddsplit/ddsplit.F
- starter/source/restart/ddsplit/w_disp0_vel0_cload.F
- starter/source/restart/ddsplit/wrcommp.F
- starter/source/starter/lectur.F
- starter/source/starter/starter0.F
Add function of displacement and velocity in options /CLOAD and /PLOAD.
Add new function of displacement and velocity in options /CLOAD and /PLOAD.
> /CLOAD and /PLOAD - add function of displacement and velocity

- engine/source/materials/mat/mat095/sigeps95.F
- engine/source/materials/mat/mat100/sigeps100.F
- engine/source/materials/mat/mat100/sigpoly.F
- hm_cfg_files/config/CFG/radioss2023/LAW95.cfg
- hm_cfg_files/config/CFG/radioss2023/MAT/LAW95.cfg
- starter/source/materials/mat/mat095/hm_read_mat95.F
Correct a bug in the energy function derivative
+ add a new formulation for compressible term
+ add poisson ratio
> LAW95-100 correct polynomial energy function + add in LAW95 iform and nu

- engine/source/elements/forintp.F
> SPH order 1 correctio - forcheck fix

- starter/source/interfaces/inter3d1/i24pen3.F
improve lisibility of i24pen3.F after comment in issue #2100
> improve lisibility of i24pen3.F

- engine/source/materials/mat/mat036/sigeps36pi.F
LAW36- beam type18- correct address for IFAIL and ISMOOTH
> LAW36- beam type18- correct address for IFAIL and ISMOOTH

- engine/source/elements/beam/fail_beam18.F
Fail BIQUAD type 18 - missing argument
> Fail BIQUAD type 18 - missing argument

- engine/source/output/h3d/h3d_results/h3d_solid_scalar_1.F
WPLA output specific to composite material laws was not working for solids in H3D files. 
Replace the wrong output value in the code.
> Fix WPLA output in H3D files for composite material laws

- engine/CMake_Compilers/cmake_linux64_intel.txt
Issue introduced in #2150 : missing flag for Intel compiler
> Fix engine build with Intel compiler

- engine/source/materials/mat/mat190/conversion.F
- starter/source/materials/mat/mat190/hm_read_mat190.F
LAW190:correct compatibility with property + 2ndderivative factors correction
Law is isotropic.
> LAW190:correct compatibility with property + 2nd derivative factors correction

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
- hm_cfg_files/config/CFG/Keyword971_R8.0/COMPONENT/part.cfg
SECTION_SPH & EOS_GRUNEISEN conversion
SECTION_SPH & EOS_GRUNEISEN conversion
> SECTION_SPH & EOS_GRUNEISEN conversion

- hm_cfg_files/config/CFG/Keyword971_R13.0/data_hierarchy.cfg
- starter/source/properties/thickshell/hm_read_prop21.F
Activate conversion of Dyna *SECTION_TSHELL to Radioss /PROP/TYPE20, /PROP/TYPE21, /PROP/TYPE22
Activation of conversion of Dyna *SECTION_TSHELL
> activate conversion of Dyna *SECTION_TSHELL

- engine/source/elements/beam/fail_beam3.F
Failure for type 3 beams - add msg when element is deleted
> Failure for type 3 beams - add msg when deleted

- common_source/tools/input_output/write_routtines.c
- engine/source/output/sta/state_n_vel.F
Wrong Gzip file closure with INIMAP. Possible gzip write issue found with /STATE Gzipped file
> Issue with Commit bee2923091408e34d94210e0114fcc5f2112b08c : 
